### ISSUE TITLE
非v2ray创建的端口可以统计吗

### ISSUE THREAD

**Issue by FFFcat** [Jrohy/multi-v2ray#100]
觉得程序显示的iptables统计很简洁，想把443端口和80端口加进去，v2ray stats的时候也能看到，可以实现吗？

**Comment by Jrohy** [comment]
global_setting/calcul_traffic.sh 这个脚本传入个端口即可统计

**Comment by FFFcat** [comment]
可以举一个80端口的例子嘛…刚刚接触Linux…麻烦了…🙂

**Comment by Jrohy** [comment]
`bash /usr/local/mul-v2ray/global_setting/calcul_traffic.sh 80`

**Comment by FFFcat** [comment]
哇原来这样也可以。但是输入v2ray stats 1 没有显示80端口的流量呀。还是每次查只能bash 脚本？

**Comment by Jrohy** [comment]
要查非v2ray端口的话调用该脚本，`v2ray stats`只能查v2ray相关的端口

**Comment by FFFcat** [comment]
嗯，好。我也知道直接加进去肯定要改过很多配置，就那样弄好了。谢谢你。

**Comment by FFFcat** [comment]
嗯，好。我也知道直接加进去肯定要改过很多配置，就那样弄好了。谢谢你。
