### ISSUE TITLE
无法连接Pandora音乐电台，无论电脑还是手机端的v2ray客户端都不行

### ISSUE THREAD

**Issue by forgotmymilk** [Jrohy/multi-v2ray#101]
希望能给出解决办法。
在没有出解决方法之前，我只能使用SS/SSR连接Pandora，同一个服务器，multi-v2ray脚本不行，非得SS/SSR才行，有点奇怪。
如果有修改配置文件的地方，请告知文件地址和修改方法。

希望知道的朋友告知方法，谢谢。

**Comment by Jrohy** [comment]
会不会客户端设置问题，试下全局？

**Comment by gqm36524** [comment]
v2ray支持纯tcp代理吗？我感觉v2ray只能通过http代理，其他的数据包类型貌似代理不了

**Comment by forgotmymilk** [comment]
> 会不会客户端设置问题，试下全局？

不是客户端设置问题，全局也没用。不过，
新版已经把问题解决了。
