### ISSUE TITLE
我想询问关于SSL证书的位置存放

### ISSUE THREAD

**Issue by xubuddy** [Jrohy/multi-v2ray#104]
你好，请问用你们的脚本做了tls，SSL证书一般是保存在那个文件夹？求解答！谢谢！

**Comment by Jrohy** [comment]
![image](https://user-images.githubusercontent.com/12463263/50370479-7f6b5880-05e2-11e9-8b6e-4d5e783a2d5e.png)

**Comment by xubuddy** [comment]
谢谢
