### ISSUE TITLE
脚本中的mtproxy如何设置代理赞助频道

### ISSUE THREAD

**Issue by FFFcat** [Jrohy/multi-v2ray#105]
从mtproxybot获得的tag该怎么用呢？

**Comment by Jrohy** [comment]
设置代理赞助是telegram的功能，和脚本无关

**Comment by FFFcat** [comment]
…我找不到脚本安装mtproxy的位置…

**Comment by Jrohy** [comment]
默认是新建端口再切换传输协议那里有， 不过你可以直接`v2ray add mtproto` 直接生成

**Comment by Jrohy** [comment]
不清楚了，没玩过

**Comment by FFFcat** [comment]
请问，mtproto的配置文件储存是在哪里的啊？
