### ISSUE TITLE
提一些Bug

### ISSUE THREAD

**Issue by CYF--cc** [Jrohy/multi-v2ray#108]
使用v2ray命令无法添加ss。。
如果要修改ss的密码（选项为：10），一按1就会选择更改emil的选项。。。

**Comment by Jrohy** [comment]
`v2ray add ss`添加没问题，修改ss密码的话确实是bug

**Comment by Jrohy** [comment]
v2.6.3版本已修复修改ss密码选项的bug @CYF--cc
