### ISSUE TITLE
V2ray配置Shadowsocks协议能不能开启tcpFastOpen？

### ISSUE THREAD

**Issue by aglent** [Jrohy/multi-v2ray#109]
脚本可以开启Vmes下的tcpFastOpen 但是不能开启shadowsocks下的tcpFastOpen 说是这个协议下不支持
我自己手动在配置文件里加了一条 会有什么副作用吗？
另外脚本安装时候能否有提示 让用户选择配置哪些传输协议 可否？

**Comment by Jrohy** [comment]
安装完可以切换，不提示是用来快速部署，而且kcp+伪装就很好用了
