### ISSUE TITLE
ubuntu 18并不能运行安装脚本

### ISSUE THREAD

**Issue by Cirooo** [Jrohy/multi-v2ray#111]
vultr， ubuntu 18，不能运行安装脚本
command not found 然后停掉了，我手动安装脚本里的依赖包之后再运行也还是不行。-z -f的我不清楚是不是少了什么，把条件表达式运行一下也提示command not found

**Comment by Jrohy** [comment]
@Cirooo  再试下， vultr ubuntu18 pip无法安装的bug已修复

**Comment by Jrohy** [comment]
@Cirooo vultr ubuntu18 已修复

**Comment by Cirooo** [comment]
是pip么？我挨个装Python跟pip3，之后也不行。不过暂时都无所谓了，我刚才用了原版的脚本，手动配置了，看什么时候被墙
