### ISSUE TITLE
为什么用了这个提示被监视，有后台？

### ISSUE THREAD

**Issue by fredwangcf** [Jrohy/multi-v2ray#112]
为什么用了这个方案，电脑立即提示被监视，有后台？吓的我是赶紧卸载

**Comment by Jrohy** [comment]
哪里提示啥监视

**Comment by Jrohy** [comment]
脚本只是安装在linux端，方便修改v2ray json而已

**Comment by fredwangcf** [comment]
> 脚本只是安装在linux端，方便修改v2ray json而已

macos terminal 提示someone watching,doing something naughty. 我卸载后换了官方命令，就没有这个问题了。

**Comment by Jrohy** [comment]
这么牛逼吗😂， 可惜我没macos来进行测试， 不放心可以看看源码，比较简单其实

**Comment by Jrohy** [comment]
后期我看下能不能搞成，pip的包，拆分成修改json的包模块, 然后`pip install xxx`, 估计兼容性就会好点
