### ISSUE TITLE
不能与LNMP共存  iptables 被清空，连不上vps了

### ISSUE THREAD

**Issue by boovi2018** [Jrohy/multi-v2ray#114]
原来V2RAY端口443，装LNMP显示冲突，V2RAY端口改为441，但是每次重启都会连接不上，需要再重启服务器一次， 这次重启再多次也完全不能连不下了，推测是IPtables 被清空了。

**Comment by Jrohy** [comment]
看下`iptables -nvL`

**Comment by Jrohy** [comment]
什么vps呢， 我用vultr centos7 安装完再重启也正常， 而且也真的没见过有配22端口这规则

**Comment by boovi2018** [comment]
我也是vultr Debian 9 这个22端口本身是配置好的，一直存在，如果被删了，就登不下vps了

**Comment by Jrohy** [comment]
我试下

**Comment by boovi2018** [comment]
不用忙活，可能是个例，
我想问问，脚本有删iptables 的规则吗

**Comment by boovi2018** [comment]
会不会在启动时配置iptables？

**Comment by Jrohy** [comment]
确实因为加入了新的iptables 流量统计规则，新安装的会自动清理之前版本的iptables规则， 我发现一个用grep 的bug(没加 -w 整个单词进行匹配),  可能会误清了， 抱歉😭

**Comment by Jrohy** [comment]
看看能不能进后台， 拿回有用的文件

**Comment by Jrohy** [comment]
我今晚回去更新下，修复这个致命问题

**Comment by boovi2018** [comment]
网站没关系，都有备份

**Comment by Jrohy** [comment]
@boovi2018 程序清理iptables 就两个地方, 这个是首次安装脚本/更新脚本时运行的， 用来清理旧的规则
`https://github.com/Jrohy/multi-v2ray/blob/master/global_setting/clean_iptables.sh`

**Comment by boovi2018** [comment]
对了，我是手动在iptables.rules里，增加了允许465端口进出，就是以下这几项，重启后就登不上了
-A INPUT -p tcp -dport 465 -j ACCEPT  
-A INPUT -p tcp -sport 465 -j ACCEPT
-A OUTPUT -p tcp --dport 465 -j ACCEPT

**Comment by Jrohy** [comment]
然后还有python, 哪里，删除端口，就清对应端口的iptables规则，大概看好像又没问题😂

**Comment by Jrohy** [comment]
![image](https://user-images.githubusercontent.com/12463263/50685144-07297c00-1053-11e9-8aa6-b7e81e2a0069.png)
删除端口后清理对应端口的流量统计规则

**Comment by boovi2018** [comment]
我重装一次，看看还会会出现这种情况

**Comment by Jrohy** [comment]
测试了，删除端口清理对应的Iptables规则再重启也是没问题vultr 的debian9
