### ISSUE TITLE
Iptables 端口流量的问题

### ISSUE THREAD

**Issue by ilifelog** [Jrohy/multi-v2ray#115]
**OS：centos 7**

Iptables 端口流量统计

1.查看流量统计

2.重置流量统计

tip: v2ray功能端口默认自动开启iptables的流量统计

请输入数字选择功能：1

> Traceback (most recent call last):
>   File "/usr/local/multi-v2ray/global_setting/iptables_ctr.py", line 25, in <module>
>     print(calcul_iptables_traffic(group.port))
>   File "/usr/local/multi-v2ray/utils.py", line 171, in calcul_iptables_traffic
>     return "{0}:  upload:{1} download:{2} total:{3}".format(color_str(Color.GREEN, str(port)), 
> NameError: name 'color_str' is not defined

**Comment by ilifelog** [comment]
修改/usr/local/multi-v2ray/utils.py 第171和172行代码：
        return "{0}:  upload:{1} download:{2} total:{3}".format(ColorStr.green(str(port)),
                ColorStr.cyan(upload_traffic), ColorStr.cyan(download_traffic), ColorStr.cyan(total_traffic))
可以用了。我不会用github，请大佬检查是不是这样修复。

**Comment by Jrohy** [comment]
你是用最新版-f安装的？

**Comment by ilifelog** [comment]
全新安装的。

**Comment by ilifelog** [comment]
出现这个问题后我尝试过降级2.6.2版本
好像也有问题。
我也不会py，对比着其他代码改了
修改前：
```
        return "{0}:  upload:{1} download:{2} total:{3}".format(color_str(Color.GREEN, str(port)), 
                color_str(Color.CYAN, upload_traffic), color_str(Color.CYAN, download_traffic), color_str(Color.CYAN, total_traffic))
```
修改后：
```
return "{0}: upload:{1} download:{2} total:{3}".format(ColorStr.green(str(port)),
ColorStr.cyan(upload_traffic), ColorStr.cyan(download_traffic), ColorStr.cyan(total_traffic))
```

**Comment by Jrohy** [comment]
我试试， 正常应该是用realease最新而不是代码最新， release较稳定点

**Comment by Jrohy** [comment]
最新代码是换了演示显示的ColorStr

**Comment by ilifelog** [comment]
嗯。麻烦您修复一下。我再尝试更新一下。

**Comment by Jrohy** [comment]
ok ,我测试下

**Comment by ilifelog** [comment]
你修复好了。我用什么命令更新？

**Comment by Jrohy** [comment]
等下，我发现问题所在了

**Comment by Jrohy** [comment]
`v2ray update.sh`, 更新下脚本

**Comment by Jrohy** [comment]
谢谢反馈☺

**Comment by ilifelog** [comment]
ok
