### ISSUE TITLE
v2ray info命令行出错

### ISSUE THREAD

**Issue by Lancenas** [Jrohy/multi-v2ray#116]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'loader'

**Comment by Jrohy** [comment]
什么vps商的什么系统呢，.bashrc有没加入环境变量

**Comment by Lancenas** [comment]
Ubuntu 16.04  .bashrc添加了export PYTHONPATH=:/usr/local/multi-v2ray
source /etc/bash_completion.d/v2ray.bash

**Comment by Jrohy** [comment]
加了环境变了也是不行，什么vps商呢

**Comment by Lancenas** [comment]
意大利Aruba，除了"4.查看配置"其它配置都没问题，使用没问题。其实也无所谓打开配置config.json就可以看到了。

**Comment by Jrohy** [comment]
感觉比较麻烦😂

**Comment by Jrohy** [comment]
要解决这个问题，就要变成pip的包，不用到环境变量， 然后`pip install xxx`就能安装, 3.0想搞成这样
