### ISSUE TITLE
如何用sh -c "" 封装一下

### ISSUE THREAD

**Issue by snowdream** [Jrohy/multi-v2ray#119]
sh -c "source <(curl -sL https://git.io/fNgqx)"

我想这样封装一下，执行不了。

**Comment by Jrohy** [comment]
封装的意义？

**Comment by snowdream** [comment]
https://github.com/snowdream/node-lsm <https://github.com/snowdream/node-lsm>
封装工具

**Comment by Jrohy** [comment]
最好不用sh来执行， 可以wget https://git.io/fNgqx下载后bash或者source来执行

**Comment by snowdream** [comment]
@Jrohy  --remove  这种方式 这个参数不知道怎么传进去。

**Comment by Jrohy** [comment]
下载multi-v2ray.sh脚本下来， 运行`bash multi-v2ray.sh --remove `

**Comment by snowdream** [comment]
@Jrohy 搞定，谢谢。
https://github.com/snowdream/node-lsm

nlsm install multi-v2ray
nlsm uninstall multi-v2ray
nlsm update multi-v2ray
