### ISSUE TITLE
tls开启失败

### ISSUE THREAD

**Issue by Helixzhang** [Jrohy/multi-v2ray#123]
acme.sh的安装目录已经修改至/usr/local/acme.sh，脚本中运行bash: /root/.acme.sh/acme.sh会提示No such file or directory，麻烦更新acme.sh的运行位置

**Comment by Jrohy** [comment]
可以自己先生成证书，再填证路径

**Comment by Jrohy** [comment]
自定义证书路径

**Comment by Helixzhang** [comment]
明白，提示作者大大更新一下

**Comment by Jrohy** [comment]
谢谢提醒，周末更新下

**Comment by Helixzhang** [comment]
谢谢作者

**Comment by Jrohy** [comment]
@Helixzhang 我用centos7 ` curl https://get.acme.sh | sh` 来安装， acme.sh脚本还是安装在/root/.acme.sh/目录下，没变😂

**Comment by Helixzhang** [comment]
`[Fri Jan 25 20:23:13 CST 2019] Installing from online archive.
[Fri Jan 25 20:23:13 CST 2019] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz
[Fri Jan 25 20:23:14 CST 2019] Extracting master.tar.gz
[Fri Jan 25 20:23:14 CST 2019] Installing to /usr/local/acme.sh
[Fri Jan 25 20:23:14 CST 2019] Installed to /usr/local/acme.sh/acme.sh
[Fri Jan 25 20:23:14 CST 2019] Installing alias to '/root/.bashrc'
[Fri Jan 25 20:23:14 CST 2019] OK, Close and reopen your terminal to start using acme.sh
[Fri Jan 25 20:23:14 CST 2019] Installing cron job
14 0 * * * "/usr/local/acme.sh"/acme.sh --cron --home "/usr/local/acme.sh" > /dev/null
[Fri Jan 25 20:23:14 CST 2019] Good, bash is found, so change the shebang to use bash as preferred.
[Fri Jan 25 20:23:14 CST 2019] OK
[Fri Jan 25 20:23:14 CST 2019] Install success!`

**Comment by Jrohy** [comment]
用vultr 的debian9 也是正常
![_20190125214900](https://user-images.githubusercontent.com/12463263/51749709-10a28300-20eb-11e9-8dc4-9317ae514b50.png)

**Comment by Helixzhang** [comment]
那就不知道是不是我是特技了😂
