### ISSUE TITLE
单网卡多ip怎么设置？才能使每个ip都能使用代理？

### ISSUE THREAD

**Issue by mailrock** [Jrohy/multi-v2ray#125]
VPS配置有多个ip 分别是ip1，ip2，ip3，其中ip1为主ip，ip2与ip3为附加ip
怎么使用vmess模式在客户端上使用ip2或者ip3，然后通过ip138.com等网站查询的ip是IP2或者ip3？客户端与服务器段分别怎样设置才可以？（单用户或多用户模式都可以，具体提供一下设置的办法或者json文件），谢谢。

**Comment by Jrohy** [comment]
如果ip2或者ip3也能访问到vps的话，填的vmess信息手动换成ip2/ip3就好

**Comment by mailrock** [comment]
我试过可以用ip2登陆ssh，但是在客户端改成ip2后代理服务器就不通了。

**Comment by Jrohy** [comment]
查看下/etc/v2ray/config.json 配置文件里有没写ip的, 有就换成Ip2试试

**Comment by mailrock** [comment]
{
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "log": {
    "error": "/var/log/v2ray/error.log",
    "access": "/var/log/v2ray/access.log",
    "loglevel": "info"
  },
  "inbounds": [
    {
      "port": 55907,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "ef07be85-d27b-40a8-88e5-ded29d9a7859",
            "alterId": 16
          }
        ]
      },
      "streamSettings": {
        "wsSettings": {},
        "security": "none",
        "quicSettings": {},
        "kcpSettings": {
          "downlinkCapacity": 100,
          "congestion": false,
          "uplinkCapacity": 100,
          "readBufferSize": 2,
          "tti": 50,
          "mtu": 1350,
          "writeBufferSize": 2,
          "header": {
            "type": "srtp"
          }
        },
        "httpSettings": {},
        "tlsSettings": {},
        "tcpSettings": {},
        "network": "kcp"
      }
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "ip": [
          "0.0.0.0/8",
          "10.0.0.0/8",
          "100.64.0.0/10",
          "169.254.0.0/16",
          "172.16.0.0/12",
          "192.0.0.0/24",
          "192.0.2.0/24",
          "192.168.0.0/16",
          "198.18.0.0/15",
          "198.51.100.0/24",
          "203.0.113.0/24",
          "::1/128",
          "fc00::/7",
          "fe80::/10"
        ],
        "outboundTag": "blocked"
      }
    ]
  }
}

**Comment by mailrock** [comment]
这个是服务器端的，怎么改？

**Comment by Jrohy** [comment]
看下官方文档，我也没体验过多ip设置😂

**Comment by smthvitas** [comment]
我这也碰到这个问题，服务器端两个ip，ssh连接任意一个ip都可以，v2ray就只能让客户端配置主ip才能连上。配置文件一切不动，切换到辅ip就不通。
这个issue为什么close了？

**Comment by Jrohy** [comment]
因为我也没机会体验多IP，要自己摸索怎么配置了😂

**Comment by Jrohy** [comment]
可以去v2ray官方，问下怎么换成副ip来配置

**Comment by smthvitas** [comment]
搞定了。在服务器主机添加一条路由规则
iptables -t nat -A PREROUTING -p udp -d 副IP -j REDIRECT
iptables -t nat -A PREROUTING -p tcp  -d 副IP -j REDIRECT

原理似乎是不带参数的REDIRECT把副IP的流量直接转发到主IP了。

**Comment by Jrohy** [comment]
👍

**Comment by mailrock** [comment]
> 
> 
> 搞定了。在服务器主机添加一条路由规则
> iptables -t nat -A PREROUTING -p udp -d 副IP -j REDIRECT
> iptables -t nat -A PREROUTING -p tcp -d 副IP -j REDIRECT
> 
> 原理似乎是不带参数的REDIRECT把副IP的流量直接转发到主IP了。

副ip使用代理的问题似乎解决了，新的问题是通过ipaddress.com等ip网站验证ip的时候还是显示为主ip，无法以副ip来做访问网站。
