### ISSUE TITLE
请问一个问题和tls及ws有关。

### ISSUE THREAD

**Issue by GHNNS** [Jrohy/multi-v2ray#126]
就是使用本脚本配置WS和TLS以后，还有必要再手动再配置ngix服务器吗？
另外证书会自动续期吗？谢谢！

**Comment by Jrohy** [comment]
证书会自动续期的(设置定时任务)，至于是否需要nginx，个人觉得没什么必要

**Comment by GHNNS** [comment]
好的清楚了，非常感谢！
