### ISSUE TITLE
2.流量统计(iptables) 无效，是宝塔面板没放行端口么？

### ISSUE THREAD

**Issue by anbell2** [Jrohy/multi-v2ray#127]
宝塔面板+LNMP+wordpress建站分流+TLS+V2RAY（WS）

按用户分开查流量统计可以，可是按端口查，始终是0

是因为宝塔面板没有放行IP统计的端口么？

**Comment by Jrohy** [comment]
有可能，尽量先跑multi-v2ray搭建

**Comment by anbell2** [comment]
测试了下，每次服务器重启，流量统计失效，服务器重启后，需要再手动重启一次V2才生效。不知道是不是个案。

说话在宝塔里开不开放端口，没有影响。

**Comment by Hi-Peanut** [comment]
我的也是宝塔，也是流量统计是0。
