### ISSUE TITLE
同时安装v2ray-mkcp和ss怎么弄

### ISSUE THREAD

**Issue by becapital** [Jrohy/multi-v2ray#128]
同时安装v2ray-mkcp和ss怎么弄

**Comment by Jrohy** [comment]
先新增端口，再切换传输协议

**Comment by becapital** [comment]
我是说同时mkcp+ss

**Comment by becapital** [comment]
root@localhost:~# v2ray add ss
请选择shadowsocks的加密方式：
1.aes-256-cfb
2.aes-128-cfb
3.chacha20
4.chacha20-ietf
5.aes-256-gcm
6.aes-128-gcm
7.chacha20-poly1305
3
产生随机密码 G6pPyb4H5lJQfWxK , 回车直接使用该密码, 否则输入自定义密码: test
产生随机端口24002, 回车直接以该端口新建Group, 否则输入自定义端口: 586

新端口为: 586
新增端口组成功!
 * Restarting v2ray v2ray                                                                                                                                                                       [ OK ] 
root@localhost:~# v2ray status
 * v2ray is not running
root@localhost:~# v2ray restart
 * Restarting v2ray v2ray                                                                                                                                                                              start-stop-daemon: warning: failed to kill 7938: No such process
                                                                                                                                                                                                [ OK ]
v2ray重启成功!
root@localhost:~# v2ray status
 * v2ray is not running
root@localhost:~# 
还是不行，增加了以后，失败没有能启动

**Comment by Jrohy** [comment]
v2ray 没启动成功

**Comment by becapital** [comment]
那要咋办嫩？谢谢

**Comment by Jrohy** [comment]
机器配置不高吧，启动v2ray 都会被kill
