### ISSUE TITLE
https://pypi.org/project/v2ray-util/ 这个项目可直接取代脚本了？

### ISSUE THREAD

**Issue by bigbighill** [Jrohy/multi-v2ray#135]
https://pypi.org/project/v2ray-util/ 这个项目可直接取代脚本了？

**Comment by Jrohy** [comment]
后面multi-v2ray会直接调用`pip install v2ray-util`来安装,  只不过还没完成多语言，所以还没调用

**Comment by Jrohy** [comment]
你也可以直接`pip install v2ray-util`来安装独立使用， v2ray-util运行时会检测v2ray有没安装，没安装自动安装

**Comment by Jrohy** [comment]
用pip来安装的话就彻底解决找包路径问题，不用设置环境变量就能找到相应的包
