### ISSUE TITLE
debian 9 安装成功，客户端连不上

### ISSUE THREAD

**Issue by cwcwcw721** [Jrohy/multi-v2ray#136]
Debian 9 x86_64  上安装的，安装正常，使用查看配置给的vmess：链接导入v2rayN 无法科学上网，v2rayW也试过

**Comment by cwcwcw721** [comment]
500 Internal Privoxy Error
Privoxy encountered an error while processing your request:

Could not load template file forwarding-failed or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

访问出现500错误

**Comment by Jrohy** [comment]
上面访问报错日志怎么来的呢😂

**Comment by Jrohy** [comment]
什么vps商的debian9

**Comment by cwcwcw721** [comment]
搬瓦工的，那个日志是我开着梯子，浏览器访问页面出现的

**Comment by Jrohy** [comment]
尝试切换协议或者新增个端口也不行?

**Comment by cwcwcw721** [comment]
嗯，我还新增了一个ss的组也不行。。原来是搭ss的，要不我再去运营商那问下，在vps商那检查是显示没有被墙
