### ISSUE TITLE
ip显示问题

### ISSUE THREAD

**Issue by alililala** [Jrohy/multi-v2ray#137]
两个配置，A和B，都采用WS+TLS方式，A配置完ip会显示某个域名如C，然后配置B的时候，开启TLS绑定的是D域名，配置完查看配置的时候会发现，A配置里边的域名C会被D取代。两个配置都显示的IP是D，而不是A显示C，B显示D。大佬不知道我说清楚了没。

**Comment by Jrohy** [comment]
还没支持多域名，目前仅支持单域名

**Comment by alililala** [comment]
> 还没支持多域名，目前仅支持单域名

哦哦，原来是脚本不支持，还以为是我的个人设置问题。

**Comment by Jrohy** [comment]
这个是动态端口配置， 脚本没有设置nginx/caddy分流的

**Comment by alililala** [comment]
> 这个是动态端口配置， 脚本没有设置nginx/caddy分流的

哦。动态端口配置没细看，所以不认出来，不好意思。没有分流的话是不是就只能用一个443端口？

**Comment by Jrohy** [comment]
要不要套看自己测试的速度如何了，毕竟速度才是关键。 多域名支持必须的

**Comment by alililala** [comment]
> 要不要套看自己测试的速度如何了，毕竟速度才是关键。 多域名支持必须的

哦，主要是想都试一下。测试发现套CF，云朵点灰，能用，云朵点亮后总不能用。怀疑是端口问题。是不是只能使用特定端口。如果建站的话有没有影响。还是说要添加反代才行。我感觉我说的有点乱。
