### ISSUE TITLE
Centos7

### ISSUE THREAD

**Issue by DaedalusT** [Jrohy/multi-v2ray#139]
centos7 下可以安装脚本，无法使用v2ray命令

[root@host ~]# v2ray
bash: v2ray: command not found

**Comment by Jrohy** [comment]
应该环境变量问题， 可以试下https://pypi.org/project/v2ray-util/  用pip来安装

**Comment by DaedalusT** [comment]
> 应该环境变量问题， 可以试下https://pypi.org/project/v2ray-util/ 用pip来安装

多谢，已经解决，Debian，Ubuntu下安装完脚本可以直接使用'v2ray'命令，centos下则需要使用'bash v2ray'
