### ISSUE TITLE
选择打开流量统计时报错

### ISSUE THREAD

**Issue by Seekerzero** [Jrohy/multi-v2ray#14]

**Comment by Seekerzero** [comment]
Traceback (most recent call last):
  File "/usr/local/v2ray.fun/other_setting/stats_ctr.py", line 3, in <module>
    import read_json
  File "/usr/local/v2ray.fun/read_json.py", line 118, in <module>
    read_sin_user(conf_inbound, multiUserConf, index_dict)
  File "/usr/local/v2ray.fun/read_json.py", line 45, in read_sin_user
    conf_host = conf_stream["wsSettings"]["headers"]["Host"]
KeyError: 'Host'

**Comment by Jrohy** [comment]
修改下/etc/v2ray/config.json文件里的host字段， 改问Host
![image](https://user-images.githubusercontent.com/12463263/43048001-f6b7f350-8e12-11e8-84c9-94e3cf7b08a4.png)

**Comment by Seekerzero** [comment]
更新了脚本就这样了QAQ

**Comment by Jrohy** [comment]
最开始的v2ray.fun这个模板字段就写错了，只有http/2是host，ws和http在headers里面都是Host, 因为刚刚的版本用到这个才去修正了

**Comment by Seekerzero** [comment]
哦哦
是要去手动修改吗？？
改成自己的域名？？？

**Comment by Seekerzero** [comment]
还是改大小写？？？

**Comment by Jrohy** [comment]
手动改host为Host, 最开始的模板写错了的

**Comment by Seekerzero** [comment]
好了
谢谢大佬！！！

**Comment by Jrohy** [comment]
不客气

**Comment by wangwill** [comment]
更新脚本后遇到同样问题 Host。。

但是检查 /etc/v2ray/config.json 是小写host

**Comment by Jrohy** [comment]
@wangwill 就是要改成大写Host

**Comment by wangwill** [comment]
抱歉刚刚在平板上没看全  改Host后问题解决

再次感谢
