### ISSUE TITLE
v2配置问题

### ISSUE THREAD

**Issue by ttff2323** [Jrohy/multi-v2ray#141]
请问应该怎么配置广告过滤

**Comment by Jrohy** [comment]
暂不支持，后面会加入

**Comment by MicMAO** [comment]
老哥你好 我有个问题想问一下您，能给个什么联系方式吗？

**Comment by Jrohy** [comment]
@MicMAO  issue留言都行

**Comment by MicMAO** [comment]
是这样的，我一直闹不明白。
1》新建端口和新建用户有什么区别
2》我现在多用户管理的办法是，新建几个端口，每个人用一个端口。但是我感觉速度会变慢
3》我怎么新建不出来用户呢，不知道怎么新建用户，只会新建端口。
4》综上所述，多用户管理的时候。应该用新建端口，还是新建用户。


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Jrohy <notifications@github.com>
发送时间: Tuesday, April 2, 2019 5:52:33 PM
收件人: Jrohy/multi-v2ray
抄送: MicMAO; Mention
主题: Re: [Jrohy/multi-v2ray] v2配置问题 (#141)


@MicMAO<https://github.com/MicMAO> issue留言都行

―

**Comment by Jrohy** [comment]
新建用户是同一个端口下面新建用户(不同uuid)。新建端口好点，可以iptable流量统计

**Comment by MicMAO** [comment]
所以我现在这种直接新建N个端口来用是没问题的了？
感谢您的回答

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Jrohy <notifications@github.com>
发送时间: Tuesday, April 2, 2019 7:22:01 PM
收件人: Jrohy/multi-v2ray
抄送: MicMAO; Mention
主题: Re: [Jrohy/multi-v2ray] v2配置问题 (#141)


新建用户是同一个端口下面新建用户(不同uuid)。新建端口好点，可以iptable流量统计

―

**Comment by Jrohy** [comment]
没问题的

**Comment by MicMAO** [comment]
Thanks again

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Jrohy <notifications@github.com>
发送时间: Tuesday, April 2, 2019 9:10:32 PM
收件人: Jrohy/multi-v2ray
抄送: MicMAO; Mention
主题: Re: [Jrohy/multi-v2ray] v2配置问题 (#141)


没问题的

―
