### ISSUE TITLE
真实config.json位置问题

### ISSUE THREAD

**Issue by Mycheol** [Jrohy/multi-v2ray#144]
首先感谢大佬！
用了这个多端口多协议管理脚本之后，比起官方脚本来说，添加多个用户方便多了。

最近因为写项目要重装VPS的系统，同时使用这个机器扶墙的人比较多，于是想把配置文件copy出来。
重装系统以及脚本后发现一个问题：`/root`目录和`/etc/v2ray/`目录里都有一个**config.json**文件！

事情是这样的：
我记得以前**V2Ray**官方的说法——配置文件应该是`/etc/v2ray/config.json`。
那么装好系统和这个脚本之后，我就把之前copy下来的旧配置文本paste到`/etc/v2ray/config.json`里。
执行v2ray命令，在面板选择查看配置，输出的确实是我以前的配置，而且在v2rayN试了能正常使用。
然后我想不起来有没有先安装BBR，就`ls`看了一下`/root`目录，结果发现这里也有一个config.json文件！
看了一眼，发现这居然是v2ray的配置文件，但并不是我的旧配置，入站协议里面只有一个端口和uuid。
我把这个配置里的port，uuid以及alterid以及加密方式协议填到v2rayN里，发现并不能使用。
我是个大眼睛，没在意也不记得没重装系统以前`/root`目录下有没有这个JSON文件。我把它删除了发现也并没有影响v2ray的使用。

![qq 20190227184422](https://user-images.githubusercontent.com/37826133/53487175-d2bbc480-3ac5-11e9-8678-0847897522ab.png)

现在就有一些疑问：真正的config文件是不是和官方脚本的一样是`/etc/v2ray/config.json`？（我感觉是一样的，不然我的旧配置应该不能连接了）还有就是`/root`目录下的config文件是不是**mutil-v2ray**安装时生成的？它到底有没有作用，如果没有为什么要生成这个配置文件呢？

**Comment by Jrohy** [comment]
安装完成会自动生成客户端json /root/config.json

**Comment by Mycheol** [comment]
感谢回答！
刚去试了一下面板第7项功能——生成客户端配置文件。按操作选了一个节点序号。
发现`/root`目录下果然多出一个config文件。这次仔细看了一下确实是是客户端json。
那么昨天应该是装完脚本后，自动生成了一个节点，并分别在`/etc/v2ray/`目录以及`/root/`目录，
保存了服务端与客户端config文件。
然后我手动修改服务端配置文件，导致自动生成的客户端文件里面的配置没有对应的服务端不起作用。
mmp，真的是打扰了！
