### ISSUE TITLE
Centos7防火墙问题

### ISSUE THREAD

**Issue by cloverxzh** [Jrohy/multi-v2ray#145]
给大佬递茶！多用户管理很方便~
有一个问题非常疑惑，脚本跑完之后v2ray就直接可以用（之前用官方脚本的时候设置好之后还需要配置firewall），我列出firewall的所有端口发现并没有v2ray使用的几个端口，那这个端口是如何配置的呢？如果我开通了动态端口10000-20000，是否需要在firewall手动开放10000-20000端口呢？

**Comment by Jrohy** [comment]
只有流量统计iptable的，其他的开通端口没设置，不需要手动开放
