### ISSUE TITLE
选择Vmess 脚本没有加密选项问题 security none

### ISSUE THREAD

**Issue by matthew-zao** [Jrohy/multi-v2ray#146]
如题，发现脚本除了选择shadowsocks 可以选择加密方式。选择其他的协议似乎没有能够更改加密方式的选项。因为选择了Vmess config.json 里面默认是security none， 是不是其实vmess 没有再次加密必要？

**Comment by Jrohy** [comment]
服务端没必要配加密方式的， 客户端配了服务端会自动识别

**Comment by Mycheol** [comment]
根据 V2Ray 官方的说法：只需要你的客户端（PC，手机）的配置文件中设置了加密方式，那么就会按配置的加密方式发送数据，服务器端会自动识别相应的加密方式，是不需要配置的。

![qq 20190228160856](https://user-images.githubusercontent.com/37826133/53551034-37812880-3b73-11e9-9367-8e49d0cbd3f8.png)

你可以去查阅一下官方文档中关于security的配置解释，包括在streamSettings中都有相应的介绍。

简单来说，具体到这个脚本生成的配置文件。你如果通过生成的`vmess://`链接导入配置到客户端，客户端呈现的加密方式会是 `none`（从我的使用经验上来看，至少在 **iOS** 的客户端 **ShadowRocket** 以及 **Mac OS** 的GUI **v2rayX**中是这样的，至于 **Windows** 的GUI——**v2rayN**则会自动设置成 `aes-128-gcm`，这应该是作者在GUIconfig.json中的默认设置）。但是你可以在这些客户端程序中选择加密方式，或是手动修改客户端config.json文件内容为上图中其它的加密方式，来确保你的数据安全性。
