### ISSUE TITLE
脚本与某个zsh主题冲突的问题

### ISSUE THREAD

**Issue by aglent** [Jrohy/multi-v2ray#147]
这几天我安装了一个zsh主题 https://github.com/denysdovhan/spaceship-prompt
之后 执行一键脚本的4号菜单（查看配置文件） 提示错误：
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'loader'
不安装这个zsh主题就没问题
请问这是哪里产生冲突了 如何解决？谢谢！

**Comment by Jrohy** [comment]
可以换下其他主题试试😂
