### ISSUE TITLE
可以添加端口流量的清除功能么？

### ISSUE THREAD

**Issue by Glanwu** [Jrohy/multi-v2ray#148]
大佬，
第一次留言，很喜欢的你的脚本。有个小小的想法，不知道会不会放在下面版本更新里。
1. 可以添加端口流量的清除功能么？或者增加每月月头1号端口流量自动清零。
2. 查看端口流量，可以在端口后面显示邮件地址么，这样可以很直观的知道是哪个人，因为邮件都是自己根据名字写的。
以上，谢谢。

**Comment by Jrohy** [comment]
端口流量统计后面加邮件的话，假如该端口有多个用户就不好加了。
