### ISSUE TITLE
安装脚本有点问题

### ISSUE THREAD

**Issue by nickonline2005** [Jrohy/multi-v2ray#149]
debian9系统，如果是用root用户安装的话，安装依赖时脚本检查到不是sudo用户，会报错，导致没安装上pip3，进而导致没安装上pyopenssl，虽然脚本还会继续运行到结束，但是v2ray不能启动。

安装脚本会调用这个安装依赖的脚本:https://git.io/fhqMz，root用户想安装的话，手动下载这个脚本，然后注释掉第51和52行，运行这个脚本，然后重新安装脚本就行了。

**Comment by Jrohy** [comment]
哪家vps商呢

**Comment by Jrohy** [comment]
抱什么错最好截下图

**Comment by Jrohy** [comment]
用root用户没问题的，不用root用户就会报错

**Comment by nickonline2005** [comment]
搬瓦工，报错就是安装依赖脚本里面的那个：Error: You must be sudo user to run this script

**Comment by nickonline2005** [comment]
找到问题所在了，我搬瓦工的机器上竟然没有sudo命令。。。。。
