### ISSUE TITLE
profile.py和名字和python3内置的库名一样，会导致其他程序出现坑爹的问题

### ISSUE THREAD

**Issue by DDogeChan** [Jrohy/multi-v2ray#152]

**Comment by Jrohy** [comment]
什么问题呢，能否截个图

**Comment by Shuyakano** [comment]
> Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'loader'

基本全是这个报错...

**Comment by DDogeChan** [comment]
因为安装了multi-v2ray后，PATH加入了/usr/local/multi-v2ray，其他python脚本如果import了profile会引用到/usr/local/multi-v2ray里面的profile.py，有很多程序会用到这个profile module的。
```
import profile
print(profile.__file__)

```

**Comment by Jrohy** [comment]
如果有冲突可以用着https://pypi.org/project/v2ray-util/用着这个先，后面会改造成调用这个来安装，无需环境变量

**Comment by Jrohy** [comment]
@DDogeChan  更新下脚本，现在脚本直接用pip来安装了, 不会出现库名冲突的情况了
