### ISSUE TITLE
新增端口导致流量统计的bug

### ISSUE THREAD

**Issue by brunuhvill** [Jrohy/multi-v2ray#154]
![I2YDF~4{18_HURH4{HXHMO](https://user-images.githubusercontent.com/48313077/54065179-c23ee300-4257-11e9-8cfa-9b62a96d749b.png)
之前v2ray流量统计正常，但是当我新增端口后，再去查看v2ray流量（同一个），就会这样的情况，说没有上传和下载流量
我在debian9和ubuntu16试过几次，都是这样

**Comment by Jrohy** [comment]
新增端口后会重启v2ray, 然后就重置上传下载流量了

**Comment by Jrohy** [comment]
经常新增端口建议用iptables来统计流量

**Comment by brunuhvill** [comment]
一个端口建3个用户同时使用，和3个端口 每个端口一个用户，在使用速度上有什么区别么?

**Comment by brunuhvill** [comment]
@Jrohy 一个端口建3个用户同时使用，和3个端口 每个端口一个用户，在使用速度上有什么区别么?

**Comment by Jrohy** [comment]
三个不同端口， 被qos后也能换端口， 我一般都是建多个端口，也能保证速度
