### ISSUE TITLE
你好，安装后输入v2ray,显示找不到文件

### ISSUE THREAD

**Issue by hanjiexx8** [Jrohy/multi-v2ray#155]
bash: /usr/local/sbin/v2ray: No such file or directory

**Comment by Jrohy** [comment]
可能环境变量问题，可以试下这个: https://pypi.org/project/v2ray-util/, pip安装无需环境变量

**Comment by hanjiexx8** [comment]
谢谢大佬的答复，已搞定

**Comment by Jrohy** [comment]
更新下脚本，现在用pip来安装了
