### ISSUE TITLE
机器更换IP后，有什么办法让配置统一更换IP吗

### ISSUE THREAD

**Issue by hanjiexx8** [Jrohy/multi-v2ray#156]
您好，请问如果机器的IP被封了，更换IP后，使用什么方法可以快速让所有配置都更新成新的IP呢

**Comment by Jrohy** [comment]
用sed命令替换下
``sed -i "s/原来ip/新ip/g" /etc/v2ray/config.json``
然后重启v2ray

**Comment by hanjiexx8** [comment]
好的，谢谢解答
