### ISSUE TITLE
开启TLS失败

### ISSUE THREAD

**Issue by Kakushi** [Jrohy/multi-v2ray#158]
正在获取SSL证书，请稍等。。。
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   705  100   705    0     0   1897      0 --:--:-- --:--:-- --:--:--  1900
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  174k  100  174k    0     0   984k      0 --:--:-- --:--:-- --:--:--  990k
[Wed Mar 13 23:48:06 UTC 2019] Installing from online archive.
[Wed Mar 13 23:48:06 UTC 2019] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz
[Wed Mar 13 23:48:07 UTC 2019] Extracting master.tar.gz
[Wed Mar 13 23:48:07 UTC 2019] Installing to /root/.acme.sh
[Wed Mar 13 23:48:07 UTC 2019] Installed to /root/.acme.sh/acme.sh
[Wed Mar 13 23:48:07 UTC 2019] Installing alias to '/root/.bashrc'
[Wed Mar 13 23:48:07 UTC 2019] OK, Close and reopen your terminal to start using acme.sh
[Wed Mar 13 23:48:07 UTC 2019] Installing cron job
[Wed Mar 13 23:48:07 UTC 2019] Good, bash is found, so change the shebang to use bash as preferred.
[Wed Mar 13 23:48:07 UTC 2019] OK
[Wed Mar 13 23:48:07 UTC 2019] Install success!
[Wed Mar 13 23:48:08 UTC 2019] Standalone mode.
[Wed Mar 13 23:48:08 UTC 2019] Registering account
[Wed Mar 13 23:48:08 UTC 2019] Registered
[Wed Mar 13 23:48:09 UTC 2019] ACCOUNT_THUMBPRINT='dtkugDRZeGxELwfgp5Ln9OvQCRJmYmqu4AITsQk_tIE'
[Wed Mar 13 23:48:09 UTC 2019] Creating domain key
[Wed Mar 13 23:48:09 UTC 2019] The domain key is here: /root/.acme.sh/VPN.VFHPDCWY.CF_ecc/VPN.VFHPDCWY.CF.key
[Wed Mar 13 23:48:09 UTC 2019] Single domain='VPN.VFHPDCWY.CF'
[Wed Mar 13 23:48:09 UTC 2019] Getting domain auth token for each domain
[Wed Mar 13 23:48:09 UTC 2019] Getting webroot for domain='VPN.VFHPDCWY.CF'
[Wed Mar 13 23:48:09 UTC 2019] get to authz error.
[Wed Mar 13 23:48:09 UTC 2019] _authorizations_map='vpn.vfhpdcwy.cf,{"identifier":{"type":"dns","value":"vpn.vfhpdcwy.cf"},"status":"pending","expires":"2019-03-20T23:48:09Z","challenges":[{"type":"tls-alpn-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/RoHBRuXyQdNDVwyHl4MiHTuhC7jLBy0LuN-o5Q2FtR8/13625019647","token":"hxGR7WMYyj0NpLG8EKb2wMGvyMQWznReu2NAXQlsKv4"},{"type":"http-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/RoHBRuXyQdNDVwyHl4MiHTuhC7jLBy0LuN-o5Q2FtR8/13625019648","token":"2RA-0XejdPO1Ns3j3eeDo7IsS0f_NOlVhBpf0wESvco"},{"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/RoHBRuXyQdNDVwyHl4MiHTuhC7jLBy0LuN-o5Q2FtR8/13625019649","token":"J7gThf8QApX5lQl1hv4c7E5PgV3oC8oJMLWCCZPvzzY"}]}
'
[Wed Mar 13 23:48:09 UTC 2019] Please add '--debug' or '--log' to check more details.
[Wed Mar 13 23:48:09 UTC 2019] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

**Comment by Jrohy** [comment]
`bash /root/.acme.sh/acme.sh  --issue -d ${domain} --standalone  --keylength ec-256`
可以试下单独运行
