### ISSUE TITLE
流量统计

### ISSUE THREAD

**Issue by FFFcat** [Jrohy/multi-v2ray#16]
作者大大你好，我想问下流量统计中，为什么需要有效email才可以使用呀？

**Comment by Jrohy** [comment]
![image](https://user-images.githubusercontent.com/12463263/43357382-1400336a-92b3-11e8-9ccf-0a1a451eaa56.png)
官网的说明

**Comment by FFFcat** [comment]
大大知道原理吗？

**Comment by Jrohy** [comment]
这个要问v2ray作者了

**Comment by FFFcat** [comment]
好吧，谢谢大大。
