### ISSUE TITLE
invalid user

### ISSUE THREAD

**Issue by GHNNS** [Jrohy/multi-v2ray#160]
在vmess协议下，会报错rejected  v2ray.com/core/proxy/vmess/encoding: invalid user，但使用ss正常。
![批注 2019-03-15 204405](https://user-images.githubusercontent.com/20828349/54432307-c5f4cd00-4763-11e9-8772-c82fa9b065f8.jpg)

**Comment by Jrohy** [comment]
会不会客户端设置不对呢

**Comment by GHNNS** [comment]
有考虑过设置的问题，所以删除过本地的v2ray-core，从新下载了v2ray-core进行链接，依旧是这个问题。在手机上也是重置设置过。
配置是直接copy的v2ray info里面的协议信息进行链接配置的。
