### ISSUE TITLE
路由器安装后，无法打开网页

### ISSUE THREAD

**Issue by dahuziqi** [Jrohy/multi-v2ray#161]
将/root/config.json内容复制到老毛子华硕路由器（Padavan）的“v2ray_config_script”中，路由器日志显示连接成功，QQ、wechat、winscp均可连接使用，但墙内外的网页都无法打开。
同样的配置，用Windows的客户端正常。
用bash <(curl -L -s https://opt.cn2qq.com/opt-script/v2ray.sh)这个脚本生成的配置文件复制到路由器，连接到其生成的服务器端后正常。

**Comment by Jrohy** [comment]
生成的配置文件只适用于windows客户端，其他都没去适配
