### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by FemalePresident** [Jrohy/multi-v2ray#162]
你好，我在一台64M小内存主机上用老脚本并没有任何问题。
升级下脚本后就提示如下错误：

V2Ray v4.18.0 is installed.
-bash: /usr/local/bin/v2ray: No such file or directory

multi-v2ray install success!

-bash: /usr/local/bin/v2ray: No such file or directory
please input 'v2ray' command to manage v2ray

我想问下能不能提供使用PIP之前的脚本？
在这台小内存主机上安装PIP一大堆问题...

**Comment by Jrohy** [comment]
可以，我看下切换个分支修改，不用pip来安装

**Comment by Jrohy** [comment]
用来给小内存vps使用

**Comment by FemalePresident** [comment]
感谢...

用老脚本已经稳定100多天了，今天闲着没事就选择了下升级脚本，一下子感觉天都塌了...

**Comment by Jrohy** [comment]
我也有装不上pip的vps,  非pip安装的方式打算唯一个pip依赖安装也去掉

**Comment by FemalePresident** [comment]
----------------------------------------------------------------------
 CPU Model            : Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
 CPU Cores            : 1 Cores @ 600.000 MHz x86_64
 CPU Cache            : 15360 KB
 OS                   : Ubuntu 16.04.6 LTS (64 Bit) OpenVZ
 Kernel               : 2.6.32-042stab134.8
 Total Space          : 1.4 GB / 3.0 GB
 Total RAM            : 10 MB / 64 MB (32 MB Buff)
 Total SWAP           : 18 MB / 64 MB
 Uptime               : 21 days 0 hour 12 min
 Load Average         : 0.08, 0.11, 0.09
 TCP CC               : cubic
 ASN & ISP            : AS8100, CUST10107-CA
 Organization         :
 Location             : El Segundo, United States / US
 Region               : California
----------------------------------------------------------------------
 I/O Speed( 1.0GB )   : 25.8 MB/s
 I/O Speed( 1.0GB )   : 43.5 MB/s
 I/O Speed( 1.0GB )   : 60.9 MB/s
 Average I/O Speed    : 43.4 MB/s
----------------------------------------------------------------------

3.99刀的小鸡，用老版本的脚本超级稳，速度也很快。

**Comment by FemalePresident** [comment]
大佬 有办法使用到更换PIP之前的最后一个版本吗？我记得好像是2.6来着 后面的忘记了...

老版本真的挺稳的，现在换了PIP后，DO家的机器不管怎么安装PY和PIP一直报错，机器直接删除了...

**Comment by Jrohy** [comment]
等下我加个no-pip分支的

**Comment by FemalePresident** [comment]
太感谢了...

**Comment by alililala** [comment]
> 等下我加个no-pip分支的

新版本非得输v2ray-util才行吗？而且还是英文版的。。。看的不舒服，还望大佬能看到。

**Comment by Jrohy** [comment]
新版本输入v2ray就行

**Comment by FemalePresident** [comment]
大佬 不能退回到指定版本吗？我在另外一台VPS上的脚本没有升级，可是查不到版本号...

**Comment by Jrohy** [comment]
@FemalePresident  已新增no-pip分支， https://github.com/Jrohy/multi-v2ray/tree/no-pip

**Comment by Jrohy** [comment]
相应的安装脚本也变了

**Comment by FemalePresident** [comment]
感谢  还是原来的配方，还是原来的味道！！！

**Comment by FemalePresident** [comment]
大佬 我想问下这个分支的话 考虑升级吗？还是算是最终版了？在脚本功能中的升级和通过命令升级一样吗？

**Comment by alililala** [comment]
> 相应的安装脚本也变了

然后手贱又点了里边的脚步升级，然后就又回到原来的问题了。提示找不到

**Comment by alililala** [comment]
> 相应的安装脚本也变了

然后手贱又点了里边的脚步升级，然后就又回到原来的问题了。提示找不到

**Comment by Jrohy** [comment]
内置的更新脚本有个更新地址忘了换，等下推2.7.1版本

**Comment by FemalePresident** [comment]
大佬 能不能考虑下这两种安装方式独立？根据使用者的需求自行选择。

**Comment by alililala** [comment]
> 内置的更新脚本有个更新地址忘了换，等下推2.7.1版本

做了第一批小白鼠23333

**Comment by Jrohy** [comment]
好了，2.7.1推送了，内置更地址也修复正常了

**Comment by alililala** [comment]
> 好了，2.7.1推送了，内置更地址也修复正常了

我比较好奇带pip功能的那个跟这个有功能区别吗？

**Comment by Jrohy** [comment]
@alililala  pip安装的话就不用设置环境变量，像 #152 , #155  这种问题就不会出现，但前提是vps能安装上pip。
功能上的话后期只会向pip的增功能

**Comment by alililala** [comment]
> @alililala pip安装的话就不用设置环境变量，像 #152 , #155 这种问题就不会出现，但前提是vps能安装上pip。
> 功能上的话后期只会向pip的增功能

哦，看来pip的是以后的方向，那带pip的那个会增加中文设置界面不，英文的总是有点不习惯。

**Comment by Jrohy** [comment]
@alililala 会尝试下

**Comment by alililala** [comment]
> @alililala 会尝试下

感谢大佬，等带pip有了中文第一时间尝试。顺便提一下，non-pip分支的这个最新版本每次点脚本升级都会重新安装一次，而不是根据版本号决定需不需要升级。貌似更新逻辑变了

**Comment by FemalePresident** [comment]
大佬  能考虑下非pip作为萌新版或者稳定版，pip作为开发版或者测试版？功能在pip版测试稳定后更新非pip版本吗？

pip在U和D上问题出的很多，一键脚本根本无法适应不同的机器。

**Comment by Jrohy** [comment]
@alililala 因为最新版是3点多版本了, 不能更新到3.0.6的，所以根据版本号决定升级的判断去掉了

**Comment by Jrohy** [comment]
@FemalePresident  非pip版本不会做功能更新,两个版本差异很大的，文件目录不一样，合并代码很麻烦的， 我在master分支加下装不上pip的声明吧

**Comment by alililala** [comment]
> @FemalePresident 非pip版本不会做功能更新,两个版本差异很大的，文件目录不一样，合并代码很麻烦的， 我在master分支加下装不上pip的声明吧

非pip版本设置界面比如只要按个1就进了1的配置了，不需要输回车，而pip版本的需要按一下1再按一下回车才能进去。

**Comment by Jrohy** [comment]
只输入v2ray可以的，只要不是单独pip install v2ray-util安装就行， pip版因为菜单都是换成python 的input方法，所以需要回下车才行

**Comment by alililala** [comment]
> 只输入v2ray可以的，只要不是单独pip install v2ray-util安装就行， pip版因为菜单都是换成python 的input方法，所以需要回下车才行

试了几遍也不行，提示-bash: v2ray: command not found，只能输v2ray-util才能进去。

**Comment by Jrohy** [comment]
@alililala  你执行下 ``which v2ray-util`` 命令，看下v2ray-util安装到什么目录了

**Comment by alililala** [comment]
> which v2ray-util

/usr/local/bin/v2ray-util

**Comment by FemalePresident** [comment]
大佬  我想问下像开头配置图中的机器建议或者适合安装pip版本吗？

**Comment by Jrohy** [comment]
@alililala  执行下应该就可以，确实是个bug，我修改下脚本
ln -s $(which v2ray-util) /usr/local/bin/v2ray

**Comment by alililala** [comment]
> @alililala 执行下应该就可以，确实是个bug，我修改下脚本
> `ln -s $(which v2ray-util) /usr/local/bin/v2ray`

ln: failed to create symbolic link ‘/usr/local/bin/v2ray’: File exists
不行，失败。

**Comment by Jrohy** [comment]
@alililala  先干掉，应该是nopip分支留下的, `rm -f /usr/local/bin/v2ray`

**Comment by Jrohy** [comment]
@FemalePresident 只要安装上Pip就行

**Comment by alililala** [comment]
> @alililala 先干掉，应该是nopip分支留下的, `rm -f /usr/local/bin/v2ray`

bingo   搞定了。

**Comment by Jrohy** [comment]
@alililala  谢谢反馈👍

**Comment by alililala** [comment]
> @alililala 谢谢反馈

客气了，我才是应该谢谢的。大佬辛苦了，现在就差一个中文选项和脚本升级选项了。

**Comment by FemalePresident** [comment]
@Jrohy 大佬 你能上我的机器测试下能不能装pip吗？@uniform_con  这是我电报名

**Comment by Jrohy** [comment]
运行这个会报什么错呢
`python3 <(curl -sL https://bootstrap.pypa.io/get-pip.py)`

**Comment by FemalePresident** [comment]
好像是py和pip3找不到安装文件  稍等   我这安装下再试试

**Comment by FemalePresident** [comment]
@Jrohy 

root@V2Ray:~# python3 <(curl -sL https://bootstrap.pypa.io/get-pip.py)
Collecting pip
  Using cached https://files.pythonhosted.org/packages/d8/f3/413bab4ff08e1fc4828dfc59996d721917df8e8583ea85385d51125dceff/pip-19.0.3-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.0.3
    Uninstalling pip-19.0.3:
      Successfully uninstalled pip-19.0.3
Successfully installed pip-19.0.3
root@V2Ray:~#
看样子是不是没问题？

**Comment by Jrohy** [comment]
看起来好像没啥问题， 只要pip3 命令能用就好

**Comment by FemalePresident** [comment]
现在是要运行source <(curl -sL https://git.io/fNgqx)这条命令还是pip 安装的那个命令？

**Comment by FemalePresident** [comment]
运行pip install v2ray-util后提示

Requirement already satisfied: v2ray-util in /usr/local/lib/python3.5/dist-packages (3.0.6)

**Comment by Jrohy** [comment]
已将安装了

**Comment by FemalePresident** [comment]
如果想实现楼上网友说的免回车功能 必须要在source <(curl -sL https://git.io/fNgqx)这条命令下安装才能运行吗？

**Comment by Jrohy** [comment]
不行的，暂不支持免回车

**Comment by FemalePresident** [comment]
谢谢大佬，占用你一天的时间。现在测试直接输入v2ray可以使用。

谢谢。

**Comment by Jrohy** [comment]
不客气
