### ISSUE TITLE
请问怎么改成中文？

### ISSUE THREAD

**Issue by hkbbdx** [Jrohy/multi-v2ray#163]
原先的机子上装了是中文版的，昨晚装的新机子后发现是英文的。是能用，但是不方便，需要猜

**Comment by anbell2** [comment]
同感，新版3.06改成英文了，不习惯，能改成中文不？

**Comment by Jrohy** [comment]
后面我看下能不能加入中文

**Comment by Jrohy** [comment]
估计这周可以完成中英文切换(python脚本的)

**Comment by Glanwu** [comment]
期待中文和英文切换

**Comment by Jrohy** [comment]
新版已支持中英文切换

**Comment by Jrohy** [comment]
`source <(curl -sL https://git.io/fNgqx) -k --zh`
保留配置安装中文版
