### ISSUE TITLE
tls证书路径错误

### ISSUE THREAD

**Issue by SafariTsai** [Jrohy/multi-v2ray#165]
脚本生成的路径是/root/.acme.sh/域名_ecc/XXXXXX
实际证书路径为/.acme.sh/域名/XXXXX
然后导致v2ray启动失败

**Comment by Jrohy** [comment]
是3.0.6版本吗

**Comment by SafariTsai** [comment]
> 是3.0.6版本吗

是的，不过之前也是这样。用的cloudcone的小鸡centos7，而且不能用websocket+tls不知道和宝塔有没有关系。

**Comment by Jrohy** [comment]
如果之前版本也是不行的话，建议裸机安装了，没测过和宝塔的兼容性

**Comment by SafariTsai** [comment]
估计是宝塔，反正路径改回去就可以了。
