### ISSUE TITLE
 centos7输入v2ray显示-bash: v2ray: command not found

### ISSUE THREAD

**Issue by brunuhvill** [Jrohy/multi-v2ray#166]
centos7安装后，输入v2ray，显示-bash: v2ray: command not found

**Comment by Jrohy** [comment]
是新版3.0.6版本吗

**Comment by DaedalusT** [comment]
我更新到最新脚本以后，v2ray-util就没了，用了pip3 install v2ray-util这个命令以后，只提示已经安装

**Comment by Jrohy** [comment]
@DaedalusT  3.1.0版本也是这样吗

**Comment by Jrohy** [comment]
升级用 `source <(curl -sL https://git.io/fNgqx) -k` 来升试下

**Comment by DaedalusT** [comment]
> 升级用 `source <(curl -sL https://git.io/fNgqx) -k` 来升试下

我试过了，
Requirement already up-to-date: v2ray_util in /usr/local/python3/lib/python3.7/site-packages (3.1.0)
which: no v2ray-util in (/root/.pyenv/shims:/root/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
反馈是这个

**Comment by Jrohy** [comment]
全新安装v2ray-util命令也不可用?

**Comment by DaedalusT** [comment]
> 卸了重新安装
> 全新安装v2ray-util命令也不可用?

rm的时候提示v2ray-util not installed，重新安装还是失败，然后pip3 install也无效。。。

**Comment by Jrohy** [comment]
`pip list`看下有没有, 有的话`pip uninstall v2ray-util`卸载

**Comment by DaedalusT** [comment]
> `pip3 list`看下有没有, 有的话`pip3 uninstall v2ray-util`卸载

尝试了，pip3 list下的确有v2ray-util，卸载完重装跟原来的报错一样。。。

**Comment by Jrohy** [comment]
什么VPS商，python3是自己安装的吗

**Comment by DaedalusT** [comment]
> 什么VPS商，python3是自己安装的吗

搬瓦工的，自己通过wget装的3.7.2版本

**Comment by Jrohy** [comment]
pip是什么版本，其他包能装是吗

**Comment by DaedalusT** [comment]
> pip是什么版本，其他包能装是吗

pip 19.0.3 from /usr/local/python3/lib/python3.7/site-packages/pip (python 3.7)

**Comment by Jrohy** [comment]
可以借VPS来协助安装么，tg联系

**Comment by Jrohy** [comment]
我用vultr 的centos7 来测试, 先用
`bash <(curl -sL https://git.io/fhqMz) --latest` 编译安装3.7.2，
再全新安装中文版，`source <(curl -sL https://git.io/fNgqx) --zh`
也是没问题
`

**Comment by DaedalusT** [comment]
> 我用vultr 的centos7 来测试, 先用
> `bash <(curl -sL https://git.io/fhqMz) --latest` 编译安装3.7.2，
> 再全新安装中文版，`source <(curl -sL https://git.io/fNgqx) --zh`
> 也是没问题
> `

可以了，看样子是Python库的问题？
