### ISSUE TITLE
想写 v2ray 面板来管理 v2ray，请问 v2ray_util/web.py 如何运行呢

### ISSUE THREAD

**Issue by tiseheaini** [Jrohy/multi-v2ray#169]
在 github 上看到 https://github.com/csshuai/multi-v2ray-admin 这个项目，里面有用到 5000 端口的服务
![WX20190321-153912](https://user-images.githubusercontent.com/1763737/54738531-99bbcf00-4bef-11e9-8c15-35b759cd0b40.png)
flask 掌握的知识不是很多，来 issues 来问一下 web.py 如何运行。

**Comment by Jrohy** [comment]
新版这块暂不支持
