### ISSUE TITLE
您好，脚本安装完成之后启动失败，报错如下

### ISSUE THREAD

**Issue by Fwyang1994** [Jrohy/multi-v2ray#17]
`bash multi-v2ray.sh
multi-v2ray.sh: line 7: syntax error near unexpected token `newline'
multi-v2ray.sh: line 7: `<!DOCTYPE html>'`

**Comment by Jrohy** [comment]
安装完后直接打``v2ray``没反应? multi-v2ray.sh这个脚本是用来管理安装卸载更新的

**Comment by Fwyang1994** [comment]
有反应，bash:404:command not find,
恩，系统是debian 9.5

**Comment by Jrohy** [comment]
那可能没装成功，第一次安装建议`source <(curl -sL https://git.io/fNgqx)`

**Comment by Fwyang1994** [comment]
额，，我就是直接复制的这行啊

**Comment by Jrohy** [comment]
什么厂商的debian9.5呢

**Comment by Fwyang1994** [comment]
do的，抱歉我这回复有点慢

**Comment by Jrohy** [comment]
有空我试下这家的

**Comment by Fwyang1994** [comment]
好的，谢谢了。issue我就先关了。

**Comment by Jrohy** [comment]
测试了下没问题do 的debian9.5
