### ISSUE TITLE
语言问题

### ISSUE THREAD

**Issue by alililala** [Jrohy/multi-v2ray#170]
加入的中文安装是全新安装还是保留配置文件的安装？要是全新的就不敢安装啊。里边有配置文件，不想动那些配置文件。

**Comment by Jrohy** [comment]
保留配置安装，现在还没打3.0.7版本的pip包上传，我先试下 #168  能否实现先

**Comment by alililala** [comment]
> 保留配置安装，现在还没打3.0.7版本的pip包上传，我先试下 #168 能否实现先

好的。期待新版。希望新版能有升级脚本的功能。

**Comment by alililala** [comment]
现在可以更新了吗？

**Comment by Jrohy** [comment]
@alililala  可以更新了， `source <(curl -sL https://git.io/fNgqx) -k --zh`
直接更新到中文版保留配置

**Comment by Jrohy** [comment]
当然切换语言在全局配置那里，随时切换都行

**Comment by Jrohy** [comment]
版本是3.1.0 最新， https://pypi.org/project/v2ray-util/

**Comment by alililala** [comment]
> 当然切换语言在全局配置那里，随时切换都行

好吧，已经更新错了，正在恢复

**Comment by alililala** [comment]
已经更新错了。正在恢复。

**Comment by alililala** [comment]
![image](https://user-images.githubusercontent.com/11522340/54775491-18912600-4c49-11e9-86cf-fdc4235c9712.png)
每次更新都需要检查这些吗？

**Comment by alililala** [comment]
![image](https://user-images.githubusercontent.com/11522340/54775654-64dc6600-4c49-11e9-916e-ffedda14ca1b.png)
更新不了，用你上面的代码更新完还是英文。

**Comment by Jrohy** [comment]
3.0.7更新到3.1.0，可以直接 pip install -U v2ray-util

**Comment by alililala** [comment]
还是一样，没成功。

**Comment by alililala** [comment]
![image](https://user-images.githubusercontent.com/11522340/54779069-40848780-4c51-11e9-9a5d-1858f8852753.png)
是不是这个有问题，我看了一下有两个版本。

**Comment by Jrohy** [comment]
有可能，用新一点的python版本安装

**Comment by Jrohy** [comment]
要不pip包降级，新版pip包不支持python3.4了

**Comment by Jrohy** [comment]
更改下安装py3安装逻辑，安装了py3就不会再安装

**Comment by alililala** [comment]
> 更改下安装py3安装逻辑，安装了py3就不会再安装
实在不会操作，老板能远程帮助吗？也不知道问题在哪儿。

**Comment by alililala** [comment]
> 有可能，用新一点的python版本安装

输入Python显示如下，看起来py应该是新版了。
![image](https://user-images.githubusercontent.com/11522340/54806587-6c395900-4cb5-11e9-910c-f94df45d2544.png)

> 更改下安装py3安装逻辑，安装了py3就不会再安装
这个就不太会了。

**Comment by Jrohy** [comment]
可以tg联系，提供vps信息来连接操作么

**Comment by Jrohy** [comment]
可以远程协助，但最好能提供vps信息方便点，可以tg联系

**Comment by alililala** [comment]
可以，大佬你的tg是啥，这是我的https://t.me/leek_shoot
