### ISSUE TITLE
中文安装怎么还是英文呢

### ISSUE THREAD

**Issue by nianjiuren** [Jrohy/multi-v2ray#171]
Iptables流量 没有正常记录过啊 大佬

**Comment by Jrohy** [comment]
别急，pip还是3.0.6版本的，还没打3.0.7版本上传

**Comment by Jrohy** [comment]
#168 我想先看下查看日志能否实现先

**Comment by nianjiuren** [comment]
谢谢，大佬，我说怎么安装都是英文

Jrohy <notifications@github.com>于2019年3月22日 周五00:12写道：

**Comment by Jrohy** [comment]
可以更新了，3.1.0版本

**Comment by Jrohy** [comment]
支持中英文切换

**Comment by Jrohy** [comment]
@nianjiuren Iptables流量统计已恢复
