### ISSUE TITLE
能否增加对Raspbian的支持

### ISSUE THREAD

**Issue by jasonchu024** [Jrohy/multi-v2ray#177]
pi@pi:~ $ cat /etc/issue
Raspbian GNU/Linux 9 \n \l

**Comment by Jrohy** [comment]
没有机器，也没玩过😂

**Comment by jasonchu024** [comment]
那我自己fork一份耍耍

**Comment by jasonchu024** [comment]
试了一下可以的。在multi-v2ray.sh和py3_install.sh的checkSys里加一段Raspbian识别代码就可以了

    elif [[ $(cat /etc/issue | grep Raspbian) ]];then
        OS='Raspbian'
        PACKAGE_MANAGER='apt-get'

加一下？

**Comment by Jrohy** [comment]
可以，你提下PR都行

**Comment by Jrohy** [comment]
@jasonchu024 已添加
