### ISSUE TITLE
GCP安装本脚本中文版无法启动

### ISSUE THREAD

**Issue by panjian-win** [Jrohy/multi-v2ray#179]
我在google的实例中全新安装中文版脚本
遇到这个问题
特向大佬请教！

-bash: v2ray: command not found
please input 'v2ray' command to manage v2ray

[root@google ~]# v2ray
-bash: v2ray: command not found

**Comment by Jrohy** [comment]
v2ray-util命令可以用吗， 是最新v3.1.0版本吗

**Comment by Mizeron** [comment]
> v2ray-util命令可以用吗， 是最新v3.1.0版本吗

我和lz一样的情况，但我是在v2ray更新脚本后出现的。运行你说的这个命令就能出菜单了，回报一下。

另外，更新完脚本后，全局设置的6.更新脚本 不见了，变成了现在的切换语言了。是否以后更新脚本需要输入教程里的那条更新的命令了？

**Comment by Jrohy** [comment]
@Mizeron 因为换成py来操作更新，所以暂时不能设置更新脚本，只能通过更新脚本命令来更新
