### ISSUE TITLE
请教，如何修改IP地址

### ISSUE THREAD

**Issue by sll523911** [Jrohy/multi-v2ray#181]
这套程序感觉有个比较大的不便就是一旦修改了服务器的IP地址后，配置不会随地址的变更而改变，目前没有发现该如何修改，希望提供便捷入口，指导如何进行修改操作，谢谢！

**Comment by Jrohy** [comment]
/etc/v2ray_util/util.cfg 直接改配置文件

**Comment by yanyoyos** [comment]
/etc/v2ray_util/util.cfg这个文件里并没有设置IP地址的代码呀，/etc/v2ray/config.json也没有，可以告诉我IP地址到底在哪改的吗，万分感谢!!!

**Comment by jasonchu024** [comment]
> /etc/v2ray_util/util.cfg

这个文件里并没有IP地址，有domain，要改哪个呢？
