### ISSUE TITLE
代码提供的时间服务器访问失败

### ISSUE THREAD

**Issue by jasonchu024** [Jrohy/multi-v2ray#182]
换pool.ntp.org是可以的

# ntpdate time.nist.gov
29 Mar 22:22:28 ntpdate[22256]: no server suitable for synchronization found
# ntpdate pool.ntp.org
29 Mar 22:27:26 ntpdate[22312]: adjust time server 85.199.214.101 offset -0.001401 sec

**Comment by Jrohy** [comment]
已更改
