### ISSUE TITLE
请问如何修改vmess链接里的IP地址

### ISSUE THREAD

**Issue by yanyoyos** [Jrohy/multi-v2ray#186]
我用来搭飞机的服务器有ipv4和ipv6两个ip地址，创建时默认用的是ipv4的地址，我想改成ipv6的地址。已经试过不对服务器修改，直接把v2rayN里的服务器IP换成ipv6地址可以连上使用。但是现在我想把服务器里的配置文件也改一下，使生成的vmess链接中对应的IP为ipv6地址，以及通过飞机访问其他网站时显示的也为服务器的ipv6地址，在/etc/v2ray_util/util.cfg，/etc/v2ray/config.json并没有找到相关的设置项，也不知道vmess的配置文件在哪，请问我应该在哪里修改？万分感谢！！！

**Comment by Jrohy** [comment]
程序不支持ipv6目前， 毕竟我也没用过😂

**Comment by yanyoyos** [comment]
好吧，谢谢了
