### ISSUE TITLE
默认安装后 日志里面存在大量failed

### ISSUE THREAD

**Issue by EnzoTools** [Jrohy/multi-v2ray#192]
source <(curl -sL https://git.io/fNgqx) --zh
使用这个命令安装完成后，查看日志
tail -f /var/log/v2ray/* | grep failed

会发现有大量的失败：
`2019/05/06 01:30:47 [Info] [4140274332] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/05/06 01:30:47 [Info] [4140274332] v2ray.com/core/common/mux: session 11 ends. > io: read/write on closed pipe
2019/05/06 01:30:47 [Info] [4140274332] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/05/06 01:30:47 [Info] [4140274332] v2ray.com/core/common/mux: session 12 ends. > io: read/write on closed pipe
2019/05/06 01:30:47 [Info] [4140274332] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/05/06 01:30:47 [Info] [4140274332] v2ray.com/core/common/mux: session 10 ends. > io: read/write on closed pipe`

目前环境：

服务器：阿里云轻量服务器（VPS）香港地区 34元/月
系统：CentOS 7.3
模式：TCP、KCP-WECHAT-VIDEO、KCP+DTLS等模式都存在该问题，其他模式没测试
没安装BBR/锐速
开启/关闭 TLS依然这样
TCP/UDP端口全部都放行了，没设拦截规则
selinux、firewalld也都已经关闭掉了
----------
客户端使用v2rayN以及v2rayNG也都存在该问题

配置：
Group: A
IP: hk01.xxxxx.xxxxx(秘密)
Port: 30756
TLS: 开启
UUID: 285f7c6e-6f56-11e9-95cf-00163e020cfd
Alter ID: 16
Network: kcp dtls

config.json
`{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "info"
  },
  "inbounds": [
    {
      "port": 30756,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "285f7c6e-6f56-11e9-95cf-00163e020cfd",
            "alterId": 16
          }
        ]
      },
      "streamSettings": {
        "network": "kcp",
        "security": "tls",
        "tlsSettings": {
          "certificates": [
            {
              "certificateFile": "/home/ssl/fullchain1.pem",
              "keyFile": "/home/ssl/privkey1.pem"
            }
          ]
        },
        "tcpSettings": {},
        "httpSettings": {},
        "kcpSettings": {
          "mtu": 1350,
          "tti": 50,
          "uplinkCapacity": 100,
          "downlinkCapacity": 100,
          "congestion": false,
          "readBufferSize": 2,
          "writeBufferSize": 2,
          "header": {
            "type": "dtls"
          }
        },
        "wsSettings": {},
        "quicSettings": {}
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "ip": [
          "0.0.0.0/8",
          "10.0.0.0/8",
          "100.64.0.0/10",
          "169.254.0.0/16",
          "172.16.0.0/12",
          "192.0.0.0/24",
          "192.0.2.0/24",
          "192.168.0.0/16",
          "198.18.0.0/15",
          "198.51.100.0/24",
          "203.0.113.0/24",
          "::1/128",
          "fc00::/7",
          "fe80::/10"
        ],
        "outboundTag": "blocked"
      }
    ]
  }
}
`

**Comment by EnzoTools** [comment]
忘记说了，可以正常使用，只是这大量的field一直在日志里面刷屏
调试了四个小时，找了网上众多资料还没能解决掉

**Comment by Jrohy** [comment]
有可能墙的问题

**Comment by Jrohy** [comment]
可以向官方v2ray反馈下

**Comment by EnzoTools** [comment]
你们也有这种问题吗？昨晚我换了其他服务器商也有这个问题。

**Comment by Jrohy** [comment]
翻墙速度快吗，如果不慢就没关系

**Comment by EnzoTools** [comment]
翻墙速度快，但经常断流。

**Comment by EnzoTools** [comment]
[https://github.com/v2ray/v2ray-core/issues/1614](url)

参考这个，开发者给出的建议是使用TCP协议，放弃UDP

看到自己监听端口里的 udp6陷入沉思... 

我换个协议试试看

**Comment by EnzoTools** [comment]
没解决掉
