### ISSUE TITLE
开启后tls无法连接

### ISSUE THREAD

**Issue by longchena** [Jrohy/multi-v2ray#194]
开启后tls无法连接，用的自动创建证书，查看log提示:
v2ray.com/core/proxy/vmess/encoding: failed to read request header > remote error: tls: bad certificate

**Comment by Jrohy** [comment]
生成证书过程中有报错么

**Comment by longchena** [comment]
创建过程中没有报错
-----
please input group alphabet to modify tls: B
group tls status: open


1.open TLS
2.close TLS
please select: 1
1. Let's Encrypt certificate(auto create, please prepare domain)
2. Customize certificate(prepare certificate file paths)

please select: 1
local vps ip address: ****
please input your vps domain: ***.xyz

auto generate SSL certificate, please wait..
[Mon May 20 17:10:09 CST 2019] Domains not changed.
[Mon May 20 17:10:09 CST 2019] Skip, Next renewal time is: Mon Jul  1 21:50:32 UTC 2019
[Mon May 20 17:10:09 CST 2019] Add '--force' to force to renew.
v2ray restart success !

**Comment by huxingchuan573** [comment]
把客户端端口改443看能不能连
