### ISSUE TITLE
Centos 7 X86 64 Minimal 安装后报酬 没有“v2ray"命令

### ISSUE THREAD

**Issue by jfc8000** [Jrohy/multi-v2ray#195]
以前安装是正常的
脚本升级后就提示错误 top命令可以看到 v2ray 进程是运行的

**Comment by Jrohy** [comment]
`v2ray-util`命令有吗

**Comment by Jrohy** [comment]
可以运行下`pip list` 看下有没有安装到v2ray-util, 新版依赖于https://pypi.org/project/v2ray-util/

**Comment by jfc8000** [comment]
v2ray-util 可以调出管理界面 但是 无法添加用户
返回如下
1.新增用户
2.新增端口
3.删除用户
4.删除端口

请选择: 1
Traceback (most recent call last):
  File "/usr/bin/v2ray-util", line 10, in <module>
    sys.exit(menu())
  File "/usr/lib/python3.6/site-packages/v2ray_util/main.py", line 246, in menu
    user_manage()
  File "/usr/lib/python3.6/site-packages/v2ray_util/main.py", line 160, in user_manage
    multiple.new_user()
  File "/usr/lib/python3.6/site-packages/v2ray_util/config_modify/multiple.py", line 54, in new_user
    gs = GroupSelector(_('user number'))
  File "/usr/lib/python3.6/site-packages/v2ray_util/util_core/selector.py", line 82, in __init__
    self.group = self.group_list[0]
IndexError: list index out of range

**Comment by jfc8000** [comment]
错了 可以配置 上面是 因为没有添加“端口”

**Comment by Jrohy** [comment]
`ln -s $(which v2ray-util) /usr/local/bin/v2ray`

**Comment by jfc8000** [comment]
[root@DefiniteMelodic-VM ~]# ln -s $(which v2ray-util) /usr/local/bin/v2ray
-bash: which: command not found
ln: failed to create symbolic link './v2ray': File exists

**Comment by jfc8000** [comment]
[root@DefiniteMelodic-VM ~]# v2ray
-bash: v2ray: command not found

**Comment by Jrohy** [comment]
之前安装过了其他脚本么

**Comment by Jrohy** [comment]
/usr/local/bin/v2ray 可以移走这个文件再创建

**Comment by jfc8000** [comment]
新装的系统 
/usr/local/bin 下面是空的没有 v2ray

**Comment by Jrohy** [comment]
看漏了是which命令没有😂

**Comment by jfc8000** [comment]
复制的你的命令
[root@DefiniteMelodic-VM ~]# ln -s $(which v2ray-util) /usr/local/bin/v2ray
-bash: which: command not found

**Comment by Jrohy** [comment]
type v2ray-uti
看下type命令有没有，查看下v2ray-util的安装位置，然后ln -s /xxx/v2ray-util /usr/local/bin/v2ray

**Comment by jfc8000** [comment]
谢谢指教  已经解决
其实就是 which 命令没有安装

[root@DefiniteMelodic-VM ~]# v2ray

欢迎使用 v2ray-util 管理程序

1.服务管理              2.用户管理

3.更改配置              4.查看配置

5.全局功能              6.更新V2Ray

7.生成客户端配置文件

请选择:

**Comment by xiechangan123** [comment]
最近低调点，勿更新，最好七月开始更新。不想看到大佬删库跑路，或者说等我学会shell和python你再跑路

**Comment by Jrohy** [comment]
@xiechangan123 有什么好建议好功能吗，确实没什么好点子来更新😂

**Comment by xiechangan123** [comment]
v2ray在k2p路由器官改固件中，需要自定义入口端口和模式，  "protocol": "dokodemo-door",
    "port": 1234",这个脚本就不能很好适应了。还需要自己手动改，我是没改成功的。。。。所以需要菜单有这个开关，方便填入。padavan好像也是要如上类似设置的，因为失败过，就没折腾老毛子。。。
参考https://www.right.com.cn/forum/thread-373412-1-1.html

**Comment by rhotov** [comment]
> v2ray在k2p路由器官改固件中，需要自定义入口端口和模式， "protocol": "dokodemo-door",
> "port": 1234",这个脚本就不能很好适应了。还需要自己手动改，我是没改成功的。。。。所以需要菜单有这个开关，方便填入。padavan好像也是要如上类似设置的，因为失败过，就没折腾老毛子。。。
> 参考https://www.right.com.cn/forum/thread-373412-1-1.html

并不用改，这个脚本跑完之后，K2P里直接填配置文件就行，服务器json不用做任何改动。
