### ISSUE TITLE
开启tls错误

### ISSUE THREAD

**Issue by paniy** [Jrohy/multi-v2ray#196]
开启时报错如下：
[Fri May 17 23:27:51 CST 2019] Please install socat tools first.
[Fri May 17 23:27:51 CST 2019] _on_before_issue.

**Comment by Jrohy** [comment]
我测试下

**Comment by Jrohy** [comment]
已加依赖， `source <(curl -sL https://git.io/fNgqx) -k` 更新下

**Comment by paniy** [comment]
感谢

**Comment by paniy** [comment]
开启似乎依旧有错误，日志如下：
[Fri May 17 23:56:28 CST 2019] xxx.com:Verify error:Fetching http://xxx.com/.well-known/acme-challenge/EVcMD066uXMKcsIe3oReJies9-ssbfyqDaShfBsFoRI: Error getting validation data
[Fri May 17 23:56:28 CST 2019] Please add '--debug' or '--log' to check more details.
[Fri May 17 23:56:28 CST 2019] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

**Comment by Jrohy** [comment]
ok, 我测试下

**Comment by Jrohy** [comment]
bash /root/.acme.sh/acme.sh  --issue -d $domain  --standalone  --keylength ec-256
程序核心签证书的命令，测试了下确实不行

**Comment by Jrohy** [comment]
可以换下其他域名试试

**Comment by Jrohy** [comment]
curl https://get.acme.sh | sh
bash /root/.acme.sh/acme.sh --issue -d $domian --standalone --keylength ec-256
可以这样测试生成证书

**Comment by paniy** [comment]
不好意思，测试后问题在于没有开放80端口。无法访问日志目录，导致错误。

**Comment by 1608637229** [comment]
遇到一样的错误啊。debian 9怎么开放端口。请教下
