### ISSUE TITLE
无法导入配置到v2ray客户端

### ISSUE THREAD

**Issue by veryrich** [Jrohy/multi-v2ray#198]
![image](https://user-images.githubusercontent.com/12951051/58533468-3667a200-821b-11e9-83b0-09f3f885fe4f.png)

导入后点击确定提示这个，客户端版本V2rayX Version 1.5.1 (1278)

**Comment by Jrohy** [comment]
生成的配置文件仅适合于原生的v2ray使用, vmess字符串则适合于v2rayN
