### ISSUE TITLE
 一些网站不能再PAC模式下直接访问

### ISSUE THREAD

**Issue by forgotmymilk** [Jrohy/multi-v2ray#199]
整个维基百科
quora
reddit
这些早就被Q了，应该要添加到代理列表吧？

**Comment by Jrohy** [comment]
你客户端设置么，我v2rayN一直都没问题

**Comment by Jrohy** [comment]
你可以看下服务器端v2ray设置，除了常规内网的屏蔽，默认路由什么黑名单、白名单都不会去做设置，这些都是留给使用者根据意愿来自行设置的，包括广告屏蔽

**Comment by Jrohy** [comment]
所以服务器端所有网站流量都是走代理的

**Comment by forgotmymilk** [comment]
我用的v2rayN v2.9版本，默认pac没动，上面说的那些网站无法访问。我找了一个白名单PAC，quora 能在PAC启动下访问，但是reddit和wikipedia还是不行，非得访问的时候去开启一下全局。访问完，有去改成PAC模式。挺烦的。

**Comment by Jrohy** [comment]
可以换下233脚本搭建试试
