### ISSUE TITLE
在 hiveOS 安裝時出現 "cannot execute binary file"

### ISSUE THREAD

**Issue by Prof684** [Jrohy/multi-v2ray#20]
用 bash curl -sL https://git.io/fNgqx 時就出現:

/usr/bin/curl: /usr/bin/curl: cannot execute binary file

是不可以安裝在 hiveOS 嗎?

**Comment by Jrohy** [comment]
检查下curl有没安装

**Comment by Prof684** [comment]
之前已經檢查了, curl 有安裝:

root@Rig1:~# sudo apt install curl
Reading package lists... Done
Building dependency tree
Reading state information... Done
curl is already the newest version (7.47.0-1ubuntu2.8).
0 upgraded, 0 newly installed, 0 to remove and 42 not upgraded.

上網查了也有人說 "cannot execute binary file" 有可能跟 32 bit / 64 bit 有關

**Comment by Jrohy** [comment]
![image](https://user-images.githubusercontent.com/12463263/43756380-f1ea1624-9a46-11e8-9b58-dfbf5b18aca8.png)
就这个v2ray程序，其实不是二进制的，改名为v2ray.sh看下能不能执行

**Comment by Prof684** [comment]
我用了: git clone https://github.com/Jrohy/multi-v2ray
之後 :  cd multiv2ray
然後:  v2ray

就可以执行, 但是我在使用"查看配置"等功能的時候就出現: bash: /usr/local/bin/v2ray: No such file or directory

是不是我 clone 的 destination 有問題?

**Comment by Jrohy** [comment]
将v2ray文件复制到/usr/local/bin目录
