### ISSUE TITLE
有没有办法让这个启用全局代理，路由器中

### ISSUE THREAD

**Issue by forgotmymilk** [Jrohy/multi-v2ray#200]
就是在服务器中设置，默认全局代理，通过服务器的无论客户端选择PAC还是其他模式，都是全局。主要是用在路由器中，路由器有一个V2RAY的插件，但是没有设置项，无法设置全局。所以想问下，能否把这个功能直接坐到服务器里，这样只有有客户端连接，全都走代理。

**Comment by Jrohy** [comment]
服务器端默认就是全局代理，除了那些内网屏蔽外，估计你是客户端没设置好
