### ISSUE TITLE
升级报错

### ISSUE THREAD

**Issue by zlylong** [Jrohy/multi-v2ray#201]
Looking in indexes: http://sg.mirrors.cloud.aliyuncs.com/pypi/simple/
Requirement already up-to-date: v2ray_util in /usr/local/lib/python3.7/site-packages (3.0.1)
Requirement already satisfied, skipping upgrade: pyOpenSSL in /usr/local/lib/python3.7/site-packages (from v2ray_util) (19.0.0)
Requirement already satisfied, skipping upgrade: six>=1.5.2 in /usr/local/lib/python3.7/site-packages (from pyOpenSSL->v2ray_util) (1.12.0)
Requirement already satisfied, skipping upgrade: cryptography>=2.3 in /usr/local/lib/python3.7/site-packages (from pyOpenSSL->v2ray_util) (2.5)
Requirement already satisfied, skipping upgrade: asn1crypto>=0.21.0 in /usr/local/lib/python3.7/site-packages (from cryptography>=2.3->pyOpenSSL->v2ray_util) (0.24.0)
Requirement already satisfied, skipping upgrade: cffi!=1.11.3,>=1.8 in /usr/local/lib/python3.7/site-packages (from cryptography>=2.3->pyOpenSSL->v2ray_util) (1.11.5)
Requirement already satisfied, skipping upgrade: pycparser in /usr/local/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.3->pyOpenSSL->v2ray_util) (2.19)

**Comment by Jrohy** [comment]
pip uninstall v2ray_util

**Comment by zlylong** [comment]
仍然无法更新到最新版。

root@iZt4n32jby4d2elap0p0y2Z:~#
root@iZt4n32jby4d2elap0p0y2Z:~# pip3 uninstall v2ray_util
Uninstalling v2ray-util-3.0.1:
  Would remove:
    /usr/local/bin/v2ray-util
    /usr/local/lib/python3.6/dist-packages/v2ray_util-3.0.1.dist-info/*
    /usr/local/lib/python3.6/dist-packages/v2ray_util/*
  Would not remove (might be manually added):
    /usr/local/lib/python3.6/dist-packages/v2ray_util/util.dat
Proceed (y/n)? y
  Successfully uninstalled v2ray-util-3.0.1
root@iZt4n32jby4d2elap0p0y2Z:~# pip3 install -U v2ray_util
Looking in indexes: http://sg.mirrors.cloud.aliyuncs.com/pypi/simple/
Collecting v2ray_util
  Downloading http://sg.mirrors.cloud.aliyuncs.com/pypi/packages/22/2d/7cda24c444934bd25b3659d10365cb0b9a898b3231f8dcff00b8025351d1/v2ray_util-3.0.1-py3-none-any.whl (55kB)
    100% |████████████████████████████████| 61kB 15.6MB/s
Requirement already satisfied, skipping upgrade: pyOpenSSL in /usr/local/lib/python3.6/dist-packages (from v2ray_util) (19.0.0)
Requirement already satisfied, skipping upgrade: six>=1.5.2 in /usr/lib/python3/dist-packages (from pyOpenSSL->v2ray_util) (1.11.0)
Requirement already satisfied, skipping upgrade: cryptography>=2.3 in /usr/local/lib/python3.6/dist-packages (from pyOpenSSL->v2ray_util) (2.5)
Requirement already satisfied, skipping upgrade: cffi!=1.11.3,>=1.8 in /usr/local/lib/python3.6/dist-packages (from cryptography>=2.3->pyOpenSSL->v2ray_util) (1.11.5)
Requirement already satisfied, skipping upgrade: asn1crypto>=0.21.0 in /usr/local/lib/python3.6/dist-packages (from cryptography>=2.3->pyOpenSSL->v2ray_util) (0.24.0)
Requirement already satisfied, skipping upgrade: pycparser in /usr/local/lib/python3.6/dist-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.3->pyOpenSSL->v2ray_util) (2.19)
Installing collected packages: v2ray-util
Successfully installed v2ray-util-3.0.1

**Comment by zlylong** [comment]
感觉是被劫持了。

**Comment by Jrohy** [comment]
pip 源不是官方的， 阿里云新加坡..

**Comment by zlylong** [comment]
换了清华源就正常了。非常感谢您！
