### ISSUE TITLE
WS+TLS隔一段时间后就无法使用了

### ISSUE THREAD

**Issue by Kaze1027** [Jrohy/multi-v2ray#202]
我使用了Cloudfalre来隐藏IP，不过我刚刚搭建的时候能用，过一会儿就不能用了，v2rayNG客户端下面的提示信息是：
failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.kaze.space:777/XJ9Lgjrl/):  > dial tcp 216.24.184.235:777: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed。

**Comment by Kaze1027** [comment]
访问/www.kaze.space:777/XJ9Lgjrl/会提示：Client sent an HTTP request to an HTTPS server.

**Comment by roxsky** [comment]
你WS+TLS怎么开的?我没找到可以开这个配置的选项啊.

**Comment by Jrohy** [comment]
先切换成ws，再开启tls

**Comment by DRRoJohn** [comment]
我也出现了这样的问题，请问你解决了吗？

**Comment by Jrohy** [comment]
这个向v2ray官方反应下，脚本只是方便修改json

**Comment by Kaze1027** [comment]
> 这个向v2ray官方反应下，脚本只是方便修改json

好的，谢谢

**Comment by WoChen5770** [comment]
我这边的问题是 不管什么传输方式，只要机器重启了，日志就显示认证失败，要手动进脚本重启下V2RAY才可以。

**Comment by sportfit** [comment]
不得不说使用到现在，这个ws+tls很正常，前些日子七七八八折腾其它脚本，搞到宕机. it's awesome.,thks

**Comment by lv4lv** [comment]
CDN里flexible改成full试试
