### ISSUE TITLE
没有办法使用caddy反向代理v2, 是因为这个脚本不支持吗

### ISSUE THREAD

**Issue by hbc007** [Jrohy/multi-v2ray#204]
v2和caddy都确认配置好了, 可以直接连v2的端口, 也可以通过caddy正常访问网页, 但是caddy里配置的proxy没有办法正常使用

```
https://域名
{
    tls 邮箱
    log /var/log/caddy/v2.log
    root /var/www/
    proxy /brkWall https://localhost:8200 {
        insecure_skip_verify
        header_upstream X-Forwarded-Proto "https"
        header_upstream Host {Host}
    }
}
```

而且这两个服务的日志都没有记录出错, 客户端记录
`[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status405] > v2ray.com/core/common/retry: all retry attempts failed`

**Comment by Jrohy** [comment]
没测试过这方面的，脚本只是修改v2ray json而已
