### ISSUE TITLE
开启tls失败

### ISSUE THREAD

**Issue by huxingchuan573** [Jrohy/multi-v2ray#206]
过程如下：
root@ localhost:"# v2ray tls
group tls status: close

1. open TLS
2. close TLS 

please select:1
1. Let's Encrypt certificate(auto create, please prepare domain)
2. Customize certificate(prepare certificate file paths)

please select:1
local vps ip address:67.*.*.2

please input your vps domain:v2ray. *.cf 
domain can't analysis to local ip!!!
 
v2ray restart success !

**Comment by Jrohy** [comment]
你在vps ping下域名，看下是否匹配上机器ip
