### ISSUE TITLE
大佬 能不能加入nginx 走cdn

### ISSUE THREAD

**Issue by gboys90** [Jrohy/multi-v2ray#207]
最近功夫网发威了  死了一堆 实在没法了  只能走CDN  这个脚本不好走cdn  有点麻烦 大佬能否考虑加入下nginx或者Caddy

**Comment by roxsky** [comment]
我也是刚想提这个建议的，就看到你发的issue了，希望大佬能提供下caddy或者nginx，现在如果不隐藏的话很容易出问题。

**Comment by rainbowshine521** [comment]
我也是准备提这个建议的，看到这里就直接留言了。希望大佬能考虑一下这个需求~

**Comment by linGinc** [comment]
我也是想发这个的，用WS加nginx或者caddy走CDN，现在救活了我被ban的IP，但还是比较喜欢您的脚本的，期待加入这个

**Comment by sportfit** [comment]
虽然这个没用过，但是被吓到了，非常期待大佬脚本里能增加这个。到目前为止还没被ban过ip，这与我良好的使用习惯有莫大关系，服务端该做的防护全上了，桌面及移动端没任何国产软件，浏览器必须firefox加持隐私插件，晚上移动端尽量不要用

**Comment by sportfit** [comment]
虽然这个没用过，但是被吓到了，非常期待大佬脚本里能增加这个。到目前为止还没被ban过ip，我的使用习惯比较好，服务端该做的防护全上了，桌面及移动端没任何毒瘤，浏览器必须firefox加持隐私插件，晚上移动端尽量不要用，最最最重要的是杜绝热门vps

**Comment by Hi-Peanut** [comment]
这个脚本配合宝塔BT我弄成功了WS+TLS+CF的CDN，我参考的这个教程https://imtrq.com/archives/1487

**Comment by DeSireFire** [comment]
> 这个脚本配合宝塔BT我弄成功了WS+TLS+CF的CDN，我参考的这个教程https://imtrq.com/archives/1487

如果可以的话，可否分享你的nginx配置文件和v2ray配置文件？最好带上它们的版本号..
想进行一下对照
昨天折腾了快一整天，崩溃了

**Comment by DeSireFire** [comment]
已解决!

**Comment by Jrohy** [comment]
3.5版本开始支持80端口或者443端口直接走cdn,无需caddy或者nginx
