### ISSUE TITLE
安装完成出现-bash: python3: command not found

### ISSUE THREAD

**Issue by kinkinparkscar** [Jrohy/multi-v2ray#21]
搬瓦工centOS 7,   安装完成出现不显示配置信息，出现-bash: python3: command not found

**Comment by Jrohy** [comment]
yum install epel-release
yum install python34
再试下安装python3

**Comment by Jrohy** [comment]
新版提高centos7 python3的安装成功率了

**Comment by wang125606757** [comment]
同求   搬瓦工centos7
[root@host ~]# yum install epel-release
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.scalabledns.com
 * elrepo-kernel: repos.dfw.lax-noc.com
 * extras: mirror.hostduplex.com
 * ius: mirrors.kernel.org
 * updates: mirror.fileplanet.com
Package epel-release-7-11.noarch already installed and latest version
Nothing to do
[root@host ~]# yum install python34
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.scalabledns.com
 * elrepo-kernel: repos.dfw.lax-noc.com
 * extras: mirror.hostduplex.com
 * ius: mirrors.kernel.org
 * updates: mirror.fileplanet.com
No package python34 available.
Error: Nothing to do
