### ISSUE TITLE
建议增加后台保活机制

### ISSUE THREAD

**Issue by Googleing** [Jrohy/multi-v2ray#212]
不知道为什么，隔一段时间就连不上了，与此同时ssr链接正常。
去重启服务之后，一切正常。
判断应该是后台掉了。

**Comment by Jrohy** [comment]
脚本只是改json，无法判断此代理外部能否用😂，如果一段时间代理无法用就看日志然后和官方反馈

**Comment by Googleing** [comment]
能不能弄个定时重启任务呢？doub的ssr脚本就支持定时重启保活。

**Comment by Jrohy** [comment]
@Googleing 设置每天定时更新即可，更新完都会重启下v2ray

**Comment by Googleing** [comment]
有点尴尬😂 流量统计开启就不能自动更新了……

顺便问一下你这个脚本的 json 配置路径是哪里，我想改下某个参数，按官方文档的 /etc/v2ray/config.json 找不到

**Comment by Jrohy** [comment]
确实就是这个路径`/etc/v2ray/config.json`
v2ray流量统计重启就会流量统计重置的，可以用iptable的统计流量方式

**Comment by Googleing** [comment]
嗯，可能是宝塔的权限问题昨天没显示路径，目前已解决。
重启功能我感觉也可以通过宝塔的定时任务解决。
