### ISSUE TITLE
希望增加账号禁用或流量用量限制功能

### ISSUE THREAD

**Issue by Googleing** [Jrohy/multi-v2ray#216]
多人使用的时候，感觉还是需要这个功能，便于控制。

**Comment by Jrohy** [comment]
流量限制向官方反馈下，脚本就是方便改Json而已

**Comment by Googleing** [comment]
那账号禁用能不能实现一下。
以及重启就会清空流量记录这个也有点头疼。

**Comment by Jrohy** [comment]
可以用iptables统计流量就不会重启重置了

**Comment by Googleing** [comment]
明白，但是😂这样就不能共用多人共用端口了，想走cloudflare，支持的端口数量有限

**Comment by Jrohy** [comment]
重启不重置只能向v2ray官方提，也是调用其api来查询的

**Comment by 1608637229** [comment]
> 那账号禁用能不能实现一下。
> 以及重启就会清空流量记录这个也有点头疼。

重启重置感觉等于废了一半这个流量统计功能。。不过没办法，v2ray自己不支持
