### ISSUE TITLE
最新的 v2ray cdn 模式和 ws 有什么区别

### ISSUE THREAD

**Issue by yesmiley** [Jrohy/multi-v2ray#221]
😂 我感觉和以前的 websocket 模式是一样的吧？

**Comment by Jrohy** [comment]
其实封装多一层，会顺便帮改了端口和保存域名，80端口的也需要域名

**Comment by Googleing** [comment]
😂可是我在用原来的版本 ws也需要制定域名，只不过好像是个摆设，任何域名都可以用，所以也相当于可以实现直连和cdn并存了
手动设置80/443然后开cdn应该是一样的吧

**Comment by Jrohy** [comment]
嗯嗯只是方便直接开
