### ISSUE TITLE
请问大佬ws+TLS走CDN能多端口吗？

### ISSUE THREAD

**Issue by zhuhuan124** [Jrohy/multi-v2ray#222]
RT，我用了一个端口能正常工作，但是多开了几个端口以后就报错[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination

**Comment by Jrohy** [comment]
journalctl  -xe看下是否端口占用，比如已经开了一个443端口的，就不能再开多个443端口，可以开个80端口

**Comment by zhuhuan124** [comment]
> journalctl -xe看下是否端口占用，比如已经开了一个443端口的，就不能再开多个443端口，可以开个80端口

。。。大佬，能看 Caddy是否正常工作吗？之前我自己装的caddy，现在重装了系统直接用的这个一键脚本里面的，但是我发现caddy好像并没有工作。也不能套cf

**Comment by Jrohy** [comment]
并没有安装caddy和nginx的，直接v2ray 的ws + tls

**Comment by zhuhuan124** [comment]
> 并没有安装caddy和nginx的，直接v2ray 的ws + tls

但是直接ws+tls会被墙吗。。今天上午我看见微博说北京理工大学有人注册专利检测v2ray的特征

**Comment by Jrohy** [comment]
有走cdn的，用命令`v2ray cdn`, 我都是用被墙的ip套cdn来翻，80端口速度还可以
