### ISSUE TITLE
error running on docker

### ISSUE THREAD

**Issue by emfox** [Jrohy/multi-v2ray#223]
here is the log:

emfox@sss:~/v2ray$ sudo docker exec -it v2ray v2ray start
/bin/sh: service: not found
v2ray start fail !

**Comment by emfox** [comment]
and another:

emfox@sss:~/v2ray$ sudo docker exec -it v2ray v2ray add
random generate (srtp | wechat-video | utp | dtls) fake header, new protocol: dtls

random generate port 65327, enter to use, or input customize port: 80

new port: 80

add port group success!
/bin/sh: iptables: not found
sh: iptables: not found
sh: iptables: not found
sh: iptables: not found
sh: iptables: not found
/bin/sh: iptables: not found
sh: iptables: not found
sh: iptables: not found
sh: iptables: not found
sh: iptables: not found
/bin/sh: service: not found

**Comment by emfox** [comment]
maybe we should use debain instead of alpine?

**Comment by Jrohy** [comment]
restart v2ray, u should restart container`docker restart v2ray` after change v2ray config.json

**Comment by emfox** [comment]
> restart v2ray, u should restart container`docker restart v2ray` after change v2ray config.json

Thanks.
So we suppose not to use start stop or new on docker mode, right? please consider document this.

**Comment by Jrohy** [comment]
will have new version to friendly docker

**Comment by Jrohy** [comment]
3.6.5 version fix it !!! @emfox 
u can restart v2ray in container

**Comment by emfox** [comment]
this works:
`docker exec -it v2ray bash`
`v2ray start`

but this doesn't work:
`docker exec -t v2ray v2ray start`

just get the result 'v2ray start success !' but actually no v2ray process running.

**Comment by Jrohy** [comment]
u should run command in container
enter container and run command

**Comment by emfox** [comment]
> u should run command in container
> enter container and run command

ok
