### ISSUE TITLE
安装问题！Centos7！

### ISSUE THREAD

**Issue by Bobo-cats** [Jrohy/multi-v2ray#224]
error：
安装中文版..

/proc/self/fd/11:136: parse error near `]]'

!

**Comment by Jrohy** [comment]
什么vps商的centos7

**Comment by Bobo-cats** [comment]
瓦工!

**Comment by Jrohy** [comment]
我也是用瓦工的centos7搭建，没遇到过这问题😂

**Comment by Bobo-cats** [comment]
TG有群不？ 我想进去!  我搜了问题，可能是zsh  if[ ]  不能为空!

**Comment by Bobo-cats** [comment]
zsh问题! bash就可以! 大佬可以检查下zsh部分的代码! 语法方面可能存在错误!

**Comment by Jrohy** [comment]
并没有zsh代码的，shell都是在bash平台上开发，没有测试zsh兼容

**Comment by Jrohy** [comment]
你可以先下载脚本:`curl -Ls https://git.io/fNgqx -o install.sh`
再安装: `bash install.sh --zh`

**Comment by jamesNg0123** [comment]
谷歌centos7系统，运行中文脚本·到最后为什么提示：pip3 no install!

**Comment by Jrohy** [comment]
@jamesNg0123 运行下python3 <(curl -sL https://bootstrap.pypa.io/get-pip.py)，看报什么错

**Comment by jamesNg0123** [comment]
> @jamesNg0123 运行下`python3 <(curl -sL https://bootstrap.pypa.io/get-pip.py)`，看报什么错

运行后这样提示：
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/bin/pip'
Consider using the `--user` option or check the permissions.

**Comment by jamesNg0123** [comment]
> @jamesNg0123 运行下`python3 <(curl -sL https://bootstrap.pypa.io/get-pip.py)`，看报什么错

ROOT后·运行您发这个代码·没有报错··但我又从新运行下中文安装代码·到最后显示
pip3 no install!

**Comment by Jrohy** [comment]
pip命令有安装吗，有安装好可以直接 `pip install v2ray-util`来安装

**Comment by jamesNg0123** [comment]
> pip命令有安装吗，有安装好可以直接 `pip install v2ray-util`来安装

安装好PIP命令后·运行你这个指令显示：
ERROR: Could not find a version that satisfies the requirement v2ray-util (from versions: none)
ERROR: No matching distribution found for v2ray-util

**Comment by Jrohy** [comment]
不知道你这个pip是不是安装到python2里了，pip必须安装到python3里
