### ISSUE TITLE
走CDN的时候部分域名会提示”域名检测错误“

### ISSUE THREAD

**Issue by DockerCS** [Jrohy/multi-v2ray#226]
用.com域名是没有问题的，但是用.best域名会出现提示”域名检测错误“

**Comment by Jrohy** [comment]
本机用ping命令ping下检测错误的域名，看下能否Ping通

**Comment by jacklihuafei** [comment]
本机是可以ping的通的，我的是XXX.eu.org，欧盟二级域名
