### ISSUE TITLE
为什么输入V2RAY 后加的参数没有反应

### ISSUE THREAD

**Issue by chickmy** [Jrohy/multi-v2ray#227]
![image](https://user-images.githubusercontent.com/42132304/65798688-227b7080-e127-11e9-8587-6b13313f3406.png)

**Comment by Jrohy** [comment]
输入v2ray有反应吗

**Comment by chickmy** [comment]
> 输入v2ray有反应吗
 直接输入v2ray 有反应，但是加参数没有反应
有个疑问想问一下作者 我开启TLS后，把CF云朵打开后就连接不上了，关闭云朵就正常~

**Comment by Jrohy** [comment]
可以试下v2ray-util -h有没反应

**Comment by chickmy** [comment]
> 可以试下v2ray-util -h有没反应

ok 有打印结果了

**Comment by Jrohy** [comment]
cf的没遇到过这种情况，我的vps都是被封ip的，必须开启云朵代理真实ip才能连，关闭云朵解释成真实ip就没法连

**Comment by Jrohy** [comment]
会不会cf的dns域名设置有问题呢

**Comment by chickmy** [comment]
v3.6.4的版本取消了CDN参数？
修改域名的DNS也是正常的~
我的IP没有被墙，关闭了云朵，连接真实IP正常，开云朵，走CDN就连不上了

**Comment by chickmy** [comment]
cf ssl选项 我选Flexible

**Comment by Jrohy** [comment]
并没有取消cdn参数的

**Comment by chickmy** [comment]
![image](https://user-images.githubusercontent.com/42132304/65807921-fae7d080-e145-11e9-8e7d-a983f58d12c2.png)

**Comment by chickmy** [comment]
v2ray-util cdn 也是没有反应

**Comment by Jrohy** [comment]
v2ray-util -v看下版本

**Comment by Jrohy** [comment]
你这个应该很早以前版本

**Comment by chickmy** [comment]
谢谢作者，真的是搞糊涂了....

**Comment by chickmy** [comment]
source <(curl -sL https://git.io/fNgqx) -k
好像脚本没有办法更新到最新的程序

**Comment by Jrohy** [comment]
pip list查看下版本，
pip install -U v2ray-util来升级

**Comment by chickmy** [comment]
Package      Version
------------ -------
asn1crypto   0.24.0 
cffi         1.12.3 
cryptography 2.7    
pip          19.2.3 
pycparser    2.19   
pyOpenSSL    19.0.0 
setuptools   39.2.0 
six          1.12.0 
v2ray-util   3.0.1  
wheel        0.33.6

最新版本是3.0.1 。这个好像是旧版

**Comment by Jrohy** [comment]
刚换成pip时出的版本，pip install -U v2ray-util无法升级吗

**Comment by chickmy** [comment]
没有办法升级

**Comment by Jrohy** [comment]
要不拷贝config.json出来，然后重新全新安装看下？

**Comment by chickmy** [comment]
我试过很多次重新安装了，还是安装3.0.1的版本
curl -Ls https://git.io/fNgqx -o install.sh
bash install.sh --zh

**Comment by Jrohy** [comment]
难道是pip源的问题？https://pypi.org/project/v2ray-util/ 
pip源最新3.6.4， 你可以先用pip install v2ray-util单独安装试下

**Comment by Jrohy** [comment]
pip install v2ray-util 可以直接这样安装来使用的

**Comment by chickmy** [comment]
谢谢作者，可能是我源的问题，我本地安装可以了pip install v2ray_util-3.6.4-py3-none-any.whl
