### ISSUE TITLE
求教WS+TLS 默認走的是80？無CDN

### ISSUE THREAD

**Issue by PS0123456** [Jrohy/multi-v2ray#230]
看了前面的Issues，知道您是直接使用V2ray WS+TLS ,裝機嘗試之後，端口監測發現貌似走的是80？而不是443？(設置的port其實是無效的嗎？）
另外，lets證書是自動續簽的嗎？（看配置文件發現是自動續簽的，再次跟您確認下）

**Comment by Jrohy** [comment]
会续签的，端口有80和443两个端口现在 cdn,因为走ws，cloudfare只支持这两个端口

**Comment by Jrohy** [comment]
你可以两个端口都开，来对比下速度

**Comment by PS0123456** [comment]
我没表达清楚。不开CDN，自带的was+tls可以走任意端口？那我是不是可以关闭80和443

**Comment by Jrohy** [comment]
是的，不开cdn走任何端口都行，端口任意开多个都行的

**Comment by minitru1014** [comment]
> 是的，不开cdn走任何端口都行，端口任意开多个都行的

大佬 请问直接开启cdn 会和宝塔里的nginx有冲突吗？宝塔有建站

**Comment by Jrohy** [comment]
@minitru1014 只要端口不冲突就行， 开启cdn会用到80或者443端口

**Comment by yihongyuelan** [comment]
@Jrohy CouldFlare官网上说支持的端口不止80和443：
https://support.cloudflare.com/hc/en-us/articles/200169156-Identifying-network-ports-compatible-with-Cloudflare-s-proxy

`HTTP ports supported by Cloudflare:

80
8080
8880
2052
2082
2086
2095
HTTPS ports supported by Cloudflare:

443
2053
2083
2087
2096
8443`

**Comment by Jrohy** [comment]
@yihongyuelan 感谢反馈👍，后期测试好会加新端口
