### ISSUE TITLE
走cdn时不开cf可以走通，套上cf全代理后无法使用？

### ISSUE THREAD

**Issue by DRRoJohn** [Jrohy/multi-v2ray#231]
只是dns下是可以ws+tls的，cf那边一开就在应用内可以ping，但是完全走不通。报错是tls握手失败？
![Screenshot_20191002230808](https://user-images.githubusercontent.com/51868881/66091554-e80e3b00-e54d-11e9-92f0-a57d893a4e93.jpg)

**Comment by DRRoJohn** [comment]
A unified platform for anti-censorship.
http: TLS handshake error from 112.44.***.**:*****: EOF
服务端出现该报错

**Comment by DRRoJohn** [comment]
是因为ws用于伪装的域名存在要求吗？

**Comment by Jrohy** [comment]
我也遇到了，一个域名可以，一个域名不行😂，在测试中

**Comment by Jrohy** [comment]
@DRRoJohn 测试了，要ssl那里为FULL才行

**Comment by Jrohy** [comment]
80端口就都可以，443端口就必须为full

**Comment by DRRoJohn** [comment]
@Jrohy 一直是full，用的443端口，现在没有伪装的情况下是可以走通，但是伪装成baidu就不行

**Comment by Jrohy** [comment]
@DRRoJohn 确实不行，会出新版走cdn去掉伪装

**Comment by DRRoJohn** [comment]
是core本身不接受伪装吗



---原始邮件---
发件人: "Jrohy"<notifications@github.com&gt;
发送时间: 2019年10月3日(星期四) 上午10:36
收件人: "Jrohy/multi-v2ray"<multi-v2ray@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"DRRoJohn"<2847896575@qq.com&gt;;
主题: Re: [Jrohy/multi-v2ray] 走cdn时不开cf可以走通，套上cf全代理后无法使用？ (#231)



@DRRoJohn 确实不行，会出新版走cdn去掉伪装

**Comment by Jrohy** [comment]
@DRRoJohn 不走cdn纯粹ws 是可以伪装的，走了cdn+ 伪装就不行了

**Comment by Jrohy** [comment]
3.6.6版本已去掉cdn 伪装，感谢反馈
