### ISSUE TITLE
docker里面开启CDN 443报curl错误

### ISSUE THREAD

**Issue by buxuku** [Jrohy/multi-v2ray#232]
在ubuntu18里面通过docker运行，开启cdn的时候。提示如下错误

```
1. Let’s Encrypt 生成证书(准备域名)
2. 自定义已存在的其他路径的证书(准备证书文件路径)

请选择: 1

正在获取SSL证书，请稍等..
sh: curl: not found
bash: /root/.acme.sh/acme.sh: No such file or directory
stoping v2ray...
v2ray stop success !
starting v2ray...
v2ray start fail !
```

**Comment by Jrohy** [comment]
docker里面获取证书不行的，要不外面获取后绑定目录映射进去，然后里面填证书地址，要不就走cdn 80端口无需证书

**Comment by danxin2019** [comment]
在root用户下直接安装的也出现同样的错误提示

**Comment by danxin2019** [comment]
> docker里面获取证书不行的，要不外面获取后绑定目录映射进去，然后里面填证书地址，要不就走cdn 80端口无需证书

在root用户下直接安装的也出现同样的错误提示

**Comment by Jrohy** [comment]
@danxin2019 yum install curl

**Comment by danxin2019** [comment]
> @danxin2019 yum install curl

我是零基础的，能指导更详细点吗？

**Comment by Jrohy** [comment]
@danxin2019 centos就运行 yum install curl, Debian/ubuntu就运行apt-get install curl

**Comment by danxin2019** [comment]
1. Let’s Encrypt 生成证书(准备域名)
2. 自定义已存在的其他路径的证书(准备证书文件路径)

请选择: 2
请输入证书cert文件路径: /usr/local/nginx/conf/ssl/.............
请输入证书key文件路径: /usr/local/nginx/conf/ssl/.............
restarting v2ray...
v2ray restart fail !

**Comment by danxin2019** [comment]
> @danxin2019 centos就运行 yum install curl, Debian/ubuntu就运行apt-get install curl

1. Let’s Encrypt 生成证书(准备域名)
2. 自定义已存在的其他路径的证书(准备证书文件路径)

请选择: 2
请输入证书cert文件路径: /usr/local/nginx/conf/ssl/…
请输入证书key文件路径: /usr/local/nginx/conf/ssl/…
restarting v2ray...
v2ray restart fail !

> @danxin2019 centos就运行 yum install curl, Debian/ubuntu就运行apt-get install curl
加装了curl,还是失败

**Comment by Jrohy** [comment]
你看下是不是端口占用了 @danxin2019
