### ISSUE TITLE
开启tls后这样

### ISSUE THREAD

**Issue by minitru1014** [Jrohy/multi-v2ray#233]
![image](https://user-images.githubusercontent.com/28612397/67137842-fbb7e200-f26d-11e9-8cb6-9e375e4b386b.png)
之前脚本开启tls后好像还要跑一些脚本现在只有这样了，原先访问域名能打开一个阿帕奇的网页，现在访问打不开了。是有问题了吗

**Comment by Jrohy** [comment]
这个是已经签过证书了才这样
