### ISSUE TITLE
请问大佬如何配置

### ISSUE THREAD

**Issue by chinacuizichao** [Jrohy/multi-v2ray#234]
按照github的readme安装完，生成完端口，拷贝配置到v2rayU并不能翻墙。小白想问下：如何调试呢？

**Comment by chinacuizichao** [comment]
Group: A
IP: 184.170.211.77
Port: 30062
TLS: 关闭
UUID: 6faada42-ea70-11e9-afd3-aaaa000e3751
Alter ID: 16
Network: kcp srtp

vmess://eyJ2IjogIjIiLCAicHMiOiAiIiwgImFkZCI6ICIxODQuMTcwLjIxMS43NyIsICJwb3J0IjogMzAwNjIsICJhaWQiOiAxNiwgInR5cGUiOiAic3J0cCIsICJuZXQiOiAia2NwIiwgInBhdGgiOiAiIiwgImhvc3QiOiAiIiwgImlkIjogIjZmYWFkYTQyLWVhNzAtMTFlOS1hZmQzLWFhYWEwMDBlMzc1MSIsICJ0bHMiOiAibm9uZSJ9
这是生成出来的配置

**Comment by Jrohy** [comment]
v2rayU没用过，可以对比下倒入的配置对不对，看下v2ray的错误日志如何

**Comment by chinacuizichao** [comment]
@Jrohy 本地日志如下，给大佬添麻烦了，感谢～
2019/10/21 20:36:36 127.0.0.1:57566 accepted //www.gstatic.com:443  
2019/10/21 20:36:36 [Info] [1404883215] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [www.gstatic.com:443] with URL [//www.gstatic.com:443]
2019/10/21 20:36:36 [Info] [1404883215] v2ray.com/core/app/dispatcher: default route for tcp:www.gstatic.com:443
2019/10/21 20:36:36 [Info] v2ray.com/core/transport/internet/kcp: dialing mKCP to udp:184.170.211.77:27685
2019/10/21 20:36:36 [Info] v2ray.com/core/transport/internet/kcp: #4682 creating connection to 184.170.211.77:27685
2019/10/21 20:36:36 [Info] [1404883215] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.gstatic.com:443 via tcp:184.170.211.77:27685
2019/10/21 20:36:36 [Info] [3698017358] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [apis.google.com:443] with URL [//apis.google.com:443]
2019/10/21 20:36:36 [Info] [3698017358] v2ray.com/core/app/dispatcher: default route for tcp:apis.google.com:443
2019/10/21 20:36:36 [Info] v2ray.com/core/transport/internet/kcp: dialing mKCP to udp:184.170.211.77:27685
2019/10/21 20:36:36 127.0.0.1:57567 accepted //apis.google.com:443  
2019/10/21 20:36:36 [Info] v2ray.com/core/transport/internet/kcp: #4683 creating connection to 184.170.211.77:27685
2019/10/21 20:36:36 [Info] [3698017358] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:apis.google.com:443 via tcp:184.170.211.77:27685
2019/10/21 20:36:36 127.0.0.1:57568 accepted //api.momentumdash.com:443  
2019/10/21 20:36:36 [Info] [2697789276] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [api.momentumdash.com:443] with URL [//api.momentumdash.com:443]
2019/10/21 20:36:36 [Info] [2697789276] v2ray.com/core/app/dispatcher: default route for tcp:api.momentumdash.com:443
2019/10/21 20:36:36 [Info] v2ray.com/core/transport/internet/kcp: dialing mKCP to udp:184.170.211.77:27685
2019/10/21 20:36:36 [Info] v2ray.com/core/transport/internet/kcp: #4684 creating connection to 184.170.211.77:27685
2019/10/21 20:36:36 [Info] [2697789276] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:api.momentumdash.com:443 via tcp:184.170.211.77:27685
2019/10/21 20:36:36 127.0.0.1:57569 accepted //www.google.com:443  
2019/10/21 20:36:36 [Info] [2673462392] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [www.google.com:443] with URL [//www.google.com:443]
2019/10/21 20:36:36 [Info] [2673462392] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:443
2019/10/21 20:36:36 [Info] v2ray.com/core/transport/internet/kcp: dialing mKCP to udp:184.170.211.77:27685
2019/10/21 20:36:36 [Info] v2ray.com/core/transport/internet/kcp: #4685 creating connection to 184.170.211.77:27685
2019/10/21 20:36:36 [Info] [2673462392] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via tcp:184.170.211.77:27685
2019/10/21 20:36:44 127.0.0.1:57570 accepted //www.google.com:443  
2019/10/21 20:36:44 [Info] [3449183825] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [www.google.com:443] with URL [//www.google.com:443]
2019/10/21 20:36:44 [Info] [3449183825] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:443
2019/10/21 20:36:44 [Info] v2ray.com/core/transport/internet/kcp: dialing mKCP to udp:184.170.211.77:27685
2019/10/21 20:36:44 [Info] v2ray.com/core/transport/internet/kcp: #4686 creating connection to 184.170.211.77:27685
2019/10/21 20:36:44 [Info] [3449183825] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via tcp:184.170.211.77:27685
2019/10/21 20:36:54 [Info] v2ray.com/core/transport/internet/kcp: #4674 closing connection to 184.170.211.77:27685
2019/10/21 20:36:54 [Info] [2694439684] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2019/10/21 20:36:54 [Info] [2694439684] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > io: read/write on closed pipe
2019/10/21 20:36:54 [Info] v2ray.com/core/transport/internet/kcp: #4675 closing connection to 184.170.211.77:27685
2019/10/21 20:36:54 [Info] [549576879] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2019/10/21 20:36:54 [Info] [549576879] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > io: read/write on closed pipe
2019/10/21 20:36:54 127.0.0.1:57571 accepted //www.google.com:443  
2019/10/21 20:36:54 [Info] [1138457959] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [www.google.com:443] with URL [//www.google.com:443]
2019/10/21 20:36:54 [Info] [1138457959] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:443
2019/10/21 20:36:54 [Info] v2ray.com/core/transport/internet/kcp: dialing mKCP to udp:184.170.211.77:27685
2019/10/21 20:36:54 [Info] v2ray.com/core/transport/internet/kcp: #4687 creating connection to 184.170.211.77:27685
2019/10/21 20:36:54 [Info] [1138457959] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via tcp:184.170.211.77:27685
2019/10/21 20:36:54 [Info] v2ray.com/core/transport/internet/kcp: #4676 closing connection to 184.170.211.77:27685
2019/10/21 20:36:54 [Info] [745508500] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2019/10/21 20:36:54 [Info] [745508500] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > io: read/write on closed pipe
2019/10/21 20:36:54 [Info] [1130283488] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [clients4.google.com:443] with URL [//clients4.google.com:443]
2019/10/21 20:36:54 [Info] [1130283488] v2ray.com/core/app/dispatcher: default route for tcp:clients4.google.com:443
2019/10/21 20:36:54 [Info] v2ray.com/core/transport/internet/kcp: dialing mKCP to udp:184.170.211.77:27685
2019/10/21 20:36:54 127.0.0.1:57572 accepted //clients4.google.com:443  
2019/10/21 20:36:54 [Info] v2ray.com/core/transport/internet/kcp: #4688 creating connection to 184.170.211.77:27685
2019/10/21 20:36:54 [Info] [1130283488] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:clients4.google.com:443 via tcp:184.170.211.77:27685
2019/10/21 20:36:55 [Info] v2ray.com/core/transport/internet/kcp: #4677 closing connection to 184.170.211.77:27685
2019/10/21 20:36:55 [Info] [1670409659] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2019/10/21 20:36:55 [Info] [1670409659] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > io: read/write on closed pipe
2019/10/21 20:36:57 [Info] v2ray.com/core/transport/internet/kcp: #4678 closing connection to 184.170.211.77:27685

**Comment by Jrohy** [comment]
也不知是不是墙的原因，可以换下其他协议试试

**Comment by chinacuizichao** [comment]
换shadowsocks可以了，但是又不安全😂，大佬现在用什么协议呢？

**Comment by Jrohy** [comment]
ws + cdn

**Comment by chinacuizichao** [comment]
多谢大佬，我试试看
