### ISSUE TITLE
-bash: v2ray: command not found 如何解决？

### ISSUE THREAD

**Issue by yu4618** [Jrohy/multi-v2ray#235]
AWS的lightsail 可以免费用1个月，我安装的是centos7。

使用命令"source <(curl -sL https://git.io/fNgqx) --zh"时,会出现安装pip失败，后来单独安装了pip8.1，随后使用命令“source <(curl -sL https://git.io/fNgqx) --zh”重新安装v2ray，会报错“-bash: v2ray: command not found”。这也就意味着输入 v2ray不会出现管理界面。

在vultr上就没有这些问题，但是vultr现在没有3.5刀的机器了，所以只能用lightsail了，因此这个问题需要大佬帮我解决下。

**Comment by Jrohy** [comment]
v2ray-util命令 能否用呢

**Comment by yu4618** [comment]
> v2ray-util命令能否用呢

输入后显示"-bash: v2ray-util: command not found"

**Comment by Jrohy** [comment]
https://pypi.org/project/v2ray-util/ 实际是pip安装这个，pip list看下安装好没

**Comment by yu4618** [comment]
> https://pypi.org/project/v2ray-util/实际是pip安装这个，pip列表看下安装好没

是输入“pip list”查看吗？输入后显示“-bash: pip: command not found”

这意味着我pip环境安装错了吗？正确的命令应该是什么呢？

**Comment by Jrohy** [comment]
pip没安装好

**Comment by yu4618** [comment]
> pip没安装好

pip是用“yum install python-pip -y”安装的，正确的命令行应该怎么写呢？

**Comment by Jrohy** [comment]
https://github.com/Jrohy/python3-install 试下这个能不能安装上

**Comment by yu4618** [comment]
1. 用git clone “https://github.com/Jrohy/python3-install.git” 不报错

2.用“bash <(curl -sL https://git.io/fhqMz)”
显示
WARNING: The scripts pip, pip3 and pip3.6 are installed in '/usr/local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

安装后仍然显示“-bash: v2ray: command not found”

**Comment by Jrohy** [comment]
安装后pip能用吗

**Comment by yu4618** [comment]
> 安装后pip能用吗


输入“pip list”
仍然显示-bash: pip: command not found

**Comment by Jrohy** [comment]
要看下什么办法安装好Pip命令了

**Comment by yu4618** [comment]
> 要看下什么办法安装好Pip命令了

我再折腾下，如果还不行的话，就明天换成debian系统再试下吧

**Comment by edwinhuish** [comment]
前面加 sudo 试试？

**Comment by yu4618** [comment]
> 前面加sudo试试？

不可以的，换成debian 就好了。lightsail一直存在这个问题，vultr就可以随便用.
