### ISSUE TITLE
关于流量统计(iptables)的建议

### ISSUE THREAD

**Issue by yihongyuelan** [Jrohy/multi-v2ray#239]
非常感谢楼主对V2ray的封装，虽然我是原生党，但也不排斥这些封装。

流量查询目前有两个输出：
1. 查看流量统计
2. 重置流量统计

建议加入：
3. 退出

（更直观，虽然现在输入3也会执行break）

建议加入：
4. 实时刷新（每隔5s/10s/自定义）

再次感谢

**Comment by Jrohy** [comment]
实时刷新可以有，退出的话全部应该都支持回车退出
