### ISSUE TITLE
使用你的脚本，很好用，但是我想每步自己设置，而不是你自动生成

### ISSUE THREAD

**Issue by lxitdn** [Jrohy/multi-v2ray#24]
使用你的脚本，很好用，但是我想每步自己设置，而不是你自动生成，可以吗？

**Comment by Jrohy** [comment]
可以跑完后改的， 自动生成就是为了快速部署.

**Comment by wangwill** [comment]
关于部署Let's Encryption证书那里 希望添加“是否已部属跳过”选项      这样可以用已部署网站伪装的的证书地址

**Comment by Jrohy** [comment]
@wangwill 已部署的会跳过不会重新申请

**Comment by wangwill** [comment]
@Jrohy 我的意思是用已部署的网站（正规站/作伪装）  那边的Let's Encryption 证书地址。    就是第一次安装也可以不执行acme.sh

**Comment by Jrohy** [comment]
@wangwill  后面会优化下，首次安装不提供acme.sh, 选择tls时才安装，或者证书文件自定义路径

**Comment by Jrohy** [comment]
@wangwill 已更新

**Comment by taipei007** [comment]
大佬，冒昧的发一下issue，新的脚本好像在gcp的centos7上不能用，脚本跑完以后输入v2ray提示command not found~~~，我其他的几台vps都用的您以前的脚本正常使用！关于v2ray的命令都是提示一样的！是不是哪里有问题！我用的4.18内核！

**Comment by Jrohy** [comment]
@taipei007 下班后看看

**Comment by Jrohy** [comment]
![image](https://user-images.githubusercontent.com/12463263/44649976-0a16bf00-aa18-11e8-89df-5d4f2610af20.png)
v2ray的操作脚本会放置在/usr/local/bin/目录下，你看下相应目录有没有

**Comment by taipei007** [comment]
存在的，目录下有v2ray

**Comment by taipei007** [comment]
![image](https://user-images.githubusercontent.com/42731756/44694130-5f95af00-aa9e-11e8-8fa6-89c2d36d98f5.png)

**Comment by Jrohy** [comment]
输入命令``v2ray``还是执行不了？

**Comment by taipei007** [comment]
是的是的

**Comment by taipei007** [comment]
就是
![image](https://user-images.githubusercontent.com/42731756/44694184-b0a5a300-aa9e-11e8-8455-4faf13b1caa9.png)

**Comment by taipei007** [comment]
我另一台成功的机器不是这样的，给您截图哈！
![image](https://user-images.githubusercontent.com/42731756/44694216-dcc12400-aa9e-11e8-956a-d6eed2841d3a.png)

**Comment by taipei007** [comment]
是不是缺失什么文件了或者什么依赖没有安装

**Comment by Jrohy** [comment]
![image](https://user-images.githubusercontent.com/12463263/44695269-f82f2d80-aaa4-11e8-8a29-b01dfa16f218.png)
``echo $PATH`` 看下有没```/usr/local/bin/``` 路径, 如果没有要加下环境变量

**Comment by taipei007** [comment]
好，我尽快试试

**Comment by taipei007** [comment]
可以的，加入环境变量以后就可以用了，感谢大佬！

**Comment by taipei007** [comment]
我想请问一下，大佬有没有什么好的香港服务器推荐啊，150以下一个月的！

**Comment by Jrohy** [comment]
买不起香港服务器的😅

**Comment by Jrohy** [comment]
详情请看: [xxoox.fun](https://xxoox.fun)

**Comment by taipei007** [comment]
大佬，onevps的Tokyo怎么样，听说有qos，然后大佬的这个探针是用什么做的

**Comment by Jrohy** [comment]
qos貌似没遇到

**Comment by taipei007** [comment]
那这个探针用的什么啊，我也想弄个玩玩！

**Comment by wangwill** [comment]
@taipei007  https://github.com/ToyoDAdoubi/ServerStatus-Toyo

**Comment by taipei007** [comment]
谢谢大佬，哪个服务端和客户端博客说的不太清楚啊，我试了一下还是没成功，是不是不能在宝塔服务器安装这个脚本啊，打不开网页！服务端好像是就是设置站点的吧，然后客户端对接服务端，是这个意思么？

**Comment by wangwill** [comment]
羡慕大佬的机子每秒16MB/s的跑着

**Comment by taipei007** [comment]
机子人多啊，好像提供的是免费节点吧！

**Comment by taipei007** [comment]
我的节点装了宝塔，caddy也是总启动不了！error inspecting server blocks: duplicate site key: 域名！

**Comment by taipei007** [comment]
大佬caddy不启动会有什么后果？我的vps的caddy启动不起来

**Comment by Jrohy** [comment]
会不会端口被占了，80和443端口检查下

**Comment by taipei007** [comment]
80端口被占用了

**Comment by wangwill** [comment]
域名分流咯

**Comment by taipei007** [comment]
现在的问题是我可以打开网页但是对接不上节点

**Comment by taipei007** [comment]
我把它建好的web直接拷贝到我的宝塔站点目录下可以打开
但是caddy就是无法运行，然后最无奈的是我并不知道caddy这个软件对于这个探针对接还是什么有什么影响！就是服务端和客户端都在一个服务器上都无法进行对接！我就很绝望，然后这个caddy还没有办法进行完全卸载重装！我简直对caddy崩溃了
求大佬救我

**Comment by Jrohy** [comment]
这个不在本项目讨论范围，可以去toyo请教下

**Comment by taipei007** [comment]
好的
