### ISSUE TITLE
使用 V2ray 的流量统计有 bug

### ISSUE THREAD

**Issue by Smith-Cruise** [Jrohy/multi-v2ray#244]
我使用 v2ray 的流量统计，查看用户流量统计，每个用户显示的数据均为0，但是查看组流量统计，是有的，请问怎么回事。

我所有用户都是公用一个端口的，之前用老版的系统是能正常统计，但是不能一次性显示所有用户的流量，最近升级到新版，能一次性显示所有用户，但是每个用户的流量均为0。

**Comment by Jrohy** [comment]
```cd /usr/bin/v2ray && ./v2ctl api --server=127.0.0.1:{} StatsService.GetStats 'name: "user>>>{}>>>traffic>>>downlink" reset: false'```

**Comment by Jrohy** [comment]
试下显示什么，看看能否查出来， 我自己试是没问题，脚本就是这样查询

**Comment by tandalin** [comment]
遇到相同的问题。
可以一次查所有用户这个版本：
流量显示不正确。部分用户有流量（不确定正不正确）
大部分用户是没流量。（但确实已经使用了）

**Comment by Jrohy** [comment]
@tandalin 也试下没流量但用了的用户的查询呗，按上面的方法查看下显示什么结果

**Comment by Jrohy** [comment]
可以分别试下没流量和有流量显示的邮箱

**Comment by tandalin** [comment]
@Jrohy 现在的情况是：
我几台的VPS的情况基本相同（含三家vps供应商，都是centos7）：
1.每台都是2~3组，每组都有一个测试号（测试号也不全是在组首位）
2.用户都是config.json迁移过来的，但新建的用户也同样没流量数据，但网络都能正常代理。
3.现在只有我自己的测试帐号能产生流量数据，新创的没有流量数据，其他旧用户在我电脑测试也无法产生流量。
4.如果你问测试账号跟其他的区别，我只能说我的邮箱不一样，
没错，写到这里，我们已经知道问题所在了
_
5.只要邮箱含有数字，就无法产生流量数据

**Comment by tandalin** [comment]
@Jrohy 不管邮箱数字在开头，还是中间。只要含有数字就无流量数据

**Comment by Jrohy** [comment]
@tandalin 确实存在bug ,感谢反馈

**Comment by Jrohy** [comment]
今晚会出新包修复，再加个命令行参数，方便直接进去看

**Comment by Jrohy** [comment]
@Smith-Cruise @tandalin 新版已发布，`v2ray update.sh` 更新下
