### ISSUE TITLE
可以加入纯IPV6的VPS的支持吗?

### ISSUE THREAD

**Issue by lqhorochi** [Jrohy/multi-v2ray#245]
在纯ipv6的vps输入脚本,没有反应,估计无法解析到域名

**Comment by Jrohy** [comment]
哪一家纯ipv6 的vps商推荐下，来做测试

**Comment by lqhorochi** [comment]
> 哪一家纯ipv6 的vps商推荐下，来做测试

https://clientsarea.hostdoc.co.uk/aff.php?aff=129&pid=1001
价钱不贵,记得切换美元支付.大概45块一年.

**Comment by Jrohy** [comment]
买了，但github貌似没ipv6 地址，不好安装脚本😂

**Comment by lqhorochi** [comment]
> 买了，但github貌似没ipv6 地址，不好安装脚本😂

www.netlify.com 带ipv6解析..你将脚本转移修改一下吧!

**Comment by Jrohy** [comment]
@lqhorochi 有空研究下这个

**Comment by Jrohy** [comment]
@lqhorochi 脚本安装都没问题，pip安装都是可以，现在就差最新版v2ray-core的在线安装了 ipv6😂

**Comment by lqhorochi** [comment]
> @lqhorochi 有空研究下这个

脚本的ipv6适合,在纯IPV6的hostdoc.co.uk的vps上没反应

**Comment by Jrohy** [comment]
@lqhorochi 这周会发布适应纯ipv6的新版
