### ISSUE TITLE
获取SSL证书出错

### ISSUE THREAD

**Issue by lqhorochi** [Jrohy/multi-v2ray#246]
请选择: 正在获取SSL证书，请稍等..
[Thu Nov 14 18:41:28 UTC 2019] Standalone mode.
[Thu Nov 14 18:41:28 UTC 2019] Creating domain key
[Thu Nov 14 18:41:28 UTC 2019] The domain key is here: /root/.acme.sh/XXX.xyz_ecc/XXX.xyz.key
[Thu Nov 14 18:41:28 UTC 2019] Single domain='XXX.xyz'
[Thu Nov 14 18:41:28 UTC 2019] Getting domain auth token for each domain
[Thu Nov 14 18:41:30 UTC 2019] Getting webroot for domain='XXX.xyz'
[Thu Nov 14 18:41:31 UTC 2019] Verifying: XXX.xyz
[Thu Nov 14 18:41:31 UTC 2019] Standalone mode server
[Thu Nov 14 18:41:35 UTC 2019] XXX.xyz:Verify error:Fetching http://XXX.xyz/.well-known/acme-challenge/TvxkrixcAQt1YDCONZ_l1wOcmDfZ6NgK68JWS8_Npck: Error getting validation data
[Thu Nov 14 18:41:35 UTC 2019] Please add '--debug' or '--log' to check more details.
[Thu Nov 14 18:41:35 UTC 2019] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
restarting v2ray...
v2ray restart fail !

**Comment by Jrohy** [comment]
手动运行下 获取证书: `bash /root/.acme.sh/acme.sh  --issue -d XXX.xyz --debug --standalone  --keylength ec-256`, 看下具体报文

**Comment by AlinePyther** [comment]
我也遇到了同样的问题，以下是使用log打出的日志

[Fri Nov 15 13:42:26 CST 2019] Standalone mode.
[Fri Nov 15 13:42:26 CST 2019] Single domain='ssss.tk'
[Fri Nov 15 13:42:26 CST 2019] Getting domain auth token for each domain
[Fri Nov 15 13:42:29 CST 2019] Getting webroot for domain='ssss.tk'
[Fri Nov 15 13:42:29 CST 2019] Verifying: roly.pyther.tk
[Fri Nov 15 13:42:29 CST 2019] Standalone mode server
[Fri Nov 15 13:42:34 CST 2019] sss.tk:Verify error:Fetching http://ssss.tk/.well-known/acme-challenge/h29A02AK45wjhaWizcNbMljc3iijTWJtAJVHCzMIgN0: Error getting validation data
[Fri Nov 15 13:42:34 CST 2019] Please check log file for more details: /root/.acme.sh/acme.sh.log

**Comment by Jrohy** [comment]
@AlinePyther 查看下Log file呗

**Comment by AlinePyther** [comment]
logfile内容：

[Fri Nov 15 13:42:25 CST 2019] Running cmd: issue
[Fri Nov 15 13:42:25 CST 2019] _main_domain='xx.xx.tk'
[Fri Nov 15 13:42:25 CST 2019] _alt_domains='no'
[Fri Nov 15 13:42:25 CST 2019] Using config home:/root/.acme.sh
[Fri Nov 15 13:42:25 CST 2019] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Fri Nov 15 13:42:25 CST 2019] DOMAIN_PATH='/root/.acme.sh/xx.xx.tk_ecc'
[Fri Nov 15 13:42:25 CST 2019] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Fri Nov 15 13:42:25 CST 2019] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Fri Nov 15 13:42:25 CST 2019] GET
[Fri Nov 15 13:42:25 CST 2019] url='https://acme-v02.api.letsencrypt.org/directory'
[Fri Nov 15 13:42:25 CST 2019] timeout=
[Fri Nov 15 13:42:25 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Fri Nov 15 13:42:26 CST 2019] ret='0'
[Fri Nov 15 13:42:26 CST 2019] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Fri Nov 15 13:42:26 CST 2019] ACME_NEW_AUTHZ
[Fri Nov 15 13:42:26 CST 2019] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Fri Nov 15 13:42:26 CST 2019] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Fri Nov 15 13:42:26 CST 2019] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Fri Nov 15 13:42:26 CST 2019] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Fri Nov 15 13:42:26 CST 2019] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Fri Nov 15 13:42:26 CST 2019] ACME_VERSION='2'
[Fri Nov 15 13:42:26 CST 2019] Le_NextRenewTime
[Fri Nov 15 13:42:26 CST 2019] _on_before_issue
[Fri Nov 15 13:42:26 CST 2019] _chk_main_domain='xx.xx.tk'
[Fri Nov 15 13:42:26 CST 2019] _chk_alt_domains
[Fri Nov 15 13:42:26 CST 2019] Le_LocalAddress
[Fri Nov 15 13:42:26 CST 2019] d='xx.xx.tk'
[Fri Nov 15 13:42:26 CST 2019] Check for domain='xx.xx.tk'
[Fri Nov 15 13:42:26 CST 2019] _currentRoot='no'
[Fri Nov 15 13:42:26 CST 2019] Standalone mode.
[Fri Nov 15 13:42:26 CST 2019] _checkport='80'
[Fri Nov 15 13:42:26 CST 2019] _checkaddr
[Fri Nov 15 13:42:26 CST 2019] Using: ss
[Fri Nov 15 13:42:26 CST 2019] d
[Fri Nov 15 13:42:26 CST 2019] _saved_account_key_hash is not changed, skip register account.
[Fri Nov 15 13:42:26 CST 2019] Read key length:ec-256
[Fri Nov 15 13:42:26 CST 2019] _createcsr
[Fri Nov 15 13:42:26 CST 2019] Single domain='xx.xx.tk'
[Fri Nov 15 13:42:26 CST 2019] Getting domain auth token for each domain
[Fri Nov 15 13:42:26 CST 2019] d
[Fri Nov 15 13:42:26 CST 2019] url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Fri Nov 15 13:42:26 CST 2019] payload='{"identifiers": [{"type":"dns","value":"xx.xx.tk"}]}'
[Fri Nov 15 13:42:26 CST 2019] RSA key
[Fri Nov 15 13:42:26 CST 2019] HEAD
[Fri Nov 15 13:42:26 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Fri Nov 15 13:42:26 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g  -I  '
[Fri Nov 15 13:42:27 CST 2019] _ret='0'
[Fri Nov 15 13:42:27 CST 2019] POST
[Fri Nov 15 13:42:27 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Fri Nov 15 13:42:27 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Fri Nov 15 13:42:28 CST 2019] _ret='0'
[Fri Nov 15 13:42:28 CST 2019] code='201'
[Fri Nov 15 13:42:28 CST 2019] Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/71805421/1516359495'
[Fri Nov 15 13:42:28 CST 2019] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/71805421/1516359495'
[Fri Nov 15 13:42:28 CST 2019] url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/1245896933'
[Fri Nov 15 13:42:28 CST 2019] payload
[Fri Nov 15 13:42:28 CST 2019] POST
[Fri Nov 15 13:42:28 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/1245896933'
[Fri Nov 15 13:42:28 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Fri Nov 15 13:42:29 CST 2019] _ret='0'
[Fri Nov 15 13:42:29 CST 2019] code='200'
[Fri Nov 15 13:42:29 CST 2019] d='xx.xx.tk'
[Fri Nov 15 13:42:29 CST 2019] Getting webroot for domain='xx.xx.tk'
[Fri Nov 15 13:42:29 CST 2019] _w='no'
[Fri Nov 15 13:42:29 CST 2019] _currentRoot='no'
[Fri Nov 15 13:42:29 CST 2019] entry='"type":"http-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/1245896933/62UiQw","token":"h29A02AK45wjhaWizcNbMljc3iijTWJtAJVHCzMIgN0"'
[Fri Nov 15 13:42:29 CST 2019] token='h29A02AK45wjhaWizcNbMljc3iijTWJtAJVHCzMIgN0'
[Fri Nov 15 13:42:29 CST 2019] uri='https://acme-v02.api.letsencrypt.org/acme/chall-v3/1245896933/62UiQw'
[Fri Nov 15 13:42:29 CST 2019] keyauthorization='h29A02AK45wjhaWizcNbMljc3iijTWJtAJVHCzMIgN0.1RIZefwxSjNb63LwA_dPUpjNATq1y98-aJGvqRFmhQo'
[Fri Nov 15 13:42:29 CST 2019] dvlist='xx.xx.tk#h29A02AK45wjhaWizcNbMljc3iijTWJtAJVHCzMIgN0.1RIZefwxSjNb63LwA_dPUpjNATq1y98-aJGvqRFmhQo#https://acme-v02.api.letsencrypt.org/acme/chall-v3/1245896933/62UiQw#http-01#no'
[Fri Nov 15 13:42:29 CST 2019] d
[Fri Nov 15 13:42:29 CST 2019] vlist='xx.xx.tk#h29A02AK45wjhaWizcNbMljc3iijTWJtAJVHCzMIgN0.1RIZefwxSjNb63LwA_dPUpjNATq1y98-aJGvqRFmhQo#https://acme-v02.api.letsencrypt.org/acme/chall-v3/1245896933/62UiQw#http-01#no,'
[Fri Nov 15 13:42:29 CST 2019] d='xx.xx.tk'
[Fri Nov 15 13:42:29 CST 2019] ok, let's start to verify
[Fri Nov 15 13:42:29 CST 2019] Verifying: xx.xx.tk
[Fri Nov 15 13:42:29 CST 2019] d='xx.xx.tk'
[Fri Nov 15 13:42:29 CST 2019] keyauthorization='h29A02AK45wjhaWizcNbMljc3iijTWJtAJVHCzMIgN0.1RIZefwxSjNb63LwA_dPUpjNATq1y98-aJGvqRFmhQo'
[Fri Nov 15 13:42:29 CST 2019] uri='https://acme-v02.api.letsencrypt.org/acme/chall-v3/1245896933/62UiQw'
[Fri Nov 15 13:42:29 CST 2019] _currentRoot='no'
[Fri Nov 15 13:42:29 CST 2019] Standalone mode server
[Fri Nov 15 13:42:29 CST 2019] content='h29A02AK45wjhaWizcNbMljc3iijTWJtAJVHCzMIgN0.1RIZefwxSjNb63LwA_dPUpjNATq1y98-aJGvqRFmhQo'
[Fri Nov 15 13:42:29 CST 2019] ncaddr
[Fri Nov 15 13:42:29 CST 2019] startserver: 1621
[Fri Nov 15 13:42:29 CST 2019] Le_HTTPPort='80'
[Fri Nov 15 13:42:29 CST 2019] Le_Listen_V4
[Fri Nov 15 13:42:29 CST 2019] Le_Listen_V6
[Fri Nov 15 13:42:29 CST 2019] _content_len='87'
[Fri Nov 15 13:42:29 CST 2019] _NC='socat TCP-LISTEN:80,crlf,reuseaddr,fork'
[Fri Nov 15 13:42:30 CST 2019] serverproc='2340'
[Fri Nov 15 13:42:30 CST 2019] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/1245896933/62UiQw'
[Fri Nov 15 13:42:30 CST 2019] payload='{}'
[Fri Nov 15 13:42:30 CST 2019] POST
[Fri Nov 15 13:42:30 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/1245896933/62UiQw'
[Fri Nov 15 13:42:30 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Fri Nov 15 13:42:31 CST 2019] _ret='0'
[Fri Nov 15 13:42:31 CST 2019] code='200'
[Fri Nov 15 13:42:31 CST 2019] trigger validation code: 200
[Fri Nov 15 13:42:31 CST 2019] sleep 2 secs to verify
[Fri Nov 15 13:42:33 CST 2019] checking
[Fri Nov 15 13:42:33 CST 2019] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/1245896933/62UiQw'
[Fri Nov 15 13:42:33 CST 2019] payload
[Fri Nov 15 13:42:33 CST 2019] POST
[Fri Nov 15 13:42:33 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/1245896933/62UiQw'
[Fri Nov 15 13:42:33 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Fri Nov 15 13:42:34 CST 2019] _ret='0'
[Fri Nov 15 13:42:34 CST 2019] code='200'
[Fri Nov 15 13:42:34 CST 2019] xx.xx.tk:Verify error:Fetching http://xx.xx.tk/.well-known/acme-challenge/h29A02AK45wjhaWizcNbMljc3iijTWJtAJVHCzMIgN0: Error getting validation data
[Fri Nov 15 13:42:34 CST 2019] Skip for removelevel:
[Fri Nov 15 13:42:34 CST 2019] pid='2340'
[Fri Nov 15 13:42:34 CST 2019] No need to restore nginx, skip.
[Fri Nov 15 13:42:34 CST 2019] _clearupdns
[Fri Nov 15 13:42:34 CST 2019] dns_entries
[Fri Nov 15 13:42:34 CST 2019] skip dns.
[Fri Nov 15 13:42:34 CST 2019] _on_issue_err
[Fri Nov 15 13:42:34 CST 2019] Please check log file for more details: /root/.acme.sh/acme.sh.log
[Fri Nov 15 13:42:34 CST 2019] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/1245896933/62UiQw'
[Fri Nov 15 13:42:34 CST 2019] payload='{}'
[Fri Nov 15 13:42:34 CST 2019] POST
[Fri Nov 15 13:42:34 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/1245896933/62UiQw'
[Fri Nov 15 13:42:34 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Fri Nov 15 13:42:35 CST 2019] _ret='0'
[Fri Nov 15 13:42:35 CST 2019] code='400

**Comment by Jrohy** [comment]
是手动运行acme.sh脚本么

**Comment by Jrohy** [comment]
手动也获取不了，我也没办法😂，脚本也是运行上面的命令

**Comment by lqhorochi** [comment]
> 手动也获取不了，我也没办法，脚本也是运行上面的命令

有没有电报群可以交流一下？

**Comment by Jrohy** [comment]
没有，看下自己服务器怎么获取letsencrypt证书

**Comment by lqhorochi** [comment]
> 没有，看下自己服务器怎么获取letsencrypt证书
纯ipv6的脚步如何？能不能搞？直接套cf

**Comment by Jrohy** [comment]
纯ipv6目前还不支持

**Comment by lqhorochi** [comment]
> 纯ipv6目前还不支持

bash <(curl -sL https://scaleya.netlify.com/share/v2ray233_6.sh)

这个脚本支持纯ipv6的

**Comment by AlinePyther** [comment]
@lqhorochi @Jrohy 如果使用的centos系统，关闭防火墙就可以成功获取证书。之前由于一直使用的debian系统，没有想过这个问题。

systemctl stop firewalld.service
systemctl disable firewalld.service

亲测有效！
