### ISSUE TITLE
docker 安装证书报错

### ISSUE THREAD

**Issue by GoldSubmarine** [Jrohy/multi-v2ray#248]
使用docker， 生成 Letsencrypt 证书时报错，因为缺少 openssl 和 curl 两个包，建议默认在 docker 中安装好

**Comment by Jrohy** [comment]
用证书最好在宿主机生成后，再-v 绑定进去容器里面， 然后自定义证书路径来指定运行

**Comment by GoldSubmarine** [comment]
为什么？感觉直接在容器里只要输入一个域名就配好了，很省事啊

**Comment by Jrohy** [comment]
还没试过，有空我测试下

**Comment by Jrohy** [comment]
@GoldSubmarine 你运行的镜像里面的版本号是3.7.2最新吗

**Comment by GoldSubmarine** [comment]
![image](https://user-images.githubusercontent.com/22909744/68992460-bc99a280-08a6-11ea-892c-cf8475d07321.png)
貌似不是啊，但是这个机器是我新开的，docker也是新装的，所以pull的你的镜像应该也是最新的，是不是你的镜像没有更新啊？

**Comment by Jrohy** [comment]
我发现docker 里面的pip没安装到最新版，我修复下😂

**Comment by Jrohy** [comment]
@GoldSubmarine 好了现在latest标签为真正的3.7.2版本了

**Comment by GoldSubmarine** [comment]
太给力了，我试一下，另外，建议在主页贴上捐赠二维码

**Comment by Jrohy** [comment]
捐赠就没必要了，纯粹个人练技术🤗

**Comment by GoldSubmarine** [comment]
在docker中安装 openssl、curl、socat  三个包后，输入域名即可直接从Letsencrypt生成证书，已fq成功

大佬无私的精神太感动了😭

**Comment by Jrohy** [comment]
@GoldSubmarine 感谢测试，我考虑下加依赖

**Comment by Jrohy** [comment]
@GoldSubmarine 可以升级到3.7.3版本镜像，实现容器内iptables流量统计、证书申请、命令补全， 实现了宿主机部署的所有功能
