### ISSUE TITLE
希望加入域名证书续签的功能

### ISSUE THREAD

**Issue by lqhorochi** [Jrohy/multi-v2ray#249]
域名证书3个月后就到期,希望在脚本里添加域名证书续签的功能续命!

**Comment by Jrohy** [comment]
acme.sh有自动续签功能的，你可以看下crontab -l 里的定时任务

**Comment by lqhorochi** [comment]
> acme.sh有自动续签功能的，你可以看下crontab -l 里的定时任务

正在获取SSL证书，请稍等..
stoping v2ray...
v2ray stop success !
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   705    0   705    0     0  13557      0 --:--:-- --:--:-- --:--:-- 13823
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  190k  100  190k    0     0   374k      0 --:--:-- --:--:-- --:--:--  373k
[Sun 17 Nov 2019 01:36:10 PM EST] Installing from online archive.
[Sun 17 Nov 2019 01:36:10 PM EST] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz
[Sun 17 Nov 2019 01:36:10 PM EST] Extracting master.tar.gz
[Sun 17 Nov 2019 01:36:10 PM EST] Installing to /root/.acme.sh
[Sun 17 Nov 2019 01:36:10 PM EST] Installed to /root/.acme.sh/acme.sh
[Sun 17 Nov 2019 01:36:11 PM EST] Installing alias to '/root/.bashrc'
[Sun 17 Nov 2019 01:36:11 PM EST] OK, Close and reopen your terminal to start using acme.sh
[Sun 17 Nov 2019 01:36:11 PM EST] Installing cron job
[Sun 17 Nov 2019 01:36:11 PM EST] Good, bash is found, so change the shebang to use bash as preferred.
[Sun 17 Nov 2019 01:36:11 PM EST] OK
[Sun 17 Nov 2019 01:36:11 PM EST] Install success!
[Sun 17 Nov 2019 01:36:11 PM EST] Lets find script dir.
[Sun 17 Nov 2019 01:36:11 PM EST] _SCRIPT_='/root/.acme.sh/acme.sh'
[Sun 17 Nov 2019 01:36:11 PM EST] _script='/root/.acme.sh/acme.sh'
[Sun 17 Nov 2019 01:36:11 PM EST] _script_home='/root/.acme.sh'
[Sun 17 Nov 2019 01:36:11 PM EST] Using default home:/root/.acme.sh
[Sun 17 Nov 2019 01:36:11 PM EST] Using config home:/root/.acme.sh
https://github.com/Neilpang/acme.sh
v2.8.4
[Sun 17 Nov 2019 01:36:11 PM EST] Running cmd: issue
[Sun 17 Nov 2019 01:36:11 PM EST] _main_domain='ngngng.cf'
[Sun 17 Nov 2019 01:36:11 PM EST] _alt_domains='no'
[Sun 17 Nov 2019 01:36:11 PM EST] Using config home:/root/.acme.sh
[Sun 17 Nov 2019 01:36:11 PM EST] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Sun 17 Nov 2019 01:36:11 PM EST] DOMAIN_PATH='/root/.acme.sh/ngngng.cf_ecc'
[Sun 17 Nov 2019 01:36:11 PM EST] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Sun 17 Nov 2019 01:36:11 PM EST] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Sun 17 Nov 2019 01:36:11 PM EST] GET
[Sun 17 Nov 2019 01:36:11 PM EST] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun 17 Nov 2019 01:36:11 PM EST] timeout=
[Sun 17 Nov 2019 01:36:11 PM EST] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun 17 Nov 2019 01:36:12 PM EST] ret='0'
[Sun 17 Nov 2019 01:36:12 PM EST] ACME_KEY_CHANGE
[Sun 17 Nov 2019 01:36:12 PM EST] ACME_NEW_AUTHZ
[Sun 17 Nov 2019 01:36:12 PM EST] ACME_NEW_ORDER
[Sun 17 Nov 2019 01:36:12 PM EST] ACME_NEW_ACCOUNT
[Sun 17 Nov 2019 01:36:12 PM EST] ACME_REVOKE_CERT
[Sun 17 Nov 2019 01:36:12 PM EST] ACME_AGREEMENT
[Sun 17 Nov 2019 01:36:12 PM EST] ACME_NEW_NONCE
[Sun 17 Nov 2019 01:36:12 PM EST] ACME_VERSION
[Sun 17 Nov 2019 01:36:12 PM EST] _on_before_issue
[Sun 17 Nov 2019 01:36:12 PM EST] _chk_main_domain='ngngng.cf'
[Sun 17 Nov 2019 01:36:12 PM EST] _chk_alt_domains
[Sun 17 Nov 2019 01:36:12 PM EST] Le_LocalAddress
[Sun 17 Nov 2019 01:36:12 PM EST] d='ngngng.cf'
[Sun 17 Nov 2019 01:36:12 PM EST] Check for domain='ngngng.cf'
[Sun 17 Nov 2019 01:36:12 PM EST] _currentRoot='no'
[Sun 17 Nov 2019 01:36:12 PM EST] Standalone mode.
[Sun 17 Nov 2019 01:36:12 PM EST] _checkport='80'
[Sun 17 Nov 2019 01:36:12 PM EST] _checkaddr
[Sun 17 Nov 2019 01:36:12 PM EST] Using: ss
[Sun 17 Nov 2019 01:36:12 PM EST] d
[Sun 17 Nov 2019 01:36:12 PM EST] config file is empty, can not read CA_KEY_HASH
[Sun 17 Nov 2019 01:36:12 PM EST] Using config home:/root/.acme.sh
[Sun 17 Nov 2019 01:36:12 PM EST] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Sun 17 Nov 2019 01:36:12 PM EST] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Sun 17 Nov 2019 01:36:12 PM EST] GET
[Sun 17 Nov 2019 01:36:12 PM EST] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun 17 Nov 2019 01:36:12 PM EST] timeout=
[Sun 17 Nov 2019 01:36:12 PM EST] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun 17 Nov 2019 01:36:12 PM EST] ret='0'
[Sun 17 Nov 2019 01:36:12 PM EST] ACME_KEY_CHANGE
[Sun 17 Nov 2019 01:36:12 PM EST] ACME_NEW_AUTHZ
[Sun 17 Nov 2019 01:36:12 PM EST] ACME_NEW_ORDER
[Sun 17 Nov 2019 01:36:12 PM EST] ACME_NEW_ACCOUNT
[Sun 17 Nov 2019 01:36:12 PM EST] ACME_REVOKE_CERT
[Sun 17 Nov 2019 01:36:12 PM EST] ACME_AGREEMENT
[Sun 17 Nov 2019 01:36:12 PM EST] ACME_NEW_NONCE
[Sun 17 Nov 2019 01:36:12 PM EST] ACME_VERSION
[Sun 17 Nov 2019 01:36:12 PM EST] Use default length 2048
[Sun 17 Nov 2019 01:36:12 PM EST] length='2048'
[Sun 17 Nov 2019 01:36:12 PM EST] Using config home:/root/.acme.sh
[Sun 17 Nov 2019 01:36:12 PM EST] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Sun 17 Nov 2019 01:36:12 PM EST] Use length 2048
[Sun 17 Nov 2019 01:36:12 PM EST] Using RSA: 2048
[Sun 17 Nov 2019 01:36:13 PM EST] Create account key ok.
[Sun 17 Nov 2019 01:36:13 PM EST] RSA key
[Sun 17 Nov 2019 01:36:13 PM EST] Registering account
[Sun 17 Nov 2019 01:36:13 PM EST] url
[Sun 17 Nov 2019 01:36:13 PM EST] payload='{"resource": "new-account", "terms-of-service-agreed": true, "agreement": ""}'
[Sun 17 Nov 2019 01:36:13 PM EST] GET
[Sun 17 Nov 2019 01:36:13 PM EST] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun 17 Nov 2019 01:36:13 PM EST] timeout=
[Sun 17 Nov 2019 01:36:13 PM EST] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun 17 Nov 2019 01:36:13 PM EST] ret='0'
[Sun 17 Nov 2019 01:36:13 PM EST] Could not get nonce, let's try again.
[Sun 17 Nov 2019 01:36:16 PM EST] GET
[Sun 17 Nov 2019 01:36:16 PM EST] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun 17 Nov 2019 01:36:16 PM EST] timeout=
[Sun 17 Nov 2019 01:36:16 PM EST] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun 17 Nov 2019 01:36:16 PM EST] ret='0'
[Sun 17 Nov 2019 01:36:16 PM EST] Could not get nonce, let's try again.
[Sun 17 Nov 2019 01:36:19 PM EST] GET
[Sun 17 Nov 2019 01:36:19 PM EST] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun 17 Nov 2019 01:36:19 PM EST] timeout=
[Sun 17 Nov 2019 01:36:19 PM EST] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun 17 Nov 2019 01:36:19 PM EST] ret='0'
[Sun 17 Nov 2019 01:36:19 PM EST] Could not get nonce, let's try again.
[Sun 17 Nov 2019 01:36:22 PM EST] GET
[Sun 17 Nov 2019 01:36:22 PM EST] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun 17 Nov 2019 01:36:22 PM EST] timeout=
[Sun 17 Nov 2019 01:36:22 PM EST] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun 17 Nov 2019 01:36:23 PM EST] ret='0'
[Sun 17 Nov 2019 01:36:23 PM EST] Could not get nonce, let's try again.
[Sun 17 Nov 2019 01:36:26 PM EST] GET
[Sun 17 Nov 2019 01:36:26 PM EST] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun 17 Nov 2019 01:36:26 PM EST] timeout=
[Sun 17 Nov 2019 01:36:26 PM EST] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun 17 Nov 2019 01:36:26 PM EST] ret='0'
[Sun 17 Nov 2019 01:36:26 PM EST] Could not get nonce, let's try again.
[Sun 17 Nov 2019 01:36:29 PM EST] GET
[Sun 17 Nov 2019 01:36:29 PM EST] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun 17 Nov 2019 01:36:29 PM EST] timeout=
[Sun 17 Nov 2019 01:36:29 PM EST] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun 17 Nov 2019 01:36:29 PM EST] ret='0'
[Sun 17 Nov 2019 01:36:29 PM EST] Could not get nonce, let's try again.
[Sun 17 Nov 2019 01:36:32 PM EST] GET
[Sun 17 Nov 2019 01:36:32 PM EST] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun 17 Nov 2019 01:36:32 PM EST] timeout=
[Sun 17 Nov 2019 01:36:32 PM EST] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun 17 Nov 2019 01:36:32 PM EST] ret='0'
[Sun 17 Nov 2019 01:36:32 PM EST] Could not get nonce, let's try again.
[Sun 17 Nov 2019 01:36:35 PM EST] GET
[Sun 17 Nov 2019 01:36:35 PM EST] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun 17 Nov 2019 01:36:35 PM EST] timeout=
[Sun 17 Nov 2019 01:36:35 PM EST] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun 17 Nov 2019 01:36:36 PM EST] ret='0'
[Sun 17 Nov 2019 01:36:36 PM EST] Could not get nonce, let's try again.
[Sun 17 Nov 2019 01:36:39 PM EST] GET
[Sun 17 Nov 2019 01:36:39 PM EST] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun 17 Nov 2019 01:36:39 PM EST] timeout=
[Sun 17 Nov 2019 01:36:39 PM EST] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun 17 Nov 2019 01:36:39 PM EST] ret='0'
[Sun 17 Nov 2019 01:36:39 PM EST] Could not get nonce, let's try again.
[Sun 17 Nov 2019 01:36:42 PM EST] GET
[Sun 17 Nov 2019 01:36:42 PM EST] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun 17 Nov 2019 01:36:42 PM EST] timeout=
[Sun 17 Nov 2019 01:36:42 PM EST] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun 17 Nov 2019 01:36:42 PM EST] ret='0'
[Sun 17 Nov 2019 01:36:42 PM EST] Could not get nonce, let's try again.
[Sun 17 Nov 2019 01:36:45 PM EST] GET
[Sun 17 Nov 2019 01:36:45 PM EST] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun 17 Nov 2019 01:36:45 PM EST] timeout=
[Sun 17 Nov 2019 01:36:45 PM EST] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun 17 Nov 2019 01:36:45 PM EST] ret='0'
[Sun 17 Nov 2019 01:36:45 PM EST] Could not get nonce, let's try again.
[Sun 17 Nov 2019 01:36:48 PM EST] GET
[Sun 17 Nov 2019 01:36:48 PM EST] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun 17 Nov 2019 01:36:48 PM EST] timeout=
[Sun 17 Nov 2019 01:36:48 PM EST] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun 17 Nov 2019 01:36:49 PM EST] ret='0'
[Sun 17 Nov 2019 01:36:49 PM EST] Could not get nonce, let's try again.
[Sun 17 Nov 2019 01:36:52 PM EST] GET
[Sun 17 Nov 2019 01:36:52 PM EST] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun 17 Nov 2019 01:36:52 PM EST] timeout=
[Sun 17 Nov 2019 01:36:52 PM EST] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun 17 Nov 2019 01:36:52 PM EST] ret='0'
[Sun 17 Nov 2019 01:36:52 PM EST] Could not get nonce, let's try again.
[Sun 17 Nov 2019 01:36:55 PM EST] GET
[Sun 17 Nov 2019 01:36:55 PM EST] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun 17 Nov 2019 01:36:55 PM EST] timeout=
[Sun 17 Nov 2019 01:36:55 PM EST] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun 17 Nov 2019 01:36:55 PM EST] ret='0'
[Sun 17 Nov 2019 01:36:55 PM EST] Could not get nonce, let's try again.
[Sun 17 Nov 2019 01:36:58 PM EST] GET
[Sun 17 Nov 2019 01:36:58 PM EST] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun 17 Nov 2019 01:36:58 PM EST] timeout=
[Sun 17 Nov 2019 01:36:58 PM EST] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun 17 Nov 2019 01:36:58 PM EST] ret='0'
[Sun 17 Nov 2019 01:36:58 PM EST] Could not get nonce, let's try again.
[Sun 17 Nov 2019 01:37:01 PM EST] GET
[Sun 17 Nov 2019 01:37:01 PM EST] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun 17 Nov 2019 01:37:01 PM EST] timeout=
[Sun 17 Nov 2019 01:37:01 PM EST] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun 17 Nov 2019 01:37:01 PM EST] ret='0'
[Sun 17 Nov 2019 01:37:02 PM EST] Could not get nonce, let's try again.
[Sun 17 Nov 2019 01:37:05 PM EST] GET
[Sun 17 Nov 2019 01:37:05 PM EST] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun 17 Nov 2019 01:37:05 PM EST] timeout=
[Sun 17 Nov 2019 01:37:05 PM EST] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun 17 Nov 2019 01:37:05 PM EST] ret='0'
[Sun 17 Nov 2019 01:37:05 PM EST] Could not get nonce, let's try again.
[Sun 17 Nov 2019 01:37:08 PM EST] GET
[Sun 17 Nov 2019 01:37:08 PM EST] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun 17 Nov 2019 01:37:08 PM EST] timeout=
[Sun 17 Nov 2019 01:37:08 PM EST] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun 17 Nov 2019 01:37:08 PM EST] ret='0'
[Sun 17 Nov 2019 01:37:08 PM EST] Could not get nonce, let's try again.
[Sun 17 Nov 2019 01:37:11 PM EST] GET
[Sun 17 Nov 2019 01:37:11 PM EST] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun 17 Nov 2019 01:37:11 PM EST] timeout=
[Sun 17 Nov 2019 01:37:11 PM EST] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun 17 Nov 2019 01:37:11 PM EST] ret='0'
[Sun 17 Nov 2019 01:37:11 PM EST] Could not get nonce, let's try again.
[Sun 17 Nov 2019 01:37:14 PM EST] GET
[Sun 17 Nov 2019 01:37:14 PM EST] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun 17 Nov 2019 01:37:14 PM EST] timeout=
[Sun 17 Nov 2019 01:37:14 PM EST] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun 17 Nov 2019 01:37:14 PM EST] ret='0'
[Sun 17 Nov 2019 01:37:14 PM EST] Could not get nonce, let's try again.
[Sun 17 Nov 2019 01:37:17 PM EST] Registered
[Sun 17 Nov 2019 01:37:17 PM EST] _accUri
[Sun 17 Nov 2019 01:37:17 PM EST] Can not find account id url.
[Sun 17 Nov 2019 01:37:18 PM EST] 
[Sun 17 Nov 2019 01:37:18 PM EST] _on_issue_err
[Sun 17 Nov 2019 01:37:18 PM EST] Please add '--debug' or '--log' to check more details.
[Sun 17 Nov 2019 01:37:18 PM EST] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
[Sun 17 Nov 2019 01:37:18 PM EST] Diagnosis versions: 
openssl:openssl
OpenSSL 1.1.1c  28 May 2019
apache:
apache doesn't exists.
nginx:
nginx doesn't exists.
socat:
socat by Gerhard Rieger and contributors - see www.dest-unreach.org
Usage:
socat [options] <bi-address> <bi-address>
   options:
      -V     print version and feature information to stdout, and exit
      -h|-?  print a help text describing command line options and addresses
      -hh    like -h, plus a list of all common address option names
      -hhh   like -hh, plus a list of all available address option names
      -d     increase verbosity (use up to 4 times; 2 are recommended)
      -D     analyze file descriptors before loop
      -ly[facility]  log to syslog, using facility (default is daemon)
      -lf<logfile>   log to file
      -ls            log to stderr (default if no other log)
      -lm[facility]  mixed log mode (stderr during initialization, then syslog)
      -lp<progname>  set the program name used for logging
      -lu            use microseconds for logging timestamps
      -lh            add hostname to log messages
      -v     verbose data traffic, text
      -x     verbose data traffic, hexadecimal
      -b<size_t>     set data buffer size (8192)
      -s     sloppy (continue on error)
      -t<timeout>    wait seconds before closing second channel
      -T<timeout>    total inactivity timeout in seconds
      -u     unidirectional mode (left to right)
      -U     unidirectional mode (right to left)
      -g     do not check option groups
      -L <lockfile>  try to obtain lock, or fail
      -W <lockfile>  try to obtain lock, or wait
      -4     prefer IPv4 if version is not explicitly specified
      -6     prefer IPv6 if version is not explicitly specified
   bi-address:
      pipe[,<opts>]     groups=FD,FIFO
      <single-address>!!<single-address>
      <single-address>
   single-address:
      <address-head>[,<opts>]
   address-head:
      abstract-client:<filename>        groups=FD,SOCKET,RETRY,UNIX
      abstract-connect:<filename>       groups=FD,SOCKET,RETRY,UNIX
      abstract-listen:<filename>        groups=FD,SOCKET,LISTEN,CHILD,RETRY,UNIX
      abstract-recv:<filename>  groups=FD,SOCKET,RETRY,UNIX
      abstract-recvfrom:<filename>      groups=FD,SOCKET,CHILD,RETRY,UNIX
      abstract-sendto:<filename>        groups=FD,SOCKET,RETRY,UNIX
      create:<filename> groups=FD,REG,NAMED
      exec:<command-line>       groups=FD,FIFO,SOCKET,EXEC,FORK,TERMIOS,PTY,PARENT,UNIX
      fd:<num>  groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      gopen:<filename>  groups=FD,FIFO,CHR,BLK,REG,SOCKET,NAMED,OPEN,TERMIOS,UNIX
      interface:<interface>     groups=FD,SOCKET
      ip-datagram:<host>:<protocol>     groups=FD,SOCKET,RANGE,IP4,IP6
      ip-recv:<protocol>        groups=FD,SOCKET,RANGE,IP4,IP6
      ip-recvfrom:<protocol>    groups=FD,SOCKET,CHILD,RANGE,IP4,IP6
      ip-sendto:<host>:<protocol>       groups=FD,SOCKET,IP4,IP6
      ip4-datagram:<host>:<protocol>    groups=FD,SOCKET,RANGE,IP4
      ip4-recv:<protocol>       groups=FD,SOCKET,RANGE,IP4
      ip4-recvfrom:<protocol>   groups=FD,SOCKET,CHILD,RANGE,IP4
      ip4-sendto:<host>:<protocol>      groups=FD,SOCKET,IP4
      ip6-datagram:<host>:<protocol>    groups=FD,SOCKET,RANGE,IP6
      ip6-recv:<protocol>       groups=FD,SOCKET,RANGE,IP6
      ip6-recvfrom:<protocol>   groups=FD,SOCKET,CHILD,RANGE,IP6
      ip6-sendto:<host>:<protocol>      groups=FD,SOCKET,IP6
      open:<filename>   groups=FD,FIFO,CHR,BLK,REG,NAMED,OPEN,TERMIOS
      openssl:<host>:<port>     groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP,OPENSSL
      openssl-listen:<port>     groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,IP6,TCP,OPENSSL
      pipe:<filename>   groups=FD,FIFO,NAMED,OPEN
      proxy:<proxy-server>:<host>:<port>        groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP,HTTP
      pty       groups=FD,NAMED,TERMIOS,PTY
      sctp-connect:<host>:<port>        groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,SCTP
      sctp-listen:<port>        groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,IP6,SCTP
      sctp4-connect:<host>:<port>       groups=FD,SOCKET,CHILD,RETRY,IP4,SCTP
      sctp4-listen:<port>       groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,SCTP
      sctp6-connect:<host>:<port>       groups=FD,SOCKET,CHILD,RETRY,IP6,SCTP
      sctp6-listen:<port>       groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP6,SCTP
      socket-connect:<domain>:<protocol>:<remote-address>       groups=FD,SOCKET,CHILD,RETRY
      socket-datagram:<domain>:<type>:<protocol>:<remote-address>       groups=FD,SOCKET,RANGE
      socket-listen:<domain>:<protocol>:<local-address> groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE
      socket-recv:<domain>:<type>:<protocol>:<local-address>    groups=FD,SOCKET,RANGE
      socket-recvfrom:<domain>:<type>:<protocol>:<local-address>        groups=FD,SOCKET,CHILD,RANGE
      socket-sendto:<domain>:<type>:<protocol>:<remote-address> groups=FD,SOCKET
      socks4:<socks-server>:<host>:<port>       groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP,SOCKS4
      socks4a:<socks-server>:<host>:<port>      groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP,SOCKS4
      stderr    groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      stdin     groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      stdio     groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      stdout    groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      system:<shell-command>    groups=FD,FIFO,SOCKET,EXEC,FORK,TERMIOS,PTY,PARENT,UNIX
      tcp-connect:<host>:<port> groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP
      tcp-listen:<port> groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,IP6,TCP
      tcp4-connect:<host>:<port>        groups=FD,SOCKET,CHILD,RETRY,IP4,TCP
      tcp4-listen:<port>        groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,TCP
      tcp6-connect:<host>:<port>        groups=FD,SOCKET,CHILD,RETRY,IP6,TCP
      tcp6-listen:<port>        groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP6,TCP
      tun[:<ip-addr>/<bits>]    groups=FD,CHR,NAMED,OPEN,INTERFACE
      udp-connect:<host>:<port> groups=FD,SOCKET,IP4,IP6,UDP
      udp-datagram:<host>:<port>        groups=FD,SOCKET,RANGE,IP4,IP6,UDP
      udp-listen:<port> groups=FD,SOCKET,LISTEN,CHILD,RANGE,IP4,IP6,UDP
      udp-recv:<port>   groups=FD,SOCKET,RANGE,IP4,IP6,UDP
      udp-recvfrom:<port>       groups=FD,SOCKET,CHILD,RANGE,IP4,IP6,UDP
      udp-sendto:<host>:<port>  groups=FD,SOCKET,IP4,IP6,UDP
      udp4-connect:<host>:<port>        groups=FD,SOCKET,IP4,UDP
      udp4-datagram:<remote-address>:<port>     groups=FD,SOCKET,RANGE,IP4,UDP
      udp4-listen:<port>        groups=FD,SOCKET,LISTEN,CHILD,RANGE,IP4,UDP
      udp4-recv:<port>  groups=FD,SOCKET,RANGE,IP4,UDP
      udp4-recvfrom:<host>:<port>       groups=FD,SOCKET,CHILD,RANGE,IP4,UDP
      udp4-sendto:<host>:<port> groups=FD,SOCKET,IP4,UDP
      udp6-connect:<host>:<port>        groups=FD,SOCKET,IP6,UDP
      udp6-datagram:<host>:<port>       groups=FD,SOCKET,RANGE,IP6,UDP
      udp6-listen:<port>        groups=FD,SOCKET,LISTEN,CHILD,RANGE,IP6,UDP
      udp6-recv:<port>  groups=FD,SOCKET,RANGE,IP6,UDP
      udp6-recvfrom:<port>      groups=FD,SOCKET,CHILD,RANGE,IP6,UDP
      udp6-sendto:<host>:<port> groups=FD,SOCKET,IP6,UDP
      unix-client:<filename>    groups=FD,SOCKET,NAMED,RETRY,UNIX
      unix-connect:<filename>   groups=FD,SOCKET,NAMED,RETRY,UNIX
      unix-listen:<filename>    groups=FD,SOCKET,NAMED,LISTEN,CHILD,RETRY,UNIX
      unix-recv:<filename>      groups=FD,SOCKET,NAMED,RETRY,UNIX
      unix-recvfrom:<filename>  groups=FD,SOCKET,NAMED,CHILD,RETRY,UNIX
      unix-sendto:<filename>    groups=FD,SOCKET,NAMED,RETRY,UNIX
restarting v2ray...
v2ray restart fail !

今晚在另一台vps上出错了!~

**Comment by Jrohy** [comment]
是centos系统么，会不会防火墙未关
