### ISSUE TITLE
gcp的centos7安装没办法进入管理界面

### ISSUE THREAD

**Issue by taipei007** [Jrohy/multi-v2ray#25]
脚本跑完以后输入v2ray提示：-bash: v2ray: command not found，已经重装系统换过服务器还是这样，Debian下面正常，腾讯云centos下正常，服务器为gcp的centos7.5！自动生成的链接是可以使用的，只是不能多用户也不能修改它的协议端口之类的，求大佬解决一下，刚从Debian跑到centos，对centos不太熟悉！
![image](https://user-images.githubusercontent.com/42731756/44646917-25c99780-aa0f-11e8-8477-970fd4fc9f4a.png)

**Comment by taipei007** [comment]
[root@china-taipei ~]# source <(curl -sL https://git.io/fNgqx)
当前为全新安装

Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.xmission.com
 * epel: mirrors.cat.pdx.edu
 * extras: mirrors.sonic.net
 * updates: yum.tamu.edu
Package epel-release-7-11.noarch already installed and latest version
Package curl-7.29.0-46.el7.x86_64 already installed and latest version
Package wget-1.14-15.el7_4.1.x86_64 already installed and latest version
Package unzip-6.0-19.el7.x86_64 already installed and latest version
Package ntp-4.2.6p5-28.el7.centos.x86_64 already installed and latest version
Package ntpdate-4.2.6p5-28.el7.centos.x86_64 already installed and latest version
Package crontabs-1.11-6.20121102git.el7.noarch already installed and latest version
Package lsof-4.87-5.el7.x86_64 already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package git.x86_64 0:1.8.3.1-14.el7_5 will be installed
--> Processing Dependency: perl-Git = 1.8.3.1-14.el7_5 for package: git-1.8.3.1-14.el7_5.x86_64
--> Processing Dependency: perl(Term::ReadKey) for package: git-1.8.3.1-14.el7_5.x86_64
--> Processing Dependency: perl(Git) for package: git-1.8.3.1-14.el7_5.x86_64
--> Processing Dependency: perl(Error) for package: git-1.8.3.1-14.el7_5.x86_64
--> Processing Dependency: libgnome-keyring.so.0()(64bit) for package: git-1.8.3.1-14.el7_5.x86_64
---> Package socat.x86_64 0:1.7.3.2-2.el7 will be installed
--> Running transaction check
---> Package libgnome-keyring.x86_64 0:3.12.0-1.el7 will be installed
---> Package perl-Error.noarch 1:0.17020-2.el7 will be installed
---> Package perl-Git.noarch 0:1.8.3.1-14.el7_5 will be installed
---> Package perl-TermReadKey.x86_64 0:2.30-20.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===================================================================================================================
 Package                        Arch                 Version                           Repository             Size
===================================================================================================================
Installing:
 git                            x86_64               1.8.3.1-14.el7_5                  updates               4.4 M
 socat                          x86_64               1.7.3.2-2.el7                     base                  290 k
Installing for dependencies:
 libgnome-keyring               x86_64               3.12.0-1.el7                      base                  109 k
 perl-Error                     noarch               1:0.17020-2.el7                   base                   32 k
 perl-Git                       noarch               1.8.3.1-14.el7_5                  updates                54 k
 perl-TermReadKey               x86_64               2.30-20.el7                       base                   31 k

Transaction Summary
===================================================================================================================
Install  2 Packages (+4 Dependent packages)

Total download size: 4.9 M
Installed size: 24 M
Downloading packages:
(1/6): libgnome-keyring-3.12.0-1.el7.x86_64.rpm                                             | 109 kB  00:00:00     
(2/6): perl-TermReadKey-2.30-20.el7.x86_64.rpm                                              |  31 kB  00:00:01     
(3/6): perl-Error-0.17020-2.el7.noarch.rpm                                                  |  32 kB  00:00:01     
(4/6): perl-Git-1.8.3.1-14.el7_5.noarch.rpm                                                 |  54 kB  00:00:01     
(5/6): socat-1.7.3.2-2.el7.x86_64.rpm                                                       | 290 kB  00:00:00     
(6/6): git-1.8.3.1-14.el7_5.x86_64.rpm                                                      | 4.4 MB  00:00:05     
-------------------------------------------------------------------------------------------------------------------
Total                                                                              875 kB/s | 4.9 MB  00:00:05     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : 1:perl-Error-0.17020-2.el7.noarch                                                               1/6 
  Installing : perl-TermReadKey-2.30-20.el7.x86_64                                                             2/6 
  Installing : libgnome-keyring-3.12.0-1.el7.x86_64                                                            3/6 
  Installing : perl-Git-1.8.3.1-14.el7_5.noarch                                                                4/6 
  Installing : git-1.8.3.1-14.el7_5.x86_64                                                                     5/6 
  Installing : socat-1.7.3.2-2.el7.x86_64                                                                      6/6 
  Verifying  : git-1.8.3.1-14.el7_5.x86_64                                                                     1/6 
  Verifying  : libgnome-keyring-3.12.0-1.el7.x86_64                                                            2/6 
  Verifying  : perl-TermReadKey-2.30-20.el7.x86_64                                                             3/6 
  Verifying  : 1:perl-Error-0.17020-2.el7.noarch                                                               4/6 
  Verifying  : socat-1.7.3.2-2.el7.x86_64                                                                      5/6 
  Verifying  : perl-Git-1.8.3.1-14.el7_5.noarch                                                                6/6 

Installed:
  git.x86_64 0:1.8.3.1-14.el7_5                            socat.x86_64 0:1.7.3.2-2.el7                           

Dependency Installed:
  libgnome-keyring.x86_64 0:3.12.0-1.el7   perl-Error.noarch 1:0.17020-2.el7   perl-Git.noarch 0:1.8.3.1-14.el7_5  
  perl-TermReadKey.x86_64 0:2.30-20.el7   

Complete!
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.xmission.com
 * epel: mirrors.cat.pdx.edu
 * extras: mirrors.sonic.net
 * updates: yum.tamu.edu
Resolving Dependencies
--> Running transaction check
---> Package python34.x86_64 0:3.4.8-2.el7 will be installed
--> Processing Dependency: python34-libs(x86-64) = 3.4.8-2.el7 for package: python34-3.4.8-2.el7.x86_64
--> Processing Dependency: libpython3.4m.so.1.0()(64bit) for package: python34-3.4.8-2.el7.x86_64
--> Running transaction check
---> Package python34-libs.x86_64 0:3.4.8-2.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===================================================================================================================
 Package                        Arch                    Version                        Repository             Size
===================================================================================================================
Installing:
 python34                       x86_64                  3.4.8-2.el7                    epel                   51 k
Installing for dependencies:
 python34-libs                  x86_64                  3.4.8-2.el7                    epel                  8.3 M

Transaction Summary
===================================================================================================================
Install  1 Package (+1 Dependent package)

Total download size: 8.3 M
Installed size: 29 M
Downloading packages:
(1/2): python34-3.4.8-2.el7.x86_64.rpm                                                      |  51 kB  00:00:00     
(2/2): python34-libs-3.4.8-2.el7.x86_64.rpm                                                 | 8.3 MB  00:00:01     
-------------------------------------------------------------------------------------------------------------------
Total                                                                              3.5 MB/s | 8.3 MB  00:00:02     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : python34-3.4.8-2.el7.x86_64                                                                     1/2 
  Installing : python34-libs-3.4.8-2.el7.x86_64                                                                2/2 
  Verifying  : python34-libs-3.4.8-2.el7.x86_64                                                                1/2 
  Verifying  : python34-3.4.8-2.el7.x86_64                                                                     2/2 

Installed:
  python34.x86_64 0:3.4.8-2.el7                                                                                    

Dependency Installed:
  python34-libs.x86_64 0:3.4.8-2.el7                                                                               

Complete!
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1604k  100 1604k    0     0  2274k      0 --:--:-- --:--:-- --:--:-- 2271k
Collecting pip
  Downloading https://files.pythonhosted.org/packages/5f/25/e52d3f31441505a5f3af41213346e5b6c221c9e086a166f3703d2ddaf940/pip-18.0-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 4.3MB/s 
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/66/e8/570bb5ca88a8bcd2a1db9c6246bb66615750663ffaaeada95b04ffe74e12/setuptools-40.2.0-py2.py3-none-any.whl (568kB)
    100% |████████████████████████████████| 573kB 5.6MB/s 
Collecting wheel
  Downloading https://files.pythonhosted.org/packages/81/30/e935244ca6165187ae8be876b6316ae201b71485538ffac1d718843025a9/wheel-0.31.1-py2.py3-none-any.whl (41kB)
    100% |████████████████████████████████| 51kB 10.7MB/s 
Installing collected packages: pip, setuptools, wheel
Successfully installed pip-18.0 setuptools-40.2.0 wheel-0.31.1
Collecting pyopenssl
  Downloading https://files.pythonhosted.org/packages/96/af/9d29e6bd40823061aea2e0574ccb2fcf72bfd6130ce53d32773ec375458c/pyOpenSSL-18.0.0-py2.py3-none-any.whl (53kB)
    100% |████████████████████████████████| 61kB 2.1MB/s 
Collecting six>=1.5.2 (from pyopenssl)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting cryptography>=2.2.1 (from pyopenssl)
  Downloading https://files.pythonhosted.org/packages/59/32/92cade62c645756a83598edf56289e9b19aae5370642a7ce690cd06bc72f/cryptography-2.3.1-cp34-abi3-manylinux1_x86_64.whl (2.1MB)
    100% |████████████████████████████████| 2.1MB 4.0MB/s 
Collecting idna>=2.1 (from cryptography>=2.2.1->pyopenssl)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.7 (from cryptography>=2.2.1->pyopenssl)
  Downloading https://files.pythonhosted.org/packages/64/3d/684e2f507c61995ee725c44e6f34e7a6a9b7286161ef370575f1bbda3899/cffi-1.11.5-cp34-cp34m-manylinux1_x86_64.whl (421kB)
    100% |████████████████████████████████| 430kB 6.4MB/s 
Collecting asn1crypto>=0.21.0 (from cryptography>=2.2.1->pyopenssl)
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting pycparser (from cffi!=1.11.3,>=1.7->cryptography>=2.2.1->pyopenssl)
  Using cached https://files.pythonhosted.org/packages/8c/2d/aad7f16146f4197a11f8e91fb81df177adcc2073d36a17b1491fd09df6ed/pycparser-2.18.tar.gz
Building wheels for collected packages: pycparser
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /root/.cache/pip/wheels/c0/a1/27/5ba234bd77ea5a290cbf6d675259ec52293193467a12ef1f46
Successfully built pycparser
Installing collected packages: six, idna, pycparser, cffi, asn1crypto, cryptography, pyopenssl
Successfully installed asn1crypto-0.24.0 cffi-1.11.5 cryptography-2.3.1 idna-2.7 pycparser-2.18 pyopenssl-18.0.0 six-1.11.0
 正在进行时间同步 
27 Aug 15:34:17 ntpdate[15173]: adjust time server 129.6.15.30 offset 0.003841 sec
 时间同步成功 
 当前系统时间 Mon, 27 Aug 2018 15:34:17 +0800
北京时间3点，VPS时间为3点

Redirecting to /bin/systemctl restart crond.service
成功配置每天北京时间3点自动升级V2ray内核任务
V2ray配置信息:
1.
Group: A
IP：
Port：50082
UUID：1b303a8d-b15b-426b-aadd-78828eafd314
Alter ID: 64
Network：kcp srtp
TLS: 关闭
DynamicPort: 关闭

vmess://


Tip: 同一Group的节点传输方式,端口,TLS,动态端口等设置相同

输入 v2ray 回车即可进行服务管理

[root@china-taipei ~]# v2ray
-bash: v2ray: command not found
[root@china-taipei ~]# ls
config.json
[root@china-taipei ~]#

**Comment by denniszzg** [comment]
也碰到同样问题。GCE搭的cenos7，修改了环境变量后解决了。
vi /etc/profile
在最后添加一行
export PATH=$PATH:/usr/local/bin
保存退出
然后执行生效
source /etc/profile

**Comment by taipei007** [comment]
感谢大佬，解决了，就是添加环境变量！
