### ISSUE TITLE
在centos7.7 中出现报错

### ISSUE THREAD

**Issue by Leanquan** [Jrohy/multi-v2ray#252]
`Error: rpmdb open failed
ln: failed to create symbolic link ‘/bin/python3’: File exists
/dev/fd/63: line 184: python3: command not found
 Time Synchronizing.. 
-bash: ntpdate: command not found
 Time sync fail, please run command to sync:ntpdate pool.ntp.org
beijing time 3, VPS time: 14

success open schedule update task: beijing time 3
`

**Comment by Jrohy** [comment]
用的什么vps, python3没安装到
