### ISSUE TITLE
纯IPV6的vps获取SSL证书失败,acme.sh无法安装

### ISSUE THREAD

**Issue by lqhorochi** [Jrohy/multi-v2ray#255]
正在获取SSL证书，请稍等..
stoping v2ray...
v2ray stop success !
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   705    0   705    0     0   3294      0 --:--:-- --:--:-- --:--:--  3309
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Couldn't connect to server
bash: /root/.acme.sh/acme.sh: No such file or directory
restarting v2ray...
v2ray restart fail !

hostdoc.co.uk的纯IPV6 VPS

**Comment by Jrohy** [comment]
@lqhorochi 因为申请证书的脚本`curl https://get.acme.sh|sh` 里面是去取github仓库的脚本

**Comment by lqhorochi** [comment]
> @lqhorochi 因为申请证书的脚本`curl https://get.acme.sh|sh` 里面是去取github仓库的脚本

可以解决吗???不套CDN不好用

**Comment by lqhorochi** [comment]
> @lqhorochi 因为申请证书的脚本`curl https://get.acme.sh|sh` 里面是去取github仓库的脚本

还有一个问题,就是用ipv6搭建的,日志出现
rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > v2ray.com/core/transport/internet/kcp: Read/Write timeout

客户端然而连不上

**Comment by lqhorochi** [comment]
> @lqhorochi 因为申请证书的脚本`curl https://get.acme.sh|sh` 里面是去取github仓库的脚本

麻烦备注一下,ipv6搭建的multi-v2ray,手机客户端只能使用kitsunebi才可以连接上服务端.

**Comment by Jrohy** [comment]
难道你用小飞机来连接么

**Comment by Jrohy** [comment]
@lqhorochi 获取证书3.7.5版本应该可以了，试下

**Comment by lqhorochi** [comment]
> @lqhorochi 获取证书3.7.5版本应该可以了，试下

试过了,还是有问题出现

[Fri Nov 29 07:46:01 PST 2019] 5543.cf:Verify error:Fetching https://5543.cf/.well-known/acme-challenge/SJPGbfZaYRXKicpN1q2b_tKiv6PDF6gpz8KgHdRnDzo: No valid IP addresses found for 5543.cf
[Fri Nov 29 07:46:01 PST 2019] Debug: get token url.
[Fri Nov 29 07:46:01 PST 2019] GET
[Fri Nov 29 07:46:01 PST 2019] url='http://5543.cf/.well-known/acme-challenge/SJPGbfZaYRXKicpN1q2b_tKiv6PDF6gpz8KgHdRnDzo'
[Fri Nov 29 07:46:01 PST 2019] timeout=1
[Fri Nov 29 07:46:01 PST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g  --connect-timeout 1'
[Fri Nov 29 07:46:02 PST 2019] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 28
[Fri Nov 29 07:46:02 PST 2019] ret='28'
[Fri Nov 29 07:46:02 PST 2019] Skip for removelevel:
[Fri Nov 29 07:46:02 PST 2019] pid='18309'
[Fri Nov 29 07:46:02 PST 2019] No need to restore nginx, skip.
[Fri Nov 29 07:46:02 PST 2019] _clearupdns
[Fri Nov 29 07:46:02 PST 2019] dns_entries
[Fri Nov 29 07:46:02 PST 2019] skip dns.
[Fri Nov 29 07:46:02 PST 2019] _on_issue_err
[Fri Nov 29 07:46:02 PST 2019] Please add '--debug' or '--log' to check more details.
[Fri Nov 29 07:46:02 PST 2019] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

**Comment by Jrohy** [comment]
域名是不是没绑定ip

**Comment by lqhorochi** [comment]
> 域名是不是没绑定ip

已经绑定了啊

**Comment by lqhorochi** [comment]
> 域名是不是没绑定ip

就是出现这几条错误

 5543.cf:Verify error:DNS problem: SERVFAIL looking up A for 5543.cf

 Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 28
 _on_issue_err

Please add '--debug' or '--log' to check more details.

See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

**Comment by Jrohy** [comment]
我测下

**Comment by Jrohy** [comment]
找到原因了，ipv6， acme.sh脚本是要加下--listen-v6, 我更新下包

**Comment by Jrohy** [comment]
@lqhorochi 运行`pip install -U v2ray-util` 更新到2572，应该就可以了，申请证书加了--listen-v6

**Comment by lqhorochi** [comment]
> @lqhorochi 运行`pip install -U v2ray-util` 更新到2572，应该就可以了，申请证书加了--listen-v6

一样出错

正在获取SSL证书，请稍等..
stoping v2ray...
v2ray stop success !
[Fri Nov 29 09:00:33 PST 2019] Lets find script dir.
[Fri Nov 29 09:00:33 PST 2019] _SCRIPT_='/root/.acme.sh/acme.sh'
[Fri Nov 29 09:00:33 PST 2019] _script='/root/.acme.sh/acme.sh'
[Fri Nov 29 09:00:33 PST 2019] _script_home='/root/.acme.sh'
[Fri Nov 29 09:00:33 PST 2019] Using default home:/root/.acme.sh
[Fri Nov 29 09:00:33 PST 2019] Using config home:/root/.acme.sh
https://github.com/Neilpang/acme.sh
v2.8.4
[Fri Nov 29 09:00:33 PST 2019] Running cmd: issue
[Fri Nov 29 09:00:33 PST 2019] _main_domain='5543.cf'
[Fri Nov 29 09:00:33 PST 2019] _alt_domains='no'
[Fri Nov 29 09:00:33 PST 2019] Using config home:/root/.acme.sh
[Fri Nov 29 09:00:33 PST 2019] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Fri Nov 29 09:00:33 PST 2019] DOMAIN_PATH='/root/.acme.sh/5543.cf_ecc'
[Fri Nov 29 09:00:33 PST 2019] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Fri Nov 29 09:00:33 PST 2019] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Fri Nov 29 09:00:33 PST 2019] GET
[Fri Nov 29 09:00:33 PST 2019] url='https://acme-v02.api.letsencrypt.org/directory'
[Fri Nov 29 09:00:33 PST 2019] timeout=
[Fri Nov 29 09:00:34 PST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Fri Nov 29 09:00:34 PST 2019] ret='0'
[Fri Nov 29 09:00:34 PST 2019] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Fri Nov 29 09:00:34 PST 2019] ACME_NEW_AUTHZ
[Fri Nov 29 09:00:34 PST 2019] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Fri Nov 29 09:00:34 PST 2019] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Fri Nov 29 09:00:34 PST 2019] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Fri Nov 29 09:00:34 PST 2019] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Fri Nov 29 09:00:34 PST 2019] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Fri Nov 29 09:00:34 PST 2019] ACME_VERSION='2'
[Fri Nov 29 09:00:34 PST 2019] Le_NextRenewTime
[Fri Nov 29 09:00:34 PST 2019] _on_before_issue
[Fri Nov 29 09:00:34 PST 2019] _chk_main_domain='5543.cf'
[Fri Nov 29 09:00:34 PST 2019] _chk_alt_domains
[Fri Nov 29 09:00:34 PST 2019] Le_LocalAddress
[Fri Nov 29 09:00:34 PST 2019] d='5543.cf'
[Fri Nov 29 09:00:34 PST 2019] Check for domain='5543.cf'
[Fri Nov 29 09:00:34 PST 2019] _currentRoot='no'
[Fri Nov 29 09:00:34 PST 2019] Standalone mode.
[Fri Nov 29 09:00:34 PST 2019] _checkport='80'
[Fri Nov 29 09:00:34 PST 2019] _checkaddr
[Fri Nov 29 09:00:34 PST 2019] Using: ss
[Fri Nov 29 09:00:34 PST 2019] d
[Fri Nov 29 09:00:34 PST 2019] _saved_account_key_hash is not changed, skip register account.
[Fri Nov 29 09:00:34 PST 2019] Read key length:ec-256
[Fri Nov 29 09:00:34 PST 2019] _createcsr
[Fri Nov 29 09:00:34 PST 2019] Single domain='5543.cf'
[Fri Nov 29 09:00:35 PST 2019] Getting domain auth token for each domain
[Fri Nov 29 09:00:35 PST 2019] d
[Fri Nov 29 09:00:35 PST 2019] url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Fri Nov 29 09:00:35 PST 2019] payload='{"identifiers": [{"type":"dns","value":"5543.cf"}]}'
[Fri Nov 29 09:00:35 PST 2019] RSA key
[Fri Nov 29 09:00:35 PST 2019] HEAD
[Fri Nov 29 09:00:35 PST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Fri Nov 29 09:00:35 PST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g  -I  '
[Fri Nov 29 09:00:35 PST 2019] _ret='0'
[Fri Nov 29 09:00:35 PST 2019] POST
[Fri Nov 29 09:00:35 PST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Fri Nov 29 09:00:35 PST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Fri Nov 29 09:00:35 PST 2019] _ret='0'
[Fri Nov 29 09:00:35 PST 2019] code='201'
[Fri Nov 29 09:00:35 PST 2019] Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/72790382/1630523427'
[Fri Nov 29 09:00:35 PST 2019] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/72790382/1630523427'
[Fri Nov 29 09:00:35 PST 2019] url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/1464660469'
[Fri Nov 29 09:00:35 PST 2019] payload
[Fri Nov 29 09:00:36 PST 2019] POST
[Fri Nov 29 09:00:36 PST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/1464660469'
[Fri Nov 29 09:00:36 PST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Fri Nov 29 09:00:36 PST 2019] _ret='0'
[Fri Nov 29 09:00:36 PST 2019] code='200'
[Fri Nov 29 09:00:36 PST 2019] d='5543.cf'
[Fri Nov 29 09:00:36 PST 2019] Getting webroot for domain='5543.cf'
[Fri Nov 29 09:00:36 PST 2019] _w='no'
[Fri Nov 29 09:00:36 PST 2019] _currentRoot='no'
[Fri Nov 29 09:00:36 PST 2019] entry='"type":"http-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/1464660469/SP63VA","token":"cftQF2HZXVYdROIs1RQ8Oj8exoJYWzjN08Emqzw3KqE"'
[Fri Nov 29 09:00:36 PST 2019] token='cftQF2HZXVYdROIs1RQ8Oj8exoJYWzjN08Emqzw3KqE'
[Fri Nov 29 09:00:36 PST 2019] uri='https://acme-v02.api.letsencrypt.org/acme/chall-v3/1464660469/SP63VA'
[Fri Nov 29 09:00:36 PST 2019] keyauthorization='cftQF2HZXVYdROIs1RQ8Oj8exoJYWzjN08Emqzw3KqE.CYkNq6FshkNHOMaDOWHjTyw_3q2xh6S8HvD8Qsio0Ho'
[Fri Nov 29 09:00:36 PST 2019] dvlist='5543.cf#cftQF2HZXVYdROIs1RQ8Oj8exoJYWzjN08Emqzw3KqE.CYkNq6FshkNHOMaDOWHjTyw_3q2xh6S8HvD8Qsio0Ho#https://acme-v02.api.letsencrypt.org/acme/chall-v3/1464660469/SP63VA#http-01#no'
[Fri Nov 29 09:00:36 PST 2019] d
[Fri Nov 29 09:00:36 PST 2019] vlist='5543.cf#cftQF2HZXVYdROIs1RQ8Oj8exoJYWzjN08Emqzw3KqE.CYkNq6FshkNHOMaDOWHjTyw_3q2xh6S8HvD8Qsio0Ho#https://acme-v02.api.letsencrypt.org/acme/chall-v3/1464660469/SP63VA#http-01#no,'
[Fri Nov 29 09:00:36 PST 2019] d='5543.cf'
[Fri Nov 29 09:00:36 PST 2019] ok, let's start to verify
[Fri Nov 29 09:00:36 PST 2019] Verifying: 5543.cf
[Fri Nov 29 09:00:36 PST 2019] d='5543.cf'
[Fri Nov 29 09:00:36 PST 2019] keyauthorization='cftQF2HZXVYdROIs1RQ8Oj8exoJYWzjN08Emqzw3KqE.CYkNq6FshkNHOMaDOWHjTyw_3q2xh6S8HvD8Qsio0Ho'
[Fri Nov 29 09:00:36 PST 2019] uri='https://acme-v02.api.letsencrypt.org/acme/chall-v3/1464660469/SP63VA'
[Fri Nov 29 09:00:36 PST 2019] _currentRoot='no'
[Fri Nov 29 09:00:36 PST 2019] Standalone mode server
[Fri Nov 29 09:00:36 PST 2019] content='cftQF2HZXVYdROIs1RQ8Oj8exoJYWzjN08Emqzw3KqE.CYkNq6FshkNHOMaDOWHjTyw_3q2xh6S8HvD8Qsio0Ho'
[Fri Nov 29 09:00:36 PST 2019] ncaddr
[Fri Nov 29 09:00:36 PST 2019] startserver: 5875
[Fri Nov 29 09:00:36 PST 2019] Le_HTTPPort='80'
[Fri Nov 29 09:00:36 PST 2019] Le_Listen_V4
[Fri Nov 29 09:00:36 PST 2019] Le_Listen_V6='1'
[Fri Nov 29 09:00:36 PST 2019] _content_len='87'
[Fri Nov 29 09:00:36 PST 2019] _NC='socat -6 TCP-LISTEN:80,crlf,reuseaddr,fork'
[Fri Nov 29 09:00:37 PST 2019] serverproc='6681'
[Fri Nov 29 09:00:37 PST 2019] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/1464660469/SP63VA'
[Fri Nov 29 09:00:37 PST 2019] payload='{}'
[Fri Nov 29 09:00:37 PST 2019] POST
[Fri Nov 29 09:00:37 PST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/1464660469/SP63VA'
[Fri Nov 29 09:00:37 PST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Fri Nov 29 09:00:37 PST 2019] _ret='0'
[Fri Nov 29 09:00:37 PST 2019] code='200'
[Fri Nov 29 09:00:38 PST 2019] trigger validation code: 200
[Fri Nov 29 09:00:38 PST 2019] sleep 2 secs to verify
sh: echo: I/O error
sh: echo: I/O error
sh: echo: I/O error
sh: printf: I/O error
[Fri Nov 29 09:00:40 PST 2019] checking
[Fri Nov 29 09:00:40 PST 2019] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/1464660469/SP63VA'
[Fri Nov 29 09:00:40 PST 2019] payload
[Fri Nov 29 09:00:40 PST 2019] POST
[Fri Nov 29 09:00:40 PST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/1464660469/SP63VA'
[Fri Nov 29 09:00:40 PST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Fri Nov 29 09:00:40 PST 2019] _ret='0'
[Fri Nov 29 09:00:40 PST 2019] code='200'
[Fri Nov 29 09:00:40 PST 2019] 5543.cf:Verify error:DNS problem: SERVFAIL looking up A for 5543.cf
[Fri Nov 29 09:00:40 PST 2019] Debug: get token url.
[Fri Nov 29 09:00:40 PST 2019] GET
[Fri Nov 29 09:00:40 PST 2019] url='http://5543.cf/.well-known/acme-challenge/cftQF2HZXVYdROIs1RQ8Oj8exoJYWzjN08Emqzw3KqE'
[Fri Nov 29 09:00:40 PST 2019] timeout=1
[Fri Nov 29 09:00:40 PST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g  --connect-timeout 1'
[Fri Nov 29 09:00:40 PST 2019] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 7
[Fri Nov 29 09:00:40 PST 2019] ret='7'
[Fri Nov 29 09:00:40 PST 2019] Skip for removelevel:
[Fri Nov 29 09:00:40 PST 2019] pid='6681'
[Fri Nov 29 09:00:40 PST 2019] No need to restore nginx, skip.
[Fri Nov 29 09:00:40 PST 2019] _clearupdns
[Fri Nov 29 09:00:40 PST 2019] dns_entries
[Fri Nov 29 09:00:40 PST 2019] skip dns.
[Fri Nov 29 09:00:40 PST 2019] _on_issue_err
[Fri Nov 29 09:00:40 PST 2019] Please add '--debug' or '--log' to check more details.
[Fri Nov 29 09:00:40 PST 2019] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
[Fri Nov 29 09:00:40 PST 2019] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/1464660469/SP63VA'
[Fri Nov 29 09:00:40 PST 2019] payload='{}'
[Fri Nov 29 09:00:40 PST 2019] POST
[Fri Nov 29 09:00:40 PST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/1464660469/SP63VA'
[Fri Nov 29 09:00:40 PST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Fri Nov 29 09:00:40 PST 2019] _ret='0'
[Fri Nov 29 09:00:40 PST 2019] code='400'
[Fri Nov 29 09:00:41 PST 2019] Diagnosis versions: 
openssl:openssl
OpenSSL 1.1.0g  2 Nov 2017 (Library: OpenSSL 1.1.1  11 Sep 2018)
apache:
apache doesn't exists.
nginx:
nginx doesn't exists.
socat:
socat by Gerhard Rieger and contributors - see www.dest-unreach.org
Usage:
socat [options] <bi-address> <bi-address>
   options:
      -V     print version and feature information to stdout, and exit
      -h|-?  print a help text describing command line options and addresses
      -hh    like -h, plus a list of all common address option names
      -hhh   like -hh, plus a list of all available address option names
      -d     increase verbosity (use up to 4 times; 2 are recommended)
      -D     analyze file descriptors before loop
      -ly[facility]  log to syslog, using facility (default is daemon)
      -lf<logfile>   log to file
      -ls            log to stderr (default if no other log)
      -lm[facility]  mixed log mode (stderr during initialization, then syslog)
      -lp<progname>  set the program name used for logging
      -lu            use microseconds for logging timestamps
      -lh            add hostname to log messages
      -v     verbose data traffic, text
      -x     verbose data traffic, hexadecimal
      -b<size_t>     set data buffer size (8192)
      -s     sloppy (continue on error)
      -t<timeout>    wait seconds before closing second channel
      -T<timeout>    total inactivity timeout in seconds
      -u     unidirectional mode (left to right)
      -U     unidirectional mode (right to left)
      -g     do not check option groups
      -L <lockfile>  try to obtain lock, or fail
      -W <lockfile>  try to obtain lock, or wait
      -4     prefer IPv4 if version is not explicitly specified
      -6     prefer IPv6 if version is not explicitly specified
   bi-address:
      pipe[,<opts>]     groups=FD,FIFO
      <single-address>!!<single-address>
      <single-address>
   single-address:
      <address-head>[,<opts>]
   address-head:
      abstract-client:<filename>        groups=FD,SOCKET,RETRY,UNIX
      abstract-connect:<filename>       groups=FD,SOCKET,RETRY,UNIX
      abstract-listen:<filename>        groups=FD,SOCKET,LISTEN,CHILD,RETRY,UNIX
      abstract-recv:<filename>  groups=FD,SOCKET,RETRY,UNIX
      abstract-recvfrom:<filename>      groups=FD,SOCKET,CHILD,RETRY,UNIX
      abstract-sendto:<filename>        groups=FD,SOCKET,RETRY,UNIX
      create:<filename> groups=FD,REG,NAMED
      exec:<command-line>       groups=FD,FIFO,SOCKET,EXEC,FORK,TERMIOS,PTY,PARENT,UNIX
      fd:<num>  groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      gopen:<filename>  groups=FD,FIFO,CHR,BLK,REG,SOCKET,NAMED,OPEN,TERMIOS,UNIX
      interface:<interface>     groups=FD,SOCKET
      ip-datagram:<host>:<protocol>     groups=FD,SOCKET,RANGE,IP4,IP6
      ip-recv:<protocol>        groups=FD,SOCKET,RANGE,IP4,IP6
      ip-recvfrom:<protocol>    groups=FD,SOCKET,CHILD,RANGE,IP4,IP6
      ip-sendto:<host>:<protocol>       groups=FD,SOCKET,IP4,IP6
      ip4-datagram:<host>:<protocol>    groups=FD,SOCKET,RANGE,IP4
      ip4-recv:<protocol>       groups=FD,SOCKET,RANGE,IP4
      ip4-recvfrom:<protocol>   groups=FD,SOCKET,CHILD,RANGE,IP4
      ip4-sendto:<host>:<protocol>      groups=FD,SOCKET,IP4
      ip6-datagram:<host>:<protocol>    groups=FD,SOCKET,RANGE,IP6
      ip6-recv:<protocol>       groups=FD,SOCKET,RANGE,IP6
      ip6-recvfrom:<protocol>   groups=FD,SOCKET,CHILD,RANGE,IP6
      ip6-sendto:<host>:<protocol>      groups=FD,SOCKET,IP6
      open:<filename>   groups=FD,FIFO,CHR,BLK,REG,NAMED,OPEN,TERMIOS
      openssl:<host>:<port>     groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP,OPENSSL
      openssl-listen:<port>     groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,IP6,TCP,OPENSSL
      pipe:<filename>   groups=FD,FIFO,NAMED,OPEN
      proxy:<proxy-server>:<host>:<port>        groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP,HTTP
      pty       groups=FD,NAMED,TERMIOS,PTY
      sctp-connect:<host>:<port>        groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,SCTP
      sctp-listen:<port>        groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,IP6,SCTP
      sctp4-connect:<host>:<port>       groups=FD,SOCKET,CHILD,RETRY,IP4,SCTP
      sctp4-listen:<port>       groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,SCTP
      sctp6-connect:<host>:<port>       groups=FD,SOCKET,CHILD,RETRY,IP6,SCTP
      sctp6-listen:<port>       groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP6,SCTP
      socket-connect:<domain>:<protocol>:<remote-address>       groups=FD,SOCKET,CHILD,RETRY
      socket-datagram:<domain>:<type>:<protocol>:<remote-address>       groups=FD,SOCKET,RANGE
      socket-listen:<domain>:<protocol>:<local-address> groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE
      socket-recv:<domain>:<type>:<protocol>:<local-address>    groups=FD,SOCKET,RANGE
      socket-recvfrom:<domain>:<type>:<protocol>:<local-address>        groups=FD,SOCKET,CHILD,RANGE
      socket-sendto:<domain>:<type>:<protocol>:<remote-address> groups=FD,SOCKET
      socks4:<socks-server>:<host>:<port>       groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP,SOCKS4
      socks4a:<socks-server>:<host>:<port>      groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP,SOCKS4
      stderr    groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      stdin     groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      stdio     groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      stdout    groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      system:<shell-command>    groups=FD,FIFO,SOCKET,EXEC,FORK,TERMIOS,PTY,PARENT,UNIX
      tcp-connect:<host>:<port> groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP
      tcp-listen:<port> groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,IP6,TCP
      tcp4-connect:<host>:<port>        groups=FD,SOCKET,CHILD,RETRY,IP4,TCP
      tcp4-listen:<port>        groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,TCP
      tcp6-connect:<host>:<port>        groups=FD,SOCKET,CHILD,RETRY,IP6,TCP
      tcp6-listen:<port>        groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP6,TCP
      tun[:<ip-addr>/<bits>]    groups=FD,CHR,NAMED,OPEN,INTERFACE
      udp-connect:<host>:<port> groups=FD,SOCKET,IP4,IP6,UDP
      udp-datagram:<host>:<port>        groups=FD,SOCKET,RANGE,IP4,IP6,UDP
      udp-listen:<port> groups=FD,SOCKET,LISTEN,CHILD,RANGE,IP4,IP6,UDP
      udp-recv:<port>   groups=FD,SOCKET,RANGE,IP4,IP6,UDP
      udp-recvfrom:<port>       groups=FD,SOCKET,CHILD,RANGE,IP4,IP6,UDP
      udp-sendto:<host>:<port>  groups=FD,SOCKET,IP4,IP6,UDP
      udp4-connect:<host>:<port>        groups=FD,SOCKET,IP4,UDP
      udp4-datagram:<remote-address>:<port>     groups=FD,SOCKET,RANGE,IP4,UDP
      udp4-listen:<port>        groups=FD,SOCKET,LISTEN,CHILD,RANGE,IP4,UDP
      udp4-recv:<port>  groups=FD,SOCKET,RANGE,IP4,UDP
      udp4-recvfrom:<host>:<port>       groups=FD,SOCKET,CHILD,RANGE,IP4,UDP
      udp4-sendto:<host>:<port> groups=FD,SOCKET,IP4,UDP
      udp6-connect:<host>:<port>        groups=FD,SOCKET,IP6,UDP
      udp6-datagram:<host>:<port>       groups=FD,SOCKET,RANGE,IP6,UDP
      udp6-listen:<port>        groups=FD,SOCKET,LISTEN,CHILD,RANGE,IP6,UDP
      udp6-recv:<port>  groups=FD,SOCKET,RANGE,IP6,UDP
      udp6-recvfrom:<port>      groups=FD,SOCKET,CHILD,RANGE,IP6,UDP
      udp6-sendto:<host>:<port> groups=FD,SOCKET,IP6,UDP
      unix-client:<filename>    groups=FD,SOCKET,NAMED,RETRY,UNIX
      unix-connect:<filename>   groups=FD,SOCKET,NAMED,RETRY,UNIX
      unix-listen:<filename>    groups=FD,SOCKET,NAMED,LISTEN,CHILD,RETRY,UNIX
      unix-recv:<filename>      groups=FD,SOCKET,NAMED,RETRY,UNIX
      unix-recvfrom:<filename>  groups=FD,SOCKET,NAMED,CHILD,RETRY,UNIX
      unix-sendto:<filename>    groups=FD,SOCKET,NAMED,RETRY,UNIX
restarting v2ray...
v2ray restart fail !

**Comment by Jrohy** [comment]
`bash /root/.acme.sh/acme.sh --issue -d 域名 --debug --standalone --keylength ec-256 --listen-v6`

**Comment by Jrohy** [comment]
我用Hostdoc的ipv6 vps尝试获取证书就可以

**Comment by lqhorochi** [comment]
> 我用Hostdoc的ipv6 vps尝试获取证书就可以

重装过vps,重新来一次就可以了,.这条反馈可以关闭了

**Comment by lanlanmao1hao** [comment]
> > 域名是不是没绑定ip
> 
> 就是出现这几条错误
> 
> 5543.cf：验证错误：DNS 问题：SERVFAIL 为 5543.cf 查找 A
> 
> 错误代码请参考[https://curl.haxx.se/libcurl/c/libcurl-errors.html：28](https://curl.haxx.se/libcurl/c/libcurl-errors.html) _on_issue_err
> 
> 请添加“--debug”或“--log”以查看更多详细信息。
> 
> 见：[https ://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh](https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh)

输入的网址不完整，少了www.  ?
