### ISSUE TITLE
v2ray的软链接好像不对

### ISSUE THREAD

**Issue by Mozartor2** [Jrohy/multi-v2ray#257]
bash: v2ray: command not found
please input 'v2ray' command to manage v2ray
 安装之后
/etc/v2ray
/var/log/v2ray
/usr/bin/v2ray
/usr/bin/v2ray/v2ray
/usr/share/bash-completion/completions/v2ray
/home/mo/v2ray
[root@instance-2 mozart_auth]# ls -lrth
total 0
lrwxrwxrwx. 1 root root 20 Nov 29 10:31 v2ray -> /usr/local/bin/v2ray
本地链接的文件不存在

root@instance-2 mo**_auth]# uname -a
Linux instance-2 3.10.0-1062.4.3.el7.x86_64 #1 SMP Wed Nov 13 23:58:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Google GCE 主机 
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4
.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.7.1908 (Core)
Release:        7.7.1908
Codename:       Core

**Comment by Jrohy** [comment]
你看下v2ray-util有没有安装成功, 设置连接命令是`ln -s $(which v2ray-util) /usr/local/bin/v2ray` ，对v2ray-util命令进行设置链接

**Comment by Mozartor2** [comment]
是  v2ray-util没有安装成功。我看了下，bwg下的centos7 没有预装python3,  GCE预装了。
日志：
Collecting pip
  Using cached https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce
5551ec1/pip-19.3.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.3.1
    Uninstalling pip-19.3.1:
      Successfully uninstalled pip-19.3.1
  WARNING: The scripts pip, pip3 and pip3.6 are installed in '/usr/local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location
.
Successfully installed pip-19.3.1

这里导致后面调用pip命令没有安装成功。

**Comment by Jrohy** [comment]
嗯看下怎么安装好pip(python3用的)， 然后可以手动安装pip install v2ray-util, 安装完后手动加链接也是可以的`ln -s $(which v2ray-util) /usr/local/bin/v2ray`
