### ISSUE TITLE
如何更新到制定版本v2ray?

### ISSUE THREAD

**Issue by wsj195328** [Jrohy/multi-v2ray#259]
由于新版本脚本config.json增加了domain字段，导致老脚本无法兼容，请问如何更新到制定版本的v2ray??

**Comment by Jrohy** [comment]
直接用新版本脚本脚本，domain字段用来记录不同组可能用不一样的域名的情况

**Comment by wsj195328** [comment]
问题就是ssl+ws复制json到新脚本不可用啊。

旧版部分：
`   "tcpSettings": {},
        "kcpSettings": {},
        "httpSettings": {},
        "wsSettings": {
          "connectionReuse": true,
          "path": "/download/",
          "headers": {
            "Host": "taobao.com"
          }
        },
        "quicSettings": {}
      }
    },`

新版部分：
` "tcpSettings": {},
        "kcpSettings": {},
        "httpSettings": {},
        "wsSettings": {
          "path": "/download/",
          "headers": {
            "Host": "taobao.com"
          }
        },
        "quicSettings": {}
      },
      "domain": "xxxx.com"
    },`

**Comment by Jrohy** [comment]
这两天会出个新版做迁移兼容

**Comment by Jrohy** [comment]
会报错么，直接用新脚本，我看了代码如果没有domain字段就用本机ip来代替

**Comment by Jrohy** [comment]
https://pypi.org/project/v2ray-util/#history
可以pip随便切换版本的, v3.5.2版本开始支持按组存域名

**Comment by wsj195328** [comment]
旧版脚本json复制到新版脚本的json, ssl就不可用了，而且v2ray info 会卡住

**Comment by wsj195328** [comment]
if "domain" in part_json and part_json["domain"]:
            conf_ip = part_json["domain"]

我看了代码是做了判断的，会不会是domain字段无法兼容旧版的？

**Comment by Jrohy** [comment]
我测了删掉domain字段也没卡住，只是变为显示本机ip, 可以试试手动添加domain字段看看，旧和新的区别就是开启了tls后多了domain字段而已
