### ISSUE TITLE
建议添加备份迁移说明

### ISSUE THREAD

**Issue by GoldSubmarine** [Jrohy/multi-v2ray#260]
看到配置文件在 /etc/v2ray/config.json，把这个文件复制走就可以备份迁移了吗？
建议在readme中添加备份迁移说明，另外 dockerfile 也需要设置数据卷

**Comment by Jrohy** [comment]
docker是自己设置数据卷的，迁移就迁移config.json就行

**Comment by GoldSubmarine** [comment]
ok，thanks
