### ISSUE TITLE
在WS-TLS模式下可否加入web

### ISSUE THREAD

**Issue by ggfvictor** [Jrohy/multi-v2ray#266]
在上述模式下希望访问https://domain.com/xxxxxxx   可以通过web访问，同时websocket也能工作、也就是分流，作者可否增加该功能   伪装更加好点

**Comment by Jrohy** [comment]
可以自己加个Nginx或者caddy, 脚本只是方便修改json，加个nginx或者caddy不好控制

**Comment by ggfvictor** [comment]
感谢作者回复，了解了，可否指点一下搭建完caddy/nginx后如何配置下吗

**Comment by Jrohy** [comment]
自己查下，或者可以试试这个脚本`https://github.com/wulabing/V2Ray_ws-tls_bash_onekey`

**Comment by kun-qian** [comment]
@Jrohy  想请教下作者. 如果把443 端口改为 ws + tls了。那nginx 就没法设置web 443了吧。所以这两个是不是要用不用的端口，但是还能起到伪装的作用吗？

**Comment by Jrohy** [comment]
能否真正起到伪装效果难说，得亲自测试下
