### ISSUE TITLE
ubuntu14 报错

### ISSUE THREAD

**Issue by xiaoxue508** [Jrohy/multi-v2ray#267]
v2ray restart
/bin/sh: 1: systemctl: not found
v2ray restart fail !

**Comment by Jrohy** [comment]
建议换成ubuntu16+等新一点的系统，脚本已全面换成systemctl 命令，不支持service命令

**Comment by WalkerInfinite** [comment]
> 建议换成ubuntu16+等新一点的系统，脚本已全面换成systemctl 命令，不支持service命令

root@AuthorizedShameless-VM:~# v2ray restart 
restarting v2ray...
v2ray restart fail !
我是ubuntu16，刚开始还行，开启了h2就不能启动重启停止了，不知道哪里的问题

**Comment by Jrohy** [comment]
`systemctl status v2ray`  看下状态

**Comment by WalkerInfinite** [comment]
> 状态

Dec 10 13:22:38 caigo systemd[1]: Started V2Ray Service.
Dec 10 13:22:38 caigo v2ray[8764]: V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
Dec 10 13:22:38 caigo v2ray[8764]: A unified platform for anti-censorship.
Dec 10 13:22:38 caigo v2ray[8764]: main: failed to read config file: /etc/v2ray/config.json > v2ray.com/core/main/json: f
Dec 10 13:22:38 caigo v2ray[8764]:  > exit status 255
Dec 10 13:22:38 caigo systemd[1]: v2ray.service: Main process exited, code=exited, status=23/n/a
Dec 10 13:22:38 caigo systemd[1]: v2ray.service: Unit entered failed state.
Dec 10 13:22:38 caigo systemd[1]: v2ray.service: Failed with result 'exit-code'.
读取json文件失败？？？？

**Comment by Jrohy** [comment]
证书文件一个cert一个key文件，有搞错么 @WalkerInfinite

**Comment by WalkerInfinite** [comment]
> 自定义证书文件一个cert一个key文件，有搞错路径么 @WalkerInfinite

证书有指定名称吗？？

**Comment by Jrohy** [comment]
@WalkerInfinite 没有指定名称的，不行的话可以用lets encript证书
