### ISSUE TITLE
添加域名失败

### ISSUE THREAD

**Issue by iamfuxiaoer** [Jrohy/multi-v2ray#268]
用的是阿里云的online后缀的域名，已经配好cloudflare，但是在vps上面属实域名的时候提示域名检测错误

**Comment by Jrohy** [comment]
有关闭cloudflare的代理吗， 你可以试下ping域名看是不是解析到你的vps ip。要等搞好后才能开启代理的

**Comment by iamfuxiaoer** [comment]
已经解决  这个主要是clouflare的问题 他的页面上显示配置完成了 但是实际上好像域名和服务器并没有完成关联，后面ping域名ping不通，过了好久之后ping域名才能通
