### ISSUE TITLE
Debian 9 安装失败

### ISSUE THREAD

**Issue by dicrm** [Jrohy/multi-v2ray#269]
安装中文版..

new install

Ign:1 http://mirror.justhost.ru/debian stretch InRelease
Hit:2 http://mirror.justhost.ru/debian stretch Release         
Hit:3 http://security.debian.org/debian-security stretch/updates InRelease
Reading package lists... Done                     
Reading package lists... Done
Building dependency tree       
Reading state information... Done
cron is already the newest version (3.0pl1-128+deb9u1).
lsof is already the newest version (4.89+dfsg-0.1).
ntpdate is already the newest version (1:4.2.8p10+dfsg-3+deb9u2).
socat is already the newest version (1.7.3.1-2+deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
 Time Synchronizing.. 
14 Dec 15:04:49 ntpdate[7505]: adjust time server 91.209.94.10 offset 0.003347 sec
 Time Sync Success 
 now: Sat, 14 Dec 2019 15:04:49 +0800
beijing time 3, VPS time: 3

success open schedule update task: beijing time 3

Collecting v2ray_util
  Using cached https://files.pythonhosted.org/packages/d9/de/5169901ef440e5231957e04549e511e2c08c062449fceebe425582f7281f/v2ray_util-3.7.5.4-py3-none-any.whl
Installing collected packages: v2ray-util
Successfully installed v2ray-util-3.7.5.4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) Unknown SSL protocol error in connection to multi.netlify.com:443 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   670  100   670    0     0   1368      0 --:--:-- --:--:-- --:--:--  1370
Installing V2Ray v4.21.3 on x86_64
Downloading V2Ray: https://github.com/v2ray/v2ray-core/releases/download/v4.21.3/v2ray-linux-64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
Traceback (most recent call last):
  File "/usr/lib/python3.5/configparser.py", line 1135, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 5, in <module>
    from v2ray_util.main import menu
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/__init__.py", line 3, in <module>
    from .util_core.trans import _
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/util_core/__init__.py", line 1, in <module>
    from .trans import _
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/util_core/trans.py", line 10, in <module>
    lang = Config().get_data('lang')
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/util_core/config.py", line 22, in get_data
    return self.config.get('data', key)
  File "/usr/lib/python3.5/configparser.py", line 778, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.5/configparser.py", line 1138, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'data'
please input 'v2ray' command to manage v2ray

**Comment by Jrohy** [comment]
看下这个文件里面有没有data字段`/etc/v2ray_util/util.cfg` ， 没有的话删掉这个文件，运行v2ray会新建这文件
