### ISSUE TITLE
WS+TLS+Web(nginx) 可正常连接，但流量统计无效？

### ISSUE THREAD

**Issue by redhandsome** [Jrohy/multi-v2ray#271]
进行流量统计（v2ray和iptable）时直接就出错了，代码如下：
------------------------------------------------------------------------------
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/main.py", line 246, in menu
    global_setting()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/main.py", line 204, in global_setting
    stats_ctr.manage()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/global_setting/stats_ctr.py", line 62, in manage
    loader = Loader()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/loader.py", line 15, in __init__
    self.load_profile()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/loader.py", line 29, in load_profile
    self.profile = Profile()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/profile.py", line 28, in __init__
    self.read_json()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/profile.py", line 72, in read_json
    group = self.parse_group(json_part, index, local_ip)
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/profile.py", line 124, in parse_group
    host = conf_stream["wsSettings"]["headers"]["Host"]
KeyError: 'headers'
------------------------------------------------------------------------------

服务端配置如下：
------------------------------------------------------------------------------
{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "info"
  },
  "inbounds": [
    {
      "port": 10010,
      "tag": "tcp",
      "listen":   "127.0.0.1",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {"email": "apple@b.com","id": "1162b4fb-947c-4053-bf27-ee3cab8e87d1","alterId": 64},
					{"email": "eat@e.com","id": "e680b1c4-a646-45a3-9cab-7b7238ac271d","alterId":  64}
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "none",
        "tlsSettings": {},
        "tcpSettings": {},
        "httpSettings": {},
        "kcpSettings": {
          "mtu": 1350,
          "tti": 50,
          "uplinkCapacity": 100,
          "downlinkCapacity": 100,
          "congestion": false,
          "readBufferSize": 2,
          "writeBufferSize": 2,
          "header": {
            "type": "wechat-video"
          }
        },
        "wsSettings": {"path":   "/video"},
        "quicSettings": {}
      },
      "tag": "A"
    },
    {
      "listen": "127.0.0.1",
      "port": 6871,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "ip": [
          "0.0.0.0/8",
          "10.0.0.0/8",
          "100.64.0.0/10",
          "169.254.0.0/16",
          "172.16.0.0/12",
          "192.0.0.0/24",
          "192.0.2.0/24",
          "192.168.0.0/16",
          "198.18.0.0/15",
          "198.51.100.0/24",
          "203.0.113.0/24",
          "::1/128",
          "fc00::/7",
          "fe80::/10"
        ],
        "outboundTag": "blocked"
      },
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      }
    ]
  },
  "strategy": "rules",
  "stats": {},
  "api": {
    "services": [
      "StatsService"
    ],
    "tag": "api"
  },
  "policy": {
    "levels": {
      "0": {
        "statsUserDownlink": true,
        "statsUserUplink": true
      },
      "1": {
				"statsUserUplink": true,
				"statsUserDownlink": true
			}
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true
    }
  }
}

------------------------------------------------------------------------------
难道是 dokodemo-door 部分出错？

**Comment by Jrohy** [comment]
手动添加一下ws的header呗， 应该是手动修改了这块，加回去就行
https://github.com/Jrohy/multi-v2ray/blob/96ca0bdd4a624921b80c0c404335334dee8e0b6f/v2ray_util/json_template/ws.json#L10

**Comment by redhandsome** [comment]
解决了，确实是 header的问题，添加 
 "headers": {
      "Host": ""
}
之后就解决了。而且这个Host的值 可以留空 可正常统计了。
多谢！
