### ISSUE TITLE
修改设置时，自动返回上层菜单

### ISSUE THREAD

**Issue by yu4618** [Jrohy/multi-v2ray#272]
![0](https://user-images.githubusercontent.com/25944173/71148737-633adf80-2267-11ea-8f40-fc235a2c8fe8.jpg)
1.如图所示，修改TLS时，还没选择开启或者关闭时，瞬间就会跳转到主菜单，其他几个选项暂时没有这个问题。
2.前几个版本用着没有这个问题。

vps是vultr的centos7纯净安装，安装过程没有报错。

**Comment by Jrohy** [comment]
用vultr 的centos7测试了没发现有这问题，是不是多回车了下，新版正常情况下，选项数量在10以内(一个字符)，是免回车的

**Comment by yu4618** [comment]
我因为这个问题，重装系统五六次了，不是回车的问题。

如果是回车的话，进入“更改配置”时就会跳到主菜单。



我现在情况时 putty 进入“更改TLS设置”会跳到主菜单。其他的选项可以随便改，不会乱跳。
用portainer这个docker图形界面自带的命令行操作docker版本的v2ray也会跳主菜单。

是我这台机器五行克v2ray吗？😭😭😭

令人费解……

**Comment by Jrohy** [comment]
单独下了个putty测了vultr的centos7也是没问题，要用tls的话，可以开启cdn https来用都行

**Comment by Jrohy** [comment]
https://pypi.org/project/v2ray-util/#history 可以随便切换版本的，可以切换到旧版新版都行，可以试试旧版是不是真的行
