### ISSUE TITLE
可以实现服务器多ip出口控制吗？

### ISSUE THREAD

**Issue by BlackMask007** [Jrohy/multi-v2ray#277]
可以实现服务器多ip出口控制吗？

例如：
一台服务器有4个ip地址，（10.10.10.100、10.10.10.101、10.10.10.102、10.10.10.103）；
所有用户从10.10.10.100入；
添加一个A用户，指定A用户从10.10.10.101出；
添加一个B用户，指定B用户从10.10.10.102出；
添加一个C用户，指定C用户从10.10.10.103出；

**Comment by Jrohy** [comment]
https://www.v2ray.com/chapter_02/protocols/vmess.html#serverobject
可以自己改下json在server部分，貌似只能针对同组(端口)的设置
