### ISSUE TITLE
最近trojan比较火，期待能出一个 doker+trojan的脚本

### ISSUE THREAD

**Issue by oyanli** [Jrohy/multi-v2ray#282]
最近troan比较火，期待能出一个 doker+trojan的脚本

doker+V2ray很好用，而且自定义选项很方便，特别是自定义证书，很容易和秋大的ss + v2ray-plugin搭配使用。现在trojan比较火，测试上似乎也比V2ray快一些，希望也能出一个doker+trojan脚本，谢谢！！

**Comment by Jrohy** [comment]
会考虑下，可能配上mysql来实现统计和限制流量

**Comment by oyanli** [comment]
期待、期待、期待，希望能尽快用上，请一定保留自定义证书路径的选项，谢谢！

感恩！！

祝春节快乐、万事顺遂！！！

**Comment by yu4618** [comment]
> 会考虑下，可能配上mysql来实现统计和限制流量

都考虑mysql了，干脆多用户和wordpress或者宝塔面板也一起弄上吧

开心.jpg

**Comment by sddtly** [comment]
multi-v2ray脚本也可以和宝塔面板共存,而且配置更简单,,用v2ray就用TLS+websocket方式,其它的不安全,,其实trojan和v2ray的TLS+websocket基本上是一样的

**Comment by Jrohy** [comment]
https://github.com/Jrohy/trojan
