### ISSUE TITLE
开启tls后，无法启动v2，显示：v2ray restart fail !

### ISSUE THREAD

**Issue by tandalin** [Jrohy/multi-v2ray#283]
初始的kcp是可以用了。
添加新端口：”ws+tls后
连kcp端口的都用不了。
显示：v2ray restart fail !

关闭tls能用。

**Comment by Jrohy** [comment]
看下v2ray status

**Comment by tandalin** [comment]
> 看下v2ray status

[root@ecs-ySy ~]# v2ray status
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: disabled)
   Active: **failed** (Result: exit-code) since 二 2020-01-21 16:30:17 CST; 10s ago
  Process: 13705 ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json (code=exited, status=23)
 Main PID: 13705 **(code=exited, status=23)**

1月 21 16:30:16 ecs-ySy systemd[1]: Started V2Ray Service.
1月 21 16:30:16 ecs-ySy systemd[1]: Starting V2Ray Service...
1月 21 16:30:16 ecs-ySy v2ray[13705]: V2Ray 4.22.1 (V2Fly, a c...
1月 21 16:30:16 ecs-ySy v2ray[13705]: A unified platform for a...
1月 21 16:30:17 ecs-ySy v2ray[13705]: main: failed to read con...
1月 21 16:30:17 ecs-ySy v2ray[13705]: > exit status 255
1月 21 16:30:17 ecs-ySy systemd[1]: v2ray.service: main proces...
1月 21 16:30:17 ecs-ySy systemd[1]: Unit v2ray.service entered...
1月 21 16:30:17 ecs-ySy systemd[1]: v2ray.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by tandalin** [comment]
{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "info"
  },
  "inbounds": [
    {
      "port": 443,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "53f8f4b0-3bfa-11ea-ac18-0084cb000000",
            "alterId": 16,
            "email": "dalin@ceshi.1"
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "certificates": [
            {
              "certificateFile": "/root/.acme.sh/001.域名.in_ecc/fullchain.cer",
              "keyFile": "/root/.acme.sh/001.域名.in_ecc/001.域名.in.ke.y"
            }
          ]
        },
        "tcpSettings": {},
        "kcpSettings": {},
        "httpSettings": {},
        "wsSettings": {
          "path": "/aeHBMbz6/",
          "headers": {
            "Host": "001.域名.in"
          }
        },
        "quicSettings": {}
      },
      "domain": "001.域名.in"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "ip": [
          "0.0.0.0/8",
          "10.0.0.0/8",
          "100.64.0.0/10",
          "169.254.0.0/16",
          "172.16.0.0/12",
          "192.0.0.0/24",
          "192.0.2.0/24",
          "192.168.0.0/16",
          "198.18.0.0/15",
          "198.51.100.0/24",
          "203.0.113.0/24",
          "::1/128",
          "fc00::/7",
          "fe80::/10"
        ],
        "outboundTag": "blocked"
      }
    ]
  }
}

**Comment by tandalin** [comment]
cetos4.7.4和7.6情况一样。
防火墙已关闭且禁止启动。
已经重启过。

**Comment by tandalin** [comment]
可以用了，好像是配置文件位置问题。谢谢谢

**Comment by ARRrui** [comment]
> 可以用了，好像是配置文件位置问题。谢谢谢

能不能展开说说解决办法 感谢
