### ISSUE TITLE
用户ID与IP显示问题

### ISSUE THREAD

**Issue by vpsceo** [Jrohy/multi-v2ray#284]
1、用户ID希望添加自定义UUID功能，方便维护服务器后恢复原来的数据。目前系统只能自动生成，不能指定回原来的UUID。
2、希望增加服务器IP指定成域名功能，防止更换服务器后导致已经分发的客户端不能使用。还得通知改IP。

**Comment by Jrohy** [comment]
改uuid的话可以直接去改json文件，开启tls就能指定域名了

**Comment by vpsceo** [comment]
UUID脚本里边能否修改一下呢？
1、随机  2、手动  3、不改动

我是说的服务器IP地址哦？这里TLS能起作用？

**Comment by Jrohy** [comment]
恢复原来的数据的话，直接用原来json文件来替换就行

**Comment by Jrohy** [comment]
你更换服务器后为了配置信息不变，用域名指定配置信息地址，将域名指向到新的ip就好
