### ISSUE TITLE
请教下iptables流量统计为零是怎么回事?

### ISSUE THREAD

**Issue by sddtly** [Jrohy/multi-v2ray#287]
端口号:  upload:0.0 bytes download:0.0 bytes total:0.0 bytes

**Comment by sddtly** [comment]
debian9 ,安装了BBRplus

**Comment by sddtly** [comment]
手动执行以下命令后可看到流量统计,
`iptables -I INPUT -p tcp --dport 12345
iptables -I INPUT -p udp --dport 12345
iptables -I OUTPUT -p tcp --sport 12345
iptables -I OUTPUT -p udp --sport 12345`

**Comment by Jrohy** [comment]
用vultr的debian9试了下，iptables统计流量没问题，没安装bbrplus

**Comment by Jrohy** [comment]
你可以不装bbrplus试下，没测试过兼容性

**Comment by sddtly** [comment]
> 你可以不装bbrplus试下，没测试过兼容性
脚本是好的,至少我Ubuntu18.04上是好用的,,,,,,

不知道为什么,,,,,我这边用"iptables-persistent" 的"netfilter-persistent save"命令,,无法使iptables规则无法持久化,,,重启后规则就没有了,,,,

后来按照下面的连接所说的方法解决的(创建自启动配置文件/etc/network/if-pre-up.d/iptables)
https://wiki.debian.org/iptables

**Comment by kun-qian** [comment]
同问

**Comment by sddtly** [comment]
> 同问

看此文章,密码:awzh       https://www.ybj.ink/254.html#title-4
