### ISSUE TITLE
服务端已经收到了请求，为什么还是没法打开google.com了？

### ISSUE THREAD

**Issue by chenyaotie** [Jrohy/multi-v2ray#288]
服务日志：
2020/02/06 15:23:44 udp:***.***.***.***:42908 accepted tcp:youtube.com:443
客服端 上显示延时143ms。
按理说已经连接上了，为什么还是无法翻出去
开启的是PAC模式。

**Comment by hunao0221** [comment]
我这里出现了同样的情况
