### ISSUE TITLE
希望大神加入Trojan的功能

### ISSUE THREAD

**Issue by trombonist852** [Jrohy/multi-v2ray#290]
强烈希望呀！！！！一直在用您的这个脚本，非常好用

**Comment by Os-glthub** [comment]
大神你好，请问Ubuntu 一键脚本，啥时候可以提上日程，最近V2走CDN都不稳

**Comment by Jrohy** [comment]
@trombonist852  https://github.com/Jrohy/trojan 独立的新项目

**Comment by trombonist852** [comment]
> @trombonist852 https://github.com/Jrohy/trojan 独立的新项目

哇 感谢大神！！！这就去试试！！！

**Comment by trombonist852** [comment]
@Jrohy 
感谢大神！这就去试试！！！
