### ISSUE TITLE
用域名开cdn失败不知道为什么

### ISSUE THREAD

**Issue by token361** [Jrohy/multi-v2ray#291]
我之前买的vps被墙了，想开cdn绕开，大神用的你的脚本，挂免费vpn连接的vps，然后安装成功了，把域名什么的输入进去，选https和http都用不了不知道为什么，ping域名已经转到cdn的地址了，是不是因为我挂vpn所以安装时时间默认同步的我vpn地址的时间啊，或者有其他的问题，麻烦大神看一下，如果需要我发什么数据的话，请尽管吩咐邮箱是haotian361@gmail.com，或者qq2227482718

**Comment by Jrohy** [comment]
http封锁太严重现在不太行了，https的证书申请到了吗

**Comment by token361** [comment]
https证书怎么申请啊 不是直接开https cdn就行吗

**Comment by Jrohy** [comment]
是的。如果真不行可以试下docker版本，我之前部了个docker版一直能用

**Comment by token361** [comment]
老哥docker版本怎么开啊  有没有什么教程什么的啊

**Comment by token361** [comment]
现在直接用脚本安装输出也有问题了  我找了个没被墙的ip 安装了这个脚本  现在用v2ray都连不上了emmm  我裂开来

**Comment by Jrohy** [comment]
1. 安装docker
`source <(curl -sL https://git.io/docker-install)`
2. 运行容器
`docker run -d --name v2ray --privileged --restart always --network host jrohy/v2ray`
3. 进入容器
`docker exec -it v2ray bash`

进入容器后在容器里面操作即可

**Comment by token361** [comment]
你好  按照这个命令安装  输出的的链接就是无法联通  不知道是不是vps有问题  要不要您受累帮我看看 IP Address: 173.82.105.170
Username: root
Password: H2JtFabXECs3

**Comment by Jrohy** [comment]
删了信息吧，敏感信息，我看到信息了

**Comment by Jrohy** [comment]
我帮你看下，要开启cdn么，要开的话给个域名，上面的服务器信息不要留着建议删了

**Comment by Jrohy** [comment]
帮你删了

**Comment by Jrohy** [comment]
@token361 可以了，日志报VMess: Invalid User 参考: `https://www.v2ray.com/chapter_00/faq.html`
服务器时间不对，帮你手动调了时间就可以了

**Comment by token361** [comment]
好的  谢谢  进去试了一下可以了 真的谢谢了 折腾了半天都不行  服务器我会换密码的 cdn什么的我自己去开启好了  刚刚家里有点事

**Comment by token361** [comment]
请问一下 我以后用这个命令修改一下可以吗 date -s "2018-2-22 19:10:30"

**Comment by Jrohy** [comment]
我就是用这个修改的，ntpdate好像同步不了，查了下可能服务商影响了， `https://askubuntu.com/questions/429306/ntpdate-no-server-suitable-for-synchronization-found`

**Comment by Jrohy** [comment]
v2ray update.sh 可以更新下脚本，刚推送了新版，去掉http 的cdn了，这种模式成功率太低也怕被墙ip(至少我测试没成功过)， 只留下https 的cdn

**Comment by token361** [comment]
emmmmm 不知道为什么我自己安装又不行了  我修改了时间 date命令出来的时间和本地时间一样的 但是不管是直接安装脚本还是用docker都不行  不走cdn的时候v2ray服务还能成功 但是输出的配置还是无法连接 一走11那个域名就显示v2ray启动失败 用脚本1启动和重启服务还是显示fail 您再帮我看看？173.82.105.170 By2j9Y752SmyU533 里面是我安装了无法使用 脚本也更新过了 都不行

**Comment by Jrohy** [comment]
域名申请到了吗，重启失败的话

**Comment by Jrohy** [comment]
![image](https://user-images.githubusercontent.com/12463263/74616675-3cfcc780-5164-11ea-8016-7ed20a017a79.png)
证书申请失败，看看能否换个域名, v2ray找不到证书所以重启不成功

**Comment by token361** [comment]
我重装了系统 把时间改了 date出来的时间也一样了 用你的脚本安装成功了  v2ray服务倒是成功启动了。。这次没套域名  还是连接不了  不知道啥情况emm

**Comment by Jrohy** [comment]
v2ray log显示啥

**Comment by token361** [comment]
密码这次没换 还是昨天那个

**Comment by token361** [comment]
-- Logs begin at Mon 2020-02-17 17:41:25 UTC, end at Mon 2020-02-17 19:54:24 UTC. --Feb 17 17:41:36 7233 systemd[1]: Started V2Ray Service.Feb 17 17:41:36 7233 v2ray[3079]: V2Ray 4.22.1 (V2Fly, a community-driven edition of V2RFeb 17 17:41:36 7233 v2ray[3079]: A unified platform for anti-censorship.Feb 17 17:43:49 7233 systemd[1]: Stopping V2Ray Service...Feb 17 17:43:49 7233 systemd[1]: Stopped V2Ray Service.Feb 17 17:43:49 7233 systemd[1]: Started V2Ray Service.Feb 17 17:43:49 7233 v2ray[3183]: V2Ray 4.22.1 (V2Fly, a community-driven edition of V2RFeb 17 17:43:49 7233 v2ray[3183]: A unified platform for anti-censorship.

**Comment by token361** [comment]
这个是日志 重复这个  2020/02/17 18:01:23 117.136.53.166:36281 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > v2ray.com/core/transport/internet/kcp: Read/Write timeout2020/02/17 18:01:23 117.136.53.166:36309 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user2020/02/17 18:01:24 117.136.53.166:36310 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user2020/02/17 18:01:25 117.136.53.166:36311 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user2020/02/17 18:01:26 117.136.53.166:36312 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user2020/02/17 18:01:27 117.136.53.166:36313 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user2020/02/17 18:01:28 117.136.53.166:36314 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user2020/02/17 18:01:29 117.136.53.166:36315 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user2020/02/17 18:01:32 117.136.53.166:36316 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user2020/02/17 18:01:32 117.136.53.166:36308 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user

**Comment by token361** [comment]
2020/02/17 18:01:23 117.136.53.166:36281 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > v2ray.com/core/transport/internet/kcp: Read/Write timeout2020/02/17 18:01:23 117.136.53.166:36309 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user2020/02/17 18:01:24 117.136.53.166:36310 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user2020/02/17 18:01:25 117.136.53.166:36311 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user2020/02/17 18:01:26 117.136.53.166:36312 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user2020/02/17 18:01:27 117.136.53.166:36313 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user2020/02/17 18:01:28 117.136.53.166:36314 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user2020/02/17 18:01:29 117.136.53.166:36315 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user2020/02/17 18:01:32 117.136.53.166:36316 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user2020/02/17 18:01:32 117.136.53.166:36308 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
这个是状态

**Comment by token361** [comment]
v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2020-02-17 17:43:49 UTC; 2h 14min ago
 Main PID: 3183 (v2ray)
   CGroup: /system.slice/v2ray.service
           └─3183 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json

Feb 17 17:43:49 7233 systemd[1]: Started V2Ray Service.
Feb 17 17:43:49 7233 v2ray[3183]: V2Ray 4.22.1 (V2Fly, a community-driven edition ...64)
Feb 17 17:43:49 7233 v2ray[3183]: A unified platform for anti-censorship.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by Jrohy** [comment]
大哥你时间不对啊，时区都不对，

**Comment by Jrohy** [comment]
改成utf时区啊,要不你时区换成北京时区

**Comment by token361** [comment]
你是说 utc时区吧  [root@7233 ~]# date
Mon Feb 17 20:34:45 UTC 2020 我刚刚用tzselect改了时区  然后重新安装了一下脚本  还是不行emmm

**Comment by Jrohy** [comment]
是的

**Comment by token361** [comment]
可是还是用不了啊  刚刚用tzselect改了时区 然后重新安装了一下脚本 还是不行emmm

**Comment by Jrohy** [comment]
可以了帮你改成utc的时间了，你之前都没改成功时区

**Comment by Jrohy** [comment]
顺便问下这家什么vps

**Comment by token361** [comment]
cloudcone家的 比较便宜方便 按小时计费比较灵活  就是ip容易被墙  顺便求一下怎么改时区的命令  我以后总不能老是来求你吧😂😂😂

**Comment by Jrohy** [comment]
我没改时区，直接改的时间，在不同国家的服务器还是用当地时区好点

**Comment by token361** [comment]
那么命令是怎么写的嘛 请教一下?

**Comment by Jrohy** [comment]
网上搜一下utc时间， date -s "2018-2-22 19:10:30"直接这样改，改为要重启下v2ray

**Comment by token361** [comment]
我之前就是这样改的啊  输这个命令  然后重启
用的下面这个教程  修改步骤如下
查看当前系统时间 date
修改当前系统时间 date -s "2018-2-22 19:10:30"
查看硬件时间 hwclock --show
修改硬件时间 hwclock --set --date "2018-2-22 19:10:30"
同步系统时间和硬件时间 hwclock --hctosys
保存时钟 clock -w
重启系统（init 6）后便发现系统时间被修改了

**Comment by Jrohy** [comment]
重启不知道是不是vps商的启动改回去了，要不不要重启，要不联系vps商反馈时间不对的问题

**Comment by token361** [comment]
好的  解决了  最后问一下在哪里申请什么后缀的域名比较便宜  我这个是申请的免费的tk域名  估计确实不行

**Comment by Jrohy** [comment]
namecheap 选些1美刀左右的

**Comment by token361** [comment]
谢谢 都搞定了  对了  你更新的那个脚本只有打开cdn的选项了  好像去的时候一起把关闭cdn的选项也去了

**Comment by Jrohy** [comment]
那个是关http cdn的（去掉域名），https cdn可以随意切换的

**Comment by hy817120** [comment]
> 然后安装成功了，把

你被墙的ip套cdn速度有多少 youtube， 我最近也被墙了 但是速度太慢了

**Comment by token361** [comment]
我最近开了个阿里云的轻服务器 香港的&nbsp; 想能不能搭个v2ray打游戏看行不行 用了docker布了你的脚本 但是不知道为什么用不了 明明显示都成功了 系统时间我看是正常的 脚本那个运行日志一输入5就卡住了 麻烦有时间帮忙看一下 不急&nbsp;centos7.3 防火墙也删了IP 用户和密码是root 和mxisfjsifgkvsxmjkfs5646D&nbsp;
