### ISSUE TITLE
v2ray电脑客户端打不开网页

### ISSUE THREAD

**Issue by LinYKen** [Jrohy/multi-v2ray#292]
500 Internal Privoxy Error
Privoxy encountered an error while processing your request:

Could not load template file forwarding-failed or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

最近这个问题一直有，而且服务器开启端口用十几个小时，就连不上了，手机也是，但是换个port改了就能接着连接

**Comment by Jrohy** [comment]
v2ray官方反馈下
