### ISSUE TITLE
请问cdn的端口如何配置？

### ISSUE THREAD

**Issue by wsj195328** [Jrohy/multi-v2ray#294]
目前我看到只有443，2053， 2083.....等这几个默认的cdn端口。首先是2053我配置cdn可用可上网，然后直接修改config.json其他端口配置项与2053一致，其他端口用不了，2053可以，请问如何让其他端口也能走cdn?

**Comment by wsj195328** [comment]
https://support.cloudflare.com/hc/en-us/articles/200169156-Identifying-network-ports-compatible-with-Cloudflare-s-proxy

看了一下代码，发现就只支持这些端口。没办法了，请问哪家CDN支持的端口比较多

**Comment by Jrohy** [comment]
不太清楚，目前只用cloudflare, 你发现其他的可以手动更改端口 + ws + https 改配置就行

**Comment by wsj195328** [comment]
好的，谢谢

**Comment by wjnds** [comment]
> 不太清楚，目前只用cloudflare, 你发现其他的可以手动更改端口 + ws + https 改配置就行

请问如何手动更改端口？任意端口比如5位数的改吗？
通过面板来修改端口后访问不了G，该端口TCP是可用的

**Comment by Jrohy** [comment]
`v2ray port`即可更改端口

**Comment by wjnds** [comment]
> `v2ray port`即可更改端口

已修改端口，但还是无法访问

**控制台信息如下：**

启动服务(2020/2/26 20:34:23)......
V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 windows/amd64)
A unified platform for anti-censorship.
2020/02/26 20:34:23 [Warning] v2ray.com/core: V2Ray 4.22.1 started
2020/02/26 20:34:28 tcp:127.0.0.1:58469 accepted tcp:www.google.com:443 [proxy] 
2020/02/26 20:34:28 tcp:127.0.0.1:58476 accepted tcp:www.gstatic.com:443 [proxy] 
2020/02/26 20:34:28 tcp:127.0.0.1:58478 accepted tcp:apis.google.com:443 [proxy] 
2020/02/26 20:34:32 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://wb.***om:41819/gxpW6MAt/):  > EOF] > v2ray.com/core/common/retry: all retry attempts failed
2020/02/26 20:34:33 tcp:127.0.0.1:58485 accepted tcp:www.google.com:443 [proxy] 
2020/02/26 20:34:37 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://wb.***om:41819/gxpW6MAt/):  > EOF] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by Jrohy** [comment]
cloudclare cdn只支持几个https的端口的(443 2053 2083 2087 2096 8443), 其他端口走不了cdn

**Comment by Jrohy** [comment]
如果要改成非cdn支持的端口， 记得去cloudflare解除域名代理，变为dns only 只做dns解释

**Comment by wsj195328** [comment]
好的，谢谢
