### ISSUE TITLE
我选择用户管理出错了。

### ISSUE THREAD

**Issue by wi6146149** [Jrohy/multi-v2ray#296]
Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/main.py", line 240, in menu
    user_manage()
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/main.py", line 163, in user_manage
    multiple.del_port()
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/v2ray.py", line 18, in wrapper
    result = func(*args, **kw)
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/config_modify/multiple.py", line 117, in del_port
    gs = GroupSelector(_('del port'))
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/selector.py", line 89, in __init__
    self.group = self.group_list[0]
IndexError: list index out of range

谷歌云+centos8   不知道如何解决

**Comment by Jrohy** [comment]
全新安装的吗，有选过什么配置没

**Comment by Jrohy** [comment]
有没有自己手动改过配置文件

**Comment by wi6146149** [comment]
全新安装的，没有动过任何东西，就是谷歌云实例，然后直接脚步，没有动过任何东西

**Comment by wi6146149** [comment]
我卸载了重新刷脚本，用户可以正常建立了，然后用v2ray，无法访问youtube呢，是从用户那里复制vmess的url的。

**Comment by Jrohy** [comment]
v2ray log 看下日志

**Comment by wi6146149** [comment]
输入了，没有显示任何东西

**Comment by Jrohy** [comment]
"access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",

**Comment by wi6146149** [comment]
没有生成这两个文件

**Comment by Jrohy** [comment]
V2ray启动成功了吗，v2ray status看下

**Comment by wi6146149** [comment]
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: disa>
   Active: active (running) since Mon 2020-02-17 22:48:46 CST; 1h 7min ago
 Main PID: 6220 (v2ray)
    Tasks: 10 (limit: 26213)
   Memory: 9.0M
   CGroup: /system.slice/v2ray.service
           └─6220 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json

Feb 17 22:48:46 huanglz systemd[1]: Stopped V2Ray Service.
Feb 17 22:48:46 huanglz systemd[1]: Started V2Ray Service.
Feb 17 22:48:46 huanglz v2ray[6220]: V2Ray 4.22.1 (V2Fly, a community-driven editi>
Feb 17 22:48:46 huanglz v2ray[6220]: A unified platform for anti-censorship.

启动成功了。

**Comment by wi6146149** [comment]
重新创建VPS，重新刷脚本，现在可以正常使用了，不过有个疑问，就是不一样的协议只能走特定的端口吗，比如https只能443，http/2是80这样，尝试其他端口，youtube上不了，不是很理解，那怎么自定义端口呢？

**Comment by Jrohy** [comment]
不一定的，cloudflare cdn 的https端口就有几个，

**Comment by wi6146149** [comment]
好的，谢谢。
