### ISSUE TITLE
请问有 tel群吗？

### ISSUE THREAD

**Issue by wangluyichen** [Jrohy/multi-v2ray#299]
请问有 tel群吗？

**Comment by slhzsy** [comment]
V2Ray绅士
分享自建闲置爱国服务，
量不在多，在于维护和更新

保证发的每条分享都是有效

所有节点搭建脚本：
https://github.com/Jrohy/multi-v2ray
https://t.me/v2ray_share

wangluyichen <notifications@github.com> 于 2020年2月22日周六 21:49写道：
