### ISSUE TITLE
修改配置时报错

### ISSUE THREAD

**Issue by rickycm** [Jrohy/multi-v2ray#30]
1.更改email

2.更改UUID

3.更改alterID

4.更改主端口

5.更改传输方式

6.更改TLS设置

7.更改广告拦截功能

8.更改动态端口

9.更改Shadowsocks加密方式

10.更改Shadowsocks密码

请输入数字选择功能： 4

Traceback (most recent call last):
  File "/usr/local/multi-v2ray/config_modify/port.py", line 3, in <module>
    import read_json
ImportError: No module named 'read_json'
Traceback (most recent call last):
  File "/usr/local/multi-v2ray/base_util/open_port.py", line 4, in <module>
    import read_json
ImportError: No module named 'read_json'

**Comment by Jrohy** [comment]
什么系统呢, 应该是环境变量没设置到,试下执行
``echo "export PYTHONPATH=$PYTHONPATH:/usr/local/multi-v2ray" >> ~/.bashrc && source ~/.bashrc```

**Comment by rickycm** [comment]
> 什么系统呢, 应该是环境变量没设置到,试下执行
> `echo "export PYTHONPATH=$PYTHONPATH:/usr/local/multi-v2ray" >> ~/.bashrc && source ~/.bashrc`

还是报一样的错，Ubuntu系统

**Comment by Jrohy** [comment]
重开终端看下

**Comment by rickycm** [comment]
> 重开终端看下

可以了，发现用sudo 安装就报错，要su 到root下，然后再招行安装
