### ISSUE TITLE
这个是不是unzip不能安装呢？

### ISSUE THREAD

**Issue by wangluyichen** [Jrohy/multi-v2ray#300]
pkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem. 
Failed to install unzip. Please install it manually.

**Comment by wangluyichen** [comment]
这个pkg被终止，该怎么做呢？

**Comment by Jrohy** [comment]
手动安装unzip看看,v2ray安装时需要的

**Comment by wangluyichen** [comment]
嗯，能告诉下debian9 手动安装的命令吗？我是好久没弄过了。

**Comment by Jrohy** [comment]
apt-get update

**Comment by wangluyichen** [comment]
嗯，好的，感谢你！！！
