### ISSUE TITLE
域名cdn代理异常

### ISSUE THREAD

**Issue by lsgbx** [Jrohy/multi-v2ray#305]
最近ip被墙了，想开个cdn中转下（Debian 9）
用的是进入服务器，v2ray-3-5(改协议）-11（走cdn），输入域名，1自动获取证书
之前没被墙的时候，cloudflare dnsonly 可以连得上，点了小云朵代理上就连不上了
cdn防火墙啥的全改最宽松了
不知道怎么回事，域名也注册新的了，看v2rayn，连那个节点一点日志都没有，日志级别warning-。V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 windows/386)
A unified platform for anti-censorship.
很久以前在另一个机器上注册过cdn，误打误撞，80端口ws协议，cdn那边还是flexible加密，小云朵确认点成橙色，然后就可以正常代理
麻烦帮忙分析一下，如果需要登录vps和cdn请给一个传递账号的联系方式

**Comment by Jrohy** [comment]
不要用http的cdn, 用https的，之前的http cdn被我取消了，基本用不了了

**Comment by lsgbx** [comment]
请问怎样配置是https的cdn呢
https://zhuanlan.zhihu.com/p/86083185
我的做法差不多就是这样的
![Screenshot_20200228-225125_Firefox](https://user-images.githubusercontent.com/36256836/75558528-eb660e00-5a7c-11ea-8aa4-167734af264c.png)
![Screenshot_20200228-225036_Firefox](https://user-images.githubusercontent.com/36256836/75558540-eef99500-5a7c-11ea-9bb2-a4802b847ab9.png)
![Screenshot_20200228-225025_Firefox](https://user-images.githubusercontent.com/36256836/75558557-f28d1c00-5a7c-11ea-9d91-adb3cc13ec57.png)
![Screenshot_20200228-225018_Firefox](https://user-images.githubusercontent.com/36256836/75558562-f5880c80-5a7c-11ea-8f5e-3a7cd85c6c08.png)
![Screenshot_20200228-225009_Firefox](https://user-images.githubusercontent.com/36256836/75558575-fa4cc080-5a7c-11ea-8f09-2d33d42524f0.png)
![Screenshot_20200228-224941_Firefox](https://user-images.githubusercontent.com/36256836/75558587-ff117480-5a7c-11ea-9b47-c41c8e468516.png)

附上一些cdn里的设置

**Comment by hy817120** [comment]
走cdn代理真的慢， 不过还是可以用，这个脚本好用

**Comment by lsgbx** [comment]
![图片](https://user-images.githubusercontent.com/36256836/75606633-b237a780-5b29-11ea-8e01-81fb4ddbf7ca.png)
![图片](https://user-images.githubusercontent.com/36256836/75606673-26724b00-5b2a-11ea-8c0d-adc872c9f921.png)
再补两个配置图

**Comment by lsgbx** [comment]
这回我换本家cf的ca了，pem，key都已上传
也在v2ray脚本里重新指定密钥
第三方ssl check成功识别cf 密钥
然后开启cdn，断连。。。。
dns清理掉，重新ping，确认是cdn的ip
开启服务端日志显示，和本地v2rayn
测试真链接，两边一点日志都不刷新
。。。。。我自闭了
不知道有没有必要去v2raycore的hub反馈求助
他们那里的cdn问题我都看了，时间错误，路径错误，ws没开，防火墙敏感度off，关闭antibot，别开https http互换，几乎所有的帖子我都研究了，依旧无法解决我的问题
而且，我是两台机器都这样。。。
诶

**Comment by lsgbx** [comment]
我好了，回我真的好了
mdzz
我把自定义证书的cert文件后缀写成了.pem
改了就好了
两台机器cdn都通了
基础不牢，地动山摇
hhhhh哭了都，搞了半个月了

**Comment by lsgbx** [comment]
cert文件后缀.cer
key文件后缀.key
