### ISSUE TITLE
同端口多配置冲突

### ISSUE THREAD

**Issue by yesmiley** [Jrohy/multi-v2ray#312]
相同端口，配置不同，添加成功，但是会导致配置不能连接，也就是冲突了。

**个人建议：要么请大神开发实现下这个功能，要么检测并禁止同端口多配置。**

**Comment by Jrohy** [comment]
是端口冲突了吗，建了多个相同端口，用的不同配置?

**Comment by Jrohy** [comment]
确实缺乏这个端口检测，近期加上

**Comment by Jrohy** [comment]
@yesmiley 新版已修复, 之前只做了tcp的端口检测，现在补上了udp端口检测占用

**Comment by yesmiley** [comment]
感谢！
