### ISSUE TITLE
流量统计建议

### ISSUE THREAD

**Issue by Shawn-Shichen-Wang** [Jrohy/multi-v2ray#313]
**首先感谢大佬维护脚本！**
- 希望加入定时自动重置所有端口流量统计功能，比如输入“010000”设置每月1号0点整重置所有端口的流量统计
- 在重置流量统计时希望增加重置所有端口选项

**Comment by hy817120** [comment]
你干脆喊大佬给你直接开发个vpn计量平台，你坐在那里收钱就行，
不懂技术有想要商业功能，最简单的方式就是拿钱，又不想拿钱还想坐地收钱，我觉得有些人的思维真的很奇葩， 这个其实有个什么难的？懂一点点python就能做到，无非是改配置文件，

**Comment by aalonelyy** [comment]
> 你干脆喊大佬给你直接开发个vpn计量平台，你坐在那里收钱就行，
> 不懂技术有想要商业功能，最简单的方式就是拿钱，又不想拿钱还想坐地收钱，我觉得有些人的思维真的很奇葩， 这个其实有个什么难的？懂一点点python就能做到，无非是改配置文件，

不好意思我之前一直在用ss的多用户脚本最近才转来v2ray，因为是几个好朋友一起租的VPS大家都不怎么懂所以才到处找的这些适合小白的，我只是从使用者角度提出自己的建议因为之前用的ss多用户脚本有这些功能。
我认为issues就是与开发者交流的地方，如果需要钱维持开发可以开捐助通道；另外我最近刚好在学Python，算是懂一点吧但是不知道从哪里下手去改，等我学的精进一些可以帮上忙一定帮助commit
