### ISSUE TITLE
第二天无法使用

### ISSUE THREAD

**Issue by Jungle-Leesin** [Jrohy/multi-v2ray#315]
搭建好之后，添加了两个用户，第二天就没法使用，只有卸载重装才可以，请问是什么问题

**Comment by Jrohy** [comment]
没法用时报的日志是什么呢，重启V2ray也是没用么

**Comment by Jungle-Leesin** [comment]
对，重启v2和服务器都没用，只有重新增加一个新的用户或者重装这个脚本才可以用

**Comment by Jrohy** [comment]
用的mkcp协议么， 可以向官方反应, 也不知是不是墙升级了

**Comment by whitepoplars** [comment]
我也有这个问题，两个用户，第二天就都不能用了

**Comment by Jrohy** [comment]
要不关掉每天自动更新，然后新建用户再试试，可能现在也没必要每天自动更新v2ray了

**Comment by whitepoplars** [comment]
好，谢谢大佬

**Comment by cheneyxx** [comment]
是自动更新出现的问题 我已经确定了 凌晨三点自动更新导致服务没有启动起来

**Comment by whitepoplars** [comment]
装了最新版本，现在一点问题都没有了
