### ISSUE TITLE
机器ip变更了，输入v2ray查看配置还是以前的ip

### ISSUE THREAD

**Issue by eicky** [Jrohy/multi-v2ray#316]
机器ip变更了，输入v2ray查看配置还是以前的ip，希望能增加动态获取ip

**Comment by eicky** [comment]
只能通过重装来变更

**Comment by Jrohy** [comment]
应该读的缓存, 只要v2ray的配置文件修改时间不变，就不会重新读配置文件和获取本机ip

**Comment by eicky** [comment]
> 应该读的缓存, 只要v2ray的配置文件修改时间不变，就不会重新读配置文件和获取本机ip

能不能改一下，希望在查看配置时动态获取一次ip

**Comment by Jrohy** [comment]
主要比较少几率换ip，每次都重新读影响速度的。

**Comment by eicky** [comment]
> 主要比较少几率换ip，每次都重新读影响速度的。

那可否在服务管理里面增加一个选项，刷新ip呢？

**Comment by Jrohy** [comment]
你可以增加个用户修改了配置文件就好

**Comment by eicky** [comment]
> 你可以增加个用户修改了配置文件就好

好的，感谢大佬
