### ISSUE TITLE
修改传输模式时报错

### ISSUE THREAD

**Issue by HNACROBEN** [Jrohy/multi-v2ray#32]
大佬，修改MTProto和Shadowsocks 都会报错，小白一枚，谢谢指导

请输入要改传输方式的节点Group字母:c
当前组的传输方式为：kcp dtls

1.普通TCP
2.HTTP伪装
3.WebSocket流量
4.普通mKCP
5.mKCP + srtp
6.mKCP + utp
7.mKCP + wechat-video
8.mKCP + dtls
9.mKCP + wireguard
10.HTTP/2
11.Socks5
12.MTProto
13.Shadowsocks
12
传输模式修改成功！

欢迎使用 multi-v2ray 管理程序

1.服务管理           2.用户管理

3.更改配置           4.查看配置

5.其他功能           6.更新V2Ray

7.生成客户端配置文件

请输入数字选择功能(按回车键退出): 4

Traceback (most recent call last):
  File "/usr/local/multi-v2ray/server_info.py", line 3, in <module>
    import read_json
  File "/usr/local/multi-v2ray/read_json.py", line 165, in <module>
    read_sin_user(detour_list, multiUserConf, index_dict)
  File "/usr/local/multi-v2ray/read_json.py", line 113, in read_sin_user
    sinUserConf['tcpFastOpen']=conf_stream_tfo
UnboundLocalError: local variable 'conf_stream_tfo' referenced before assignment

**Comment by HNACROBEN** [comment]
想关掉tfo 也报错

1.更改email

2.更改UUID

3.更改alterID

4.更改主端口

5.更改传输方式

6.更改TLS设置

7.更改tcpFastOpen设置

8.更改广告拦截功能

9.更改动态端口

10.更改Shadowsocks加密方式

11.更改Shadowsocks密码


请输入数字选择功能： 7


Traceback (most recent call last):
  File "/usr/local/multi-v2ray/config_modify/tfo.py", line 3, in <module>
    import read_json
  File "/usr/local/multi-v2ray/read_json.py", line 165, in <module>
    read_sin_user(detour_list, multiUserConf, index_dict)
  File "/usr/local/multi-v2ray/read_json.py", line 113, in read_sin_user
    sinUserConf['tcpFastOpen']=conf_stream_tfo
UnboundLocalError: local variable 'conf_stream_tfo' referenced before assignment

**Comment by Jrohy** [comment]
等下

**Comment by Jrohy** [comment]
更新下源码
```source <(curl -sL https://git.io/fNgqx) -c```

**Comment by HNACROBEN** [comment]
收到，谢谢，已解决！

**Comment by HNACROBEN** [comment]
大佬，查看SS配置 时候还有报错

IP：1**.1**.9*.***
Port：2282
Method: aes-256-gcm
Password: UMowjah592XTu1OB
Traceback (most recent call last):
  File "/usr/local/multi-v2ray/server_info.py", line 61, in <module>
    if sin_user_conf["tcpFastOpen"] != None:
KeyError: 'tcpFastOpen'

**Comment by Jrohy** [comment]
谢谢反馈，我看下

**Comment by Jrohy** [comment]
已修复，更新下

**Comment by Jrohy** [comment]
针对单台的部署没必要做订阅链接，订阅链接也是很简单，base64 vmess组合一起在base64转码一次

**Comment by taipei007** [comment]
我是想问可以实现动态订阅么？就是自动获取改变的链接，然后打包转码，对多端口不同用户实现不同的订阅链接

**Comment by Jrohy** [comment]
受众较小不会做, 不通用的东西会导致复杂
