### ISSUE TITLE
部署以后无法使用

### ISSUE THREAD

**Issue by wanghaisheng** [Jrohy/multi-v2ray#320]
开了一个用户 有人帮我测试一哈嘛
2.
Group: A
IP: 158.101.158.161
Port: 29246
TLS: 关闭
Email: techempower@163.com
UUID: 7dff0088-6a6c-11ea-930c-02001700d331
Alter ID: 32
Network: kcp srtp

vmess://eyJwcyI6ICIiLCAicG9ydCI6IDI5MjQ2LCAidiI6ICIyIiwgIm5ldCI6ICJrY3AiLCAiaG9zdCI6ICIiLCAicGF0aCI6ICIiLCAiaWQiOiAiN2RmZjAwODgtNmE2Yy0xMWVhLTkzMGMtMDIwMDE3MDBkMzMxIiwgInR5cGUiOiAic3J0cCIsICJ0bHMiOiAibm9uZSIsICJhaWQiOiAzMiwgImFkZCI6ICIxNTguMTAxLjE1OC4xNjEifQ==

**Comment by Jrohy** [comment]
kcp封锁现在可能比较严，可以试下换其他协议，比如ws + tls

**Comment by wanghaisheng** [comment]
tls我始终设置不成功 无法使用clouflare自己证书
