### ISSUE TITLE
v2ray 更新问题

### ISSUE THREAD

**Issue by tony27786** [Jrohy/multi-v2ray#322]
大佬您好，我在更新 v2ray 二进制文件时出现以下错误提示

root@xeon-hmm:~# v2ray update
Installing V2Ray vhttps://api.github.com/repos/v2ray/v2ray-core/releases/22545481 on x86_64
Downloading V2Ray: https://github.com/v2ray/v2ray-core/releases/download/vhttps://api.github.com/repos/v2ray/v2ray-core/releases/22545481/v2ray-linux-64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     25      0 --:--:-- --:--:-- --:--:--    25
awk: not an option: -e
[/tmp/v2ray/v2ray.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/v2ray/v2ray.zip or
        /tmp/v2ray/v2ray.zip.zip, and cannot find /tmp/v2ray/v2ray.zip.ZIP, period.
Shutting down V2Ray service.
Archive:  /tmp/v2ray/v2ray.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/v2ray/v2ray.zip or
        /tmp/v2ray/v2ray.zip.zip, and cannot find /tmp/v2ray/v2ray.zip.ZIP, period.
Failed to copy V2Ray binary and resources.

请问怎么解决

**Comment by Jrohy** [comment]
你可以直接运行官方脚本试下更新`bash <(curl -L -s https://install.direct/go.sh)`

**Comment by tony27786** [comment]
官方脚本没问题，谢谢大佬
