### ISSUE TITLE
Docker V2Ray 端口 nc會 failed: Connection refused

### ISSUE THREAD

**Issue by vlpeng** [Jrohy/multi-v2ray#326]
端口起不來，不知道為何？
以下為配置：

nc -v 34.94.237.180 45459
nc: connectx to 34.94.237.180 port 45459 (tcp) failed: Connection refused

nc -v 34.94.237.180 64516
nc: connectx to 34.94.237.180 port 64516 (tcp) failed: Connection refused

运行状态
请选择: 4
v2ray running..

1.
Group: A
IP: 34.94.237.180
Port: 45459
TLS: 关闭
UUID: 4f0d0d1b-7346-11ea-acb3-42010aa80021
Alter ID: 16
Network: kcp srtp
vmess://eyJ2IjogIjIiLCAicHMiOiAiIiwgImFkZCI6ICIzNC45NC4yMzcuMTgwIiwgInBvcnQiOiA0NTQ1OSwgImFpZCI6IDE2LCAidHlwZSI6ICJ
zcnRwIiwgIm5ldCI6ICJrY3AiLCAicGF0aCI6ICIiLCAiaG9zdCI6ICIiLCAiaWQiOiAiNGYwZDBkMWItNzM0Ni0xMWVhLWFjYjMtNDIwMTBhYTgwMD
IxIiwgInRscyI6ICJub25lIn0=

3.
Group: B
IP: 34.94.237.180
Port: 64516
TLS: 关闭
UUID: 7fb80962-7347-11ea-96fc-42010aa80021
Alter ID: 16
Network: kcp wechat-video

vmess://eyJ2IjogIjIiLCAicHMiOiAiIiwgImFkZCI6ICIzNC45NC4yMzcuMTgwIiwgInBvcnQiOiA2NDUxNiwgImFpZCI6IDE2LCAidHlwZSI6ICJ3ZWNoYXQtdmlkZW8iLCAibmV0IjogImtjcCIsICJwYXRoIjogIiIsICJob3N0IjogIiIsICJpZCI6ICI3ZmI4MDk2Mi03MzQ3LTExZWEtOTZmYy00MjAxMGFhODAwMjEiLCAidGxzIjogIm5vbmUifQ==

**Comment by vlpeng** [comment]
我安全組的端口，TCP / UDP都全部打開的

**Comment by Jrohy** [comment]
kcp好像是udp的, nc 能测udp不

**Comment by Jrohy** [comment]
nc udp要加个-u

**Comment by vlpeng** [comment]
UDP可以，但是 這兩個 vmess我匯進去 V2RayU，都是空值 

nc -zu 34.94.237.180 45459
Connection to 34.94.237.180 port 45459 [udp/*] succeeded!

nc -zu 34.94.237.180 64516
Connection to 34.94.237.180 port 64516 [udp/*] succeeded!

**Comment by vlpeng** [comment]
我掃全部 UDP端口，都是有開啟的，但是 V2Ray不知道為何，跑不起來

**Comment by Jrohy** [comment]
是不能用，还是指v2ray没启动成功

**Comment by Jrohy** [comment]
如果不能用可以不同网络环境试下，再不行可以换换协议，可能kcp封锁比较严

**Comment by vlpeng** [comment]
啟動成功的，
欢迎使用 v2ray-util 管理程序

1.服务管理              2.用户管理

3.更改配置              4.查看配置

5.全局功能              6.更新V2Ray

7.生成客户端配置文件         

请选择: 1

1.启动服务
2.停止服务
3.重启服务
4.运行状态
5.运行日志

请选择: 4
v2ray running..

可能kcp封锁比较严 -> 我沒在墻內 .... 我在墻外，連谷歌云LA 主機

**Comment by Jrohy** [comment]
v2rayU没试过，可以试下其他平台的客户端试试

**Comment by vlpeng** [comment]
更改传输方式，換成 WebSocket之後可以，我再多試試，謝謝您 XD

**Comment by vlpeng** [comment]
這個 專案同Trojan一樣精彩，非常完美
