### ISSUE TITLE
After enabling cdn v2ray doesnt connet

### ISSUE THREAD

**Issue by hugochavezzz** [Jrohy/multi-v2ray#327]
I have new vps ubuntu 18.04
Apdated upgraded
Installed multi-v2ray successfully
Changed protocol to websocket
Enabled cdn to my domain name to port 443
Before all of this i connected cloudflare to domain name provider, all is correct, dns A record domain name dns only
Then i enabled tls to domain name
Everything is good worked. But when i enable cloudflare dns settings to proxied v2ray cant connecr

**Comment by Jrohy** [comment]
try to change other port? u can switch it by use command `v2ray cdn`

**Comment by hugochavezzz** [comment]
I tried all available ports there, none of them working with cdn proxy

> try to change other port? u can switch it by use command `v2ray cdn`

I tried all available ports there, none of them working with cdn proxy
