### ISSUE TITLE
自动生成证书失败

### ISSUE THREAD

**Issue by TItanXXY** [Jrohy/multi-v2ray#329]
想请教一下大佬，安装完脚本之后，v2ray cdn + ip，生成证书的时候失败，报错：
创建新订单错误。找不到Le_OrderFinalize。{ 
“ type”：“ urn：ietf：params：acme：error：rejectedIdentifier”，
“ detail”：“创建新订单时出错::无法为\ xxxxxx颁发”：ACME服务器无法为IP地址颁发证书“ ，
“状态”：400

请添加'--debug'或'--log'以查看更多详细信息。
[UTC 2020年4月4日星期六18:06:14]参见：https : //github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh

这个问题应该怎么解决呢

**Comment by Jrohy** [comment]
域名有没有绑定ip呢
