### ISSUE TITLE
修改WS+TLS和H2+TLS兼失败

### ISSUE THREAD

**Issue by darktitty** [Jrohy/multi-v2ray#33]
尝试多次，443，非443，都无用，到底出了什么问题？

**Comment by darktitty** [comment]
发现没有开启TLS没问题 开启TLS就不行啦

**Comment by Jrohy** [comment]
报错信息发下，怎样失败要说清楚

**Comment by Jrohy** [comment]
证书判断确实出现问题, 过期的证书会照样用,导致tls失败

**Comment by Jrohy** [comment]
你可以先清理原来的证书，再开启tls，在~/.acme.sh/域名目录

**Comment by darktitty** [comment]
更新源码以后可以啦~也没有去目录下删除. 更新以后重新开启一下就可以啦 谢谢~

**Comment by darktitty** [comment]
晕~好神奇. 我公司电脑就没问题, 家里就不行. 但是我公司打开以后, 家里同时也打开就可以. 公司关闭, 家里单独打开就不行. 这什么情况.... 另外一个自己搭建的就没问题~

**Comment by darktitty** [comment]
2018/09/17 11:08:20 [Warning] failed to handler mux client connection > Proxy|VMess|Outbound: failed to find an available destination > Retry: [Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://www.dartitte.tk/SHRLsYOc/):  > read tcp 192.168.1.115:11349->207.246.108.28:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://www.dartitte.tk/SHRLsYOc/):  > read tcp 192.168.1.115:11354->207.246.108.28:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://www.dartitte.tk/SHRLsYOc/):  > read tcp 192.168.1.115:11355->207.246.108.28:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://www.dartitte.tk/SHRLsYOc/):  > read tcp 192.168.1.115:11359->207.246.108.28:443: i/o timeout Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://www.dartitte.tk/SHRLsYOc/):  > read tcp 192.168.1.115:11364->207.246.108.28:443: i/o timeout] > Retry: all retry attempts failed

**Comment by Jrohy** [comment]
能不能说详细点

**Comment by darktitty** [comment]
现在公司开着也不行了...一直上不了啦 不知道为啥

**Comment by darktitty** [comment]
还是TLS的问题, 一关立刻可以啦

**Comment by Jrohy** [comment]
开启tls时的过程给个报文, acme那块的

**Comment by Jrohy** [comment]
用的是letsencrypt 还是自己的证书呢

**Comment by darktitty** [comment]
lets encrypt 自动生成的. 是不是我应该把旧的删除重新生成一下?

**Comment by Jrohy** [comment]
旧的可能过期，要看报文所expired date

**Comment by darktitty** [comment]
正在获取SSL证书，请稍等。。。
[Mon Sep 17 04:15:14 UTC 2018] Domains not changed.
[Mon Sep 17 04:15:14 UTC 2018] Skip, Next renewal time is: Thu Nov 15 14:12:09 UTC 2018
[Mon Sep 17 04:15:14 UTC 2018] Add '--force' to force to renew.

操作完成！

**Comment by darktitty** [comment]
https://github.com/233boy/v2ray    我另外一个搭建的这个, 没有问题

**Comment by Jrohy** [comment]
vmess://eyJhZGQiOiAid3d3Lnh4b294Lm1sIiwgIm5ldCI6ICJ3cyIsICJhaWQiOiA2NCwgInR5cGUiOiAiIiwgInYiOiAiMiIsICJpZCI6ICJiOTY1MmIwNS1mM2NhLTQ2ZDItOGFmZC02MDVmNjQ4OGQ0YTUiLCAicGF0aCI6ICIvbmU1b3N0dkIvIiwgInRscyI6ICJ0bHMiLCAicHMiOiAiIiwgImhvc3QiOiAid3d3LnYycmF5LmNvbSIsICJwb3J0IjogNTk1MzV9

**Comment by Jrohy** [comment]
你试下能不能用，随便搭了个ws+tls

**Comment by Jrohy** [comment]
![image](https://user-images.githubusercontent.com/12463263/45606153-449ed500-ba75-11e8-85b6-0253bf8be1a0.png)
你是用生成的配置文件还是vmess字符串导入呢，不确保生成的配置文件的正确性

**Comment by Jrohy** [comment]
其实你可以一步一步来，先搭个kcp+tls的，测试没问题，就证明证书没问题，再切换到ws+tls或者h2+tls

**Comment by darktitty** [comment]
好的. 谢谢. 我晚上回去好好测试一下试试

**Comment by darktitty** [comment]
最后问个问题: 端口是使用443好还是非443好? 安全性而言

**Comment by Jrohy** [comment]
动态端口可以自己开来测试下对速度影响大不大，反正可以随时开关.
443还是非443，给不了太多意见，我基本都是mkcp，也很少封ip

**Comment by darktitty** [comment]
好奇怪. KCP+TLS 没问题 换成WS就不行了

**Comment by darktitty** [comment]
WS只有关闭TLS才可以

**Comment by Jrohy** [comment]
那就不清楚了，不知会不会墙的识别问题
可以这台不行的试试233的脚本，测试下

**Comment by darktitty** [comment]
嗯, 我去试试. 很奇怪的是我在公司好像就可以. 不会是因为网络运营商不同, 或者我是用无线网卡的原因吧

**Comment by xlsdg** [comment]
刚试了下 WebSocket+TLS+Nginx+CloudFlare 终于可以了，服务端配置文件需要手工改一下："inbound" 下添加 "listen":"127.0.0.1" 。

**Comment by darktitty** [comment]
> 刚试了下 WebSocket+TLS+Nginx+CloudFlare 终于可以了，服务端配置文件需要手工改一下："inbound" 下添加 "listen":"127.0.0.1" 。

自己手动装了Nginx?

**Comment by xlsdg** [comment]
我是服务器 Debian9(64bit)+宝塔Linux面板安装的。

**Comment by xlsdg** [comment]
Nginx 配 Https 证书就行，服务端不用打开 TLS。

**Comment by darktitty** [comment]
这些都不会...只会一键...我慢慢研究下吧
