### ISSUE TITLE
在vps上ping出的地址是127.0.0.1，但不能开启TLS

### ISSUE THREAD

**Issue by LeeQin123** [Jrohy/multi-v2ray#332]
我的域名在vps上ping出的地址是127.0.0.1，但是却不能开启TLS，提示domain can't analysis to local ip!!!

**Comment by Jrohy** [comment]
ping出来得是实际vps ip，不能是127.0.0.1的

**Comment by LeeQin123** [comment]
> ping出来得是实际vps ip，不能是127.0.0.1的

明白了，非常感谢！
