### ISSUE TITLE
cdn代理流量 v2ray不能重启

### ISSUE THREAD

**Issue by crosspacific** [Jrohy/multi-v2ray#333]
运行v2ray add建多个端口, 然后v2ray cdn再切换为cdn， 同时代理多个端口的cdn流量，安装时v2ray不能自动重启。安装结束后，也不能手动启动服务.

**Comment by Jrohy** [comment]
v2ray status看下状态

**Comment by Jrohy** [comment]
重启过程中有报错么

**Comment by crosspacific** [comment]
这是状态
 v2ray.service - V2Ray - A unified platform for anti-censorship
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: en
   Active: **failed** (Result: exit-code) since Wed 2020-04-08 00:21:07 UTC; 33s ago
     Docs: https://v2ray.com
           https://guide.v2fly.org
  Process: 14770 ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json (
 Main PID: 14770 (code=exited, status=23)

Apr 08 00:21:07 debian2 systemd[1]: Started V2Ray - A unified platform for anti-
Apr 08 00:21:07 debian2 v2ray[14770]: V2Ray 4.23.1 (V2Fly, a community-driven ed
Apr 08 00:21:07 debian2 v2ray[14770]: A unified platform for anti-censorship.
Apr 08 00:21:07 debian2 v2ray[14770]: main: failed to read config files: [/etc/v
Apr 08 00:21:07 debian2 v2ray[14770]: v2ctl> Read config:  /etc/v2ray/config.jso
Apr 08 00:21:07 debian2 v2ray[14770]: v2ray.com/core/infra/conf: Failed to build
Apr 08 00:21:07 debian2 systemd[1]: v2ray.service: Main process exited, code=exi
Apr 08 00:21:07 debian2 systemd[1]: v2ray.service: Unit entered failed state.
Apr 08 00:21:07 debian2 systemd[1]: v2ray.service: Failed with result 'exit-code
lines 1-17/17 (END)...skipping...
● v2ray.service - V2Ray - A unified platform for anti-censorship
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
   Active: **failed** (Result: exit-code) since Wed 2020-04-08 00:21:07 UTC; 33s ago
     Docs: https://v2ray.com
           https://guide.v2fly.org
  Process: 14770 ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json (**code=exited, status=23**)
 Main PID: 14770 (code=exited, status=23)
Apr 08 00:21:07 debian2 systemd[1]: Started V2Ray - A unified platform for anti-censorship.
Apr 08 00:21:07 debian2 v2ray[14770]: V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/amd64)
Apr 08 00:21:07 debian2 v2ray[14770]: A unified platform for anti-censorship.
Apr 08 00:21:07 debian2 v2ray[14770]: main: failed to read config files: [/etc/v2ray/config.json] > v2ray.com/core/main/json: failed to
Apr 08 00:21:07 debian2 v2ray[14770]: v2ctl> Read config:  /etc/v2ray/config.json
Apr 08 00:21:07 debian2 v2ray[14770]: v2ray.com/core/infra/conf: Failed to build TLS config. > v2ray.com/core/infra/conf: failed to par
Apr 08 00:21:07 debian2 systemd[1]: v2ray.service: Main process exited, code=exited, status=23/n/a
Apr 08 00:21:07 debian2 systemd[1]: v2ray.service: Unit entered failed state.
Apr 08 00:21:07 debian2 systemd[1]: v2ray.service: Failed with result 'exit-code'.

重启只提示
v2ray restart fail !

**Comment by Jrohy** [comment]
是不是手动指定证书路径的

**Comment by lingan1996** [comment]
@Jrohy 我也遇到同样的问题，重启失败，不是手动指定的证书路径

**Comment by gboys90** [comment]
是不是装了宝塔面板  我的也无法启动
