### ISSUE TITLE
使用ws协议的时候，速度太慢了。

### ISSUE THREAD

**Issue by jayvee902** [Jrohy/multi-v2ray#334]
使用ws协议的时候，速度太慢了。使用v2ray原版不慢啊。

**Comment by Jrohy** [comment]
项目只是方便改json, 你可以自己改也行的

**Comment by jayvee902** [comment]
> 项目只是方便改json, 没有说有没有用到原版v2ray, 你也可以自己改json

如果仅仅方便改json，那也太浪费multi-v2ray了 。
