### ISSUE TITLE
安装出错

### ISSUE THREAD

**Issue by yuzhia** [Jrohy/multi-v2ray#337]
Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 5, in <module>
    from v2ray_util.main import menu
  File "/usr/local/python3/lib/python3.8/site-packages/v2ray_util/__init__.py", line 3, in <module>
    from .util_core.trans import _
  File "/usr/local/python3/lib/python3.8/site-packages/v2ray_util/util_core/__init__.py", line 1, in <module>
    from .trans import _
  File "/usr/local/python3/lib/python3.8/site-packages/v2ray_util/util_core/trans.py", line 10, in <module>
    lang = Config().get_data('lang')
  File "/usr/local/python3/lib/python3.8/site-packages/v2ray_util/util_core/config.py", line 16, in __init__
    self.config.read(self.config_path)
  File "/usr/local/python3/lib/python3.8/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/local/python3/lib/python3.8/configparser.py", line 1082, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/etc/v2ray_util/util.cfg', line: 1
'<HTML>\n'

这是不支持python3.8吗

**Comment by nistudyc** [comment]
我安装也是出错了。。。。。

**Comment by Jrohy** [comment]
用的什么系统呢，python3.8是自己安装的吗

**Comment by jipiyan** [comment]
> 用的什么系统呢，python3.8是自己安装的吗

纯净debian 8和9都出错了。。。

**Comment by yuzhia** [comment]
> 3

python自己安装的   这个v2都安装成功了 就是报这个错 启动不了

**Comment by Jrohy** [comment]
晚上回去我测试下

**Comment by nistudyc** [comment]
> 用的什么系统呢，python3.8是自己安装的吗

纯净版centos8，没有自己安装python3.8.

**Comment by jipiyan** [comment]
好像闪过去
`
curl $BASH_COMPLETION_SHELL > /usr/share/bash-completion/completions/v2ray
[[ -z $(echo $SHELL|grep zsh) ]] && source /usr/share/bash-completion/completions/v2ray
`
这里bash-completion有错误

**Comment by jipiyan** [comment]
> 用的什么系统呢，python3.8是自己安装的吗

我把v2ray.sh中第22行
`BASE_SOURCE_PATH="https://multi.netlify.com"`
改为
`BASE_SOURCE_PATH="https://multi.netlify.app"`
安装就正确了，谢谢大大的脚本

**Comment by sjkhsl** [comment]
我也出现错误了！你解决了吗？

**Comment by nistudyc** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 5, in <module>
    from v2ray_util.main import menu
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/__init__.py", line 3, in <module>
    from .util_core.trans import _
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/__init__.py", line 1, in <module>
    from .trans import _
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/trans.py", line 10, in <module>
    lang = Config().get_data('lang')
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/config.py", line 16, in __init__
    self.config.read(self.config_path)
  File "/usr/lib64/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib64/python3.6/configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/etc/v2ray_util/util.cfg', line: 1
'<HTML>\n'
please input 'v2ray' command to manage v2ray

我这边出现的代码是这个

**Comment by 839891627** [comment]
+1 一样的问题哦

**Comment by jipiyan** [comment]
> Traceback (most recent call last):
> File "/usr/local/bin/v2ray", line 5, in
> from v2ray_util.main import menu
> File "/usr/local/lib/python3.6/site-packages/v2ray_util/**init**.py", line 3, in
> from .util_core.trans import _
> File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/**init**.py", line 1, in
> from .trans import _
> File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/trans.py", line 10, in
> lang = Config().get_data('lang')
> File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/config.py", line 16, in **init**
> self.config.read(self.config_path)
> File "/usr/lib64/python3.6/configparser.py", line 697, in read
> self._read(fp, filename)
> File "/usr/lib64/python3.6/configparser.py", line 1080, in _read
> raise MissingSectionHeaderError(fpname, lineno, line)
> configparser.MissingSectionHeaderError: File contains no section headers.
> file: '/etc/v2ray_util/util.cfg', line: 1
> '\n'
> please input 'v2ray' command to manage v2ray
> 
> 我这边出现的代码是这个

你把v2ray.sh脚本下载到服务器上，然后把脚本第24行
`BASE_SOURCE_PATH="https://multi.netlify.com"`
改为
`BASE_SOURCE_PATH="https://multi.netlify.app"`
再运行
`
source v2ray.sh
`
应该就可以了

**Comment by nistudyc** [comment]
我试一下

**Comment by jipiyan** [comment]
> 我试一下

试之前先运行一下
`
source v2ray.sh --remove
`

**Comment by nistudyc** [comment]
> > 我试一下
> 
> 试之前先运行一下
> `source v2ray.sh --remove`
> 主要是/etc/v2ray_util/v2ray这个文件脚本不会自动更新

好的！

**Comment by Ros-ua** [comment]
source <(curl -sL https://multi.netlify.com/v2ray.sh)
same mistake

**Comment by Jrohy** [comment]
应该是netlify.com不给用.com域名了，只能用.app,  我修改下下载链接

**Comment by Jrohy** [comment]
已提交新版变更了下载链接

**Comment by nistudyc** [comment]
> > Traceback (most recent call last):
> > File "/usr/local/bin/v2ray", line 5, in
> > from v2ray_util.main import menu
> > File "/usr/local/lib/python3.6/site-packages/v2ray_util/**init**.py", line 3, in
> > from .util_core.trans import _
> > File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/**init**.py", line 1, in
> > from .trans import _
> > File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/trans.py", line 10, in
> > lang = Config().get_data('lang')
> > File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/config.py", line 16, in **init**
> > self.config.read(self.config_path)
> > File "/usr/lib64/python3.6/configparser.py", line 697, in read
> > self._read(fp, filename)
> > File "/usr/lib64/python3.6/configparser.py", line 1080, in _read
> > raise MissingSectionHeaderError(fpname, lineno, line)
> > configparser.MissingSectionHeaderError: File contains no section headers.
> > file: '/etc/v2ray_util/util.cfg', line: 1
> > '\n'
> > please input 'v2ray' command to manage v2ray
> > 我这边出现的代码是这个
> 
> 你把v2ray.sh脚本下载到服务器上，然后把脚本第24行
> `BASE_SOURCE_PATH="https://multi.netlify.com"`
> 改为
> `BASE_SOURCE_PATH="https://multi.netlify.app"`
> 再运行
> `source v2ray.sh`
> 我改了以后是成功安装的



> 应该是netlify.com不给用.com域名了，只能用.app, 我修改下下载链接

改为.app之后已经可以正常安装了，感谢！

**Comment by Ros-ua** [comment]
source <(curl -sL https://multi.netlify.app/v2ray.sh)
working
case solved
Thank you
