### ISSUE TITLE
建议加入监听本地HTTP和SOCKS的inbound设置

### ISSUE THREAD

**Issue by steven756284184** [Jrohy/multi-v2ray#338]
如题

**Comment by Jrohy** [comment]
可以自己改下json来加，先备份

**Comment by steven756284184** [comment]
改了之后数据统计功能会报错，目测是`v2ray_util/util_core/profile.py`的`Profile.parse_group()`方法在139-151行的位置对于http协议没有判断，导致153行引用`clients`变量时报错`UnboundLocalError: local variable 'clients' referenced before assignment`. 希望提供的信息准确……
