### ISSUE TITLE
MTPROTO问题

### ISSUE THREAD

**Issue by darktitty** [Jrohy/multi-v2ray#34]
MTPROTO: PC端TG没问题, 手机端TG不行.     换成SOCKS5, PC和手机就都可以

**Comment by Jrohy** [comment]
确实，我测试下

**Comment by darktitty** [comment]
好的. 等你好消息

**Comment by Jrohy** [comment]
测试了好久，确实v2ray搭建的mtproto都手机端都上不去了，只有desktop客户端能上， 估计墙升级，用原生方式搭建的mtproto还是能用

**Comment by Jrohy** [comment]
测试网络广东联通，不知其他地方的运营商如何

**Comment by darktitty** [comment]
那就乖乖的用Socks5好啦

**Comment by taipei007** [comment]
可以用的，是tgx不行，原版能用！

**Comment by taipei007** [comment]
希望大佬更新一个新功能，就是一键更改所有端口的配置！目前有一个端口下不同uuid的更改！但是没有不同端口下一键更改所有配置的功能，这个功能就不算鸡肋了，大佬！

**Comment by Jrohy** [comment]
一键更改成相同配置?

**Comment by Jrohy** [comment]
@darktitty @taipei007 确实tgx不行mtproto, 原版就ok

**Comment by Jrohy** [comment]
尝试新的模式改一个端口就行，没必要全部都改

**Comment by Jrohy** [comment]
要追求不同端口一样配置的话，这个需求比较少，可以自己fork来改
