### ISSUE TITLE
关于这个脚本的功能想请教一下

### ISSUE THREAD

**Issue by gin063** [Jrohy/multi-v2ray#343]
本人是小白。
①我有安装了233的一键脚本，是不是需要再安装这个才能多设备同时连接啊？
②我目前在使用的时候，比如说路由器在使用，但是用4g网小火箭有时候连不上，把二维码分享给朋友，朋友表示能ping通但就是不能上网。
③我有尝试过在config.json文件里面新增端口和uuid，多设备能ping通但连接不稳定，有时候连得上有时候不行，是否和运营商有关系？我以前用ssr没出现这种问题，脚本都是默认的不限用户数，我和朋友用同一个账号密码没问题。
还请大神解惑，感激不尽。

**Comment by Jrohy** [comment]
和别的脚本一起使用可能有冲突，最好独立使用，网络环境会影响fq效果的

**Comment by gin063** [comment]
> 和别的脚本一起使用可能有冲突，最好独立使用，网络环境会影响fq效果的

好的，谢谢大神。那我卸载233的脚本只安装这个试试。
