### ISSUE TITLE
连接大约10个小时后就不能连接了

### ISSUE THREAD

**Issue by cws999** [Jrohy/multi-v2ray#345]
不知道哪里出问题了，似乎被墙发现了

**Comment by Jrohy** [comment]
可以试试换换协议

**Comment by cws999** [comment]
> 可以试试换换协议
换了几种协议，还是不行

**Comment by han963xiao** [comment]
我也遇到了这个问题，每次10个小时左右就不能使用了，每次需要重新再开一个新的协议

**Comment by Li6lac** [comment]
> 可以试试换换协议

换成TCP就好了，但是IP会被封了。报错谷歌是时间不同步，但是我手动设置了，仍然没解决。

**Comment by Li6lac** [comment]
> 可以试试换换协议

貌似是移动网的原因，很奇怪

**Comment by Li6lac** [comment]
我感觉我的都没有10小时。每天换一两次吧

**Comment by abelyuan00** [comment]
同样问题，但是ping了发现不是被墙，请问解决了吗

**Comment by Li6lac** [comment]
> 同样问题，但是ping了发现不是被墙，请问解决了吗

我更换了更复杂的隐藏方式。你如果自己有一个域名的话，可参考https://github.com/wulabing/V2Ray_ws-tls_bash_onekey。

**Comment by yunyexiansheng** [comment]
好奇怪，感觉墙升级了，以前用 kcp 随便一个协议用好几个月没事，最近端口被封锁了，然后换成 kcp + wech 后 ip 被封锁了...GCP 的
