### ISSUE TITLE
一会儿就报这个错误，百度说是时间问题？但是一开始可以用啊？具体怎么解决呢。谢谢

### ISSUE THREAD

**Issue by Li6lac** [Jrohy/multi-v2ray#347]
connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF

**Comment by Jrohy** [comment]
如果一开始能用，可能是kcp不太稳，可以换下其他协议

**Comment by Li6lac** [comment]
好的






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jrohy"<notifications@github.com&gt;; 
发送时间: 2020年5月9日(星期六) 下午5:00
收件人: "Jrohy/multi-v2ray"<multi-v2ray@noreply.github.com&gt;; 
抄送: "西电李凯"<781592119@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Jrohy/multi-v2ray] 一会儿就报这个错误，百度说是时间问题？但是一开始可以用啊？具体怎么解决呢。谢谢 (#347)





 
如果一开始能用，可能是kcp不太稳，可以换下其他协议
