### ISSUE TITLE
安装错误 pip no install!

### ISSUE THREAD

**Issue by wyap-echo** [Jrohy/multi-v2ray#349]
WARNING: The scripts pip, pip3 and pip3.6 are installed in '/usr/local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-20.1
 Time Synchronizing.. 
17 May 09:42:26 ntpdate[1169]: adjust time server 218.161.118.185 offset 0.023377 sec
 Time Sync Success 
 now: Sun, 17 May 2020 09:42:26 +0000
pip no install!

**Comment by Jrohy** [comment]
试下安装pip, python3 <(curl -sL https://bootstrap.pypa.io/get-pip.py)

**Comment by wyap-echo** [comment]
哇 老哥 还是出错还是同样的错误

**Comment by Jrohy** [comment]
什么系统呢

**Comment by wyap-echo** [comment]
Centos 7 是系统不支持吗 防火墙我也关闭了

**Comment by Jrohy** [comment]
支持的，看下pip或者pip3命令有没有

**Comment by wyap-echo** [comment]
没有 提示找不到命令

**Comment by Jrohy** [comment]
看下怎么安装pip了

**Comment by wyap-echo** [comment]
好了 老哥 安装好了 但是又提示这个错误 手动输入后还是提示错误
V2Ray v4.23.1 is installed.
-bash: v2ray: command not found

multi-v2ray install success!
-bash: v2ray: command not found
please input 'v2ray' command to manage v2ray

**Comment by Jrohy** [comment]
安装了是有v2ray-util的，自己建个可以的链接为v2ray

**Comment by Jrohy** [comment]
ln -s $(which v2ray-util) /usr/local/bin/v2ray

**Comment by wyap-echo** [comment]
谢谢 老哥 下午搞定了 ，还有一个疑问 就是使用这个测速软件导入v2ray 链接无法测试是后台禁止了吗？https://github.com/tindy2013/stairspeedtest-reborn

**Comment by Jrohy** [comment]
应该没有的

**Comment by wyap-echo** [comment]
好的谢谢
