### ISSUE TITLE
多用户（uuid）和多端口到底有什么用？

### ISSUE THREAD

**Issue by Li6lac** [Jrohy/multi-v2ray#350]
不理解v2ray的多用户是什么意思？
不是可以一个端口多个设备用吗？

**Comment by Jrohy** [comment]
可以多个端口，或者同一个端口建立多个用户

**Comment by Li6lac** [comment]
> 可以多个端口，或者同一个端口建立多个用户

好的，谢谢你，明白了。就是我这里一直碰到EOF的问题。我发现是可能是KCP协议的问题，但是换了TCP容易被封。此外，是不是换成websockets+tls+域名，伪装，速度会变慢。

**Comment by Jrohy** [comment]
要自己测试下了，也和线路比较大关系

**Comment by Li6lac** [comment]
> 要自己测试下了，也和线路比较大关系

好的，谢谢你
