### ISSUE TITLE
pip no install!

### ISSUE THREAD

**Issue by Ros-ua** [Jrohy/multi-v2ray#354]
Updated:
  epel-release.noarch 0:7-12                                                                                                                                           

Complete!
Loaded plugins: fastestmirror
ius-release.rpm                                                                                                                                 |  137 B  00:00:00     
Cannot open: https://centos7.iuscommunity.org/ius-release.rpm. Skipping.
Error: Nothing to do
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.vodien.com
 * epel: mirrors.aliyun.com
 * extras: mirror.vodien.com
 * updates: mirror.vodien.com
No package python36u available.
Error: Nothing to do
ln: failed to create symbolic link ‘/bin/python3’: File exists
/dev/fd/63: line 180: python3: command not found
 Time Synchronizing.. 
200 OK
 Time Sync Success 
 now: Thu, 21 May 2020 07:50:31 +0000
pip no install!
Connection closing...Socket close.

**Comment by Jrohy** [comment]
python3 命令没有，看下怎么安装

**Comment by Ros-ua** [comment]
IUS has always maintained links that get users the latest release of the ius-release package. Currently those links are served by our CDN.

https://repo.ius.io/ius-release-el6.rpm
https://repo.ius.io/ius-release-el7.rpm
Before we started using the ius.io domain, we pointed users to different URLs.

https://rhel6.iuscommunity.org/ius-release.rpm
https://rhel7.iuscommunity.org/ius-release.rpm
https://centos6.iuscommunity.org/ius-release.rpm
https://centos7.iuscommunity.org/ius-release.rpm
The server handling the *.iuscommunity.org redirects will be decommissioned on 2020-06-01. The website has pointed users to the new URLs for some time now. Please update any automation, scripts, or notes that is still reference the old URLs.


maybe need change link

**Comment by Jrohy** [comment]
centos7 os?

**Comment by Ros-ua** [comment]
yes, centos 7

**Comment by Ros-ua** [comment]
https://python3.netlify.app/install.sh
maybe here need to change this part:
#online install python3
webInstall(){
    if [[ ${PACKAGE_MANAGER} == 'yum' || ${PACKAGE_MANAGER} == 'dnf' ]];then
        if ! type python3 >/dev/null 2>&1;then
            if [[ ${PACKAGE_MANAGER} == 'yum' ]];then
                ${PACKAGE_MANAGER} install epel-release -y
                ${PACKAGE_MANAGER} install https://centos7.iuscommunity.org/ius-release.rpm -y
                ${PACKAGE_MANAGER} install python36u -y

https://centos7.iuscommunity.org/ius-release.rpm have problems as I understand
maybe  I am wrong

**Comment by Ros-ua** [comment]
yum install https://repo.ius.io/ius-release-el7.rpm -y
yum install python36u -y
these ones worked for me

**Comment by Jrohy** [comment]
now is ok, `https://github.com/Jrohy/python3-install`

**Comment by Ros-ua** [comment]
Thank you Jrohy
