### ISSUE TITLE
想知道能不能通过mysql管理多用户？

### ISSUE THREAD

**Issue by bbhxwl** [Jrohy/multi-v2ray#355]
想知道能不能通过mysql管理多用户？

**Comment by Jrohy** [comment]
不能且没必要，还增加了使用内存

**Comment by bbhxwl** [comment]
> 不能且没必要，还增加了使用内存

多些大佬回复，每次添加用户，都要重新一下v2ray么？请问一下有没有什么远程api添加用户的方法。

**Comment by bbhxwl** [comment]
能限制每个用户的流量么？

**Comment by Jrohy** [comment]
不能限制，只能统计
