### ISSUE TITLE
怎么创建多个用户？用什么命令

### ISSUE THREAD

**Issue by bbhxwl** [Jrohy/multi-v2ray#356]
怎么创建多个用户？用什么命令？难道要自己改json么?

**Comment by Jrohy** [comment]
输入v2ray,选第二项，里面的新增端口或者新增用户

**Comment by bbhxwl** [comment]
> 输入v2ray,选第二项，里面的新增端口或者新增用户

看到了。github界面里面没说，我就不知道怎么弄了。第一次用。谢谢。
