### ISSUE TITLE
多ip的服务器上配置tls会识别错ip

### ISSUE THREAD

**Issue by Nz666-Kshatriya** [Jrohy/multi-v2ray#359]
因为我的服务器都是3个IP的，但是其中有些会被墙掉，所以需要启用备用ip，但配置tls的时候它不能按照我的需要识别ip，请问如何解决

**Comment by Jrohy** [comment]
识别ip，是请求这个地址来识别的http://api.ipify.org

**Comment by Jrohy** [comment]
https://github.com/Jrohy/multi-v2ray/blob/f98a01004fd3333a48fb161be7a34dee03ec8be0/v2ray_util/util_core/utils.py#L90

**Comment by Jrohy** [comment]
https://github.com/Jrohy/multi-v2ray/blob/f98a01004fd3333a48fb161be7a34dee03ec8be0/v2ray_util/util_core/utils.py#L90-L99

**Comment by Nz666-Kshatriya** [comment]
所以我要更改我的默认main IP才可以吧？

**Comment by Jrohy** [comment]
是的， 改完你可以在vps上curl 那个地址看下ip识别成什么

**Comment by Nz666-Kshatriya** [comment]
好的，谢谢大神

**Comment by Nz666-Kshatriya** [comment]
很抱歉的问一句，这个main IP在哪可以修改，因为我搜不到类似的话题

**Comment by Jrohy** [comment]
vps控制台没得修改么

**Comment by Nz666-Kshatriya** [comment]
很神奇的一点，我这个控制台一修改，就没办法wget了

**Comment by Jrohy** [comment]
我看下这两天出个宽松一点的版本，不校验本机ip来申请证书

**Comment by Nz666-Kshatriya** [comment]
好的，谢谢大神

**Comment by Jrohy** [comment]
@Nz666-Kshatriya 3779版本已做优化, 更新下

**Comment by Nz666-Kshatriya** [comment]
动作真快啊我的天，更新脚本还是v2ray

**Comment by Jrohy** [comment]
v2ray update.sh来更新

**Comment by Nz666-Kshatriya** [comment]
真的非常感谢，解决了一个大麻烦！
