### ISSUE TITLE
vmess码保存的位置是？

### ISSUE THREAD

**Issue by Nz666-Kshatriya** [Jrohy/multi-v2ray#364]
一个一个复制vmess有点麻烦，不知道vmess保存的实际位置是在哪里，想通过ftp直接导出

**Comment by Jrohy** [comment]
没有保存的，需要的时候显示出所有节点生成

**Comment by bbhxwl** [comment]
等过段时间不忙了是可以帮你做一个。简单的。base64 加密就好了。

**Comment by Nz666-Kshatriya** [comment]
> 等过段时间不忙了是可以帮你做一个。简单的。base64 加密就好了。

谢谢大佬!
