### ISSUE TITLE
ws+tls端口不是强制443吗？还是要自己手动修改？

### ISSUE THREAD

**Issue by cllcll** [Jrohy/multi-v2ray#365]
请问大佬，设置了ws+tls端口不是强制443吗？还是要自己手动修改？
是不是在修改prot的地方修改端口为443就可以了
ws+tls用别的端口也能使用？

**Comment by Jrohy** [comment]
别的端口也能使用的，修改端口那里可以改

**Comment by cllcll** [comment]
谢谢。好像用ws+tls 别的端口不太合适吧？

**Comment by Jrohy** [comment]
不放心就443端口

**Comment by cllcll** [comment]
好的，问题可以关闭了。谢谢，辛苦了
