### ISSUE TITLE
大佬麻烦问下，查流量的文件在哪里呢

### ISSUE THREAD

**Issue by bbhxwl** [Jrohy/multi-v2ray#366]
刚才在trojan地方问错了，想知道具体怎么查询用户流量的数据库文件位置。

**Comment by Jrohy** [comment]
保存在内存里面，重启v2ray流量统计数据就会丢失

**Comment by bbhxwl** [comment]
没有文件保存的地方么？那不是开账号后，别人的流量就无法统计了？

**Comment by bbhxwl** [comment]
也限制不了同时在线的话，那就是开1个号，可以无数人使用，没有任何限制了？

**Comment by Jrohy** [comment]
向官方v2ray提意见，限制使用人数

**Comment by Jrohy** [comment]
v2ray不支持限制连接数的

**Comment by Nz666-Kshatriya** [comment]
> 也限制不了同时在线的话，那就是开1个号，可以无数人使用，没有任何限制了？

sspanel不知道怎么实现限制设备数的

**Comment by seiuneko** [comment]
可以持久化流量数据吗？

**Comment by Jrohy** [comment]
v2ray不支持
