### ISSUE TITLE
allowInsecure为false无法工作

### ISSUE THREAD

**Issue by cheneyxx** [Jrohy/multi-v2ray#368]
服务器配置为ws+tls情况下客户端allowInsecure为false无法工作

**Comment by Jrohy** [comment]
@cheneyxx 什么客户端呢，我在v2rayN测试没这个问题， false或者true都可以工作

**Comment by cheneyxx** [comment]
> @cheneyxx 什么客户端呢，我在v2rayN测试没这个问题， false或者true都可以工作

不好意思大佬 最后实测是服务器域名伪装的问题
