### ISSUE TITLE
uuid达到200个的时候，就无法正常使用，

### ISSUE THREAD

**Issue by bbhxwl** [Jrohy/multi-v2ray#372]
uuid添加100个测试可以用，到200个不正常，我看tg群别人说他测试1000多个也没啥影响，是不是这个版本的v2有什么bug？机器的内存够用，还是无法正常运行，求指点。

**Comment by Jrohy** [comment]
V2仓库反馈下，本项目铺助只是修改json而已

**Comment by bbhxwl** [comment]
> V2仓库反馈下，本项目铺助只是修改json而已

好吧，大牛如果知道的话，麻烦告诉一下。
