### ISSUE TITLE
今天全新安装的时候，状态信息是这样的（OpenVZ的小鸡，centos 7 minimal系统）

### ISSUE THREAD

**Issue by laozui** [Jrohy/multi-v2ray#373]
v2ray status
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Thu 2020-06-04 02:28:37 UTC; 10min ago
     Docs: https://www.v2ray.com/
           https://www.v2fly.org/
  Process: 6215 ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json (code=exited, status=218/CAPABILITIES)
 Main PID: 6215 (code=exited, status=218/CAPABILITIES)

Jun 04 02:28:36 zz.xh systemd[1]: Unit v2ray.service entered failed state.
Jun 04 02:28:36 zz.xh systemd[1]: v2ray.service failed.
Jun 04 02:28:37 zz.xh systemd[1]: v2ray.service holdoff time over, scheduling restart.
Jun 04 02:28:37 zz.xh systemd[1]: Stopped V2Ray Service.
Jun 04 02:28:37 zz.xh systemd[1]: start request repeated too quickly for v2ray.service
Jun 04 02:28:37 zz.xh systemd[1]: Failed to start V2Ray Service.
Jun 04 02:28:37 zz.xh systemd[1]: Unit v2ray.service entered failed state.
Jun 04 02:28:37 zz.xh systemd[1]: v2ray.service failed.

**Comment by Jrohy** [comment]
v2ray restart 有用不

**Comment by laozui** [comment]
大佬，重启无效。换协议这些都无效。我看了下，按您的版本，v2ray也是更新到最新的 4.23.4 昨天是4.23.3我用您的脚本是可以正常运行的。会不会是对config.json有什么新的要求了？

**Comment by laozui** [comment]
[root@zz ~]# bash <(curl -L -s https://install.direct/go.sh) 
Latest version v4.23.4 is already installed.
[root@zz ~]# v2ray restart
restarting v2ray...
v2ray restart fail !
[root@zz ~]# v2ray stop
stoping v2ray...
v2ray stop fail !
[root@zz ~]# v2ray start
starting v2ray...
v2ray start fail !

**Comment by Jrohy** [comment]
应该不会一个小版本就将配置文件格式改掉的，我也测试下

**Comment by laozui** [comment]
谢谢您的回复！我后来尝试用了kvm的一台小鸡，可以正常用。谢谢！可能是ovz的某些限制导致了个别问题。

**Comment by fanlyu** [comment]
遇到了同样问题
