### ISSUE TITLE
请开发者注意修改V2ray新版本的更新地址

### ISSUE THREAD

**Issue by wsktig** [Jrohy/multi-v2ray#378]
请开发者注意修改V2ray新版本的更新地址
根据https://github.com/v2ray/v2ray-core/releases

Please refer to https://github.com/v2fly/v2ray-core/releases for further updates instead of the V2Ray release page. Currently, update in V2Fly will be mirrored to the V2Ray release page but this will NOT continue indefinitely.

**Comment by Jrohy** [comment]
V2ray的官方仓库已有更新了
