### ISSUE TITLE
有人测试过阿里云轻量服务器为什么不能正常运行吗？

### ISSUE THREAD

**Issue by bbhxwl** [Jrohy/multi-v2ray#379]
有人测试过阿里云轻量服务器为什么不能正常运行吗？程序是启动起来了。

**Comment by bbhxwl** [comment]
不知道怎么好了，我v2ray restart 好多次，不知道哪一次突然好了，奇怪啊。

**Comment by Jrohy** [comment]
不建议国内的vps搭梯子，没做好隐藏有风险

**Comment by Seekerzero** [comment]
@bbhxwl  老哥你最近还在用吗？我今天搭了一个，用的新加坡的服务器，但是却连不上。是不是新内核的原因？

**Comment by Seekerzero** [comment]
好了，我发现了，这个轻量服务器必须得把firewalld关掉才行，设置端口都不行。

**Comment by britthoule** [comment]
problem still coming, i have switched from Centos to Ubuntu to Aliyun Linus to Debian....its all same. :(

**Comment by bbhxwl** [comment]
错误日志里面，一直提示无效的用户，也是奇怪，有几个轻量没管他过一会就好了，有一个一直不行，不知道原因。
