### ISSUE TITLE
更新v4.24.2以后md5校验会默认启动

### ISSUE THREAD

**Issue by ZetaAquilae8474** [Jrohy/multi-v2ray#381]
用ws过cf的cdn 在md5校验开启的情况下会无限无效用户 需要更新一个选项关闭
(成linux白痴了 不知道怎么改json 但也是个问题

**Comment by Jrohy** [comment]
关闭貌似不能通过改json来关的，换成VMessAEAD就能规避md5

**Comment by ZetaAquilae8474** [comment]
> 关闭貌似不能通过改json来关的，换成VMessAEAD就能规避md5

翻了翻找到问题了 v2rayn会把testsEnabled直接抹掉 ng会自己开启
