### ISSUE TITLE
请问下怎么样备份自己的v2ray设置

### ISSUE THREAD

**Issue by tikkacn** [Jrohy/multi-v2ray#382]
是这样的，原来的multi-v2ray部署的vps就要到期，想搬家到其他vps上面，原来用的域名链接方式登录，是ws+tls方式，现在想不更改客户端设置情况下实现搬家，这种情况可以吗？

**Comment by Jrohy** [comment]
备份v2ray配置文件json，估计证书要重新签

**Comment by tikkacn** [comment]
好的，测试成功，多谢
