### ISSUE TITLE
请问谷歌云主机centos7安装时出现如下提示，该如何解决，可否提供具体步骤，非常感谢！

### ISSUE THREAD

**Issue by bctiantian** [Jrohy/multi-v2ray#384]
Collecting pip
  Downloading pip-20.1.1-py2.py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 10.1 MB/s
Collecting wheel
  Downloading wheel-0.34.2-py2.py3-none-any.whl (26 kB)
Installing collected packages: pip, wheel
  Attempting uninstall: pip
    Found existing installation: pip 9.0.3
    Uninstalling pip-9.0.3:
      Successfully uninstalled pip-9.0.3
  **WARNING: The scripts pip, pip3 and pip3.6 are installed in '/usr/local/bin' wh                                                                             ich is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warn                                                                             ing, use --no-warn-script-location.
  WARNING: The script wheel is installed in '/usr/local/bin' which is not on PAT                                                                             H.
  Consider adding this directory to PATH or, if you prefer to suppress this warn                                                                             ing, use --no-warn-script-location.**
Successfully installed pip-20.1.1 wheel-0.34.2
SELINUX=enforcing
 Time Synchronizing..
20 Jun 17:47:03 ntpdate[4186]: adjust time server 216.240.36.24 offset -0.000638                                                                              sec
 Time Sync Success
 now: Sat, 20 Jun 2020 17:47:03 +0800
**pip no install!**
-----------------------------------------------------------------------------
主机：centos7
加粗部分为报错内容。

**Comment by bctiantian** [comment]
我用vultr的centos7主机安装就没有问题。

**Comment by Jrohy** [comment]
谷歌云添加下环境变量，再安装
```echo 'export PATH=$PATH:/usr/local/bin' >> /etc/profile; source /etc/profile;```

**Comment by Jrohy** [comment]
已经优化了py3在谷歌云的安装
