### ISSUE TITLE
麻烦问一下查询所有人流量信息的代码

### ISSUE THREAD

**Issue by bbhxwl** [Jrohy/multi-v2ray#386]
我使用/usr/bin/v2ray/v2ctl api --server=127.0.0.1:10086 StatsService.QueryStats 'pattern: "user" reset: false'

好像查不到呢？求指点一下谢谢。

**Comment by britthoule** [comment]
new update is a mess, lot are things are not behaving properly now.

**Comment by bbhxwl** [comment]
Is there a problem with the latest traffic query? What should be done?

**Comment by bbhxwl** [comment]
> new update is a mess, lot are things are not behaving properly now.

Is there a problem with the latest traffic query? What should be done?

**Comment by bbhxwl** [comment]
最新版本有问题吗？应该怎么解决？

**Comment by britthoule** [comment]
no, traffic is good.
but when i use alicloud with multi-v2ray.....things dont work.
v2ray does not connect from home. Timeout all time.
please, do something
