### ISSUE TITLE
老哥，最新的流量统计好像是不可以使用了。

### ISSUE THREAD

**Issue by bbhxwl** [Jrohy/multi-v2ray#387]
老哥，最新的流量统计好像是不可以使用了。统计不到。流量都是0

**Comment by bbhxwl** [comment]
我以前安装的老版本以前可以，我没更新过内核，只restart 过，他会自动更新？现在我安装的所有版本都无法使用流量查询了。

**Comment by Jrohy** [comment]
用的什么协议呢，我用tls + ws 和tls +kcp测试的都能统计到流量， 最新版v2

**Comment by bbhxwl** [comment]
> 用的什么协议呢，我用tls + ws 和tls +kcp测试的都能统计到流量， 最新版v2

用的纯ws协议，以前可以，最近不行了，脚本是不是会自动更新的？我只每天重启一次，以前安装过的脚本好像也更新了？

**Comment by bbhxwl** [comment]
![QQ图片20200702015329](https://user-images.githubusercontent.com/26525599/86276085-dbb32d80-bc06-11ea-9233-f4e4e9614626.png)

**Comment by bbhxwl** [comment]
> 用的什么协议呢，我用tls + ws 和tls +kcp测试的都能统计到流量， 最新版v2

发了图片，老哥看下呗。

**Comment by bbhxwl** [comment]
流量只显示4个，不会显示某个邮箱的。以前不是这样的。

**Comment by bbhxwl** [comment]
> 用的什么协议呢，我用tls + ws 和tls +kcp测试的都能统计到流量， 最新版v2

我测试的真的是你这里最新的脚本安装代码呢。好像就是查不到的啊。代码是
source <(curl -sL https://multi.netlify.app/v2ray.sh) --zh

**Comment by Jrohy** [comment]
不用命令查，通过脚本查不行？脚本这方面没变更过
