### ISSUE TITLE
allowInsecure设定为false之后无法使用

### ISSUE THREAD

**Issue by KevinChan0623** [Jrohy/multi-v2ray#389]
allowInsecure设定为false之后无法使用

**Comment by Jrohy** [comment]
#368 之前测过ws+tls的情况下没问题

**Comment by KevinChan0623** [comment]
> #368 之前测过ws+tls的情况下没问题

v2rayn/v2rayng里面allowinsecure设为false就用不了

**Comment by Jrohy** [comment]
v2rayn测试没问题，true or false都可以, v2rayng就没条件测

**Comment by KevinChan0623** [comment]
> v2rayn测试没问题，true or false都可以, v2rayng就没条件测

啊为什么我不行，是要设置什么吗？
