### ISSUE TITLE
强烈建议默认开启BBR~

### ISSUE THREAD

**Issue by zhbzhbzhbz** [Jrohy/multi-v2ray#391]
非常感谢作者的无私付出，您这个库我用了好久了。
不过今天偶然才发现居然没开启BBR（233boy的那个就默认开启了）。开了之后，我、朋友、另一个用您库的朋友都感觉近来卡顿的V2ray+ws+tls快了好多！延迟也低了
所以如果您方便的话可以在脚本里加一下？如果不方便，您看是否可以在README里标注一下？这样免得大家以为默认是开了的，可以帮助大家有更好的体验

**Comment by karon110** [comment]
同意，确实开启以后速度会提高很多，延迟也是降低到50ms，强烈建议标注

**Comment by lxhao61** [comment]
有专门开启BBR的一键脚本，不必加。建议README里标注一下没有开BBR即可。

**Comment by zhbzhbzhbz** [comment]
> 有专门开启BBR的一键脚本，不必加。建议README里标注一下没有开BBR即可。

嗯嗯也可以的

**Comment by yesmiley** [comment]
Unnecessary. Just do it yourself.

**Comment by zhbzhbzhbz** [comment]
> Unnecessary. Just do it yourself.

But it should be reminded at least, or the users may assume it is on by default.

**Comment by yesmiley** [comment]
> > Unnecessary. Just do it yourself.
> 
> But it should be reminded at least, or the users may assume it is on by default.

Uh, nobody could think so, at least on behalf of myself.
Enabling BBR is more like a job on the level of system.

**Comment by zhbzhbzhbz** [comment]
> > > Unnecessary. Just do it yourself.
> > 
> > 
> > But it should be reminded at least, or the users may assume it is on by default.
> 
> Uh, nobody could think so, at least on behalf of myself.
> Enabling BBR is more like a job on the level of system.

Many users will do, because in the v2ray project with the most stars, "https://github.com/233boy/v2ray",  the BBR is turned on by default.

**Comment by Jrohy** [comment]
@zhbzhbzhbz readme里已添加建议

**Comment by zhbzhbzhbz** [comment]
> @zhbzhbzhbz readme里已添加建议

感谢~
