### ISSUE TITLE
证书过期

### ISSUE THREAD

**Issue by wialny** [Jrohy/multi-v2ray#393]
刚刚提示证书过期，不知道怎么更新？
用crontab -e里的"/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null报错
用v2ray cdn来重新生成证书成功，但path变了，得去客户端一个个修改
请问有没有什么命令可以在不改变任何配置的情况下让旧证书续期或者申请新证书的呀？再或者更改配置里可以增加一项修改path也行

**Comment by Jrohy** [comment]
报什么错呢

**Comment by Jrohy** [comment]
可以自己改下配置文件改成和原来一样的path路径的

**Comment by wialny** [comment]
抱歉, 当时没有记录下来. 因为我对linux一无所知, 只会用大佬的脚本, 所以也不会在服务器修改文件
今天再用"/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null这行命令, 无任何信息返回
用v2ray cdn重新生成证书后, 目前一切正常. 如果下次再出现类似问题, 我会记录下错误信息

**Comment by alexliyu7352** [comment]
如果采用nginx代理, 那么自然会报错, 因为验证方式是通过80端口, 所以先要暂停你的nginx, 或者nginx关闭80端口.
自己修改下cron脚本就好,
在"/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
之前增加service nginx stop, 之后增加service nginx start
或者修改nginx配置文件关闭80端口
