### ISSUE TITLE
v2ray v4.27.0版正式新增VLESS协议，望支持。

### ISSUE THREAD

**Issue by lxhao61** [Jrohy/multi-v2ray#395]
VLESS是一个无状态的轻量传输协议，特别套tls应用，比VMess性能更佳。另外支持回落模式，相较于其它协议回落方案，更简洁、高效、安全，功能也更强大。望添加支持此协议。
https://github.com/v2ray/v2ray-core/releases
https://www.v2fly.org/config/protocols/vless.html
https://github.com/v2ray/v2ray-core/issues/2636

**Comment by lxhao61** [comment]
目前已支持图形化配置 VLESS 的部分客户端列表
Qv2ray（v2.6.3+），支持 Linux、macOS、Windows
v2rayN（v3.21+），支持 Windows
v2rayNG（v1.3.0+），支持 Android
PassWall（v3.9.35+），支持 OpenWrt
https://www.v2fly.org/config/protocols/vless.html

**Comment by reborn341** [comment]
是的，muti脚本我最喜欢用了

**Comment by lxhao61** [comment]
是的。可惜迟迟不支持VLESS。

**Comment by Jrohy** [comment]
其实vless协议的json修改已经添加，只是在考虑使用vless协议时是否必要添加nginx的部署, 假如加上nginx部署怎么实现比较好(裸机部和docker化都要考虑)

**Comment by lxhao61** [comment]
大神，喜欢你的脚本是：向导式，多用户、 多端口管理，且可以任意配合外部程序实现多种应用！如添加nginx或caddy等任意、添加加速等。让用户选择，积木式搭建实现特色应用。
另外VLESS协议回落不一定必须绑定nginx，caddy等也可以；目前只是无人公布模板。请保持你脚本专业及特色好吗，让用户选择！


以上是我一个享受你成果的用户诚挚反馈，也万分感谢你付出。谢谢！！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jrohy/multi-v2ray"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月30日(星期天) 晚上9:04
收件人:&nbsp;"Jrohy/multi-v2ray"<multi-v2ray@noreply.github.com&gt;;
抄送:&nbsp;"刘欣豪"<751142257@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Jrohy/multi-v2ray] v2ray v4.27.0版正式新增VLESS协议，望支持。 (#395)





 
其实vless协议的json修改已经添加，只是在考虑使用vless协议时是否必要添加nginx的部署, 假如加上nginx部署怎么实现比较好(裸机部和docker化都要考虑)

**Comment by adminzhuang** [comment]
同求！感谢付出~

**Comment by gqm36524** [comment]
怎么切换成VLESS协议啊

**Comment by lxhao61** [comment]
@gqm36524 
目前只能手工修改配置文件。

**Comment by kokorobeats** [comment]
同求！感谢dalao!!!!!!

**Comment by hadifarnoud** [comment]
please support VLESS

**Comment by knowledge-one** [comment]
please support VLESS!!!

**Comment by zbttl** [comment]
vless 现在协议还在不停变动，可以等稳定一些再支持。
不过如果手工修改为 vless 会导致流量检测报错，这个大佬有没有办法暂时修一下？

**Comment by zerofo** [comment]
求支持

**Comment by fy-deng** [comment]
大佬辛苦了！please support VLESS+tcp+xtls!
