### ISSUE TITLE
V2ray更新源即将变更，望脚本跟进修正

### ISSUE THREAD

**Issue by KANIKIG** [Jrohy/multi-v2ray#396]
v2ray官方已给出提示
This script will be obsolete soon, please switch to the fhs-install-v2ray project in time.
URL: https://github.com/v2fly/fhs-install-v2ray

**很棒的管理脚本，感谢您的维护。**

**Comment by Jrohy** [comment]
周末会更新下，还是用回旧脚本定义的文件位置, 因为新脚本会使v2ray核心变成全局命令而和管理脚本冲突

**Comment by Jrohy** [comment]
已修复安装，更新下脚本

**Comment by KANIKIG** [comment]
感谢
