### ISSUE TITLE
/etc/v2ray/config.json: No such file or directory

### ISSUE THREAD

**Issue by tqangxl** [Jrohy/multi-v2ray#398]
检测到本机没安装v2ray, 正在自动安装..
WARN: This script will be obsolete soon, please switch to the fhs-install-v2ray project in time.
URL: https://github.com/v2fly/fhs-install-v2ray
cp: cannot create regular file ‘/etc/v2ray/config.json’: No such file or directory
new UUID: 
new port: 63440
sed: can't read /etc/v2ray/config.json: No such file or directory
random generate (srtp | wechat-video | utp | dtls | wireguard) fake header, new protocol: mKCP + wireguard

**Comment by Masterlovsky** [comment]
同样的问题
检测到没有安装V2ray，正在自动安装
FileNotFoundError: [Errno 2] No such file or directory: '/etc/v2ray/config.json'

**Comment by tqangxl** [comment]
安装前需要先运行:
mkdir -p /etc/v2ray/
touch /etc/v2ray/config.json

运行失败了，执行下上面的命令，再装一次就OK了

**Comment by Masterlovsky** [comment]
> 安装前需要先运行:
> mkdir -p /etc/v2ray/
> touch /etc/v2ray/config.json
> 
> 运行失败了，执行下上面的命令，再装一次就OK了

不可以的，v2ray核心更新了，这样能装上但是v2ray运行不起来，restart failed
