### ISSUE TITLE
multi-v2ray安装过程中报错，如何解决？

### ISSUE THREAD

**Issue by Chenx221** [Jrohy/multi-v2ray#399]
`检测到本机没安装v2ray, 正在自动安装..
WARN: This script will be obsolete soon, please switch to the fhs-install-v2ray project in time.
URL: https://github.com/v2fly/fhs-install-v2ray
new UUID: ***
new port: 44158
random generate (srtp | wechat-video | utp | dtls | wireguard) fake header, new protocol: mKCP + wechat-video 

Failed to restart v2ray.service: Unit v2ray.service not found.
v2ray restart fail !
1.
Group: A
IP: ***
Port: 44158
TLS: 关闭
UUID: ***
Alter ID: 16
Network: kcp wechat-video

vmess://***

Tip: 同一Group的节点传输方式,端口配置,TLS等设置相同
please input 'v2ray' command to manage v2ray`

multi-v2ray安装过程中报错

**Comment by Jrohy** [comment]
已修复安装源，更新下脚本
