### ISSUE TITLE
ARM更新了包的名称，原本的更新脚本无法使用，望更新，谢谢~

### ISSUE THREAD

**Issue by sayainchina** [Jrohy/multi-v2ray#403]
ARM更新了包的名称，原本的更新脚本无法使用，望更新，谢谢~

https://www.v2fly.org/guide/install.html#linux-%E5%AE%89%E8%A3%85%E8%84%9A%E6%9C%AC

https://github.com/v2ray/v2ray-core/issues/2328

**Comment by Jrohy** [comment]
原来的更新脚本已做arm架构的下载优化，用3.7.8版本试试安装v2ray

**Comment by sayainchina** [comment]
> 原来的更新脚本已做arm架构的下载优化，用3.7.8版本试试安装v2ray

非常感谢更新！

**Comment by sayainchina** [comment]
> 原来的更新脚本已做arm架构的下载优化，用3.7.8版本试试安装v2ray

非常感谢更新！
