### ISSUE TITLE
老版本无法安装

### ISSUE THREAD

**Issue by Glanwu** [Jrohy/multi-v2ray#404]
因为ovz的机器，只能debian 8稳定，但是source <(curl -sL https://git.io/fNgqx) 之前保存的这个无法安装，各位大佬能否提供一个老版本的安装路径，谢谢

**Comment by Jrohy** [comment]
新版是因为python3无法安装，还是什么原因不能用新版

**Comment by airplayx** [comment]
安装之后是这种效果：
我还以为是机器的问题，换了几个商家都没用
![QQ截图20200829155644](https://user-images.githubusercontent.com/8004501/91631992-4ec2ff80-ea10-11ea-84ff-0746ea92c833.png)

**Comment by Jrohy** [comment]
@airplayx v2ray新版安装包内容改了，我优化下安装脚本

**Comment by Jrohy** [comment]
@airplayx 已优化可以正常安装了，感谢反馈

**Comment by airplayx** [comment]
@Jrohy 可以正常安装了，谢谢。
