### ISSUE TITLE
最新脚本还是报：-bash: /usr/local/sbin/v2ray: No such file or directory

### ISSUE THREAD

**Issue by wiilsliang** [Jrohy/multi-v2ray#405]
-bash: /usr/local/sbin/v2ray: No such file or directory
please input 'v2ray' command to manage v2ray
手动创建目录还是不行，centos7

**Comment by Jrohy** [comment]
python3安装到了吗，运行下pip list看看有没有安装v2ray-util包

**Comment by lloyd18** [comment]
我遇到同样问题，v2ray-util是有的

**Comment by Jrohy** [comment]
试下运行 `ln -s $(which v2ray-util) /usr/local/bin/v2ray` @lloyd18

**Comment by lloyd18** [comment]
`ln: failed to create symbolic link '/usr/local/bin/v2ray': File exists`

**Comment by chaselightisadream** [comment]
同样的问题

**Comment by lloyd18** [comment]
> 
> 
> 同样的问题

是不是之前装过233的版本，卸载重启再试试。

**Comment by chaselightisadream** [comment]
> > 同样的问题
> 
> 是不是之前装过233的版本，卸载重启再试试。

不是，不过我用其他办法解决了，造成这个问题的原因之一可能是其余脚本改变了v2ray service的一些默认配置指向

**Comment by knowledge-one** [comment]
我之前也遇到这个问题，系统同样是是centos7，后来是重新安装python解决的，不是脚本本身的问题。
