### ISSUE TITLE
新版的配置文件路径是啥啊

### ISSUE THREAD

**Issue by gqm36524** [Jrohy/multi-v2ray#406]
新版的配置文件路径是啥啊，我想导入旧用户配置发现不在原来那了

**Comment by Jrohy** [comment]
没有变，依然是/etc/v2ray/config.json

**Comment by Jrohy** [comment]
你可以运行systemctl status v2ray来看用的什么配置文件

**Comment by gqm36524** [comment]
万分感谢，我可能sftp卡了，已经找到了并且还学到了查询路径的方法
