### ISSUE TITLE
查询流量统计时报错

### ISSUE THREAD

**Issue by rhjdvsgsgks** [Jrohy/multi-v2ray#41]
`Ext|Tools|Control: failed to call service StatsService.GetStats > rpc error: code = Unknown desc = App|Stats|Command: user>>>邮箱>>>traffic>>>downlink not found.`

**Comment by Jrohy** [comment]
要有邮箱才能统计流量

**Comment by rhjdvsgsgks** [comment]
邮箱已经填写了

**Comment by Jrohy** [comment]
填入符合要求的邮箱

**Comment by Jrohy** [comment]
不清楚你是怎样产生了，说的条件太少了，什么系统总得说说吧

**Comment by Jrohy** [comment]
测试了，节点没走过流量官方的v2ray就会报这个错，走下流量就好

**Comment by rhjdvsgsgks** [comment]
谢谢
