### ISSUE TITLE
怎么查看v2ray 核心的版本呢？

### ISSUE THREAD

**Issue by bbhxwl** [Jrohy/multi-v2ray#414]
怎么查看v2ray 核心的版本呢？中转出错，不知道为什么，听说可能版本不一致，不知道怎么查具体版本是多少。还有命令输入v2ray 后，无法退出。

**Comment by Jrohy** [comment]
v2ray -v

**Comment by bbhxwl** [comment]
> v2ray -v

多谢，没注意看文档，只在机器里面输入v2ray 提示的那几个选项了。
老大是不是原来有个ssr项目，怎么找不到了呢。还想问几个问题。

**Comment by Jrohy** [comment]
没有ssr项目
