### ISSUE TITLE
tls open close

### ISSUE THREAD

**Issue by Ros-ua** [Jrohy/multi-v2ray#423]
when create tls is open by default, previously had to open in first.
now even when close tls it is still open. can not close tls.
![1](https://user-images.githubusercontent.com/51153745/96335315-75b1bf80-10aa-11eb-8af3-b7fa3717fa9d.JPG)
![2](https://user-images.githubusercontent.com/51153745/96335322-7cd8cd80-10aa-11eb-989d-12a8e45bf12e.JPG)

**Comment by Jrohy** [comment]
mkcp type? what stream type

**Comment by Ros-ua** [comment]
Network: WebSocket TLS: open
Network: tcp TLS: open
both always open tls. 
tried on debian 9 and centos 7, both same result

**Comment by Ros-ua** [comment]
I mean I input this source <(curl -sL https://multi.netlify.app/v2ray.sh)
and I get this
![1](https://user-images.githubusercontent.com/51153745/96338058-18276e00-10be-11eb-8a66-a84d202d522b.JPG)

**Comment by Jrohy** [comment]
3.8.3 fixed it!, please update

**Comment by Ros-ua** [comment]
is that ok that Alter ID: 0 not for vless but for vmess? 
previously you had alter id 16 
for me trojan is working, vmess WebSocket and vmess tcp not working 
![1](https://user-images.githubusercontent.com/51153745/96340003-adc8fa80-10ca-11eb-8124-7db71a8c8a37.JPG)

**Comment by Jrohy** [comment]
default vmess alterid is 0, to open VMessAEAD, https://www.v2fly.org/config/protocols/vmess.html

**Comment by Ros-ua** [comment]
Thanks, Jrohy, everything ok now!
