### ISSUE TITLE
希望能增加VLESS over WS with TLS的搭配协议

### ISSUE THREAD

**Issue by knowledge-one** [Jrohy/multi-v2ray#427]
希望能增加VLESS over WS with TLS的搭配协议，有ws（套cdn）需求，目前只能依靠手动修改配置文件，且修改后不能通过脚本管理用户，修改的参考配置文件模版如下：
https://github.com/v2fly/v2ray-examples/tree/master/VLESS-TCP-XTLS-WHATEVER

希望作者可以添加一些vless的搭配协议

**Comment by Jrohy** [comment]
vless + ws 2.8.4版本以支持，更新下

**Comment by dalton-chiou** [comment]
3.8.4 :)   3.8.5又加入更新指定版本，正是我需要的。谢谢。
