### ISSUE TITLE
安装第二天就会出现 failed to handler mux client connection

### ISSUE THREAD

**Issue by abelyuan00** [Jrohy/multi-v2ray#428]
在vps上部署第一天正常使用，第二天（10来个小时左右）就会出现failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF, 改了时间没有用，卸载脚本然后重新安装又可以了，status里会出现 v2ray(running) (thawing)， 查了一下没搜到这个thawing状态怎么解决

**Comment by abelyuan00** [comment]
另一个vps4.27版本的服务器没有这个问题

**Comment by Jrohy** [comment]
什么协议

**Comment by abelyuan00** [comment]
Mkcp+dtls 另一个vps上用的4.27版本的v2ray一直没有任何问题

**Comment by Jrohy** [comment]
可以换下其他协议试试，比如vless的
