### ISSUE TITLE
pip no install!

### ISSUE THREAD

**Issue by oushujun** [Jrohy/multi-v2ray#429]
看了之前类似的issues，都不是这个情况。用的AWS默认系统，pip和pip3都有，分别在：
/usr/local/bin/pip
/usr/local/bin/pip3

然鹅还是提示没安装pip：

sudo bash v2ray.sh 
new install

Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
195 packages excluded due to repository priority protections
Package socat-1.7.3.2-2.amzn2.0.1.x86_64 already installed and latest version
Package crontabs-1.11-6.20121102git.amzn2.noarch already installed and latest version
Package 1:bash-completion-2.1-6.amzn2.noarch already installed and latest version
Package which-2.20-7.amzn2.0.2.x86_64 already installed and latest version
Nothing to do
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
195 packages excluded due to repository priority protections
Package wget-1.14-18.amzn2.1.x86_64 already installed and latest version
Nothing to do
Collecting pip
  Using cached pip-20.2.4-py2.py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.2.4
    Uninstalling pip-20.2.4:
      Successfully uninstalled pip-20.2.4
Successfully installed pip-20.2.4
 Time Synchronizing.. 
200 OK
 Time Sync Success 
 now: Sun, 25 Oct 2020 14:50:53 +0800
pip no install!

**Comment by Jrohy** [comment]
再试下安装，已优化环境变量设置
