### ISSUE TITLE
CentOS7安装过程中提示bash: pip3: command not found

### ISSUE THREAD

**Issue by rhotov** [Jrohy/multi-v2ray#43]
最后提示python3: can't open file '/usr/local/multi-v2ray/server_info.py': [Errno 2] No such file or directory

**Comment by Jrohy** [comment]
检查下有没这文件, 没有重新跑脚本

**Comment by rhotov** [comment]
没有server_info.py这个文件，重跑了一次还是没有，后来换成CentOS7.5就好了，又试了Debian8也没问题，看来是CentOS7的诡异bug。
