### ISSUE TITLE
ubuntu14.04出现错误

### ISSUE THREAD

**Issue by Glanwu** [Jrohy/multi-v2ray#433]
PORT:41380
UUID:3147664b-d994-4233-a15c-297f129c8771
/dev/fd/63: line 354: systemctl: command not found
-bash: v2ray: command not found

multi-v2ray install success!
-bash: v2ray: command not found
please input 'v2ray' command to manage v2ray

**Comment by Jrohy** [comment]
尽量换新一点系统，脚本只支持systemctl  的管理方式
