### ISSUE TITLE
ipv6主机部署，部署完之后ip显示ipv4

### ISSUE THREAD

**Issue by zyaowei** [Jrohy/multi-v2ray#434]
我是在euserv机子上，通过嘿呦终端部署了v2ray，安装完成之后显示的是ipv4的ip，连不通。
请问这个问题应该怎么解决。

**Comment by zyaowei** [comment]
Group: A
IP: 159.69.108.193
Port: 42840
TLS: 关闭
UUID: 75dede0c-1f69-11eb-9eb3-a7093557607a
Alter ID: 0
Network: kcp srtp
TcpFastOpen: open

我的理解上方ip应该是ipv6才对。

**Comment by Jrohy** [comment]
有ipv4地址的话就会优先ipv4的

**Comment by Jrohy** [comment]
http://api.ipify.org
http://icanhazip.com
这两个地址来获取ip的，第一个获取不了才去请求第二个

**Comment by zyaowei** [comment]
多谢。
euserv是纯v6机，获取的ipv4应该是通过NTA64获得的。
那么又有了另一个问题,，通过NTA64获取的ipv4地址，一直在改变。
那么纯ipv6的机子，部署完之后，获取的是当时的ipv4，过几分钟就不好用了。

请问有解决办法吗？

**Comment by Jrohy** [comment]
自己手动替换成ipv6地址吧

**Comment by zyaowei** [comment]
config文件中没有ip的字段，貌似不可以改。
请问在哪个文件中可以修改呢？

**Comment by Jrohy** [comment]
使用的时候将ipv4替换为ipv6地址

**Comment by zyaowei** [comment]
好的，多谢，我去试试。

**Comment by zyaowei** [comment]
试过了后结果汇报：
1.问题出在证书上，需要手动申请证书进行替换。
2.ipv4地址换为ipv6地址，不好用。
3.套cf中转，地址改为域名后就可以用了。

还有一个事情请教：
各项设置我看了一下，貌似没有vless+ws+tls。
ipv6的话，需要套cf，所以目前只能用vmess+ws+tls。
