### ISSUE TITLE
更新脚本失败

### ISSUE THREAD

**Issue by dalton-chiou** [Jrohy/multi-v2ray#436]
我现在的版本是3.7.8，想更新至最新的3.8.3，运行v2ray update.sh，提示更新成功，然而版本仍然停留在3.7.8。
以下是错误信息：
usr/local/lib/python3.5/dist-packages/_distutils_hack/__init__.py:19: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  "Distutils was imported before Setuptools, but importing Setuptools "
/usr/local/lib/python3.5/dist-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ImportError: No module named 'pip'

请问如何解决？

**Comment by Jrohy** [comment]
没安装到pip

**Comment by dalton-chiou** [comment]
我系统（debian 9) 里有pip,pip2,pip3。我试着运行您的脚本（source <(curl -sL https://python3.netlify.app/install.sh)重新安装，结果dpkg报错。

**Comment by Jrohy** [comment]
我试了vultr debian9安装没问题

**Comment by dalton-chiou** [comment]
以前安装也没有问题。升级脚本遇到问题。我自己去琢磨一下，不行就重装系统。
