### ISSUE TITLE
脚本生成的链接，不能正常使用

### ISSUE THREAD

**Issue by yeslinlei** [Jrohy/multi-v2ray#44]
脚本生成的链接，不能正常使用，具体如下:
配置为ws+tls
1，shadowrocket 2.1.10，pp助手上下载的，无法正常使用，导入链接后，没有ws协议，估计可能这个版本软件就不支持这种协议。
2，kitsunebi lite不能正常使用，链接识别以后，把伪装的域名填到路径的选项里面了，域名那一项空的。
3，app store下载的最新的shadowrocket 2.1.23可以正常用。
希望能够更新，使得kitsunebi lite能用，谢谢，请测试。

**Comment by Jrohy** [comment]
纯脚本的不会加，后面打算搞的web版可能会有

**Comment by Jrohy** [comment]
生是另一种格式成的连接是v2rayN格式的,kitsubebi lite估计

**Comment by Jrohy** [comment]
没有统一的字符串分享链接

**Comment by yeslinlei** [comment]
OK 谢谢

Jrohy <notifications@github.com>于2018年9月28日 周五13:29写道：
