### ISSUE TITLE
新增的vless+ws，fallbacks是否多余？

### ISSUE THREAD

**Issue by dalton-chiou** [Jrohy/multi-v2ray#442]
看了一下生成的json，vless+ws有fallbacks项。按照官方文档，fallbacks“只能用于 TCP+TLS 传输组合“，又说”其它传输组合必须删掉 fallbacks 项或所有子元素，此时也不会开启 Fallback，VLESS 会等待读够所需长度，协议版本无效或身份认证失败时，将直接断开连接“。
不过我倒没遇到什么”断开连接“之类的事，正常使用。只是有点疑惑。请教一下。

**Comment by Jrohy** [comment]
谢谢提醒，没有留意到只能用于tcp + tls组合，下个版本删除掉

**Comment by Jrohy** [comment]
3.8.7版本已做优化
