### ISSUE TITLE
大神，会支持Xray吗

### ISSUE THREAD

**Issue by datout** [Jrohy/multi-v2ray#445]
xray 1.1.1版本

**Comment by Jrohy** [comment]
应该会

**Comment by l3617** [comment]
v2ray-core v4.33.0删除了xtls蛋疼，安装了vless＋xtls模式，v2ray电脑手机都不可以选xtls底层传输，不然连接不了，不选就可以

**Comment by datout** [comment]
> v2ray-core v4.33.0删除了xtls蛋疼，安装了vless＋xtls模式，v2ray电脑手机都不可以选xtls底层传输，不然连接不了，不选就可以

手动退回吧。。换了个脚本搭建了Xtls。。坐等大神更新脚本

**Comment by Jrohy** [comment]
3.9.0以支持，更新下

**Comment by datout** [comment]
> 3.9.0以支持，更新下

![image](https://user-images.githubusercontent.com/70312079/101606635-8b09f100-3a3e-11eb-8477-7a66bdcce424.png)
运行了 一下 python3-install的脚本 还是报错

**Comment by Jrohy** [comment]
python3没安装到吗

**Comment by datout** [comment]
> python3没安装到吗， 尽量用新一点的系统好点

用的是Debian 8

**Comment by Jrohy** [comment]
pip不支持python3.4了，我看下怎么优化下

**Comment by Jrohy** [comment]
@datout 更新下，以支持python3.4的pip安装了

**Comment by datout** [comment]
@Jrohy 谢谢安装好了，顺便问下有没有可能 脚本增加nginx之类的安装 伪装网站。

**Comment by Jrohy** [comment]
@datout 不支持，只专心做新功能适配和配置修改

**Comment by datout** [comment]
@Jrohy 
好像没有用。没法翻墙。。选的xtls，貌似 4.33.0已经不支持xtls了。需要xray的内核吧

**Comment by datout** [comment]
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-12-09 06:43:23 EST; 4min 18s ago
 Main PID: 6822 (v2ray)
    Tasks: 7 (limit: 545)
   Memory: 3.6M
   CGroup: /system.slice/v2ray.service
           └─6822 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json

Dec 09 06:43:23 107-173-122-14-host systemd[1]: Started V2Ray Service.
Dec 09 06:43:24 107-173-122-14-host v2ray[6822]: V2Ray 4.33.0 (V2Fly, a community-driven edition of V2Ray
Dec 09 06:43:24 107-173-122-14-host v2ray[6822]: A unified platform for anti-censorship.
Dec 09 06:43:24 107-173-122-14-host v2ray[6822]: 2020/12/09 06:43:24 [Info] v2ray.com/core/main/jsonem: R

**Comment by Jrohy** [comment]
你运行xray命令来安装xray或者回退v2ray版本

**Comment by datout** [comment]
@Jrohy xray是不是没办法统计流量，自定义邮箱不成功。

**Comment by Jrohy** [comment]
@datout 确实会报错，流量统计的

**Comment by Amos-Dan** [comment]
> @datout 确实会报错，流量统计的

目前就xray的发展情况，考虑抛弃v2ray，仅支持xray吗？
