### ISSUE TITLE
保留配置 更新后，无法使用

### ISSUE THREAD

**Issue by cocpublic** [Jrohy/multi-v2ray#447]
v2ray: 4.33.0
v2ray_util: 3.9.0.1

Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/main.py", line 251, in menu
    user_manage()
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/main.py", line 167, in user_manage
    multiple.new_user()
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/v2ray.py", line 20, in wrapper
    result = func(*args, **kw)
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/config_modify/multiple.py", line 48, in new_user
    gs = GroupSelector(_('add user'))
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/selector.py", line 91, in __init__
    self.group = self.group_list[0]
IndexError: list index out of range

**Comment by Jrohy** [comment]
v2ray还是xray添加用户，添加什么协议的用户

**Comment by Jrohy** [comment]
原来是什么协议的配置的

**Comment by cocpublic** [comment]
> v2ray还是xray添加用户，添加什么协议的用户

v2ray的，原来是 vmess的

**Comment by cocpublic** [comment]
需要什么日志吗

**Comment by Jrohy** [comment]
没测试出有问题，新版这一块也没改动(涉及json)修改的

**Comment by Jrohy** [comment]
不需要日志只需要json

**Comment by cocpublic** [comment]
json 在哪个目录，我捞出来看看

**Comment by Jrohy** [comment]
/etc/v2ray/config.json

**Comment by cocpublic** [comment]
{                                                                                                                 
  "inbounds": [{                                                                                                  
    "port": 38091,                                                                                                
    "protocol": "vmess",                                                                                          
    "settings": {                                                                                                 
      "clients": [                                                                                                
        {                                                                                                         
          "id": "0b9210d9-3b11-4a70-8f6d-9f08ebc0a9e4",                                                           
          "level": 1,                                                                                             
          "alterId": 64                                                                                           
        }                                                                                                         
      ]                                                                                                           
    }                                                                                                             
  }],                                                                                                             
  "outbounds": [{                                                                                                 
    "protocol": "freedom",                                                                                        
    "settings": {}                                                                                                
  },{                                                                                                             
    "protocol": "blackhole",                                                                                      
    "settings": {},                                                                                               
    "tag": "blocked"                                                                                              
  }],                                                                                                             
  "routing": {                                                                                                    
    "rules": [                                                                                                    
      {                                                                                                           
        "type": "field",                                                                                          
        "ip": ["geoip:private"],                                                                                  
        "outboundTag": "blocked"                                                                                  
      }                                                                                                           
    ]                                                                                                             
  }                                                                                                               
}

**Comment by Jrohy** [comment]
这是全新安装的吗，配置这么少

**Comment by cocpublic** [comment]
我先用 v2ray 才能里面的 6.更新v2ray 升级，出现问题后,使用source <(curl -sL https://multi.netlify.app/v2ray.sh) -k 升级

**Comment by Jrohy** [comment]
运行下`v2ray new`重新建配置文件吧，这个配置不符合的

**Comment by cocpublic** [comment]
ok

**Comment by cocpublic** [comment]
全新安装了一次，配置丢了，重新配了下，已经正常使用了
