### ISSUE TITLE
遭遇 ModuleNotFoundError: No module named 'read_json'

### ISSUE THREAD

**Issue by choicky** [Jrohy/multi-v2ray#45]
vultr 上新安装的 ubuntu 18.04

运行 v2ray 进行配置或者修改时，出错，提示`ModuleNotFoundError: No module named 'read_json'`

我是使用非root用户，通过 `sudo`命令安装的。

运行 `grep v2ray.fun ~/.bashrc` 没有返回。

运行 ` echo "export PYTHONPATH=$PYTHONPATH:/usr/local/multi-v2ray" >> ~/.bashrc && source ~/.bashrc` 之后， `grep v2ray.fun ~/.bashrc`  有返回，但依然遭遇 ModuleNotFoundError: No module named 'read_json'

**Comment by Jrohy** [comment]
最好用root用户安装

**Comment by Jrohy** [comment]
要让PYTHONPATH=/usr/local/multi-v2ray 环境变量生效

**Comment by choicky** [comment]
> 
> 
> 要让PYTHONPATH=/usr/local/multi-v2ray 环境变量生效
> `echo $PYTHONPATH`看下有没返回

我之前已经 `source ~/.bashrc` 了。`echo $PYTHONPATH` 输出如下：
```
:/usr/local/multi-v2ray:/usr/local/multi-v2ray

```

但目前依然遭遇 `ModuleNotFoundError: No module named 'read_json'`

**Comment by Jrohy** [comment]
下班后我测试下vultr的ubuntu18.04

**Comment by Jrohy** [comment]
我用paris的ubuntu18.04测试了没问题，你可以重装测试下

**Comment by choicky** [comment]
@Jrohy 好奇怪，我在 paris 新开了个 vps，依然遭遇一样的问题。我重新 seattle 的vps的系统，依然遭遇一样的问题。我的过程如下：

1. 创建 ubuntu 用户，将其加到 sudo 

2. 安装multi-v2ray （命令有点差异）

使用 sudo 运行官网的安装命令 `source <(curl -sL https://git.io/fNgqx)` 会出错，提示 `sudo: source: command not found
`，因此，我是运行如下的命令安装的：
```
curl -sL https://git.io/fNgqx |sudo bash
```

安装过程是顺利的

3. 安装之后，使用 `sudo v2ray` 编辑用户的 UUDI 等就会重现我说的问题。

**Comment by choicky** [comment]
update 一下。使用 root 用户安装是正常的。就是使用 sudo 组的用户安装会遭遇此问题。

ubuntu 习惯上推荐使用 非root 用户 登录 ssh、运行命令。

**Comment by Jrohy** [comment]
不是root用户来运行没怎么试过，有空会试下

**Comment by choicky** [comment]
```
adduser ubuntu
usermod -aG sudo ubuntu
```

然后用 ubuntu ssh 登录 就能重现该问题

**Comment by Jrohy** [comment]
你还是用root用户安装吧，没时间测试非root用户的，最近代码都在重构
