### ISSUE TITLE
为啥我的服务器用不了提示这个呢

### ISSUE THREAD

**Issue by cwv587** [Jrohy/multi-v2ray#450]
安装中文版..

new install

Loaded plugins: fastestmirror, langpacks
Determining fastest mirrors
Package crontabs-1.11-6.20121102git.el7.noarch already installed and latest version
Package 1:bash-completion-2.1-8.el7.noarch already installed and latest version
Package which-2.20-7.el7.x86_64 already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package socat.x86_64 0:1.7.3.2-2.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

====================================================================================================== Package               Arch                   Version                        Repository          Size
======================================================================================================Installing:
 socat                 x86_64                 1.7.3.2-2.el7                  os                 290 k

Transaction Summary
======================================================================================================Install  1 Package

Total download size: 290 k
Installed size: 1.1 M
Downloading packages:
socat-1.7.3.2-2.el7.x86_64.rpm                                                 | 290 kB  00:00:00     Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : socat-1.7.3.2-2.el7.x86_64                                                         1/1   Verifying  : socat-1.7.3.2-2.el7.x86_64                                                         1/1 
Installed:
  socat.x86_64 0:1.7.3.2-2.el7                                                                        
Complete!
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
Package wget-1.14-18.el7_6.1.x86_64 already installed and latest version
Nothing to do

这是咋回事儿，卡在这不动了。

**Comment by cwv587** [comment]
一直提示这个
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
Package socat-1.7.3.2-2.el7.x86_64 already installed and latest version
Package crontabs-1.11-6.20121102git.el7.noarch already installed and latest version
Package 1:bash-completion-2.1-8.el7.noarch already installed and latest version
Package which-2.20-7.el7.x86_64 already installed and latest version
Nothing to do
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
Package wget-1.14-18.el7_6.1.x86_64 already installed and latest version
Nothing to do

**Comment by Jrohy** [comment]
什么vps商，什么系统

**Comment by cwv587** [comment]
> 什么vps商，什么系统

腾讯云的   centos7

**Comment by Jrohy** [comment]
国内vps不好连国外资源吧，比如github的资源就不好下来， 而且还可能会有运行fq软件的警告
