### ISSUE TITLE
xray的配置信息在哪里看的？

### ISSUE THREAD

**Issue by fscarmen** [Jrohy/multi-v2ray#453]
wget https://github.com/XTLS/Xray-core/releases/download/v1.1.4/Xray-linux-64.zip，下载到本地之后安装
bash <(curl -L -s https://multi.netlify.app/go.sh) -l Xray-linux-64.zip -x，按xray-1-1启动服务
然后选4.查看配置，显示“Tip: 同一Group的节点传输方式,端口配置,TLS等设置相同”
cat /etc/xray/config.json 看到的内容也不知道如何弄入Qv2ray

**Comment by Jrohy** [comment]
你可以xray new重新生成配置

**Comment by fscarmen** [comment]
生成配置了，以下两个地方有疑问
TLS: 关闭，这个在qv2ray的tls下面的安全类型选“None”吗？请问xray不是应该选xtls吗？
Network: kcp dtls，这里的dtls是指协议设置里的请求头选“dtls”吗？

**Comment by Jrohy** [comment]
嗯
