### ISSUE TITLE
这个工具直接生成的客户端config.json导入到qv2ray好像直接全局代理了啊？

### ISSUE THREAD

**Issue by takfate** [Jrohy/multi-v2ray#456]
这个工具直接生成的客户端config.json导入到qv2ray好像直接全局代理了啊？
需要怎么改动吗

**Comment by takfate** [comment]
是因为没有inbound吗

**Comment by Jrohy** [comment]
设置里有得改吧，如果有分享字符串也可以字符串导入都行

**Comment by takfate** [comment]
不对啊，很奇怪的，导入了就是全局，怎么改都是全局

**Comment by takfate** [comment]
我第一次改用vless，是设置的姿势不对吗。

**Comment by Jrohy** [comment]
应该是配置文件全局设置，你可以不用配置文件导入，直接拷贝配置导入

**Comment by Jrohy** [comment]
目前vless还不支持分享链接

**Comment by takfate** [comment]
我好像理解了，qv2ray导入这个文件直接识别为`复杂配置`。所以路由策略需要自己定义。

**Comment by takfate** [comment]
已经完全解决了，自己定义可以实现，用qv2ra文档里的方案就行了。
感觉vless还没完全完善好，等正式版发布吧。
发布后，等GUI都全面支持，差不多才好用。
