### ISSUE TITLE
xray的流控设置如何更改

### ISSUE THREAD

**Issue by yasuis** [Jrohy/multi-v2ray#457]
设置选项中未找到splice的流控更改设置

**Comment by Jrohy** [comment]
splice怎么改， https://github.com/XTLS/Xray-examples 这个例子仓库也没看到这个配置

**Comment by Jrohy** [comment]
![image](https://user-images.githubusercontent.com/12463263/103250521-34ddfd00-49af-11eb-9897-812461cad829.png)
我看只有客户端填splice而已，服务端还是direct
