### ISSUE TITLE
No package python34 available

### ISSUE THREAD

**Issue by two4mamba** [Jrohy/multi-v2ray#46]
No package python34 available.
Error: Nothing to do
-bash: python3: command not found
-bash: pip3: command not found

Centos7系统，安装出现上面错误，自己手动安装了python34，在更改配置的时候还是出现了错误;

**Comment by Jrohy** [comment]
什么商家的机器呢， 安装了python3
```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py
```
来安装Pip

**Comment by Jrohy** [comment]
```
yum install epel-release python34  -y
```

**Comment by two4mamba** [comment]
这个命令好像不可以安装，返回错误如下：
Package epel-release-7-11.noarch already installed and latest version
No package python34 available.
Nothing to do

**Comment by Jrohy** [comment]
可以自己编译python36都行，只要有Python3就行
