### ISSUE TITLE
有个小白问题

### ISSUE THREAD

**Issue by caissonfiv** [Jrohy/multi-v2ray#462]
v2ray打开trojan，xray同时打开xtls，两个都是占用443端口，我试了一下发现都可以使用，是什么原理呢。。。？

**Comment by Jrohy** [comment]
检查下是不是两个都是443端口，两个都是443应该有一个启动会失败的

**Comment by caissonfiv** [comment]
检查端口只有v2ray的使用了443端口，xray没有使用端口

**Comment by caissonfiv** [comment]
能同时使用当然是最好了。。就是不知道什么原理 - -

**Comment by Jrohy** [comment]
不可能同时使用同一个端口的，属于不同应用，会端口冲突

**Comment by caissonfiv** [comment]
所以就很奇怪。。。。。
