### ISSUE TITLE
创建SS协议并设置密码后，重新更改密码报错

### ISSUE THREAD

**Issue by MiKing233** [Jrohy/multi-v2ray#465]
创建了新的端口设置协议为Shadowsocks,加密协议aes-256-gcm,随后在脚本中更改密码，出现如下错误，并且密码没有被成功更改

![image](https://user-images.githubusercontent.com/26044744/105003965-48d8c400-5a6e-11eb-965f-a5b8e2ed5485.png)

**Comment by MiKing233** [comment]
补充：删除SS端口和用户都会出现如下错误，该错误导致SS一旦创建无法更改删除

**Comment by Jrohy** [comment]
改下配置文件权限试试，没权限
