### ISSUE TITLE
xray 证书申请失败

### ISSUE THREAD

**Issue by aoeg** [Jrohy/multi-v2ray#473]
试了多次，换了域名也不行
是freenom申请 cf域名和ml域名，都不行

**Comment by Jrohy** [comment]
看看报什么错

**Comment by aoeg** [comment]
[Wed Feb  3 07:11:02 UTC 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g '
[Wed Feb  3 07:11:02 UTC 2021] _ret='0'
[Wed Feb  3 07:11:02 UTC 2021] code='200'
[Wed Feb  3 07:11:02 UTC 2021] f.*****.cf:Verify error:Fetching http://f.*****.cf/.well-known/acme-challenge/wQI5btzgObmpFWY_njW-x0AlEmpaq974Q7_0dcmAIUA: Error getting validation data
[Wed Feb  3 07:11:02 UTC 2021] Debug: get token url.
[Wed Feb  3 07:11:02 UTC 2021] GET
[Wed Feb  3 07:11:02 UTC 2021] url='http://f.******.cf/.well-known/acme-challenge/wQI5btzgObmpFWY_njW-x0AlEmpaq974Q7_0dcmAIUA'
[Wed Feb  3 07:11:02 UTC 2021] timeout=1
[Wed Feb  3 07:11:02 UTC 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g  --connect-timeout 1'
[Wed Feb  3 07:11:02 UTC 2021] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 7
[Wed Feb  3 07:11:02 UTC 2021] ret='7'
[Wed Feb  3 07:11:02 UTC 2021] Skip for removelevel:
[Wed Feb  3 07:11:02 UTC 2021] pid='34533'
[Wed Feb  3 07:11:02 UTC 2021] No need to restore nginx, skip.
[Wed Feb  3 07:11:02 UTC 2021] _clearupdns
[Wed Feb  3 07:11:02 UTC 2021] dns_entries
[Wed Feb  3 07:11:02 UTC 2021] skip dns.
[Wed Feb  3 07:11:02 UTC 2021] _on_issue_err
[Wed Feb  3 07:11:02 UTC 2021] Please add '--debug' or '--log' to check more details.
[Wed Feb  3 07:11:02 UTC 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Wed Feb  3 07:11:02 UTC 2021] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/10569739613/nsErWg'
[Wed Feb  3 07:11:02 UTC 2021] payload='{}'
[Wed Feb  3 07:11:02 UTC 2021] POST
[Wed Feb  3 07:11:02 UTC 2021] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/10569739613/nsErWg'
[Wed Feb  3 07:11:02 UTC 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g '

**Comment by aoeg** [comment]
网上找了方法，关了防火墙，开放所有端口等，能够申请证书了，但是17 vless xtls安装后是用不了的，选7 mkcp可以用。
不知何故。

**Comment by Jrohy** [comment]
要xray才行，新版v2ray没有xtls了
