### ISSUE TITLE
安装出错（PIP NO INSTALL）

### ISSUE THREAD

**Issue by DesWatEer** [Jrohy/multi-v2ray#474]
![image](https://user-images.githubusercontent.com/66418381/106851396-2216c080-66f1-11eb-93f3-83c03e336aab.png)

**Comment by eicky** [comment]
pip没安装, 去安装一下这个吧

**Comment by DesWatEer** [comment]
请问一下pip是什么，在哪里能安装

**Comment by Brianliao1986** [comment]
我最近安装也是碰到了这些问题，为什么会突然这样的呢？以前一直都很顺利安装的。

**Comment by DesWatEer** [comment]
对的，我以前就没有这个问题，现在不知怎么突然就有了

**Comment by Lv-Max** [comment]
有可能机子系统太精简 没包含pip 自己安装一下就好了 不懂就去查一下吧

**Comment by DesWatEer** [comment]
问题解决了，原来pip大概是Python中的组件。我先是在自己电脑上安装了Python，没用。然后在：https://github.com/Jrohy/multi-v2ray里找到了作者大大给的Python安装链接：https://github.com/Jrohy/python3-install。

![image](https://user-images.githubusercontent.com/66418381/106929197-0a6e2500-674f-11eb-923f-faca3671b053.png)
安装这条，它应该是在服务器内安装了Python？
然后问题就解决了

**Comment by Jrohy** [comment]
pip官方安装脚本https://bootstrap.pypa.io/get-pip.py, 不支持python3.5的pip安装估计，换成安装python3-pip就行，脚本已做更新

**Comment by DesWatEer** [comment]
![image](https://user-images.githubusercontent.com/66418381/106998559-aa639700-67bf-11eb-909f-059a95a5cc85.png)
应该是用这个安装pip
