### ISSUE TITLE
安装成功但没有配置显示

### ISSUE THREAD

**Issue by DesWatEer** [Jrohy/multi-v2ray#475]
![image](https://user-images.githubusercontent.com/66418381/106933218-a26e0d80-6753-11eb-95aa-1451f8744c78.png)

**Comment by Jrohy** [comment]
什么vps商的什么系统，我测试下

**Comment by Jrohy** [comment]
python3.9是自己编译安装的么

**Comment by DesWatEer** [comment]
用的是vulter的Debian9
之前出现的是pip no install 的问题， 于是我在自己电脑上安装了python3.9，发现没用。
所以我就去安装了作者大大你给的依赖：
![image](https://user-images.githubusercontent.com/66418381/106988244-41255900-67aa-11eb-859d-95fab27fee26.png)
安装pip no install 就解决了，但是这个问题就出现了

**Comment by Jrohy** [comment]
我测了编译安装3.9也没问题，不过你不用编译安装了，因为脚本已做优化兼容python3.5安装pip了

**Comment by DesWatEer** [comment]
可是我试过上面那个不编译的，不行

**Comment by Jrohy** [comment]
现在再试下应该可以了，我也是用vultr家的来测试的

**Comment by DesWatEer** [comment]
可以了，谢谢大大
