### ISSUE TITLE
请问一下，vless默认是tls协议还是xtls

### ISSUE THREAD

**Issue by token361** [Jrohy/multi-v2ray#476]
麻烦问一下这个脚本选择vless会自动变成xtls吗，我看配置似乎还是tls啊，需要自己手动改配置吗还是有快捷指令

**Comment by Jrohy** [comment]
xtls的话用xray比较好，切换协议有，找找

**Comment by token361** [comment]
好的，找到了，但是似乎没有vless+xtls+ws的选项啊,有走cdn代理的需求，这种情况是不是只能选择vless+ws的选项

**Comment by Jrohy** [comment]
确实目前只有vless+ws而已

**Comment by Jrohy** [comment]
@token361 试了下直接单个inbound里包含vless + xtls + ws时没法启动，貌似不支持, 只能fallback里跳到ws，但这样复杂度就很高了。
