### ISSUE TITLE
将config.json改为对应ws+tls+nginx的传输方式之后，脚本报错

### ISSUE THREAD

**Issue by rhotov** [Jrohy/multi-v2ray#48]
手动将config.json改为以下内容后，脚本报错

config.json
`    "streamSettings": {
      "network": "ws",
      "wsSettings": {
      "path": "/ray"
      }
    }`

上述改动删除了默认的host部分，以对应ws+tls+nginx的传输方式（tls由nginx而非v2ray管理，客户端config.json中服务器名称填自己申请的域名，端口填443而非自定义的那个监听端口，并且开启tls，使用cloudflare cdn中转）

重启服务后，功能是没问题的，也实现了ws+tls+nginx的传输方式，就是每次运行v2ray管理脚本的时候按查看配置就会报错并且无法输出vmess链接：

Traceback (most recent call last):
  File "/usr/local/multi-v2ray/server_info.py", line 3, in <module>
    import read_json
  File "/usr/local/multi-v2ray/read_json.py", line 133, in <module>
    config = json.load(json_file)
  File "/usr/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name enclosed in double quotes: line 72 column 1 (char 1255)

**Comment by Jrohy** [comment]
加载json文件都报错, 检查下修改后的json文件, 尽量不要手动修改, ws path也不要写死， 脚本生成的随机path, nginx也是可以加载的

**Comment by rhotov** [comment]
明白了，我恢复备份再试试看。

**Comment by leviacn** [comment]
我也是准备用这个multi-v2ray 和 WordPress构建一个 ws+tls+nginx的传输方式，使用cloudflare cdn中转，你最后成功没有？

**Comment by ke1079556** [comment]
> 我也是准备用这个multi-v2ray 和 WordPress构建一个 ws+tls+nginx的传输方式，使用cloudflare cdn中转，你最后成功没有？

成功了，改写nginx配置文件就行

**Comment by leviacn** [comment]
可以把改的配置文件放上来参考下吗？完全不用改服务端的config.json是吧？

ke1079556 <notifications@github.com> 于2020年2月21日周五 下午4:08写道：
