### ISSUE TITLE
域名检测错误!!

### ISSUE THREAD

**Issue by firstwaterer** [Jrohy/multi-v2ray#481]
![IMG_20210219_174319](https://user-images.githubusercontent.com/75522951/108487250-03f8b500-72da-11eb-86b6-c58d76a2ccb4.jpg)

freenom使用的nameserver是cloudflare的
Cloudflare这边https关闭
ssl设置选择灵活

dns添加了ipv6 AAAA记录
proxerer.ga
和
www.proxerer.ga

求助😮

**Comment by firstwaterer** [comment]
ping得通的

**Comment by Jrohy** [comment]
在vps上ping www.proxerer.ga看看，我这边就ping不通了。。

**Comment by XiuSe** [comment]
我这边也出现了这样的问题 VPS上能PING通

**Comment by bici-zhuguangzu** [comment]
仅ipv6环境如果已经配置dns64+nat64会导致访问请求本地IP使用IPV4访问url
最简单方法：
/usr/local/lib/python3.6/site-packages/v2ray_util/util_core
get_ip函数两个域名对调一下就可以了
