### ISSUE TITLE
能支持vless+ws+tls吗?

### ISSUE THREAD

**Issue by jidanyunmian** [Jrohy/multi-v2ray#484]
打算套cdn用,但是发现脚本不支持vless+ws+tls协议,要不是就只有ws的,要不就只有tls的,能支持吗

**Comment by Jrohy** [comment]
vless_ws 模式就支持的， 默认就是开启tls, 只是xtls就不行(测试过无法启动)

**Comment by l3617** [comment]
> vless_ws 模式就支持的， 默认就是开启tls, 只是xtls就不行(测试过无法启动)

v2ray和xray新核心支持grpc协议了，现在脚本支持吗

**Comment by Jrohy** [comment]
@l3617 不支持

**Comment by twcoin** [comment]
脚本不支持可以自己写配置文件搞定

**Comment by Jrohy** [comment]
@l3617 grpc新版以支持
