### ISSUE TITLE
出现奇怪的问题 cpu使用率100%

### ISSUE THREAD

**Issue by cheneyxx** [Jrohy/multi-v2ray#485]
![image](https://user-images.githubusercontent.com/10344793/110323237-4f87be80-804f-11eb-9397-73956ffa1ff4.png)
![image](https://user-images.githubusercontent.com/10344793/110323275-5b738080-804f-11eb-9a7c-6ef84f45fc3f.png)

重启vps无效 使用的是trojan 探针显示cpu使用率100% 但是没什么流量 我就去看了下 v2ray日志信息一直显示这个 重启服务后好了 但是过段时间又会这样 不知道是什么情况

**Comment by Jrohy** [comment]
可以贴上配置向v2官方那里反馈下
