### ISSUE TITLE
开启Vmess+WebSocket+TLS+CDN模式后组变化

### ISSUE THREAD

**Issue by DesWatEer** [Jrohy/multi-v2ray#489]
我在cloudflare上解析了VPS后依次走ws，TLS。这时已经有一个普通端口的组了
最后开启CDN，输入和先前一样的域名后走443端口后又会自动生成一个443端口的组

我想问问这两个组是  都是走的CDN  还是只有一个443端口走的CDN？

如果都是,我删掉一个组可以吗？
如果不是,我删掉不走CDN的组可以吗

还是说443端口的组其实并没有成功开启ws,tls,应该先开CDN再来开ws,tls?
如果有几个组，可以单独为一个组开启CDN吗？

**Comment by Jrohy** [comment]
开cdn其实就是开ws + tls，只是只有固定端口能开，你看下是否有两个443端口的组，如果存在可能启动不了

**Comment by DesWatEer** [comment]
> 开cdn其实就是开ws + tls，只是只有固定端口能开，你看下是否有两个443端口的组，如果存在可能启动不了

那是否意味着我开启CDN后就不需要走ws和tls？

**Comment by Jrohy** [comment]
cdn 就是走 ws + tls的

**Comment by Jrohy** [comment]
有没有开启都有得写的，开了ws + tls的组只要符合cf的端口都可以走cdn的，只是cdn选项一部到位了

**Comment by DesWatEer** [comment]
谢谢了大大，现在在用ws+tls，等哪天被墙了就来试试CDN
