### ISSUE TITLE
不能同时使用MTProto与v2ray吗

### ISSUE THREAD

**Issue by share18x** [Jrohy/multi-v2ray#49]

**Comment by Jrohy** [comment]
可以的，支持多种传输协议一起，你可以新建端口再切换，或者v2ray add 命令行来直接新建常用协议

**Comment by Jrohy** [comment]
另外Mtproto安卓端用telegram x可能用不了，换成原版的telegram或者桌面端就能用

**Comment by share18x** [comment]
v2ray怎么监听ipv6,我用ipv6连上去，就是上不了网

**Comment by Jrohy** [comment]
ipv6, 没研究过了

**Comment by share18x** [comment]
感谢回答

**Comment by taipei007** [comment]
大佬，你开发web了？能前后端对接的？这么强？

**Comment by taipei007** [comment]
我可是大佬的忠实小迷弟

**Comment by Jrohy** [comment]
@tracyone 可以的，只不过上班忙开发比较慢

**Comment by Jrohy** [comment]
后面会发出纯web项目，加上本项目来组合，即multi-v2ray支持命令和web操控，所以才需代码重构

**Comment by tracyone** [comment]
艾特错人了。

**Comment by Jrohy** [comment]
哈哈抱歉，手机@人比较难点准😂

**Comment by tracyone** [comment]
我也是菜鸟。。。
