### ISSUE TITLE
连接不上

### ISSUE THREAD

**Issue by fuchengxin** [Jrohy/multi-v2ray#496]
大佬，一键脚本安装之后仍然访问不了，加速器也安装了，ping ip没问题，防火墙也关闭了，手机电脑都连不上，小弟小白，请问怎么排查问题？

**Comment by Jrohy** [comment]
vmess协议吗，可以试试vless协议的

**Comment by fuchengxin** [comment]
换成vless 可以访问了  感谢大佬 vmess是因为需要域名吗？

**Comment by Jrohy** [comment]
难道是墙加强封锁的原因? 我有空测测vmess

**Comment by Jrohy** [comment]
> 换成vless 可以访问了 感谢大佬 vmess是因为需要域名吗？

不需要域名都是可以的

**Comment by fuchengxin** [comment]
感觉大佬，那个bbr plus 加速可能有问题，我试了2波，一装ip就被墙了 目前用的bbr 魔改加速管理

**Comment by Jrohy** [comment]
试了下用vultr的来测，首次安装搭建的vmess能翻

**Comment by fuchengxin** [comment]
我用的oracle cloud试验的，但是现在有个问题，好像安卓应用没有支持vless协议的 几乎都是 shadowsocks sockes与vmess

**Comment by Jrohy** [comment]
v2rayNG应该可以吧

**Comment by Jrohy** [comment]
https://github.com/2dust/v2rayNG/releases

**Comment by fuchengxin** [comment]
我用的就是v2rayNG,里面没有看到配置vless的

**Comment by Jrohy** [comment]
![image](https://user-images.githubusercontent.com/12463263/113975388-030fe880-9872-11eb-9fd2-980b1cdac48c.png)
我看是有的，找找
