### ISSUE TITLE
Err when input v2ray in xshell(Debian 8 x86_64)

### ISSUE THREAD

**Issue by FuxkGFW4ever** [Jrohy/multi-v2ray#50]
The script told me that input "v2ray"  to mange the v2ray service, but when I did so following err message print out, it said "-bash: /usr/local/sbin/v2ray: No such file or directory". So some tips? Thanks!
<img width="314" alt="multi-v2ray err" src="https://user-images.githubusercontent.com/44162803/46947465-7d01f500-d0ad-11e8-9b13-bd4cbb532aa7.png">

**Comment by Jrohy** [comment]
@FuxkGFW4ever add env path :/usr/local/bin to os environment

**Comment by FuxkGFW4ever** [comment]
> 加入环境变量
昨天我好像在前边加入了路径什么的试了一次成功之后，现在直接输入“v2ray”就可以进入管理界面了。

**Comment by FuxkGFW4ever** [comment]
> @FuxkGFW4ever add env path :/usr/local/bin to os environment

It's ok now, but I can't remember what exactly I've done yesterday to make it work.
