### ISSUE TITLE
关于 别名(remarks) 这一项的设置问题

### ISSUE THREAD

**Issue by gcphym** [Jrohy/multi-v2ray#507]
作者你好 用脚本添加用户之后 生成的分享连接添加进v2rayn之后 别名(remarks) 这一项是空的 可不可以在添加用户时加一个设定别名的功能 这样更方便一点

**Comment by Radium-bit** [comment]
请问你用的是Trojan吗？Trojan没有别名在V2RayNG里甚至不可导入。#581
