### ISSUE TITLE
添加用户时”email“这一项的设置问题

### ISSUE THREAD

**Issue by gcphym** [Jrohy/multi-v2ray#508]
使用脚本添加用户时 如果不输入邮箱 而是随便写 会提示```不是合格的email格式，请重新输入"```可是似乎```”email“```这一项不是```xxx@xxx.com```这样的邮箱地址 也不影响xray的正常工作 比如```"email:a"```  ```"email:b"```  这样也都可以 建议作者可以取消这个限制

**Comment by Jrohy** [comment]
确实可以工作，但为了符合email这个字段还是有这个限制，你可以直接回车的，不用手动输入，直接回车即可使用随机生成的邮箱
