### ISSUE TITLE
xray vless + xtls 自定证书路径xray无法启动

### ISSUE THREAD

**Issue by OniquaJliu** [Jrohy/multi-v2ray#509]
vless + xtls 选择自定证书路径后xray无法启动
这是xray自动生成的配置文件， 确保文件路径有效
{
  "log": {
    "access": "/var/log/xray/access.log",
    "error": "/var/log/xray/error.log",
    "loglevel": "info"
  },
  "inbounds": [
    {
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "58d3bd7a-b3c8-11eb-b7a8-066d93aa2ee7",
            "flow": "xtls-rprx-direct"
          },
          {
            "id": "6fa9a6cc-b3c8-11eb-b7a8-066d93aa2ee7",
            "email": "xzIJ38Wf@163.com",
            "flow": "xtls-rprx-direct"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": 80
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "tcpSettings": {},
        "kcpSettings": {},
        "wsSettings": {},
        "httpSettings": {},
        "quicSettings": {},
        "grpcSettings": {},
        "xtlsSettings": {
          "certificates": [
            {
              "certificateFile": "/home/caddy/.local/share/caddy/certificates/acme.zerossl.com-v2-dv90/mydomain/mydomain.crt",
              "keyFile": "/home/caddy/.local/share/caddy/certificates/acme.zerossl.com-v2-dv90/mydomain/mydomain.key"
            }
          ],
          "alpn": [
            "http/1.1"
          ]
        }
      },
      "domain": "mydomain"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "ip": [
          "0.0.0.0/8",
          "10.0.0.0/8",
          "100.64.0.0/10",
          "169.254.0.0/16",
          "172.16.0.0/12",
          "192.0.0.0/24",
          "192.0.2.0/24",
          "192.168.0.0/16",
          "198.18.0.0/15",
          "198.51.100.0/24",
          "203.0.113.0/24",
          "::1/128",
          "fc00::/7",
          "fe80::/10"
        ],
        "outboundTag": "blocked"
      }
    ]
  }
}

**Comment by Jrohy** [comment]
看下日志报什么错

**Comment by OniquaJliu** [comment]
> 看下日志报什么错

2021/05/13 09:19:04 [Info] transport/internet/udp: listening UDP on 0.0.0.0:57344
2021/05/13 09:19:04 [Info] transport/internet/kcp: listening on 0.0.0.0:57344
2021/05/13 09:19:04 [Warning] core: Xray 1.4.2 started
2021/05/13 09:20:22 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:443
2021/05/13 09:20:22 [Warning] core: Xray 1.4.2 started

改完传输方式就不能启动了

**Comment by OniquaJliu** [comment]
> 看下日志报什么错

不知道这个日志有用吗


May 13 09:20:44 ip-172-26-12-214 systemd[1]: xray.service: Main process exited, code=exited, status=23/n/a
May 13 09:20:44 ip-172-26-12-214 systemd[1]: xray.service: Failed with result 'exit-code'.
May 13 09:20:45 ip-172-26-12-214 systemd[1]: xray.service: Service RestartSec=100ms expired, scheduling restart.
May 13 09:20:45 ip-172-26-12-214 systemd[1]: xray.service: Scheduled restart job, restart counter is at 5.
May 13 09:20:45 ip-172-26-12-214 systemd[1]: Stopped Xray Service.
May 13 09:20:45 ip-172-26-12-214 systemd[1]: xray.service: Start request repeated too quickly.
May 13 09:20:45 ip-172-26-12-214 systemd[1]: xray.service: Failed with result 'exit-code'.
May 13 09:20:45 ip-172-26-12-214 systemd[1]: Failed to start Xray Service.

**Comment by Jrohy** [comment]
看不出什么问题

**Comment by OniquaJliu** [comment]
> 看不出什么问题

有没有可能是权限问题啥的 xray没法读ssl证书？
