### ISSUE TITLE
希望能添加VMess+TCP+TLS

### ISSUE THREAD

**Issue by PC426** [Jrohy/multi-v2ray#512]
看了一下貌似没这个传输配置，希望作者大大能添加，裸ws和tcp太容易被墙，tcp（tls）、ws（tls）、http（tls）这3个貌似比较坚挺

**Comment by Jrohy** [comment]
你开启vmess后再选择开启tls就有了

**Comment by Jrohy** [comment]
开启关闭 tls是单独一项功能的

**Comment by PC426** [comment]
谢谢回复，玩法真多啊，是我忽略了
