### ISSUE TITLE
VMESS 协议现在不支持了？

### ISSUE THREAD

**Issue by DingXiangYuanZhiXing** [Jrohy/multi-v2ray#518]
我更新最新版本以后，发现没有支持VMESS协议的选项了。
![image](https://user-images.githubusercontent.com/28868457/123577286-1fcf1300-d806-11eb-9d7e-e4083696f2d4.png)

**Comment by Jrohy** [comment]
mkcp那些就是VMESS

**Comment by DingXiangYuanZhiXing** [comment]
是 4-9 那些，还是15-20那些呀？我不怎么懂。

**Comment by Jrohy** [comment]
有vless开头的肯定就是vless了, 除了socks5, trojan, http, ss, mtproto外其他都是vmess

**Comment by DingXiangYuanZhiXing** [comment]
以前有 VMESS + WS + TLS 的这种模式。现在好像这个mKCP IP 都是直接暴露的，感觉有点不安全啊。

**Comment by Jrohy** [comment]
没改过这一块，是不是记错脚本了，你可以选3 后再去手动开启tls的，有选项开启和关闭tls
