### ISSUE TITLE
如何编辑去广告

### ISSUE THREAD

**Issue by kkkbook** [Jrohy/multi-v2ray#52]
经常分享节点给人使用，但是不希望他们用测速，该如何添加进去？

**Comment by Jrohy** [comment]
![image](https://user-images.githubusercontent.com/12463263/47068531-169ce400-d21f-11e8-8d89-e031f5e4ecf5.png)
8

**Comment by kkkbook** [comment]
😂，不是这个意思；假如想屏蔽www.baidu.com，怎么添加进去？

**Comment by Jrohy** [comment]
沒這功能，要自己配置文件

**Comment by kkkbook** [comment]
在哪个文件里配置，我自己添加

**Comment by Jrohy** [comment]
改v2ray的配置文件, 参考 https://v2ray.com/chapter_02/protocols/blackhole.html blackhole协议
