### ISSUE TITLE
证书失效如何更新(已解决）

### ISSUE THREAD

**Issue by zolopp** [Jrohy/multi-v2ray#521]
大家好，目前用客户端连接v2ray会提示
app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to
和 x509: certificate has expired or is not yet valid: current time
搜索了一下，提示说是证书或者系统时间的问题，
刚刚核对了一下本地和服务器的时间，是一致的，就只有证书的问题了。
装了太久，已经完全没有印象证书的事情了，
求证书更新方式，多谢了

**Comment by Jrohy** [comment]
`crontab -l`会有更新证书命令的，手动运行下能否更新，不能的话就调整下

**Comment by zolopp** [comment]
> `crontab -l`会有更新证书命令的，手动运行下能否更新，不能的话就调整下

感谢回复，证书已经更新了！
但是目前其它客户端登录还会报其它错，
 app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to
 > dial tcp: lookup a.tokenstore.net on 127.0.0.1:53: read udp 127.0.0.1:35463->127.0.0.1:53: i/o timeout transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://域名:8443/U71hB0gN/): > dial tcp: operation was canceled] > common/retry: all retry attempts failed

**Comment by zhicheng233** [comment]
> `crontab -l`会有更新证书命令的，手动运行下能否更新，不能的话就调整下
没有咋办？qwq
