### ISSUE TITLE
修改端口的VLESS_XTLS在PC端能用，ios端shadowrocket无法正常fq，怎么回事？已经是最新版shadowrocket

### ISSUE THREAD

**Issue by Alyle-L** [Jrohy/multi-v2ray#522]

**Comment by Jrohy** [comment]
同样用的最新版shadworocket，没发现这个问题，检查下配置对不对，v2rayN的vless分享连接是可以复制到shadowrocket里面添加的

**Comment by Jrohy** [comment]
配置对的话试下和pc同一网络试试

**Comment by Alyle-L** [comment]
> 同样用的最新版shadworocket，没发现这个问题，检查下配置对不对，v2rayN的vless分享连接是可以复制到shadowrocket里面添加的

我就是直接复制vless链接到shadowrocket的，创建VLESS_XTLS链接后改了端口，因443端口在7.1被封了（之前用trojan）

**Comment by Alyle-L** [comment]
其他协议的都正常，就xtls协议的在手机端不行

**Comment by Jrohy** [comment]
试了和pc同一网络下来翻吗

**Comment by Alyle-L** [comment]
> 试了和pc同一网络下来翻吗

一直都处于同一WIFI下

**Comment by Jrohy** [comment]
流控是xtls-rprx-direct的方式吗，这种我就试没问题

**Comment by Alyle-L** [comment]
是的

**Comment by Alyle-L** [comment]
我可你提交vless链接给你，但是不好在这里发......

**Comment by Alyle-L** [comment]
流控是xtls-rprx-direct的方式

**Comment by Jrohy** [comment]
可以建多不一样的端口来测试下

**Comment by Alyle-L** [comment]
> 可以建多不一样的端口来测试下

这个试过多次了，我都开始怀疑是不是shadowrocket问题了......
毕竟pc这端是没问题的

**Comment by Alyle-L** [comment]
对了，有一个设置没说，我所有链接用"-"符号启用多个端口的，当然VLESS_XTLS这种链接也创建了好多个

**Comment by Alyle-L** [comment]
Group: D
IP: xtls.******.top
Port: 16560-16564
TLS: xtls 开启, flow: xtls-rprx-direct
ID: ***************
Encryption: none
Network: tcp

vless://********@xtls.*******.top:16560?encryption=none&security=xtls&flow=xtls-rprx-direct&type=tcp

Tip: 同一Group的节点传输方式,端口配置,TLS等设置相同

**Comment by Jrohy** [comment]
建一个单端口的试试呗，多个端口的确实没测过

**Comment by Alyle-L** [comment]
手机还是不行，pc可以

**Comment by orrzz** [comment]
想体验vless+xtls下，可惜遇到同样问题，Group A:SS 没问题，GroupB：Vless+xlts死活上不去 （加了域名）求指点

**Comment by shijiezhou1** [comment]
Encounter same problem vless can use in macbook, and the shadowrocket cannot connect to the internet.

**Comment by bby0** [comment]
近期出现了同样的问题

**Comment by Alyle-L** [comment]
> 最近出现了同样的问题

![image](https://user-images.githubusercontent.com/47237633/189084047-6bbcc68c-f338-43a3-8c17-46e47a2de203.png)

**Comment by Alyle-L** [comment]
结束

**Comment by duxiangfei** [comment]
用小火箭设置 vless时，参数比v2rayN 参数少一些，是不是因为有些参数无法设置，导致vless 无法连接
