### ISSUE TITLE
docker镜像是否有望支持arm架构宿主机

### ISSUE THREAD

**Issue by leo-je** [Jrohy/multi-v2ray#523]
docker镜像是否有望支持arm架构宿主机

**Comment by Jrohy** [comment]
先自行编译镜像吧，参考项目里面的dockerfile来编译，只是FROM 基础镜像里面改成FROM arm64v8/centos就好

**Comment by Jrohy** [comment]
还有FROM alpine:latest 改成FROM arm64v8/alpine:latest

**Comment by leo-je** [comment]
好的
