### ISSUE TITLE
内置的SS版本是多少，手机+PC端没问题，梅林上死活连不上

### ISSUE THREAD

**Issue by orrzz** [Jrohy/multi-v2ray#525]
服务器：轻量云

布置了v2ray+SS+【UDPSpeeder+UDP2raw，用于主机加速】

现象：

手机v2rayNG，使用内置SS没问题，PC端V2rayN也没问题，路由器端梅林内置科学插件连不上，内置版本如下所示：

`shadowsocks-libev 3.1.0
maintained by Max Lv<max.c.1v@gmail.com>and Linus Yang<1aokongzi@gmail.com>
usage: ss-server`
`
shadowsocks-libev 3.3.5

  maintained by Max Lv <max.c.lv@gmail.com> and Linus Yang <laokongzi@gmail.com>

  usage:    ss-redir`

求教：内置的SS版本号多少，用什么命令查看，如何升级或降级？

**Comment by orrzz** [comment]
服务器端错误提示：
`2021/07/31 18:17:11 1.1.1.1    37781 rejected proxy/shadowsocks:failed to read address>cipher:message authentication failed
2021/87/31 18:17:17 1.1.1.1 :47398 rejected proxy/shadowsocks:failed to read address>cipher:message authentication failed`

**Comment by Jrohy** [comment]
只是xray/v2ray支持ss协议

**Comment by orrzz** [comment]
目前只能DD了系统，重新安装了秋水的脚本，感谢J大的解答

**Comment by orrzz** [comment]
重新DD了系统，已成功，感谢大佬的解答
