### ISSUE TITLE
Docker版xray定时升级脚本，执行后是安装的v2ray，望修正。

### ISSUE THREAD

**Issue by huxc573** [Jrohy/multi-v2ray#530]
如题目，执行后直接更新的v2ray服务，同事会导致xray的服务无法连接，需要重启。
![Snipaste_2021-08-31_17-33-25](https://user-images.githubusercontent.com/29273553/131479619-3938ae0c-dbab-4221-927c-43574c5258b9.png)

**Comment by Jrohy** [comment]
新版已修复，更新下
