### ISSUE TITLE
更新v2ray有bug???

### ISSUE THREAD

**Issue by Potterli20** [Jrohy/multi-v2ray#531]
欢迎使用 v2ray 管理程序

1.服务管理              2.用户管理

3.更改配置              4.查看配置

5.全局功能              6.更新V2ray

7.生成客户端配置文件         

请选择: 5

1.流量统计(v2ray)
2.流量统计(iptables)
3.禁止bittorrent
4.定时更新V2ray
5.清理v2ray日志
6.Switch to English

请选择: 4
当前定时更新任务状态: 关闭

1.开启定时更新任务

2.关闭定时更新任务

Tip: 开启定时更新v2ray的更新时间为每天北京时间3:00更新
请选择: 1
Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/main.py", line 257, in menu
    global_setting()
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/main.py", line 221, in global_setting
    update_timer.manage()
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/global_setting/update_timer.py", line 64, in manage
    planUpdate()
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/global_setting/update_timer.py", line 40, in planUpdate
    restartCron()
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/global_setting/update_timer.py", line 13, in restartCron
    IS_CENTOS = True if "centos" in platform.linux_distribution()[0].lower() else False
AttributeError: module 'platform' has no attribute 'linux_distribution'

**Comment by Potterli20** [comment]
欢迎使用 v2ray 管理程序

1.服务管理              2.用户管理

3.更改配置              4.查看配置

5.全局功能              6.更新V2ray

7.生成客户端配置文件         

请选择: 5

1.流量统计(v2ray)
2.流量统计(iptables)
3.禁止bittorrent
4.定时更新V2ray
5.清理v2ray日志
6.Switch to English

请选择: 4
当前定时更新任务状态: 开启

1.开启定时更新任务

2.关闭定时更新任务

Tip: 开启定时更新v2ray的更新时间为每天北京时间3:00更新
请选择: 2
成功关闭定时更新任务
Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/main.py", line 257, in menu
    global_setting()
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/main.py", line 221, in global_setting
    update_timer.manage()
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/global_setting/update_timer.py", line 68, in manage
    restartCron()
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/global_setting/update_timer.py", line 13, in restartCron
    IS_CENTOS = True if "centos" in platform.linux_distribution()[0].lower() else False
AttributeError: module 'platform' has no attribute 'linux_distribution'

**Comment by Potterli20** [comment]
更新也有问题
root@debian: v2ray update
Latest version v4.41.1 is already installed.
root@debian: v2ray update v4.42.1
Installing V2Ray v4.42.1 on x86_64
Downloading V2Ray: https://github.com/v2fly/v2ray-core/releases/download/v4.42.1/v2ray-linux-64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   626  100   626    0     0   1617      0 --:--:-- --:--:-- --:--:--  1617
100 13.5M  100 13.5M    0     0  14.7M      0 --:--:-- --:--:-- --:--:-- 14.7M
awk: not an option: -e
Shutting down V2Ray service.
Archive:  /tmp/v2ray/v2ray.zip
  inflating: /usr/bin/v2ray/v2ray    
  inflating: /usr/bin/v2ray/geoip.dat  
  inflating: /usr/bin/v2ray/geosite.dat  
  inflating: /usr/bin/v2ray/v2ctl    
Restarting V2Ray service.
V2Ray v4.42.1 is installed.

**Comment by Jrohy** [comment]
可能3.9版本py有兼容性问题，后面我测测

**Comment by Jrohy** [comment]
@Potterli20 这个我测试没问题

> 更新也有问题
> root@debian: v2ray update
> Latest version v4.41.1 is already installed.
> root@debian: v2ray update v4.42.1
> Installing V2Ray v4.42.1 on x86_64
> Downloading V2Ray: https://github.com/v2fly/v2ray-core/releases/download/v4.42.1/v2ray-linux-64.zip
> % Total % Received % Xferd Average Speed Time Time Time Current
> Dload Upload Total Spent Left Speed
> 100 626 100 626 0 0 1617 0 --:--:-- --:--:-- --:--:-- 1617
> 100 13.5M 100 13.5M 0 0 14.7M 0 --:--:-- --:--:-- --:--:-- 14.7M
> awk: not an option: -e
> Shutting down V2Ray service.
> Archive: /tmp/v2ray/v2ray.zip
> inflating: /usr/bin/v2ray/v2ray
> inflating: /usr/bin/v2ray/geoip.dat
> inflating: /usr/bin/v2ray/geosite.dat
> inflating: /usr/bin/v2ray/v2ctl
> Restarting V2Ray service.
> V2Ray v4.42.1 is installed.

**Comment by Jrohy** [comment]
确实python3.9 定时更新任务会报错

**Comment by Jrohy** [comment]
新版已修复，更新下

**Comment by Potterli20** [comment]
> 新版已修复，更新下

好了

**Comment by Potterli20** [comment]
> 新版已修复，更新下

Installing V2Ray v4.41.1 on x86_64
Downloading V2Ray: https://github.com/v2fly/v2ray-core/releases/download/v4.41.1/v2ray-linux-64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   626  100   626    0     0   9205      0 --:--:-- --:--:-- --:--:--  9205
100 17.4M  100 17.4M    0     0  24.9M      0 --:--:-- --:--:-- --:--:-- 63.9M
awk: not an option: -e
Shutting down V2Ray service.
Archive:  /tmp/v2ray/v2ray.zip
  inflating: /usr/bin/v2ray/v2ctl    
  inflating: /usr/bin/v2ray/geosite.dat  
  inflating: /usr/bin/v2ray/geoip.dat  
  inflating: /usr/bin/v2ray/v2ray    
Restarting V2Ray service.
V2Ray v4.41.1 is installed.

**Comment by Jrohy** [comment]
@Potterli20 你这是旧系统吗，awk -e用不了，最后能安装到吗

**Comment by Potterli20** [comment]
> @Potterli20 你这是旧系统吗，awk -e看起来用不了，最后能安装到吗

我是用Debian 11最后要手动更新

**Comment by Jrohy** [comment]
已添加依赖

**Comment by Jrohy** [comment]
你可以手动安装下`apt-get install gawk`就行了

**Comment by Potterli20** [comment]
> 你可以手动安装下`apt-get install gawk`就行了, 没安装前, `awk --help`都会报错

现在没有报错了，但是为什么还是v4.41.1😂

**Comment by Jrohy** [comment]
再试下更新看看`v2ray update v4.42.1`, 更新完运行`v2ray -v`

**Comment by Potterli20** [comment]
> 再试下更新看看`v2ray update v4.42.1`, 更新完运行`v2ray -v`

对哈，我就是手动更新，但是在脚本上不能，这是什么问题？

**Comment by Jrohy** [comment]
要更新最新测试版只能这么更新，要加个版本号

**Comment by Potterli20** [comment]
> 要更新最新测试版只能这么更新，要加个版本号

懂了
