### ISSUE TITLE
Centos7.9使用安装脚本安装卡住不动

### ISSUE THREAD

**Issue by JLTG2018** [Jrohy/multi-v2ray#533]
直接运行source <(curl -sL https://multi.netlify.app/v2ray.sh) --zh ，卡在了V2Ray v4.41.1 is installed.

**Comment by Jrohy** [comment]
我用vultr的centos7.9测试没问题

**Comment by JLTG2018** [comment]
找到问题了，我在Centos7.9上使用pyenv去管理python版本会导致这个问题，关闭pyenv就没问题了，感谢 @Jrohy
