### ISSUE TITLE
是否可以新增一条命令一键输出统计流量呢？

### ISSUE THREAD

**Issue by miangou** [Jrohy/multi-v2ray#542]
是否可以新增一条命令一键输出统计流量呢？

**Comment by Jrohy** [comment]
iptables流量还是v2ray/xray统计的流量

**Comment by Jrohy** [comment]
3.10.7支持一条命令查询流量，更新下

**Comment by miangou** [comment]
root@****:~# v2ray stats A
当前V2ray流量统计状态: True

1.开启流量统计

2.关闭流量统计

3.查看用户流量统计

4.查看组流量统计

5.重置流量统计

tip: 重启v2ray会重置流量统计!!!

请选择: 
root@*****:~# v2ray -v
v2ray: 4.43.0

v2ray_util: 3.10.8.1

**Comment by miangou** [comment]
仍然不行
