### ISSUE TITLE
vless+ws+tls的配置不会自动配置fallback

### ISSUE THREAD

**Issue by roxsky** [Jrohy/multi-v2ray#544]
今天设置后发现fallback没生效，去配置文件看了下发现根本就没有fallback的设置，可以添加上去吗？

**Comment by Jrohy** [comment]
fallback只能用于tcp + tls组合的
![image](https://user-images.githubusercontent.com/12463263/141403628-63c1fcf4-04a1-4c73-ace5-8feb79282fca.png)
https://www.v2fly.org/config/protocols/vless.html#fallbackobject
