### ISSUE TITLE
弱弱的问一句，有人提过可视化图形面板吗？

### ISSUE THREAD

**Issue by icloudu888** [Jrohy/multi-v2ray#55]
如题
能做成可视化的图形面板吗
网站样式的。。

**Comment by Jrohy** [comment]
后台接口很早就写好了，就差前端, 自己想练下手，之后会放出来初版项目，估计不怎样😂

**Comment by icloudu888** [comment]
不急，还有时间，酸酸乳看样子危险。。v2ray应该是未来。还是总控面板方便，管理多用户，多节点方便很多。如果需要众筹或者赞助，我愿意出一份力。

**Comment by Jrohy** [comment]
谢谢支持😊
