### ISSUE TITLE
最近上不了？ 求大神指点12

### ISSUE THREAD

**Issue by xiaoer371** [Jrohy/multi-v2ray#550]
服务器搭建一年了，最近就上不了。
但是都可以ping 通，端口也都是打开了， 不知道哪里出问题了。

64 bytes from nrt20s20-in-f14.1e100.net (172.217.175.78): icmp_seq=18 ttl=119 time=0.608 ms
64 bytes from nrt20s20-in-f14.1e100.net (172.217.175.78): icmp_seq=19 ttl=119 time=0.678 ms
64 bytes from nrt20s20-in-f14.1e100.net (172.217.175.78): icmp_seq=20 ttl=119 time=0.711 ms
64 bytes from nrt20s20-in-f14.1e100.net (172.217.175.78): icmp_seq=21 ttl=119 time=0.698 ms
64 bytes from nrt20s20-in-f14.1e100.net (172.217.175.78): icmp_seq=22 ttl=119 time=0.662 ms
64 bytes from nrt20s20-in-f14.1e100.net (172.217.175.78): icmp_seq=23 ttl=119 time=0.641 ms
64 bytes from nrt20s20-in-f14.1e100.net (172.217.175.78): icmp_seq=24 ttl=119 time=0.686 ms
64 bytes from nrt20s20-in-f14.1e100.net (172.217.175.78): icmp_seq=25 ttl=119 time=0.650 ms
^C
--- youtube-ui.l.google.com ping statistics ---
25 packets transmitted, 25 received, 0% packet loss, time 24592ms

可以连上服务器，服务器可以 ping 通。  不明白怎么就翻不了？？？

**Comment by xiaoer371** [comment]
难道是ip 被墙了，  ping 是正常的， 会一点丢包就是了。   我试一下  换几个服务器看看～

**Comment by Jrohy** [comment]
添加不同的协议试试

**Comment by xiaoer371** [comment]
> 

我这边是换协议 ，是可以了。 好像不稳定，新开的服务器，没一天就又不行，换个协议又好了。  测试中～
