### ISSUE TITLE
脚本没有chacha20-ietf-poly1305加密

### ISSUE THREAD

**Issue by gcphym** [Jrohy/multi-v2ray#558]
开发者你好 使用脚本搭建ss没有chacha20-ietf-poly1305加密 只有chacha20-poly1305 请问这两种加密方式是不是没有实质区别 只是名字不一样？

**Comment by Jrohy** [comment]
一样的，https://www.v2fly.org/config/protocols/shadowsocks.html#inboundconfigurationobject

**Comment by gcphym** [comment]
> 一样的，https://www.v2fly.org/config/protocols/shadowsocks.html

感谢
