### ISSUE TITLE
大佬，脚本能做到限制一个链接的同时在线设备限制么

### ISSUE THREAD

**Issue by vhdalao001** [Jrohy/multi-v2ray#56]
大佬，脚本能做到限制一个链接的同时在线设备限制么，比如一个链接只能让一个设备在线！

**Comment by Jrohy** [comment]
v2ray官方反应下呗，脚本本身很难限制这些的, 只是方便修改配置文件

**Comment by vhdalao001** [comment]
大佬，最近几天我发现，ws，http，http/2或者三者加tls的情况下无法使用，软件提示closed by peer，一半这种情况时端口被防火墙堵了，但是我明明放行了，把tls关了换kcp或者tcp就行了，ws不加tls也能用，但加了就连不上，其他http直接就连不上，脚本代码是最新的，在两台鸡上测试均是这个问题！是不是哪里弄错了！

**Comment by vhdalao001** [comment]
可能不一定是您脚本的问题，有可能是v2源代码的问题把，我去试试更换443端口试一下

**Comment by vhdalao001** [comment]
正在获取SSL证书，请稍等。。。
[Wed Oct 31 17:09:19 CST 2018] Standalone mode.
[Wed Oct 31 17:09:19 CST 2018] Registering account
[Wed Oct 31 17:09:20 CST 2018] Registered
[Wed Oct 31 17:09:20 CST 2018] ACCOUNT_THUMBPRINT='xMr9L_iNOTgGYAREisddfgerBXW5rbQEcK_G2I'
[Wed Oct 31 17:09:20 CST 2018] Creating domain key
[Wed Oct 31 17:09:20 CST 2018] The domain key is here: /www/server/panel/vhost/cert/domain_ecc/domain.key
[Wed Oct 31 17:09:20 CST 2018] Single domain=''
[Wed Oct 31 17:09:20 CST 2018] Getting domain auth token for each domain
[Wed Oct 31 17:09:20 CST 2018] Getting webroot for domain='domain'
[Wed Oct 31 17:09:20 CST 2018] Getting new-authz for domain='domain'
[Wed Oct 31 17:09:20 CST 2018] The new-authz request is ok.
[Wed Oct 31 17:09:20 CST 2018] Verifying:domain
[Wed Oct 31 17:09:20 CST 2018] Standalone mode server
[Wed Oct 31 17:09:24 CST 2018] Success
[Wed Oct 31 17:09:24 CST 2018] Verify finished, start to sign.
[Wed Oct 31 17:09:25 CST 2018] Cert success.

**Comment by vhdalao001** [comment]
v2rayN提示远程服务器返回错误: (500) 内部服务器错误。应该是服务没起来，不在运行

**Comment by Jrohy** [comment]
你是自定义证书路径？

**Comment by vhdalao001** [comment]
可能跟我安装的宝塔有关系？所以证书安装在这种地方？

**Comment by vhdalao001** [comment]
大佬有没有自己测试一下，有一个人跟我说过他说http/2对nginx支持不太好，他说他用caddy开启h2，我倒是不认同的，因为以前的时候我记得大佬脚本是可以正常运行的！只是最近不知道怎么回事我的小鸡开了tls或者h2就会出现服务无法运行的情况

**Comment by Jrohy** [comment]
有测但没用nginx和caddy来分流测

**Comment by taipei007** [comment]
我试过空白机器没有nginx，也不行，连不上网，服务断不在运行，centos7系统

**Comment by Jrohy** [comment]
我这边测试了h2, ws+tls都可以，端口随机

**Comment by taipei007** [comment]
乖乖，那我这啥情况，我新开一台装的centos7不行，又开了一台debian9都是update以后全新安装的，端口也是随机的，竟然都是服务无法运行，心塞！不能用二级域名么？端口随机是吧，我一会试一下

**Comment by Jrohy** [comment]
最好可以自己试下修改json看下行不行，看看墙程度

**Comment by taipei007** [comment]
服务不在运行，开了tls就炸貌似跟墙关系不大
