### ISSUE TITLE
请问可以在服务端手动更新geosite文件吗

### ISSUE THREAD

**Issue by gcphym** [Jrohy/multi-v2ray#560]
开发者你好 请问可以在服务端手动更新geosite geoip吗 没找到文件在哪

**Comment by Jrohy** [comment]
/usr/bin/xray或者/usr/bin/v2ray目录下面

**Comment by gcphym** [comment]
> /usr/bin/xray或者/usr/bin/v2ray目录下面

找到了 谢谢
