### ISSUE TITLE
无法更新v5.0.3的v2ray

### ISSUE THREAD

**Issue by Potterli20** [Jrohy/multi-v2ray#566]
无法更新v5.0.3的v2ray
https://github.com/v2fly/v2ray-core/releases/tag/v5.0.3

**Comment by waini1110** [comment]
更新只能更新release版本，pre-release 版本怎么可能更新，建议close 这个issue

**Comment by waini1110** [comment]
更新只能更新release版本，pre-release 版本怎么可能更新，建议close 这个issue

**Comment by Potterli20** [comment]
> 更新只能更新release版本，pre-release 版本怎么可能更新，建议close 这个issue

你想太多了，哈哈哈，我用手动更新 v2ray update v5.0.2

**Comment by Potterli20** [comment]
反正，这个问题，迟早问题而已

**Comment by Jrohy** [comment]
要手动指定版本更新的，默认只会更新最新release版本

**Comment by Potterli20** [comment]
> 要更新pre-release要手动指定版本更新的，默认只会更新最新release版本

这个，可能你到时候修改一下脚本了
确实有点小麻烦

**Comment by Potterli20** [comment]
> 设计就是这样，为什么作者发布的不是release而是pre-release,就是可能包含不稳定的功能，不可能默认更新就是最新pre-release 的，只有敢尝鲜的才手动更新

这个我是知道的，我也自己尝试过手动更新，但是是失败的

**Comment by Jrohy** [comment]
@Potterli20 已做优化可以更新了

**Comment by Potterli20** [comment]
> @Potterli20 已做优化可以更新了

okkk
