### ISSUE TITLE
提前给个bug

### ISSUE THREAD

**Issue by Potterli20** [Jrohy/multi-v2ray#567]
目前我使用了v2ray的v5.0.3
好像启动不了

回到4.44是正常的🌝🌝

**Comment by Jrohy** [comment]
确实启动不了，不知道是不是配置文件变动还是启动方式有变，感兴趣的自己探索下

**Comment by Potterli20** [comment]
> 确实启动不了，不知道是不是配置文件变动还是启动方式有变，目前不支持运行

很奇怪怪

**Comment by Potterli20** [comment]
> 确实启动不了，不知道是不是配置文件变动还是启动方式有变，目前不支持运行

docker 上是否可以加个apk update && apk upgrade

**Comment by Jrohy** [comment]
@Potterli20 没必要的不会随便改

**Comment by Potterli20** [comment]
> @Potterli20 没必要的不会随便改

因为默认的ca是2019的，还没有更新
怕是出问题

**Comment by Jrohy** [comment]
@Potterli20 这个镜像不是通过systemctl来管理服务的。。

**Comment by Potterli20** [comment]
> @Potterli20 这个镜像不是通过systemctl来管理服务的。。

为什么我遇到的bug那么奇怪🌝🌝

**Comment by Potterli20** [comment]
> @Potterli20 没必要的不会随便改

那个能不能加个iptables的依赖更新
我每次dd完系统都是没有iptables🌝

**Comment by xxoocn** [comment]
运行v2ray进入交互式界面，使用什么命令退出？Ctrl+C有时退不出。

**Comment by Jrohy** [comment]
@xxoocn 基本逻辑都是回车回到上一级，如果是顶级的话就是退出程序

**Comment by xxoocn** [comment]
解决了，谢谢

在 2022年3月20日，11:19，Jrohy ***@***.***> 写道：

﻿
@xxoocn 基本逻辑都是回车回到上一级，如果是顶级的话就是退出程序

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
