### ISSUE TITLE
Vmess + TCP + TLS转换后的clash链接全部超时

### ISSUE THREAD

**Issue by oscarlic** [Jrohy/multi-v2ray#573]
clash core自1.9.0以后不再向下兼容，最新Clash PC客户端已经使用新的clash core。我是通过替换老版本的clash core来解决这个问题的，请问开发者能否修复一下呢？

https://github.com/Fndroid/clash_for_windows_pkg/issues/2588

**Comment by Jrohy** [comment]
项目没有提供clash链接的。

**Comment by oscarlic** [comment]
> 项目没有提供clash链接的。

好的
