### ISSUE TITLE
telegram连接不上

### ISSUE THREAD

**Issue by shin8085** [Jrohy/multi-v2ray#574]
浏览器、google 商店等都可以正常连接，但是telegram APP一直在connecting。。。
试了网上其他的vmess节点都可以正常连接，但是就是自己搭的节点连不上telegram APP
经过测试web端的telegram是可以正常连接的应该不是ip的问题。

**Comment by dycuo** [comment]
可以分享一下最后怎样解决的吗？我也遇到了同样的问题，就是某个节点搭的代理无法脸上APP, 网页版可以
