### ISSUE TITLE
希望增加一个禁止BT的功能

### ISSUE THREAD

**Issue by luojianxhlxt** [Jrohy/multi-v2ray#58]
因为服务器禁止BT，怕有人下BT被ban。
官方好像是能做到的，要是不麻烦的话，希望能增加这个功能。

**Comment by taipei007** [comment]
瞎说 ，官方怎么做到了？v2这个审计都实现不了！

**Comment by wialny** [comment]
可能离题了, 我这里用BT的话, v2ray就会坏掉.  坏掉时本地有发送流量, 但接收不到任何v2ray的代理流量.  奇怪的是BT没走代理, 是直连的.

**Comment by luojianxhlxt** [comment]
> 瞎说 ，官方怎么做到了？v2这些审计都实现不了！

看的白话文教程，上面是这么写的
{
  "log": {
    "loglevel": "warning",
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log"
  },
  "inbound": {
    "sniffing": {
      "enabled": true,
      "destOverride": [
        "http",
        "tls"
      ]
    },
    "port": 16823,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "b831381d-6324-4d53-ad4f-8cda48b30811",
          "alterId": 64
        }
      ]
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "block"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "AsIs",
      "rules": [
        {
          "type": "field",
          "outboundTag": "block",
          "protocol": [
            "bittorrent"
          ]
        }
      ]
    }
  }
}

**Comment by rhotov** [comment]
也就是说在config.json里手动加一段"outboundDetour"就可以了。

**Comment by Jrohy** [comment]
@rhotov @luojianxhlxt 新版已支持BT的禁止和放行了， 在全局功能菜单里
