### ISSUE TITLE
增加功能建议：增加自动配置caddy域名指定与伪装功能

### ISSUE THREAD

**Issue by aiyu20181** [Jrohy/multi-v2ray#59]
大部分人对于caddy的配置都是不太明白，希望可以在脚本中集合起来，这样会把TLS传输更好的配置起来。

**Comment by Jrohy** [comment]
不会加入其他的, 只会有原生功能的v2ray

**Comment by aiyu20181** [comment]
明白了，这才是您这个**脚本的设计理念**，对此我也非常赞同。
