### ISSUE TITLE
大佬，安装出现-bash: python3: command not found怎么办？搬瓦工centos7

### ISSUE THREAD

**Issue by wang125606757** [Jrohy/multi-v2ray#60]
我是小白。。网上找了好多安装Python的方法，但是都失败了。。。想求一下帮助

Package lsof-4.87-5.el7.x86_64 already installed and latest version
Nothing to do
-bash: python3: command not found
-bash: pip3: command not found
 正在进行时间同步 
 2 Nov 21:49:12 ntpdate[18429]: adjust time server 129.6.15.28 offset 0.000114 sec
 时间同步成功 
 当前系统时间 Fri, 02 Nov 2018 21:49:12 +0800
Already on 'master'
HEAD is now at dc10216 代码重构，加入json文件缓存
Already up-to-date.
Latest version v4.0 is already installed.
-bash: python3: command not found
-bash: python3: command not found
-bash: python3: command not found
Redirecting to /bin/systemctl restart v2ray.service
multi-v2ray 安装成功！
V2ray配置信息:
-bash: python3: command not found
输入 v2ray 回车即可进行服务管理

**Comment by wang125606757** [comment]
看到好多人都问到了这个问题，我根据你的提示也检查了一下，不知道这要怎么做了。。。

[root@host ~]# yum install epel-release
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile

base: mirror.scalabledns.com
elrepo-kernel: repos.dfw.lax-noc.com
extras: mirror.hostduplex.com
ius: mirrors.kernel.org
updates: mirror.fileplanet.com
Package epel-release-7-11.noarch already installed and latest version
Nothing to do
[root@host ~]# yum install python34
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
base: mirror.scalabledns.com
elrepo-kernel: repos.dfw.lax-noc.com
extras: mirror.hostduplex.com
ius: mirrors.kernel.org
updates: mirror.fileplanet.com
No package python34 available.
Error: Nothing to do

**Comment by Jrohy** [comment]
可以试下编译安装py3
