### ISSUE TITLE
http: Accept error: accept tcp [::]:3389: accept4: too many open files; retrying in 640ms

### ISSUE THREAD

**Issue by cheneyxx** [Jrohy/multi-v2ray#603]
感觉作者的脚本应该更新了 最新xray和v2fly内核用起来有点问题 会出现用一会儿就err_connection_reset和err_connection_closed 排查了半天才发现是一键脚本的问题 之前用起来都很稳 后面换了ProxySU搭建后就没问题

**Comment by Jrohy** [comment]
是配置问题没改好配置吗

**Comment by cheneyxx** [comment]
> 是配置问题没改好配置吗

配置没问题 一直用你的脚本很久了 超过了一年 配置是v2+ws+tls
