### ISSUE TITLE
V2Ray v5.1.0 Unable to load config file for v4.

### ISSUE THREAD

**Issue by Butterflyflower** [Jrohy/multi-v2ray#607]
Hello dear developer 

 After updating V2Ray v5.1.0, it prompts v2ray restart fail !

**Comment by Jrohy** [comment]
not support v2ray v5

**Comment by AAlieZZ** [comment]
It still restart fail after executing `v2ray update 4.45.2`.

**Comment by Butterflyflower** [comment]
> 不支持 v2ray v5
Thanks Reply
