### ISSUE TITLE
centos7安装后各种报错

### ISSUE THREAD

**Issue by yjj618** [Jrohy/multi-v2ray#61]
谷歌云搬瓦工安装都报错
Extracting V2Ray package to /tmp/v2ray.
Archive:  /tmp/v2ray/v2ray.zip
  inflating: /tmp/v2ray/config.json  
   creating: /tmp/v2ray/doc/
  inflating: /tmp/v2ray/doc/readme.md  
  inflating: /tmp/v2ray/geoip.dat    
  inflating: /tmp/v2ray/geosite.dat  
   creating: /tmp/v2ray/systemd/
  inflating: /tmp/v2ray/systemd/v2ray.service  
   creating: /tmp/v2ray/systemv/
  inflating: /tmp/v2ray/systemv/v2ray  
  inflating: /tmp/v2ray/v2ctl        
 extracting: /tmp/v2ray/v2ctl.sig    
  inflating: /tmp/v2ray/v2ray        
 extracting: /tmp/v2ray/v2ray.sig    
  inflating: /tmp/v2ray/vpoint_socks_vmess.json  
  inflating: /tmp/v2ray/vpoint_vmess_freedom.json  
PORT:13805
UUID:330df825-c005-4b36-b9cf-2322d7c6b10e
Created symlink from /etc/systemd/system/multi-user.target.wants/v2ray.service to /etc/systemd/system/v2ray.service.
V2Ray v4.0 is installed.
-bash: python3: command not found
-bash: python3: command not found
-bash: python3: command not found
Redirecting to /bin/systemctl restart  v2ray.service
multi-v2ray 安装成功！
V2ray配置信息:
-bash: python3: command not found
输入 v2ray 回车即可进行服务管理

**Comment by Jrohy** [comment]
没安装到python3, 也没条件测gcp的centos7😂

**Comment by taipei007** [comment]
gcp的那个系统都可以装，先update一下不行么？最多出现的是环境变量问题
