### ISSUE TITLE
一键脚本安装每个系统都会出现这个问题！

### ISSUE THREAD

**Issue by wukongfufeijichang** [Jrohy/multi-v2ray#618]
PORT:31731
UUID:50b68d5b-4e07-4bf4-bc3b-f0e9c4cd4f36
Created symlink /etc/systemd/system/multi-user.target.wants/v2ray.service → /etc/systemd/system/v2ray.service.
V2Ray v5.1.0 is installed.
new UUID: a6e35e1e-837d-4ff8-a48f-85a9f4c4a43b
new port: 31170
random generate (srtp | wechat-video | utp | dtls | wireguard) fake header, new protocol: srtp 

restarting v2ray...
**v2ray restart fail !** （出现这个问题，每个系统我都试过了一键脚本都会出现这个问题，求解决）

multi-v2ray install success!
1.
Group: A
IP: 被我删除了
Port: 31170
TLS: 关闭
UUID: 7e34ea78-01cd-4308-a70d-251188c55da5
Alter ID: 0
Network: kcp srtp

vmess://被我删除了

Tip: 同一Group的节点传输方式,端口配置,TLS等设置相同
please input 'v2ray' command to manage v2ray

**Comment by Tonkovski** [comment]
Duplicated issue, take a look at this...
#608

**Comment by Brianliao1986** [comment]
open your eyes ,and read every issue carefully
