### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by lejitao2013** [Jrohy/multi-v2ray#619]
root@AttractiveCelebrated-VM:~# v2ray status
● v2ray.service - V2Ray Service
     Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2022-11-05 13:09:03 UTC; 21s ago
    Process: 56724 ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json (code=exited, status=2)
   Main PID: 56724 (code=exited, status=2)

Nov 05 13:09:03 AttractiveCelebrated-VM v2ray[56724]: Usage of /usr/bin/v2ray/v2ray:
Nov 05 13:09:03 AttractiveCelebrated-VM systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 05 13:09:03 AttractiveCelebrated-VM systemd[1]: v2ray.service: Failed with result 'exit-code'.
Nov 05 13:09:03 AttractiveCelebrated-VM systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
Nov 05 13:09:03 AttractiveCelebrated-VM systemd[1]: Stopped V2Ray Service.
Nov 05 13:09:03 AttractiveCelebrated-VM systemd[1]: v2ray.service: Start request repeated too quickly.
Nov 05 13:09:03 AttractiveCelebrated-VM systemd[1]: v2ray.service: Failed with result 'exit-code'.
Nov 05 13:09:03 AttractiveCelebrated-VM systemd[1]: Failed to start V2Ray Service.

**Comment by xthc** [comment]
Duplicated issue, take a look at this...
https://github.com/Jrohy/multi-v2ray/issues/608

**Comment by Mashiro10032** [comment]
#608 
[可以参考这个](https://github.com/Jrohy/multi-v2ray/issues/608#issuecomment-1240384790)
`v2ray update v4.45.2`

**Comment by XP-18** [comment]
vim /etc/systemd/system/v2ray.service
把ExecStart那一行改成下面的值
ExecStart=/usr/bin/v2ray/v2ray run -config /etc/v2ray/config.json

**Comment by Jrohy** [comment]
新版已修复
