### ISSUE TITLE
脚本增加端口超过26个后，会出错的Bug

### ISSUE THREAD

**Issue by nickeywork** [Jrohy/multi-v2ray#62]
因为某些原因增加大量端口，在使用此脚本时，当group端口号的英文字符超过“Z”，下一个Group会是“[”
这个Group会无法选择，无法删除

**Comment by Jrohy** [comment]
确实会出现此问题，超过26个端口的话，后面会改下

**Comment by Jrohy** [comment]
现在可以选择了，但因为用的是ascii码对应的字符叠增，所以最大端口也是有限
