### ISSUE TITLE
希望增加VLESS-TCP-XTLS-Vision传输方式

### ISSUE THREAD

**Issue by yasuis** [Jrohy/multi-v2ray#620]
xray已更新至1.6.3，希望大佬增加VLESS-TCP-XTLS-Vision传输方式，谢谢

**Comment by datout** [comment]
+1

**Comment by yasuis** [comment]
研究过了，可自行修改/etc/xray/config.json,修改"flow": "xtls-rprx-direct"为"xtls-rprx-vison"，然后xtls改为tls就可以了

**Comment by datout** [comment]
> 研究过了，可自行修改/etc/xray/config.json,修改"flow": "xtls-rprx-direct"为"xtls-rprx-vison"，然后xtls改为tls就可以了

谢谢大佬

**Comment by avsba001** [comment]
已经加了，可以close了
