### ISSUE TITLE
v2ray start

### ISSUE THREAD

**Issue by saypig** [Jrohy/multi-v2ray#624]
[root@VM-16-14-centos local]# v2ray start
starting v2ray...
v2ray start fail !

**Comment by xylogs** [comment]
sed -i 's/v2ray .*-config/v2ray run -config/g' /etc/systemd/system/v2ray.service

**Comment by asadace1** [comment]
> sed -i 's/v2ray .*-config/v2ray run -config/g' /etc/systemd/system/v2ray.service

It still doesn't work

**Comment by asadace1** [comment]
> v2ray update 4.45.2

yes work now. thanks
