### ISSUE TITLE
multi-v2ray 脚本自动部署

### ISSUE THREAD

**Issue by mfsznk** [Jrohy/multi-v2ray#628]
手动降级下v2ray版本后，之前可以上外网，现在不行了，是那里出问题了，

**Comment by marvel084** [comment]
v2fly v5 配置文件格式发生了改变

**Comment by zhanglei0310** [comment]
> 脚本要如何升级呢

想用新版本的，/etc/systemd/system/v2ray.service这个文件，ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json，在-config前面加个run，然后systemctl daemon-reload，然后重启v2ray就行了。因为新版修改了启动命令，启动时需要加上run

**Comment by Jrohy** [comment]
@zhanglei0310 @mfsznk 已修复可以正常升级上去使用了， 会自动修改v2ray.service, v4 升到v5或者降级到v4都行
