### ISSUE TITLE
v2ray自动更新/卸载重新安装后，执行会报各种错误

### ISSUE THREAD

**Issue by sysconfon** [Jrohy/multi-v2ray#63]
在centos7里面。安装了v2ray，当v2ray自己更新或卸载重新安装之后。打开v2ray启动服务，增加端口，查询配置等，都会报错。
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'loader'

所有的错误都是导入各种模块出了问题。该问题一直存在。导致后续无法自己再增加端口/用户等其他操作行为。

**Comment by Jrohy** [comment]
检查下环境变量关于multi-v2ray是否存在  ~/.bashrc
