### ISSUE TITLE
希望在vless_tls传输方式中加入流控xtls-rprx-vision

### ISSUE THREAD

**Issue by Moebyte** [Jrohy/multi-v2ray#636]
{
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "你的UUID",
                        "flow": "xtls-rprx-vision"
                    }
                ],
在配置文件中加入`"flow": "xtls-rprx-vision"`即可，或者新增传输方式vless_tls_vision

**Comment by Jrohy** [comment]
新版已支持
