### ISSUE TITLE
对脚本有几点建议

### ISSUE THREAD

**Issue by qiankun21** [Jrohy/multi-v2ray#644]
请问能不能带脚本弹出来的菜单里面设置一个零退出脚本的功能？就是比如说在脚本的主菜单就是0退出脚本，在子菜单就是零返回上一层。还有能否在生成链接的时候支持设置别名?然后就是能不能使用域名访问xray或者是v2ray

**Comment by yasuis** [comment]
按回车就是退出脚本；在生成链接中#后即为链接名称，自己修改#后文字即可。

**Comment by qiankun21** [comment]
谢谢
