### ISSUE TITLE
希望增加REALITY中privateKey和publicKey生成功能

### ISSUE THREAD

**Issue by yasuis** [Jrohy/multi-v2ray#645]
xray升级到1.8.0后加入对REALITY的支持，但需要privateKey和publicKey配对，原版可执行./xray x25519生成，希望大佬能加上这个功能，谢谢

**Comment by Jrohy** [comment]
新版已添加，会自动运行./xray x25519的，完全不用管privateKey和publicKey的生成

**Comment by yasuis** [comment]
谢谢大佬支持
