### ISSUE TITLE
mkcp默认的加密是128-cfb,这个好像没有修改选项~

### ISSUE THREAD

**Issue by Lrvineshaw** [Jrohy/multi-v2ray#67]
如题

**Comment by Jrohy** [comment]
server端不需要改这个的，client端修改这个server端自动适配

**Comment by Jrohy** [comment]
![image](https://user-images.githubusercontent.com/12463263/48963609-1091e400-efd1-11e8-937e-1123e7bd604e.png)

**Comment by Jrohy** [comment]
暂时只支持v2ray官方的功能
