### ISSUE TITLE
可以优化下内存吗

### ISSUE THREAD

**Issue by zerozero123** [Jrohy/multi-v2ray#68]
为了更好能够提供更好的性能，V2Ray 有一个缓存机制，在上下游网络速率有差异时会缓存一部分数据。举个实际的例子，假如你在下载小姐姐，网站到你的 VPS 的速度有 500 Mbps，而 VPS 到家里宽带只有 50 Mbps，V2Ray 在 VPS 会以比较高的速率把小姐姐先下好再慢慢传到电脑里。默认情况下 V2Ray 对每个连接的缓存大小是 10 MBytes （现在默认缓存最大为 512 KBytes），也就是说如果下载小姐姐开了 32 线程，那么 V2Ray 最高会缓存 320 MBytes 的数据。这样一来那些内存只有 256 MBytes 甚至是 128 MBytes 的 VPS 压力就会比较大。所幸的是缓存的大小我们是可以修改的，减小缓存的大小可以降低对内存的占用，会对小内存机器比较友好。
我就是128MBytes的机器，用脚本安装好之后，我感觉我的机器贼卡。能在脚本中提供一项内存优化吗？
我看了官方的内存优化解释，我尝试着解决，但是看不到 /etc/systemd/system/v2ray.service文件。所以就解决不了这个问题！！！！
参考链接：https://toutyrater.github.io/app/optimization.html#%E4%BF%AE%E6%94%B9%E7%BC%93%E5%AD%98

**Comment by Jrohy** [comment]
https://v2ray.com/chapter_02/policy.html

**Comment by zerozero123** [comment]
我试下
