### ISSUE TITLE
很好用，能否生成二维码配置

### ISSUE THREAD

**Issue by becapital** [Jrohy/multi-v2ray#70]
很好用，能否生成二维码配置。
mkcp要怎么配置才快?,
我之前用的socks5+kcp...速度要比v2ray快很多啊。。。估计是服务器mkcp配置问题吗?

**Comment by icloudu888** [comment]
借个楼。。。。
动态端口，多久刷新一次呢。。
我开启了动态端口
路由器后台半小时了，，都没有发现端口有改变。。
