### ISSUE TITLE
修改tls模式之后无法连接

### ISSUE THREAD

**Issue by UDDU13668** [Jrohy/multi-v2ray#71]
证书和域名都没有问题，运行状态如下:
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2018-11-29 09:51:40 EST; 29s ago
  Process: 8174 ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json (code=exited Main PID: 8174 (code=exited, status=23)

**Comment by Jrohy** [comment]
是自定义证书，还是脚本签发的? tls加什么组合

**Comment by UDDU13668** [comment]
脚本签发的证书，tls加上各种组合都不行
之前一直在用nginx+v2ray+tls+websocket连接方式，有一天突然就连不上了
配置过程中没有任何报错，但是查看状态是failed

**Comment by UDDU13668** [comment]
现在测试的配置是kcp utp

**Comment by UDDU13668** [comment]
ystemd[1]: Stopped V2Ray Service.
Nov 29 10:12:04 ubt.com systemd[1]: Started V2Ray Service.
Nov 29 10:12:04 ubt.com v2ray[9368]: V2Ray 4.6.0 (Po) 20181122
Nov 29 10:12:04 ubt.com v2ray[9368]: A unified platform for anti-censorship.
Nov 29 10:12:04 ubt.com v2ray[9368]: main: failed to read config file: /etc/v2ray/config.json > v2ray.com/coreNov 29 10:12:04 ubt.com v2ray[9368]:  > exit status 255
Nov 29 10:12:04 ubt.com systemd[1]: v2ray.service: Main process exited, code=exited, status=23/n/a
Nov 29 10:12:04 ubt.com systemd[1]: v2ray.service: Unit entered failed state.
Nov 29 10:12:04 ubt.com systemd[1]: v2ray.service: Failed with result 'exit-code

**Comment by UDDU13668** [comment]
可以确定不是配置文件的问题，我刚才直接完全卸载然后重新安装了v2ray，但开启了tls之后还是会failed

**Comment by UDDU13668** [comment]
配置文件:
{
  "inbounds": [
    {
      "protocol": "vmess",
      "port": 48927,
      "settings": {
        "clients": [
          {
            "alterId": 64,
            "id": "cb443cbb-f850-4b5b-afa6-caf0b1527ae5"
          }
        ]
      },
      "streamSettings": {
        "wsSettings": null,
        "kcpSettings": {
          "tti": 50,
          "header": {
            "type": "srtp",
            "request": null,
            "response": null
          },
          "uplinkCapacity": 100,
          "downlinkCapacity": 100,
          "writeBufferSize": 2,
          "readBufferSize": 2,
          "mtu": 1350,
          "congestion": false
        },
        "tcpSettings": null,
        "security": "tls",
        "network": "kcp",
        "tlsSettings": {
          "certificates": [
            {
              "certificateFile": "/root/.acme.sh/yoursmile.cf_ecc/fullchain.cer",
              "keyFile": "/root/.acme.sh/yoursmile.cf_ecc/yoursmile.cf.key"
            }
          ]
        },
        "httpSettings": null
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "info"
  },
  "routing": {
    "rules": [
      {
        "type": "field",
        "ip": [
          "0.0.0.0/8",
          "10.0.0.0/8",
          "100.64.0.0/10",
          "169.254.0.0/16",
          "172.16.0.0/12",
          "192.0.0.0/24",
          "192.0.2.0/24",
          "192.168.0.0/16",
          "198.18.0.0/15",
          "198.51.100.0/24",
          "203.0.113.0/24",
          "::1/128",
          "fc00::/7",
          "fe80::/10"
        ],
        "outboundTag": "blocked"
      }
    ]
  }
}

**Comment by Jrohy** [comment]
确实看不出来，我自己取测试了kcp+tls 或者ws+tls都没问题

**Comment by Jrohy** [comment]
可以试下233的脚本, 看下开tls情况
