### ISSUE TITLE
安装时有warning

### ISSUE THREAD

**Issue by fredzhu** [Jrohy/multi-v2ray#72]
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
Debian 9 x86上安装，报这个warning.

**Comment by Jrohy** [comment]
有没有详细点的日志，太少了😂

**Comment by Jrohy** [comment]
正常安装使用不影响吧

**Comment by fredzhu** [comment]
pc上v2rayn用了一下，没问题。（其实碰到问题了，全局模式成功，pac失败，发现管理员运行就可以了）
安卓手机上v2rayng搞不定.....连接后测试第一次成功，后面就失败了。
麻烦问下手机上应该用啥app啊？
还有服务器端tls需要开吗？建议开还是不开？
Thanks

**Comment by Jrohy** [comment]
我一般都不开，开了tls速度比较影响,我直接都是kcp😂,  要测试下对速度的影响

**Comment by fredzhu** [comment]
流量统计和每天自动重启好像不能一起用？其实可以每个用户写个文件记录流量统计吧？ 希望下个版本能支持😊 另外，流量控制应该也可以: 流量超额了自动删除该用户（备份用户信息）。



发自我的小米手机
在 Jrohy <notifications@github.com>，2018年11月30日 下午6:40写道：

我一般都不开，开了tls速度比较影响,我直接都是kcp😂, 要测试下对速度的影响

**Comment by Jrohy** [comment]
@fredzhu 我也想过用文件记录流量，但想想如果不触发查询流量这个动作，脚本根本不知道耗了多少流量，中途被重启了就啥都没了，要做到每个用户记录流量还是需要v2ray官方自己来做

**Comment by fredzhu** [comment]
哦。好，那等v2ray更新统计功能吧。
目前流量统计了之后能发email通知用户吗？比如每天向某个用户发个email提示一下之类的。

**Comment by Jrohy** [comment]
没有，这类需求很少的功能，脚本只是修改json不会做多太多操作，fq才是重点

**Comment by Jrohy** [comment]
伪装类型可以修改的，修改传输协议那里可以改， 加密方式不用配置的服务器端, 客户端配置后自动适应

**Comment by Jrohy** [comment]
有禁bt功能
