### ISSUE TITLE
QUIC的问题

### ISSUE THREAD

**Issue by SneakyTurt1e** [Jrohy/multi-v2ray#73]
当前版本是否已经添加QUIC但因V2rayN不持支但未显示？

**Comment by Jrohy** [comment]
已支持quic但v2rayN还未支持，vmess分享连接暂时无效，quic可以用生成的客户端json来跑（不用v2rayN）

**Comment by Jrohy** [comment]
@SneakyTurt1e 再`v2ray update.sh`更新下，修复了个更新bug, 之前没法更新

**Comment by SneakyTurt1e** [comment]
> @SneakyTurt1e 再`v2ray update.sh`更新下，修复了个更新bug, 之前没法更新

/usr/local/bin/v2ray: line 130: syntax error near unexpected token `;;'
/usr/local/bin/v2ray: line 130: `        ;;'

**Comment by Jrohy** [comment]
应该更新到了， 这个报错可以忽略

**Comment by SneakyTurt1e** [comment]
> 应该更新到了， 这个报错可以忽略

建议可以添加个版本号之类的 便于区分

**Comment by Jrohy** [comment]
@SneakyTurt1e  新版已加入`v2ray -v` 查看版本, 更新策略也改了, 不是用最新代码来更新，而是用最新release来更
