### ISSUE TITLE
安装了其他软件，然后v2ray报错cannot import name 'Config'

### ISSUE THREAD

**Issue by WoChen5770** [Jrohy/multi-v2ray#74]
cannot import name 'Config'

**Comment by WoChen5770** [comment]
Redirecting to /bin/systemctl restart v2ray.service
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/multi-v2ray/utils.py", line 173, in open_port
    from loader import Loader
  File "/usr/local/multi-v2ray/loader.py", line 6, in <module>
    from config import Config
ImportError: cannot import name 'Config'

**Comment by Jrohy** [comment]
查看下有没设置到multi-v2ray的环境变量

**Comment by fredzhu** [comment]
@WoChen5770 你用啥系统。建议Debian9，我用这个基本没问题（除了干净系统要装sudo和curl）。

**Comment by WoChen5770** [comment]
@Jrohy @fredzhu 感谢回答。
这个问题我解决了，谷歌了一下，安装了个pip的什么东西，然后重启vps就没报错了。估计是安装其他软件的时候把相关的依赖或者软件给冲突了。
当然也可能是重启有奇效。哈哈哈
