### ISSUE TITLE
有个新想法

### ISSUE THREAD

**Issue by Tsuk1nose** [Jrohy/multi-v2ray#79]
加入BBR提升网速

**Comment by Jrohy** [comment]
只做好涵盖v2ray本身的功能(修改json)，不会另外加其他功能

**Comment by Jrohy** [comment]
当然仅限v2ray作为fq的那部分

**Comment by winxpp** [comment]
QUIC配置好后怎么导出JSON文件呢？是否能制作一个直接下载文件的功能？
话说这个脚本很不错 就是没法导出文件不方便

**Comment by Tsuk1nose** [comment]
好吧,已经自己配置好了,只是觉得如果加入BBR加速会更好一点而已.
