### ISSUE TITLE
TCP配合http伪装使用不能

### ISSUE THREAD

**Issue by SneakyTurt1e** [Jrohy/multi-v2ray#80]
如题，在不启用伪装状态下可以使用

v2ray.com/core/proxy/vmess/encoding: failed to read request header

**Comment by Jrohy** [comment]
@SneakyTurt1e  确实存在该问题， 今天会修复

**Comment by SneakyTurt1e** [comment]
刚试了带上伪装 在不用第三方客户端的情况下可以 可能是 内核的问题

**Comment by Jrohy** [comment]
确实不用客户端，用v2ray.exe就可以

**Comment by Jrohy** [comment]
@SneakyTurt1e 应该是生成的vmess字符串关于http的规则有变动， 今晚回去调整下

**Comment by Jrohy** [comment]
@SneakyTurt1e  v2.5.2版本已修复
