### ISSUE TITLE
生成的config导出后v2ray启动闪退

### ISSUE THREAD

**Issue by Violiss** [Jrohy/multi-v2ray#81]
用脚本生成config导出至本地  覆盖v2ray-windows-64中 启动v2ray.exe会闪退
但是将配置信息中的url导入v2rayN中运行正常  再将v2rayN生成的本地config覆盖至v2ray-windows-64中 则v2ray.exe正常启动运行.
请问是否是脚本生成的config格式错误？

**Comment by Jrohy** [comment]
什么配置的传输协议导出会闪退呢，最好发下配置文件

**Comment by Jrohy** [comment]
什么组合配置

**Comment by Violiss** [comment]
使用SZ /etc/v2ray/config.json   命令导出文件内容如下
{
  "outbounds": [
    {
      "settings": {},
      "protocol": "freedom"
    },
    {
      "settings": {},
      "protocol": "blackhole",
      "tag": "blocked"
    }
  ],
  "inbounds": [
    {
      "streamSettings": {
        "network": "kcp",
        "tlsSettings": {},
        "wsSettings": {},
        "tcpSettings": {},
        "kcpSettings": {
          "writeBufferSize": 2,
          "uplinkCapacity": 100,
          "tti": 50,
          "readBufferSize": 2,
          "mtu": 1350,
          "congestion": false,
          "downlinkCapacity": 100,
          "header": {
            "type": "srtp"
          }
        },
        "quicSettings": {},
        "httpSettings": {},
        "security": "none"
      },
      "protocol": "vmess",
      "port": 9254,
      "settings": {
        "clients": [
          {
            "alterId": 18,
            "id": "bb1a6ba0-fa95-11e9-9b93-aaaa00127f9c"
          }
        ]
      }
    }
  ],
  "log": {
    "access": "/var/log/v2ray/access.log",
    "loglevel": "info",
    "error": "/var/log/v2ray/error.log"
  },
  "routing": {
    "rules": [
      {
        "ip": [
          "0.0.0.0/8",
          "10.0.0.0/8",
          "100.64.0.0/10",
          "169.254.0.0/16",
          "172.16.0.0/12",
          "192.0.0.0/24",
          "192.0.2.0/24",
          "192.168.0.0/16",
          "198.18.0.0/15",
          "198.51.100.0/24",
          "203.0.113.0/24",
          "::1/128",
          "fc00::/7",
          "fe80::/10"
        ],
        "outboundTag": "blocked",
        "type": "field"
      }
    ]
  }
}

**Comment by Violiss** [comment]
> 什么组合配置
实际试用过多种传输组合 并不变化  只要是脚本安装完成后SZ导出config都会导致v2ray.exe闪退

**Comment by Violiss** [comment]
> 什么组合配置

抱歉是我搞错config文件路径了
脚本生成的config在root下 我按照官方给的/etc/v2ray/config.json导出的  哈哈不好意思  没问题了
