### ISSUE TITLE
脚本生成的链接不能用在v2rayNG上

### ISSUE THREAD

**Issue by gqm36524** [Jrohy/multi-v2ray#82]
脚本生成的链接不能用在v2rayNG上，最近的几个版本都提示导入失败，老版本提示成功，但是并没有添加进去。这个脚本生成的链接可以导入到v2rayN中，然后在v2rayN中生成分享的链接，v2rayNG就能用了。所以建议一下作者能不能修改一下脚本生成的链接按照v2rayN的格式走。

**Comment by Jrohy** [comment]
本来设计就是按v2rayN的格式搞的，你可以base64解码出来看下，至于v2rayNG确实没怎么去留意。

**Comment by Jrohy** [comment]
感觉v2rayN适配应该v2rayNG也行吧😂

**Comment by gqm36524** [comment]
可是现实是不行，你比对一下脚本的链接和v2rayN的链接是有区别的

**Comment by Jrohy** [comment]
vmess://eyJ2IjogIjIiLCAicHMiOiAiIiwgImFkZCI6ICI1MS42OC4yOS44NyIsICJwb3J0IjogMTY1OTYsICJhaWQiOiA2NCwgInR5cGUiOiAic3J0cCIsICJuZXQiOiAia2NwIiwgInBhdGgiOiAiIiwgImhvc3QiOiAiIiwgImlkIjogIjA4MzFhYzFkLTNmMDMtNDA0Ny04ZmQxLTIxOWRkZThlYWUzZSIsICJ0bHMiOiAiIn0=

**Comment by Jrohy** [comment]
你试下上面的能否导入，都是脚本生成的

**Comment by Jrohy** [comment]
试了v2rayNG也是可以导入的, 你是什么组合的配置导不进呢

**Comment by Jrohy** [comment]
脚本生成和v2rayN生成也就脚本生成去掉空格而已, 当初都是严格按照v2rayN 最新的ver 2格式搞的(分享链接格式说明(ver-2))[https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2)]

**Comment by gqm36524** [comment]
vmess://eyJhZGQiOiAiMTQ5LjEyOS45NS4yMDgiLCAicG9ydCI6IDM2OTgsICJ0eXBlIjogbnVsbCwgInBzIjogIiIsICJhaWQiOiAzMiwgImhvc3QiOiAiIiwgIm5ldCI6ICJ0Y3AiLCAiaWQiOiAiYTYxMjQ4MDAtZmFmNi0xMWU4LTkxNGItMDAxNjNlMDRiZGJmIiwgInBhdGgiOiAiIiwgInYiOiAiMiIsICJ0bHMiOiAibm9uZSJ9

**Comment by gqm36524** [comment]
这是我脚本生成出的链接

**Comment by gqm36524** [comment]
你刚才发的那个链接我能成功导入到v2rayNG,但是我用脚本生成的为啥不行==

**Comment by Jrohy** [comment]
v2rayN可以导入

**Comment by gqm36524** [comment]
对的，但是v2rayNG却不行

**Comment by Jrohy** [comment]
kcp的可以但tcp确实不行

**Comment by Jrohy** [comment]
找到问题了，等下修复下

**Comment by Jrohy** [comment]
@gqm36524 v2.5.3版本已修复，`v2ray update.sh`更新下

**Comment by gqm36524** [comment]
更新完之后输出的链接还是旧的

**Comment by gqm36524** [comment]
没问题了，可以成功导入了，谢谢J大的脚本
