### ISSUE TITLE
http/2

### ISSUE THREAD

**Issue by zerozero123** [Jrohy/multi-v2ray#85]
老哥，有空可以写写套CDN的小白教程不？

**Comment by Jrohy** [comment]
套cdn没试过

**Comment by zerozero123** [comment]
试试不？我觉的你这个脚本挺好用的，可以设置多用户 ，尤其是自动升级内核功能。如果能写个websocket教程就更完美了，有空试试。。。。。。

Jrohy <notifications@github.com> 于2018年12月9日周日 下午8:53写道：

**Comment by Jrohy** [comment]
不会写教程， 自己也没套cdn必要

**Comment by zerozero123** [comment]
好吧 sj189lyr 邮箱sj189lyr@gmail.com 签名由 网易邮箱大师 定制 On 12/09/2018 21:34, Jrohy wrote: 不会写教程， 自己也没套cdn必要 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
