### ISSUE TITLE
建议增加绑定服务器地址功能

### ISSUE THREAD

**Issue by gqm36524** [Jrohy/multi-v2ray#87]
之前用过一个55R的脚本，他的脚本可以绑定服务器地址。这样我就可以绑定域名，然后生成的分享链接服务器地址位置就是按绑定的域名生成的。这样导入的时候就会是域名，方便日后服务器被封了，换ip

**Comment by Jrohy** [comment]
比较小众的需求不会考虑

**Comment by gqm36524** [comment]
你不觉得服务器被封是个很常见的事情咩

**Comment by Jrohy** [comment]
@gqm36524 不会😂，我有些v2节点公开几个月都没被封还能翻，只试过被人可能用来某些特殊用途被封，但也不是封ip，是vps商封的
