### ISSUE TITLE
望增加443 tls ws模式

### ISSUE THREAD

**Issue by ntgeralt** [Jrohy/multi-v2ray#88]
你做的这个多用户脚本算是目前最好的了。打算从233转用你，所以稍微建议增加443 tls ws带一个真实主页。

另外卸载功能你也可以集成在菜单里

**Comment by Jrohy** [comment]
怎么带真实页面呢，443端口和tls都可以自己切换

**Comment by ntgeralt** [comment]
> 怎么带真实页面呢，443端口和tls都可以自己切换

https访问域名跳转到一个网页..还有个小建议，vmess里面remark 别名写一些关于服务端信息

**Comment by Jrohy** [comment]
跳转页面可以用nginx来搞，脚本本身只关注v2ray本身的功能
