### ISSUE TITLE
debian 8/9执行脚本后成功配置v2ray，但是执行命令v2ray出错

### ISSUE THREAD

**Issue by DaZF** [Jrohy/multi-v2ray#92]
安装以后
`root@debian:~# v2ray`
`bash: /usr/local/sbin/v2ray: No such file or directory`

**Comment by DaZF** [comment]
去查看了`/etc/profile`文件，觉得可能是权限的问题，遂执行`su root`，执行前已经是root了，但是执行以后，执行v2ray，却运行成功，很奇怪。
执行`su root`前后PATH内容不变，实在无法理解这个情况。
不过问题算是暂时解决了

**Comment by hoohle** [comment]
是不是因为用了rsakey免密登录不是真正的root权限的问题啊，我也是这个情况，系统是debian 9输入su root也就好了，开心，但不是很明白为什么
