### ISSUE TITLE
流量统计没记录

### ISSUE THREAD

**Issue by kwinH** [Jrohy/multi-v2ray#94]
@Jrohy
流量统计没记录

```
请输入所需要查看流量的组别(字母)或者序号(数字): B


```
然后就是空白 什么也没有

**Comment by Jrohy** [comment]
要使用了才有流量产生，才能统计

**Comment by kwinH** [comment]
![image](https://user-images.githubusercontent.com/22871248/51666378-a8737480-1ff8-11e9-9387-96980b687d6a.png)

还是什么都没有  @Jrohy
