### ISSUE TITLE
删除端口时，能否增加删除iptables。。

### ISSUE THREAD

**Issue by SneakyTurt1e** [Jrohy/multi-v2ray#95]
今天查看Iptables。。发现有很多相同的规则，应该时以往创建端口时产生，而删除时没能删除留下的，能不能稍加改进呢

**Comment by Jrohy** [comment]
脚本从头到尾没碰过iptables(不怎么会😂)， 脚本只是修改json，还有cron设置

**Comment by Jrohy** [comment]
v2.6.0 版本已修复， 会自动清理旧的规则
