### ISSUE TITLE
多用户能分开监控流量吗？

### ISSUE THREAD

**Issue by boovi2018** [Jrohy/multi-v2ray#96]
只看到一个流量统计信息

**Comment by boovi2018** [comment]
我设了两个用户了，两个用户都有邮箱，但查看流量没区别开，请问还有哪个设置不对



1.开启流量统计

2.关闭流量统计

3.查看流量统计

4.重置流量统计

tip: 具有有效email节点才会统计, 重启v2ray会重置流量统计!!!

请输入数字选择功能：3

downlink: 2.7 GB
uplink: 3.34 MB
total: 2.7 GB

**Comment by Jrohy** [comment]
这确实是一个bug，单个端口多用户时，直接不用选择就能看，后面会修复

**Comment by Jrohy** [comment]
[v2.6.0](https://github.com/Jrohy/multi-v2ray/releases/tag/v2.6.0)  版本已修复, 且加入了iptables端口流量统计

**Comment by boovi2018** [comment]
老大能给个选择统计全部吗，一个一个选很累的，操作比较繁琐，谢谢了

**Comment by Jrohy** [comment]
iptables端口流量统计就没问题，但v2ray的流量统计就要测试下性能如何了
