### ISSUE TITLE
已有配置可以导出吗

### ISSUE THREAD

**Issue by Allenxuxu** [Jrohy/multi-v2ray#99]
需要换服务器，想把多个账号端口配置导出，可以生成配置文件吗？

**Comment by Jrohy** [comment]
把/etc/v2ray/config.json文件拷贝过去

**Comment by Allenxuxu** [comment]
我刚试了下,出现下面这个错误
 File "/usr/local/multi-v2ray/profile.py", line 42, in read_json
    conf_inbounds = self.config["inbounds"]
KeyError: 'inbounds'

**Comment by Jrohy** [comment]
升级下脚本， 用的是新版配置文件了， 升级脚本会自动转换新版配置文件

**Comment by Allenxuxu** [comment]
完蛋了... 我已经重装了... 我重装个以前的版本试试能不能先转换过来..

**Comment by Jrohy** [comment]
和以前版本无关的

**Comment by Allenxuxu** [comment]
我手动重配吧

**Comment by Allenxuxu** [comment]
手动重配置 设置邮箱的时候 ,python报错如下

Traceback (most recent call last):
  File "/usr/local/multi-v2ray/config_modify/n_email.py", line 43, in <module>
    cw.write_email(email)
  File "/usr/local/multi-v2ray/writer.py", line 319, in write_email
    self.part_json["settings"][self.client_str][self.client_index].update({"email": email})
KeyError: 'users'

**Comment by Allenxuxu** [comment]
设置 ss 传输类型的邮箱会报错

**Comment by Jrohy** [comment]
Quic可以直接生成配置文件，因为v2rayN配置格式还没出。

**Comment by Jrohy** [comment]
@Allenxuxu v2.6.1 已修复ss 邮箱设置问题
